// Fictional review fixtures. These are not connected to the application or mailer.
const notificationFooter = "Manage notification preferences";
const member = { recipientName: "Alex", workspaceName: "Acme" };

export const emails = [
  {
    id: "invitation",
    name: "Workspace invitation",
    group: "Workspace",
    subject: "Joseph invited you to Acme on FortyOne",
    preheader: "Your team is ready for you. Join Acme as a member.",
    title: "Your team is ready for you.",
    image: "invitation.png",
    imageAlt: "Two open doorways in warm peach and orange.",
    paragraphs: [
      "Joseph invited you to join Acme on FortyOne.",
      "See what’s in progress, pick up a task, and work together in one place.",
    ],
    details: [
      ["Workspace", "Acme"],
      ["Your role", "Member"],
    ],
    action: { label: "Join Acme", path: "accept-invitation" },
    helper: "This invitation expires in 7 days.",
    footer: "Not expecting this invitation? You can ignore it.",
    source: "apps/server/templates/invites/invitation.html",
    fields: {
      ...member,
      inviterName: "Joseph",
      role: "Member",
      expiresIn: "7 days",
      verificationURL: "https://example.com/fortyone/accept-invitation",
    },
  },
  {
    id: "invitation-accepted",
    name: "Invitation accepted",
    group: "Workspace",
    subject: "Alex joined Acme",
    preheader: "Your invitation was accepted. Alex is now a member of Acme.",
    title: "Your team just grew.",
    image: "invitation-accepted.png",
    imageAlt: "Two paths come together at an open doorway.",
    paragraphs: [
      "Alex accepted your invitation and joined Acme.",
      "You’re ready to start working together.",
    ],
    details: [
      ["New member", "Alex"],
      ["Role", "Member"],
    ],
    action: { label: "Open Acme", path: "workspace" },
    helper: "A shared space for what’s next.",
    footer: "You invited Alex to this workspace.",
    recipient: "Joseph <joseph@example.com>",
    source: "apps/server/templates/invites/acceptance.html",
    fields: {
      inviteeName: "Alex",
      workspaceName: "Acme",
      role: "Member",
      loginURL: "https://example.com/fortyone/workspace",
    },
  },
  {
    id: "story-updates",
    name: "Story updates",
    group: "Notifications",
    subject: "3 updates in Acme",
    preheader: "A status change, an assignment, and a comment on your stories.",
    title: "Here’s what changed.",
    paragraphs: ["Hi Alex, you have 3 updates in Acme."],
    updates: [
      {
        id: "WEB-128",
        title: "Improve the onboarding flow",
        text: "Joseph changed the status to In progress.",
      },
      {
        id: "WEB-142",
        title: "Add workspace search",
        text: "Sarah assigned this story to you.",
      },
      {
        id: "WEB-136",
        title: "Refresh the project overview",
        text: "Joseph left a comment:",
        quote: "The updated layout is ready for your review.",
      },
    ],
    action: { label: "View notifications", path: "notifications" },
    footerLink: notificationFooter,
    source: "apps/server/templates/notifications/notification.html",
    note: "A sample grouped layout. Existing delivery rules and available event fields will be preserved during integration.",
    fields: {
      ...member,
      notificationTitle: "Here’s what changed.",
      notificationType: "story_update",
      updateCount: 3,
    },
  },
  {
    id: "conversation",
    name: "Conversation reply",
    group: "Notifications",
    subject: "Sarah replied to your comment",
    preheader: "On WEB-128 · Improve the onboarding flow",
    title: "Sarah replied to your comment",
    paragraphs: ["On WEB-128 · Improve the onboarding flow"],
    conversation: {
      original: "Can we simplify the first step?",
      author: "Sarah",
      reply:
        "Yes — I’ve removed the extra fields. Could you take another look before we ship?",
    },
    closing: "Open the conversation to reply.",
    action: {
      label: "View conversation",
      path: "stories/WEB-128/conversation",
    },
    footerLink: notificationFooter,
    source: "apps/server/templates/notifications/notification.html",
    note: "The prior-comment excerpt is a review fixture; include it only when available to the authorized recipient. Replies open the app.",
    fields: {
      ...member,
      notificationType: "comment_reply",
      authorName: "Sarah",
      storyIdentifier: "WEB-128",
      storyTitle: "Improve the onboarding flow",
    },
  },
  {
    id: "workspace-deletion",
    name: "Scheduled deletion",
    group: "Workspace",
    subject: "Acme is scheduled for deletion",
    preheader: "Deletion is scheduled in 48 hours. Open settings to cancel it.",
    tone: "warning",
    title: "Acme is scheduled for deletion.",
    paragraphs: ["Joseph requested deletion of this workspace."],
    warning: {
      title: "Deletion in 48 hours",
      text: "All workspace data will be permanently deleted. This cannot be undone.",
    },
    rows: [
      ["Workspace", "Acme"],
      ["Requested by", "joseph@example.com"],
    ],
    closing:
      "To keep Acme, open workspace settings and select Cancel scheduled deletion before the 48-hour window ends.",
    emphasis: "Cancel scheduled deletion",
    action: { label: "Open workspace settings", path: "settings" },
    fallback: "acme.fortyone.app",
    footer: "You’re receiving this because you’re a workspace admin.",
    source:
      "apps/server/templates/workspaces/deletion_scheduled_notification.html",
    note: "Opening the email link does not cancel deletion. The existing settings action is still required. The deadline is sample copy relative to the request.",
    fields: {
      workspaceName: "Acme",
      actorName: "Joseph",
      actorEmail: "joseph@example.com",
      deletionTime: "48 hours",
      restoreURL: "https://example.com/fortyone/settings",
    },
  },
  {
    id: "workspace-inactivity",
    name: "Inactive workspace",
    group: "Workspace",
    subject: "Keep your Acme workspace",
    preheader: "Sign in within 30 days to keep your workspace and its data.",
    title: "Still need your Acme workspace?",
    paragraphs: [
      "Acme hasn’t been active for a while. It’s scheduled for deletion in 30 days.",
    ],
    warning: {
      title: "Keep your work with a sign-in",
      text: "Sign in before then to keep the workspace active. Otherwise, the workspace and all its data will be deleted.",
    },
    action: { label: "Keep my workspace", path: "workspace/sign-in" },
    helper: "No longer using Acme? No action is needed.",
    footer: "A service notice about your Acme workspace.",
    source: "apps/server/templates/workspaces/inactivity_warning.html",
    fields: {
      workspaceName: "Acme",
      deletionTime: "30 days",
      workspaceURL: "https://example.com/fortyone/workspace/sign-in",
    },
  },
  {
    id: "maya-weekly",
    name: "Maya’s weekly note",
    group: "Maya",
    subject: "A little focus for the week",
    preheader: "5 stories completed. Here’s what needs your attention next.",
    title: "A little focus for the week.",
    paragraphs: [
      "Hi Alex,",
      "You completed 5 stories last week. Here’s what needs your attention now.",
    ],
    updates: [
      {
        title: "2 overdue stories",
        text: "Decide what still needs doing and reset any dates that have slipped.",
      },
      {
        title: "3 stories due this week",
        text: "Choose the most important one to move forward first.",
      },
      {
        title: "1 mention waiting for you",
        text: "Catch up with your team before planning your next steps.",
      },
    ],
    closing:
      "What’s changed since your last update? Reply to this email and I’ll help you work through the next step.",
    maya: true,
    action: { label: "Plan my week", path: "my-work?tab=assigned" },
    footerLink: notificationFooter,
    source: "apps/server/pkg/jobs/weekly_digest.go",
    fields: {
      ...member,
      completedStories: 5,
      overdueStories: 2,
      dueThisWeek: 3,
      unreadMentions: 1,
      senderProfile: "maya",
    },
  },
  {
    id: "maya-follow-up",
    name: "Maya’s confirmation",
    group: "Maya",
    subject: "Re: Activation check-in",
    preheader: "Review the proposed update. No changes have been made yet.",
    title: "Ready to update Activation.",
    paragraphs: [
      "Hi Alex,",
      "Based on your reply, here’s the change I can make.",
    ],
    proposal: {
      objective: "Activation",
      before: "At Risk",
      after: "On Track",
      checkIn: "The launch blocker is resolved.",
    },
    closing: "No changes have been made yet.",
    maya: true,
    confirmation: true,
    source: "apps/server/internal/modules/emailreply/service/reply_html.go",
    note: "CONFIRM and CANCEL are email replies, not clickable actions. This preview never writes to a workspace.",
    fields: {
      ...member,
      objectiveName: "Activation",
      currentHealth: "At Risk",
      proposedHealth: "On Track",
      checkIn: "The launch blocker is resolved.",
      senderProfile: "maya",
    },
  },
];
