package mailer

import (
	stdhtml "html"
	"html/template"
	"net/url"
	"strings"

	htmlparser "golang.org/x/net/html"
)

var allowedEmailHTMLElements = map[string]struct{}{
	"a":      {},
	"br":     {},
	"div":    {},
	"em":     {},
	"h1":     {},
	"h2":     {},
	"h3":     {},
	"h4":     {},
	"h5":     {},
	"h6":     {},
	"li":     {},
	"ol":     {},
	"p":      {},
	"span":   {},
	"strong": {},
	"ul":     {},
}

var droppedEmailHTMLElements = map[string]struct{}{
	"iframe":   {},
	"math":     {},
	"object":   {},
	"script":   {},
	"style":    {},
	"svg":      {},
	"template": {},
}

// Previously queued notification jobs may contain these two renderer-owned
// styles. Recognize these exact values and migrate their typography without
// permitting arbitrary inline CSS.
var legacyEmailStyles = map[string]struct{}{
	`margin: 0 0 12px; color: #0b0a08; font-family: Geist, Helvetica, Arial, sans-serif; font-size: 15px; font-weight: 600; line-height: 1.3;`: {},
	`margin: 0 0 12px; color: #3b3a38; font-family: Geist, Helvetica, Arial, sans-serif; font-size: 15px; line-height: 1.62;`:                  {},
}

// safeEmailHTML keeps the small HTML vocabulary generated by FortyOne's email
// copy builders. Text is always escaped, links must be absolute HTTP(S) URLs,
// and inline styles must exactly match the immutable mailer style allowlist.
func safeEmailHTML(value string) template.HTML {
	tokenizer := htmlparser.NewTokenizer(strings.NewReader(value))
	var output strings.Builder
	openElements := make([]string, 0, 8)
	droppedElements := make([]string, 0, 1)

	for {
		switch tokenizer.Next() {
		case htmlparser.ErrorToken:
			for index := len(openElements) - 1; index >= 0; index-- {
				output.WriteString("</")
				output.WriteString(openElements[index])
				output.WriteByte('>')
			}
			// #nosec G203 -- output is produced exclusively by the allowlist parser
			// above; all text and attributes are escaped before this conversion.
			return template.HTML(output.String())

		case htmlparser.TextToken:
			if len(droppedElements) == 0 {
				output.WriteString(stdhtml.EscapeString(string(tokenizer.Text())))
			}

		case htmlparser.StartTagToken:
			token := tokenizer.Token()
			name := strings.ToLower(token.Data)
			if len(droppedElements) > 0 {
				droppedElements = append(droppedElements, name)
				continue
			}
			if _, drop := droppedEmailHTMLElements[name]; drop {
				droppedElements = append(droppedElements, name)
				continue
			}
			if _, allowed := allowedEmailHTMLElements[name]; !allowed {
				continue
			}
			writeAllowedEmailStartTag(&output, name, token.Attr)
			if name != "br" {
				openElements = append(openElements, name)
			}

		case htmlparser.SelfClosingTagToken:
			if len(droppedElements) > 0 {
				continue
			}
			token := tokenizer.Token()
			name := strings.ToLower(token.Data)
			if _, allowed := allowedEmailHTMLElements[name]; allowed {
				writeAllowedEmailStartTag(&output, name, token.Attr)
			}

		case htmlparser.EndTagToken:
			name, _ := tokenizer.TagName()
			closingName := strings.ToLower(string(name))
			if len(droppedElements) > 0 {
				if droppedElements[len(droppedElements)-1] == closingName {
					droppedElements = droppedElements[:len(droppedElements)-1]
				}
				continue
			}
			closeAllowedEmailElement(&output, &openElements, closingName)
		}
	}
}

func writeAllowedEmailStartTag(output *strings.Builder, name string, attributes []htmlparser.Attribute) {
	output.WriteByte('<')
	output.WriteString(name)
	hasStyle := false
	for _, attribute := range attributes {
		attributeName := strings.ToLower(attribute.Key)
		attributeValue := strings.TrimSpace(attribute.Val)
		switch {
		case attributeName == "href" && name == "a" && safeEmailLink(attributeValue):
			output.WriteString(` href="`)
			output.WriteString(stdhtml.EscapeString(attributeValue))
			output.WriteByte('"')
		case attributeName == "style" && !hasStyle && allowedEmailStyle(attributeValue):
			hasStyle = true
			if _, legacy := legacyEmailStyles[attributeValue]; legacy {
				attributeValue = EmailStyleString("notificationText")
				if strings.HasPrefix(name, "h") {
					attributeValue = EmailStyleString("panelTitle")
				}
			}
			output.WriteString(` style="`)
			output.WriteString(stdhtml.EscapeString(attributeValue))
			output.WriteByte('"')
		}
	}
	if !hasStyle {
		key := map[string]string{"p": "notificationText", "h1": "panelTitle", "h2": "panelTitle", "h3": "panelTitle", "h4": "panelTitle", "h5": "panelTitle", "h6": "panelTitle", "ul": "notificationList", "li": "notificationItem", "a": "notificationLink"}[name]
		if key != "" {
			output.WriteString(` style="` + stdhtml.EscapeString(EmailStyleString(key)) + `"`)
		}
	}
	output.WriteByte('>')
}

func closeAllowedEmailElement(output *strings.Builder, openElements *[]string, name string) {
	match := -1
	for index := len(*openElements) - 1; index >= 0; index-- {
		if (*openElements)[index] == name {
			match = index
			break
		}
	}
	if match < 0 {
		return
	}
	for index := len(*openElements) - 1; index >= match; index-- {
		output.WriteString("</")
		output.WriteString((*openElements)[index])
		output.WriteByte('>')
	}
	*openElements = (*openElements)[:match]
}

func safeEmailLink(value string) bool {
	parsed, err := url.Parse(value)
	if err != nil || parsed.User != nil || parsed.Host == "" {
		return false
	}
	return parsed.Scheme == "https" || parsed.Scheme == "http"
}

func allowedEmailStyle(value string) bool {
	if _, allowed := legacyEmailStyles[value]; allowed {
		return true
	}
	for _, style := range emailStyles {
		if value == style {
			return true
		}
	}
	return false
}
