// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package labelssql

import (
	"context"
)

type Querier interface {
	CreateLabelForMember(ctx context.Context, arg CreateLabelForMemberParams) (Label, error)
	DeleteLabelForMember(ctx context.Context, arg DeleteLabelForMemberParams) (int64, error)
	GetLabelForMember(ctx context.Context, arg GetLabelForMemberParams) (Label, error)
	ListLabelsForMember(ctx context.Context, arg ListLabelsForMemberParams) ([]Label, error)
	ListLabelsPageForMember(ctx context.Context, arg ListLabelsPageForMemberParams) ([]Label, error)
	UpdateLabelForMember(ctx context.Context, arg UpdateLabelForMemberParams) (Label, error)
}

var _ Querier = (*Queries)(nil)
