// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mutations.sql

package storyreadsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const applyStoryPatch = `-- name: ApplyStoryPatch :one
WITH target AS (
    SELECT story.id, story.sequence_id, story.team_id, story.title, story.description, story.description_html, story.parent_id, story.objective_id, story.status_id, story.assignee_id, story.blocked_by_id, story.blocking_id, story.related_id, story.reporter_id, story.priority, story.sprint_id, story.workspace_id, story.start_date, story.end_date, story.estimate, story.archived_at, story.is_draft, story.created_at, story.updated_at, story.deleted_at, story.search_vector, story.key_result_id, story.completed_at, story.estimate_unit, story.external_creation_key, story.estimated_duration_minutes, story.minimum_focus_block_minutes, story.auto_scheduling_enabled, story.auto_scheduling_locked, story.auto_scheduling_status, story.auto_scheduling_reason, story.auto_scheduling_updated_at
    FROM public.stories AS story
    WHERE story.id = $1
      AND story.workspace_id = $2
      AND story.deleted_at IS NULL
), authorized AS (
    SELECT target.id, target.sequence_id, target.team_id, target.title, target.description, target.description_html, target.parent_id, target.objective_id, target.status_id, target.assignee_id, target.blocked_by_id, target.blocking_id, target.related_id, target.reporter_id, target.priority, target.sprint_id, target.workspace_id, target.start_date, target.end_date, target.estimate, target.archived_at, target.is_draft, target.created_at, target.updated_at, target.deleted_at, target.search_vector, target.key_result_id, target.completed_at, target.estimate_unit, target.external_creation_key, target.estimated_duration_minutes, target.minimum_focus_block_minutes, target.auto_scheduling_enabled, target.auto_scheduling_locked, target.auto_scheduling_status, target.auto_scheduling_reason, target.auto_scheduling_updated_at
    FROM target
    WHERE (
        CAST($3 AS text) = 'system'
        AND EXISTS (
            SELECT 1
            FROM public.users AS system_actor
            WHERE system_actor.user_id = $4
              AND system_actor.is_active = TRUE
              AND system_actor.is_system = TRUE
        )
    ) OR (
        CAST($3 AS text) IN ('human_user', 'oauth_user')
        AND EXISTS (
            SELECT 1
            FROM public.users AS account
            INNER JOIN public.workspace_members AS workspace_member
                ON workspace_member.workspace_id = target.workspace_id
               AND workspace_member.user_id = account.user_id
            INNER JOIN public.team_members AS team_member
                ON team_member.team_id = target.team_id
               AND team_member.user_id = account.user_id
            WHERE account.user_id = $4
              AND account.is_active = TRUE
        )
    ) OR (
        CAST($3 AS text) = 'personal_token'
        AND EXISTS (
            SELECT 1
            FROM public.api_credentials AS credential
            INNER JOIN public.principals AS principal
                ON principal.principal_id = credential.principal_id
               AND principal.workspace_id = credential.workspace_id
            INNER JOIN public.users AS account
                ON account.user_id = principal.subject_user_id
               AND account.is_active = TRUE
            INNER JOIN public.workspace_members AS workspace_member
                ON workspace_member.workspace_id = target.workspace_id
               AND workspace_member.user_id = account.user_id
            INNER JOIN public.team_members AS team_member
                ON team_member.team_id = target.team_id
               AND team_member.user_id = account.user_id
            WHERE credential.credential_id = $5
              AND credential.workspace_id = target.workspace_id
              AND credential.kind = 'personal_access_token'
              AND credential.revoked_at IS NULL
              AND credential.expires_at > $6
              AND principal.status = 'active'
              AND principal.subject_user_id = $4
              AND EXISTS (
                  SELECT 1
                  FROM public.api_credential_scopes AS credential_scope
                  WHERE credential_scope.credential_id = credential.credential_id
                    AND credential_scope.scope = 'stories:write'
              )
              AND (
                  NOT EXISTS (
                      SELECT 1
                      FROM public.api_credential_team_restrictions AS restriction
                      WHERE restriction.credential_id = credential.credential_id
                  )
                  OR EXISTS (
                      SELECT 1
                      FROM public.api_credential_team_restrictions AS restriction
                      WHERE restriction.credential_id = credential.credential_id
                        AND restriction.workspace_id = target.workspace_id
                        AND restriction.team_id = target.team_id
                  )
              )
        )
    ) OR (
        CAST($3 AS text) = 'service_account'
        AND EXISTS (
            SELECT 1
            FROM public.principals AS principal
            INNER JOIN public.api_credentials AS credential
                ON credential.principal_id = principal.principal_id
               AND credential.workspace_id = principal.workspace_id
            WHERE principal.principal_id = $4
              AND principal.workspace_id = target.workspace_id
              AND principal.kind = 'service_account'
              AND principal.status = 'active'
              AND credential.credential_id = $5
              AND credential.kind = 'service_account_key'
              AND credential.revoked_at IS NULL
              AND credential.expires_at > $6
              AND EXISTS (
                  SELECT 1
                  FROM public.api_credential_scopes AS credential_scope
                  WHERE credential_scope.credential_id = credential.credential_id
                    AND credential_scope.scope = 'stories:write'
              )
              AND (
                  NOT EXISTS (
                      SELECT 1
                      FROM public.api_credential_team_restrictions AS restriction
                      WHERE restriction.credential_id = credential.credential_id
                  )
                  OR EXISTS (
                      SELECT 1
                      FROM public.api_credential_team_restrictions AS restriction
                      WHERE restriction.credential_id = credential.credential_id
                        AND restriction.workspace_id = target.workspace_id
                        AND restriction.team_id = target.team_id
                  )
              )
        )
    )
), valid AS (
    SELECT authorized.id, authorized.sequence_id, authorized.team_id, authorized.title, authorized.description, authorized.description_html, authorized.parent_id, authorized.objective_id, authorized.status_id, authorized.assignee_id, authorized.blocked_by_id, authorized.blocking_id, authorized.related_id, authorized.reporter_id, authorized.priority, authorized.sprint_id, authorized.workspace_id, authorized.start_date, authorized.end_date, authorized.estimate, authorized.archived_at, authorized.is_draft, authorized.created_at, authorized.updated_at, authorized.deleted_at, authorized.search_vector, authorized.key_result_id, authorized.completed_at, authorized.estimate_unit, authorized.external_creation_key, authorized.estimated_duration_minutes, authorized.minimum_focus_block_minutes, authorized.auto_scheduling_enabled, authorized.auto_scheduling_locked, authorized.auto_scheduling_status, authorized.auto_scheduling_reason, authorized.auto_scheduling_updated_at
    FROM authorized
    WHERE (
        NOT CAST($7 AS boolean)
        OR CAST($8 AS uuid) IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.statuses AS status
            WHERE status.status_id = $8
              AND status.team_id = authorized.team_id
        )
    )
      AND (
        NOT CAST($9 AS boolean)
        OR CAST($10 AS uuid) IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.stories AS parent
            WHERE parent.id = $10
              AND parent.id <> authorized.id
              AND parent.workspace_id = authorized.workspace_id
              AND parent.team_id = authorized.team_id
              AND parent.deleted_at IS NULL
        )
    )
      AND (
        NOT CAST($11 AS boolean)
        OR CAST($12 AS uuid) IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.users AS assignee
            WHERE assignee.user_id = $12
              AND assignee.is_active = TRUE
              AND (
                  assignee.is_system = TRUE
                  OR (
                      EXISTS (
                          SELECT 1
                          FROM public.workspace_members AS workspace_member
                          WHERE workspace_member.workspace_id = authorized.workspace_id
                            AND workspace_member.user_id = assignee.user_id
                      )
                      AND EXISTS (
                          SELECT 1
                          FROM public.team_members AS team_member
                          WHERE team_member.team_id = authorized.team_id
                            AND team_member.user_id = assignee.user_id
                      )
                  )
              )
        )
    )
      AND (
        NOT CAST($13 AS boolean)
        OR CAST($14 AS uuid) IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.objectives AS objective
            WHERE objective.objective_id = $14
              AND objective.workspace_id = authorized.workspace_id
        )
    )
      AND (
        NOT CAST($15 AS boolean)
        OR CAST($16 AS uuid) IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.sprints AS sprint
            WHERE sprint.sprint_id = $16
              AND sprint.workspace_id = authorized.workspace_id
              AND sprint.team_id = authorized.team_id
        )
    )
      AND (
        NOT CAST($17 AS boolean)
        OR CAST($18 AS uuid) IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.key_results AS key_result
            INNER JOIN public.objectives AS objective
                ON objective.objective_id = key_result.objective_id
               AND objective.workspace_id = authorized.workspace_id
            WHERE key_result.id = $18
        )
    )
      AND (
        (
            NOT CAST($13 AS boolean)
            AND NOT CAST($17 AS boolean)
        )
        OR CASE
            WHEN CAST($17 AS boolean)
                THEN CAST($18 AS uuid)
            ELSE authorized.key_result_id
        END IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.key_results AS key_result
            WHERE key_result.id = CASE
                    WHEN CAST($17 AS boolean)
                        THEN CAST($18 AS uuid)
                    ELSE authorized.key_result_id
                END
              AND key_result.objective_id = CASE
                    WHEN CAST($13 AS boolean)
                        THEN CAST($14 AS uuid)
                    ELSE authorized.objective_id
                END
        )
    )
), updated AS (
    UPDATE public.stories AS story
    SET
        title = CASE WHEN CAST($19 AS boolean) THEN CAST($20 AS text) ELSE story.title END,
        estimate_unit = CASE WHEN CAST($21 AS boolean) THEN $22 ELSE story.estimate_unit END,
        estimated_duration_minutes = CASE WHEN CAST($23 AS boolean) THEN $24 ELSE story.estimated_duration_minutes END,
        minimum_focus_block_minutes = CASE WHEN CAST($25 AS boolean) THEN $26 ELSE story.minimum_focus_block_minutes END,
        auto_scheduling_enabled = CASE WHEN CAST($27 AS boolean) THEN CAST($28 AS boolean) ELSE story.auto_scheduling_enabled END,
        auto_scheduling_locked = CASE WHEN CAST($29 AS boolean) THEN CAST($30 AS boolean) ELSE story.auto_scheduling_locked END,
        auto_scheduling_status = CASE WHEN CAST($31 AS boolean) THEN CAST($32 AS text) ELSE story.auto_scheduling_status END,
        auto_scheduling_reason = CASE WHEN CAST($33 AS boolean) THEN $34 ELSE story.auto_scheduling_reason END,
        auto_scheduling_updated_at = CASE WHEN CAST($35 AS boolean) THEN $36 ELSE story.auto_scheduling_updated_at END,
        description = CASE WHEN CAST($37 AS boolean) THEN $38 ELSE story.description END,
        description_html = CASE WHEN CAST($39 AS boolean) THEN $40 ELSE story.description_html END,
        parent_id = CASE WHEN CAST($9 AS boolean) THEN $10 ELSE story.parent_id END,
        objective_id = CASE WHEN CAST($13 AS boolean) THEN $14 ELSE story.objective_id END,
        status_id = CASE WHEN CAST($7 AS boolean) THEN $8 ELSE story.status_id END,
        assignee_id = CASE WHEN CAST($11 AS boolean) THEN $12 ELSE story.assignee_id END,
        priority = CASE WHEN CAST($41 AS boolean) THEN CAST($42 AS text) ELSE story.priority END,
        sprint_id = CASE WHEN CAST($15 AS boolean) THEN $16 ELSE story.sprint_id END,
        key_result_id = CASE WHEN CAST($17 AS boolean) THEN $18 ELSE story.key_result_id END,
        start_date = CASE WHEN CAST($43 AS boolean) THEN $44 ELSE story.start_date END,
        end_date = CASE WHEN CAST($45 AS boolean) THEN $46 ELSE story.end_date END,
        completed_at = CASE WHEN CAST($47 AS boolean) THEN $48 ELSE story.completed_at END,
        updated_at = $49
    FROM valid
    WHERE story.id = valid.id
      AND story.workspace_id = valid.workspace_id
      AND story.updated_at = $50
    RETURNING story.id, story.assignee_id, story.updated_at
), removed_assignee_collaboration AS (
    DELETE FROM public.story_collaborators AS collaborator
    USING updated
    WHERE collaborator.story_id = updated.id
      AND collaborator.user_id = updated.assignee_id
)
SELECT
    EXISTS (SELECT 1 FROM target) AS story_exists,
    EXISTS (SELECT 1 FROM authorized) AS actor_authorized,
    EXISTS (SELECT 1 FROM valid) AS references_valid,
    EXISTS (SELECT 1 FROM updated) AS story_updated
`

type ApplyStoryPatchParams struct {
	StoryID                     uuid.UUID
	WorkspaceID                 uuid.UUID
	ActorKind                   string
	ActorID                     uuid.UUID
	ActorCredentialID           uuid.UUID
	Now                         time.Time
	SetStatusID                 bool
	StatusID                    *uuid.UUID
	SetParentID                 bool
	ParentID                    *uuid.UUID
	SetAssigneeID               bool
	AssigneeID                  *uuid.UUID
	SetObjectiveID              bool
	ObjectiveID                 *uuid.UUID
	SetSprintID                 bool
	SprintID                    *uuid.UUID
	SetKeyResultID              bool
	KeyResultID                 *uuid.UUID
	SetTitle                    bool
	Title                       string
	SetEstimateUnit             bool
	EstimateUnit                *int16
	SetEstimatedDurationMinutes bool
	EstimatedDurationMinutes    *int32
	SetMinimumFocusBlockMinutes bool
	MinimumFocusBlockMinutes    *int32
	SetAutoSchedulingEnabled    bool
	AutoSchedulingEnabled       bool
	SetAutoSchedulingLocked     bool
	AutoSchedulingLocked        bool
	SetAutoSchedulingStatus     bool
	AutoSchedulingStatus        string
	SetAutoSchedulingReason     bool
	AutoSchedulingReason        *string
	SetAutoSchedulingUpdatedAt  bool
	AutoSchedulingUpdatedAt     *time.Time
	SetDescription              bool
	Description                 *string
	SetDescriptionHtml          bool
	DescriptionHtml             *string
	SetPriority                 bool
	Priority                    string
	SetStartDate                bool
	StartDate                   *time.Time
	SetEndDate                  bool
	EndDate                     *time.Time
	SetCompletedAt              bool
	CompletedAt                 *time.Time
	UpdatedAt                   time.Time
	ExpectedUpdatedAt           time.Time
}

type ApplyStoryPatchRow struct {
	StoryExists     bool
	ActorAuthorized bool
	ReferencesValid bool
	StoryUpdated    bool
}

func (q *Queries) ApplyStoryPatch(ctx context.Context, arg ApplyStoryPatchParams) (ApplyStoryPatchRow, error) {
	row := q.db.QueryRow(ctx, applyStoryPatch,
		arg.StoryID,
		arg.WorkspaceID,
		arg.ActorKind,
		arg.ActorID,
		arg.ActorCredentialID,
		arg.Now,
		arg.SetStatusID,
		arg.StatusID,
		arg.SetParentID,
		arg.ParentID,
		arg.SetAssigneeID,
		arg.AssigneeID,
		arg.SetObjectiveID,
		arg.ObjectiveID,
		arg.SetSprintID,
		arg.SprintID,
		arg.SetKeyResultID,
		arg.KeyResultID,
		arg.SetTitle,
		arg.Title,
		arg.SetEstimateUnit,
		arg.EstimateUnit,
		arg.SetEstimatedDurationMinutes,
		arg.EstimatedDurationMinutes,
		arg.SetMinimumFocusBlockMinutes,
		arg.MinimumFocusBlockMinutes,
		arg.SetAutoSchedulingEnabled,
		arg.AutoSchedulingEnabled,
		arg.SetAutoSchedulingLocked,
		arg.AutoSchedulingLocked,
		arg.SetAutoSchedulingStatus,
		arg.AutoSchedulingStatus,
		arg.SetAutoSchedulingReason,
		arg.AutoSchedulingReason,
		arg.SetAutoSchedulingUpdatedAt,
		arg.AutoSchedulingUpdatedAt,
		arg.SetDescription,
		arg.Description,
		arg.SetDescriptionHtml,
		arg.DescriptionHtml,
		arg.SetPriority,
		arg.Priority,
		arg.SetStartDate,
		arg.StartDate,
		arg.SetEndDate,
		arg.EndDate,
		arg.SetCompletedAt,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ExpectedUpdatedAt,
	)
	var i ApplyStoryPatchRow
	err := row.Scan(
		&i.StoryExists,
		&i.ActorAuthorized,
		&i.ReferencesValid,
		&i.StoryUpdated,
	)
	return i, err
}

const authorizeStoryCreate = `-- name: AuthorizeStoryCreate :one
SELECT
    team.team_id,
    CAST(COALESCE(estimation.scheme, 'tshirt') AS text) AS estimate_scheme
FROM public.teams AS team
LEFT JOIN public.team_estimation_settings AS estimation
    ON estimation.team_id = team.team_id
   AND estimation.workspace_id = team.workspace_id
WHERE team.team_id = $1
  AND team.workspace_id = $2
  AND (
      (
          CAST($3 AS text) = 'system'
          AND EXISTS (
              SELECT 1
              FROM public.users AS system_actor
              WHERE system_actor.user_id = $4
                AND system_actor.is_active = TRUE
                AND system_actor.is_system = TRUE
          )
      ) OR (
          CAST($3 AS text) IN ('human_user', 'oauth_user')
          AND EXISTS (
              SELECT 1
              FROM public.users AS account
              INNER JOIN public.workspace_members AS workspace_member
                  ON workspace_member.workspace_id = team.workspace_id
                 AND workspace_member.user_id = account.user_id
              INNER JOIN public.team_members AS team_member
                  ON team_member.team_id = team.team_id
                 AND team_member.user_id = account.user_id
              WHERE account.user_id = $4
                AND account.is_active = TRUE
          )
      ) OR (
          CAST($3 AS text) = 'personal_token'
          AND EXISTS (
              SELECT 1
              FROM public.api_credentials AS credential
              INNER JOIN public.principals AS principal
                  ON principal.principal_id = credential.principal_id
                 AND principal.workspace_id = credential.workspace_id
              INNER JOIN public.users AS account
                  ON account.user_id = principal.subject_user_id
                 AND account.is_active = TRUE
              INNER JOIN public.workspace_members AS workspace_member
                  ON workspace_member.workspace_id = team.workspace_id
                 AND workspace_member.user_id = account.user_id
              INNER JOIN public.team_members AS team_member
                  ON team_member.team_id = team.team_id
                 AND team_member.user_id = account.user_id
              WHERE credential.credential_id = $5
                AND credential.workspace_id = team.workspace_id
                AND credential.kind = 'personal_access_token'
                AND credential.revoked_at IS NULL
                AND credential.expires_at > $6
                AND principal.status = 'active'
                AND principal.subject_user_id = $4
                AND EXISTS (
                    SELECT 1
                    FROM public.api_credential_scopes AS credential_scope
                    WHERE credential_scope.credential_id = credential.credential_id
                      AND credential_scope.scope = 'stories:write'
                )
                AND (
                    NOT EXISTS (
                        SELECT 1
                        FROM public.api_credential_team_restrictions AS restriction
                        WHERE restriction.credential_id = credential.credential_id
                    )
                    OR EXISTS (
                        SELECT 1
                        FROM public.api_credential_team_restrictions AS restriction
                        WHERE restriction.credential_id = credential.credential_id
                          AND restriction.workspace_id = team.workspace_id
                          AND restriction.team_id = team.team_id
                    )
                )
          )
      ) OR (
          CAST($3 AS text) = 'service_account'
          AND EXISTS (
              SELECT 1
              FROM public.principals AS principal
              INNER JOIN public.api_credentials AS credential
                  ON credential.principal_id = principal.principal_id
                 AND credential.workspace_id = principal.workspace_id
              WHERE principal.principal_id = $4
                AND principal.workspace_id = team.workspace_id
                AND principal.kind = 'service_account'
                AND principal.status = 'active'
                AND credential.credential_id = $5
                AND credential.kind = 'service_account_key'
                AND credential.revoked_at IS NULL
                AND credential.expires_at > $6
                AND EXISTS (
                    SELECT 1
                    FROM public.api_credential_scopes AS credential_scope
                    WHERE credential_scope.credential_id = credential.credential_id
                      AND credential_scope.scope = 'stories:write'
                )
                AND (
                    NOT EXISTS (
                        SELECT 1
                        FROM public.api_credential_team_restrictions AS restriction
                        WHERE restriction.credential_id = credential.credential_id
                    )
                    OR EXISTS (
                        SELECT 1
                        FROM public.api_credential_team_restrictions AS restriction
                        WHERE restriction.credential_id = credential.credential_id
                          AND restriction.workspace_id = team.workspace_id
                          AND restriction.team_id = team.team_id
                    )
                )
          )
      ) OR (
          CAST($3 AS text) = 'oauth_application'
          AND EXISTS (
              SELECT 1
              FROM public.oauth_application_installations AS installation
              INNER JOIN public.principals AS principal
                  ON principal.principal_id = installation.principal_id
                 AND principal.workspace_id = installation.workspace_id
              INNER JOIN public.oauth_applications AS application
                  ON application.application_id = installation.application_id
              INNER JOIN public.oauth_application_installation_scopes AS installation_scope
                  ON installation_scope.installation_id = installation.installation_id
              WHERE installation.installation_id = $5
                AND installation.workspace_id = team.workspace_id
                AND installation.principal_id = $4
                AND installation.status = 'active'
                AND principal.kind = 'oauth_application'
                AND principal.status = 'active'
                AND application.registration_kind = 'confidential'
                AND application.status = 'active'
                AND application.expires_at > $6
                AND installation_scope.scope = 'stories:write'
          )
      )
  )
`

type AuthorizeStoryCreateParams struct {
	TeamID            uuid.UUID
	WorkspaceID       uuid.UUID
	ActorKind         string
	ActorID           uuid.UUID
	ActorCredentialID uuid.UUID
	Now               time.Time
}

type AuthorizeStoryCreateRow struct {
	TeamID         uuid.UUID
	EstimateScheme string
}

func (q *Queries) AuthorizeStoryCreate(ctx context.Context, arg AuthorizeStoryCreateParams) (AuthorizeStoryCreateRow, error) {
	row := q.db.QueryRow(ctx, authorizeStoryCreate,
		arg.TeamID,
		arg.WorkspaceID,
		arg.ActorKind,
		arg.ActorID,
		arg.ActorCredentialID,
		arg.Now,
	)
	var i AuthorizeStoryCreateRow
	err := row.Scan(&i.TeamID, &i.EstimateScheme)
	return i, err
}

const createStoryMutation = `-- name: CreateStoryMutation :one
INSERT INTO public.stories (
    id,
    sequence_id,
    title,
    description,
    description_html,
    parent_id,
    objective_id,
    status_id,
    assignee_id,
    blocked_by_id,
    blocking_id,
    related_id,
    reporter_id,
    priority,
    estimate_unit,
    estimated_duration_minutes,
    minimum_focus_block_minutes,
    auto_scheduling_enabled,
    auto_scheduling_locked,
    auto_scheduling_status,
    auto_scheduling_reason,
    auto_scheduling_updated_at,
    sprint_id,
    key_result_id,
    team_id,
    workspace_id,
    start_date,
    end_date,
    external_creation_key,
    created_at,
    updated_at
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31
WHERE (
        CAST($8 AS uuid) IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.statuses AS status
            WHERE status.status_id = $8
              AND status.team_id = $25
        )
    )
  AND (
        CAST($9 AS uuid) IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.users AS assignee
            WHERE assignee.user_id = $9
              AND assignee.is_active = TRUE
              AND (
                  assignee.is_system = TRUE
                  OR (
                      EXISTS (
                          SELECT 1
                          FROM public.workspace_members AS workspace_member
                          WHERE workspace_member.workspace_id = $26
                            AND workspace_member.user_id = assignee.user_id
                      )
                      AND EXISTS (
                          SELECT 1
                          FROM public.team_members AS team_member
                          WHERE team_member.team_id = $25
                            AND team_member.user_id = assignee.user_id
                      )
                  )
              )
        )
    )
  AND (
        CAST($13 AS uuid) IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.users AS reporter
            WHERE reporter.user_id = $13
              AND reporter.is_active = TRUE
              AND (
                  reporter.is_system = TRUE
                  OR (
                      EXISTS (
                          SELECT 1
                          FROM public.workspace_members AS workspace_member
                          WHERE workspace_member.workspace_id = $26
                            AND workspace_member.user_id = reporter.user_id
                      )
                      AND EXISTS (
                          SELECT 1
                          FROM public.team_members AS team_member
                          WHERE team_member.team_id = $25
                            AND team_member.user_id = reporter.user_id
                      )
                  )
              )
        )
    )
  AND (
        CAST($6 AS uuid) IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.stories AS parent
            WHERE parent.id = $6
              AND parent.workspace_id = $26
              AND parent.team_id = $25
              AND parent.deleted_at IS NULL
        )
    )
  AND (
        CAST($7 AS uuid) IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.objectives AS objective
            WHERE objective.objective_id = $7
              AND objective.workspace_id = $26
        )
    )
  AND (
        CAST($23 AS uuid) IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.sprints AS sprint
            WHERE sprint.sprint_id = $23
              AND sprint.workspace_id = $26
              AND sprint.team_id = $25
        )
    )
  AND (
        CAST($24 AS uuid) IS NULL
        OR EXISTS (
            SELECT 1
            FROM public.key_results AS key_result
            INNER JOIN public.objectives AS objective
                ON objective.objective_id = key_result.objective_id
               AND objective.workspace_id = $26
            WHERE key_result.id = $24
              AND key_result.objective_id = $7
        )
    )
  AND (
        (
            CAST($10 AS uuid) IS NULL
            OR EXISTS (
                SELECT 1
                FROM public.stories AS related_story
                WHERE related_story.id = $10
                  AND related_story.workspace_id = $26
                  AND related_story.team_id = $25
                  AND related_story.deleted_at IS NULL
            )
        )
        AND (
            CAST($11 AS uuid) IS NULL
            OR EXISTS (
                SELECT 1
                FROM public.stories AS related_story
                WHERE related_story.id = $11
                  AND related_story.workspace_id = $26
                  AND related_story.team_id = $25
                  AND related_story.deleted_at IS NULL
            )
        )
        AND (
            CAST($12 AS uuid) IS NULL
            OR EXISTS (
                SELECT 1
                FROM public.stories AS related_story
                WHERE related_story.id = $12
                  AND related_story.workspace_id = $26
                  AND related_story.team_id = $25
                  AND related_story.deleted_at IS NULL
            )
        )
    )
RETURNING
    id,
    sequence_id,
    title,
    description,
    description_html,
    parent_id,
    objective_id,
    status_id,
    assignee_id,
    blocked_by_id,
    blocking_id,
    related_id,
    reporter_id,
    CAST(COALESCE(priority, 'No Priority') AS text) AS priority,
    estimate_unit,
    estimated_duration_minutes,
    minimum_focus_block_minutes,
    auto_scheduling_enabled,
    auto_scheduling_locked,
    auto_scheduling_status,
    auto_scheduling_reason,
    auto_scheduling_updated_at,
    sprint_id,
    key_result_id,
    team_id,
    workspace_id,
    start_date,
    end_date,
    external_creation_key,
    created_at,
    updated_at
`

type CreateStoryMutationParams struct {
	StoryID                  uuid.UUID
	SequenceID               *int32
	Title                    string
	Description              *string
	DescriptionHtml          *string
	ParentID                 *uuid.UUID
	ObjectiveID              *uuid.UUID
	StatusID                 *uuid.UUID
	AssigneeID               *uuid.UUID
	BlockedByID              *uuid.UUID
	BlockingID               *uuid.UUID
	RelatedID                *uuid.UUID
	ReporterID               *uuid.UUID
	Priority                 *string
	EstimateUnit             *int16
	EstimatedDurationMinutes *int32
	MinimumFocusBlockMinutes *int32
	AutoSchedulingEnabled    bool
	AutoSchedulingLocked     bool
	AutoSchedulingStatus     string
	AutoSchedulingReason     *string
	AutoSchedulingUpdatedAt  *time.Time
	SprintID                 *uuid.UUID
	KeyResultID              *uuid.UUID
	TeamID                   uuid.UUID
	WorkspaceID              uuid.UUID
	StartDate                *time.Time
	EndDate                  *time.Time
	ExternalCreationKey      *string
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

type CreateStoryMutationRow struct {
	ID                       uuid.UUID
	SequenceID               *int32
	Title                    string
	Description              *string
	DescriptionHtml          *string
	ParentID                 *uuid.UUID
	ObjectiveID              *uuid.UUID
	StatusID                 *uuid.UUID
	AssigneeID               *uuid.UUID
	BlockedByID              *uuid.UUID
	BlockingID               *uuid.UUID
	RelatedID                *uuid.UUID
	ReporterID               *uuid.UUID
	Priority                 string
	EstimateUnit             *int16
	EstimatedDurationMinutes *int32
	MinimumFocusBlockMinutes *int32
	AutoSchedulingEnabled    bool
	AutoSchedulingLocked     bool
	AutoSchedulingStatus     string
	AutoSchedulingReason     *string
	AutoSchedulingUpdatedAt  *time.Time
	SprintID                 *uuid.UUID
	KeyResultID              *uuid.UUID
	TeamID                   uuid.UUID
	WorkspaceID              uuid.UUID
	StartDate                *time.Time
	EndDate                  *time.Time
	ExternalCreationKey      *string
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

func (q *Queries) CreateStoryMutation(ctx context.Context, arg CreateStoryMutationParams) (CreateStoryMutationRow, error) {
	row := q.db.QueryRow(ctx, createStoryMutation,
		arg.StoryID,
		arg.SequenceID,
		arg.Title,
		arg.Description,
		arg.DescriptionHtml,
		arg.ParentID,
		arg.ObjectiveID,
		arg.StatusID,
		arg.AssigneeID,
		arg.BlockedByID,
		arg.BlockingID,
		arg.RelatedID,
		arg.ReporterID,
		arg.Priority,
		arg.EstimateUnit,
		arg.EstimatedDurationMinutes,
		arg.MinimumFocusBlockMinutes,
		arg.AutoSchedulingEnabled,
		arg.AutoSchedulingLocked,
		arg.AutoSchedulingStatus,
		arg.AutoSchedulingReason,
		arg.AutoSchedulingUpdatedAt,
		arg.SprintID,
		arg.KeyResultID,
		arg.TeamID,
		arg.WorkspaceID,
		arg.StartDate,
		arg.EndDate,
		arg.ExternalCreationKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateStoryMutationRow
	err := row.Scan(
		&i.ID,
		&i.SequenceID,
		&i.Title,
		&i.Description,
		&i.DescriptionHtml,
		&i.ParentID,
		&i.ObjectiveID,
		&i.StatusID,
		&i.AssigneeID,
		&i.BlockedByID,
		&i.BlockingID,
		&i.RelatedID,
		&i.ReporterID,
		&i.Priority,
		&i.EstimateUnit,
		&i.EstimatedDurationMinutes,
		&i.MinimumFocusBlockMinutes,
		&i.AutoSchedulingEnabled,
		&i.AutoSchedulingLocked,
		&i.AutoSchedulingStatus,
		&i.AutoSchedulingReason,
		&i.AutoSchedulingUpdatedAt,
		&i.SprintID,
		&i.KeyResultID,
		&i.TeamID,
		&i.WorkspaceID,
		&i.StartDate,
		&i.EndDate,
		&i.ExternalCreationKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStoryMediaLink = `-- name: DeleteStoryMediaLink :execrows
DELETE FROM public.story_inline_attachments
WHERE story_id = $1
  AND attachment_id = $2
`

type DeleteStoryMediaLinkParams struct {
	StoryID            uuid.UUID
	TargetAttachmentID uuid.UUID
}

func (q *Queries) DeleteStoryMediaLink(ctx context.Context, arg DeleteStoryMediaLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStoryMediaLink, arg.StoryID, arg.TargetAttachmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStoryMutation = `-- name: DeleteStoryMutation :one
WITH target AS (
    SELECT story.id, story.sequence_id, story.team_id, story.title, story.description, story.description_html, story.parent_id, story.objective_id, story.status_id, story.assignee_id, story.blocked_by_id, story.blocking_id, story.related_id, story.reporter_id, story.priority, story.sprint_id, story.workspace_id, story.start_date, story.end_date, story.estimate, story.archived_at, story.is_draft, story.created_at, story.updated_at, story.deleted_at, story.search_vector, story.key_result_id, story.completed_at, story.estimate_unit, story.external_creation_key, story.estimated_duration_minutes, story.minimum_focus_block_minutes, story.auto_scheduling_enabled, story.auto_scheduling_locked, story.auto_scheduling_status, story.auto_scheduling_reason, story.auto_scheduling_updated_at
    FROM public.stories AS story
    WHERE story.id = $1
      AND story.workspace_id = $2
      AND story.deleted_at IS NULL
), authorized AS (
    SELECT target.id, target.sequence_id, target.team_id, target.title, target.description, target.description_html, target.parent_id, target.objective_id, target.status_id, target.assignee_id, target.blocked_by_id, target.blocking_id, target.related_id, target.reporter_id, target.priority, target.sprint_id, target.workspace_id, target.start_date, target.end_date, target.estimate, target.archived_at, target.is_draft, target.created_at, target.updated_at, target.deleted_at, target.search_vector, target.key_result_id, target.completed_at, target.estimate_unit, target.external_creation_key, target.estimated_duration_minutes, target.minimum_focus_block_minutes, target.auto_scheduling_enabled, target.auto_scheduling_locked, target.auto_scheduling_status, target.auto_scheduling_reason, target.auto_scheduling_updated_at
    FROM target
    WHERE (
        CAST($3 AS text) = 'system'
        AND EXISTS (
            SELECT 1
            FROM public.users AS system_actor
            WHERE system_actor.user_id = $4
              AND system_actor.is_active = TRUE
              AND system_actor.is_system = TRUE
        )
    ) OR (
        CAST($3 AS text) IN ('human_user', 'oauth_user')
        AND EXISTS (
            SELECT 1
            FROM public.users AS account
            INNER JOIN public.workspace_members AS workspace_member
                ON workspace_member.workspace_id = target.workspace_id
               AND workspace_member.user_id = account.user_id
            INNER JOIN public.team_members AS team_member
                ON team_member.team_id = target.team_id
               AND team_member.user_id = account.user_id
            WHERE account.user_id = $4
              AND account.is_active = TRUE
        )
    ) OR (
        CAST($3 AS text) = 'personal_token'
        AND EXISTS (
            SELECT 1
            FROM public.api_credentials AS credential
            INNER JOIN public.principals AS principal
                ON principal.principal_id = credential.principal_id
               AND principal.workspace_id = credential.workspace_id
            INNER JOIN public.users AS account
                ON account.user_id = principal.subject_user_id
               AND account.is_active = TRUE
            INNER JOIN public.workspace_members AS workspace_member
                ON workspace_member.workspace_id = target.workspace_id
               AND workspace_member.user_id = account.user_id
            INNER JOIN public.team_members AS team_member
                ON team_member.team_id = target.team_id
               AND team_member.user_id = account.user_id
            WHERE credential.credential_id = $5
              AND credential.workspace_id = target.workspace_id
              AND credential.kind = 'personal_access_token'
              AND credential.revoked_at IS NULL
              AND credential.expires_at > $6
              AND principal.status = 'active'
              AND principal.subject_user_id = $4
              AND EXISTS (
                  SELECT 1
                  FROM public.api_credential_scopes AS credential_scope
                  WHERE credential_scope.credential_id = credential.credential_id
                    AND credential_scope.scope = 'stories:write'
              )
              AND (
                  NOT EXISTS (
                      SELECT 1
                      FROM public.api_credential_team_restrictions AS restriction
                      WHERE restriction.credential_id = credential.credential_id
                  )
                  OR EXISTS (
                      SELECT 1
                      FROM public.api_credential_team_restrictions AS restriction
                      WHERE restriction.credential_id = credential.credential_id
                        AND restriction.workspace_id = target.workspace_id
                        AND restriction.team_id = target.team_id
                  )
              )
        )
    )
), permitted AS (
    SELECT authorized.id, authorized.sequence_id, authorized.team_id, authorized.title, authorized.description, authorized.description_html, authorized.parent_id, authorized.objective_id, authorized.status_id, authorized.assignee_id, authorized.blocked_by_id, authorized.blocking_id, authorized.related_id, authorized.reporter_id, authorized.priority, authorized.sprint_id, authorized.workspace_id, authorized.start_date, authorized.end_date, authorized.estimate, authorized.archived_at, authorized.is_draft, authorized.created_at, authorized.updated_at, authorized.deleted_at, authorized.search_vector, authorized.key_result_id, authorized.completed_at, authorized.estimate_unit, authorized.external_creation_key, authorized.estimated_duration_minutes, authorized.minimum_focus_block_minutes, authorized.auto_scheduling_enabled, authorized.auto_scheduling_locked, authorized.auto_scheduling_status, authorized.auto_scheduling_reason, authorized.auto_scheduling_updated_at
    FROM authorized
    WHERE CAST($3 AS text) = 'system'
       OR authorized.reporter_id = $4
       OR EXISTS (
           SELECT 1
           FROM public.workspace_members AS workspace_member
           WHERE workspace_member.workspace_id = authorized.workspace_id
             AND workspace_member.user_id = $4
             AND workspace_member.role = 'admin'
       )
), deleted AS (
    UPDATE public.stories AS story
    SET
        deleted_at = $7,
        updated_at = $7
    FROM permitted
    WHERE story.id = permitted.id
      AND story.workspace_id = permitted.workspace_id
      AND story.updated_at = $8
      AND story.deleted_at IS NULL
    RETURNING story.id, story.deleted_at, story.updated_at
)
SELECT
    EXISTS (SELECT 1 FROM target) AS story_exists,
    EXISTS (SELECT 1 FROM authorized) AS actor_authorized,
    EXISTS (SELECT 1 FROM permitted) AS deletion_permitted,
    EXISTS (SELECT 1 FROM deleted) AS story_deleted,
    (SELECT deleted_at FROM deleted) AS deleted_at
`

type DeleteStoryMutationParams struct {
	StoryID           uuid.UUID
	WorkspaceID       uuid.UUID
	ActorKind         string
	ActorID           uuid.UUID
	ActorCredentialID uuid.UUID
	Now               time.Time
	DeletedAt         *time.Time
	ExpectedUpdatedAt time.Time
}

type DeleteStoryMutationRow struct {
	StoryExists       bool
	ActorAuthorized   bool
	DeletionPermitted bool
	StoryDeleted      bool
	DeletedAt         *time.Time
}

func (q *Queries) DeleteStoryMutation(ctx context.Context, arg DeleteStoryMutationParams) (DeleteStoryMutationRow, error) {
	row := q.db.QueryRow(ctx, deleteStoryMutation,
		arg.StoryID,
		arg.WorkspaceID,
		arg.ActorKind,
		arg.ActorID,
		arg.ActorCredentialID,
		arg.Now,
		arg.DeletedAt,
		arg.ExpectedUpdatedAt,
	)
	var i DeleteStoryMutationRow
	err := row.Scan(
		&i.StoryExists,
		&i.ActorAuthorized,
		&i.DeletionPermitted,
		&i.StoryDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const getOAuthApplicationStoryCreationReplay = `-- name: GetOAuthApplicationStoryCreationReplay :one
SELECT
    story.id,
    story.sequence_id,
    story.team_id,
    story.title,
    story.description,
    story.description_html,
    story.parent_id,
    story.objective_id,
    story.status_id,
    story.assignee_id,
    story.reporter_id,
    CAST(COALESCE(story.priority, 'No Priority') AS text) AS priority,
    story.sprint_id,
    story.key_result_id,
    story.estimate_unit,
    CAST(COALESCE((
        SELECT estimation.scheme
        FROM public.team_estimation_settings AS estimation
        WHERE estimation.team_id = story.team_id
          AND estimation.workspace_id = story.workspace_id
    ), 'tshirt') AS text) AS estimate_scheme,
    story.estimated_duration_minutes,
    story.minimum_focus_block_minutes,
    story.auto_scheduling_enabled,
    story.auto_scheduling_locked,
    story.auto_scheduling_status,
    story.auto_scheduling_reason,
    story.auto_scheduling_updated_at,
    story.start_date,
    story.end_date,
    story.completed_at,
    story.deleted_at,
    story.archived_at,
    story.created_at,
    story.updated_at,
    story.workspace_id,
    story.external_creation_key
FROM public.stories AS story
WHERE story.workspace_id = $1
  AND story.external_creation_key = $2
  AND story.deleted_at IS NULL
  AND CAST($3 AS text) = 'oauth_application'
  AND EXISTS (
      SELECT 1
      FROM public.oauth_application_installations AS installation
      INNER JOIN public.principals AS principal
          ON principal.principal_id = installation.principal_id
         AND principal.workspace_id = installation.workspace_id
      INNER JOIN public.oauth_applications AS application
          ON application.application_id = installation.application_id
      INNER JOIN public.oauth_application_installation_scopes AS installation_scope
          ON installation_scope.installation_id = installation.installation_id
      WHERE installation.installation_id = $4
        AND installation.workspace_id = story.workspace_id
        AND installation.principal_id = $5
        AND installation.status = 'active'
        AND principal.kind = 'oauth_application'
        AND principal.status = 'active'
        AND application.registration_kind = 'confidential'
        AND application.status = 'active'
        AND application.expires_at > $6
        AND installation_scope.scope = 'stories:write'
  )
ORDER BY story.id
LIMIT 1
`

type GetOAuthApplicationStoryCreationReplayParams struct {
	WorkspaceID         uuid.UUID
	ExternalCreationKey *string
	ActorKind           string
	ActorCredentialID   uuid.UUID
	ActorID             uuid.UUID
	Now                 time.Time
}

type GetOAuthApplicationStoryCreationReplayRow struct {
	ID                       uuid.UUID
	SequenceID               *int32
	TeamID                   uuid.UUID
	Title                    string
	Description              *string
	DescriptionHtml          *string
	ParentID                 *uuid.UUID
	ObjectiveID              *uuid.UUID
	StatusID                 *uuid.UUID
	AssigneeID               *uuid.UUID
	ReporterID               *uuid.UUID
	Priority                 string
	SprintID                 *uuid.UUID
	KeyResultID              *uuid.UUID
	EstimateUnit             *int16
	EstimateScheme           string
	EstimatedDurationMinutes *int32
	MinimumFocusBlockMinutes *int32
	AutoSchedulingEnabled    bool
	AutoSchedulingLocked     bool
	AutoSchedulingStatus     string
	AutoSchedulingReason     *string
	AutoSchedulingUpdatedAt  *time.Time
	StartDate                *time.Time
	EndDate                  *time.Time
	CompletedAt              *time.Time
	DeletedAt                *time.Time
	ArchivedAt               *time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
	WorkspaceID              uuid.UUID
	ExternalCreationKey      *string
}

func (q *Queries) GetOAuthApplicationStoryCreationReplay(ctx context.Context, arg GetOAuthApplicationStoryCreationReplayParams) (GetOAuthApplicationStoryCreationReplayRow, error) {
	row := q.db.QueryRow(ctx, getOAuthApplicationStoryCreationReplay,
		arg.WorkspaceID,
		arg.ExternalCreationKey,
		arg.ActorKind,
		arg.ActorCredentialID,
		arg.ActorID,
		arg.Now,
	)
	var i GetOAuthApplicationStoryCreationReplayRow
	err := row.Scan(
		&i.ID,
		&i.SequenceID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.DescriptionHtml,
		&i.ParentID,
		&i.ObjectiveID,
		&i.StatusID,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Priority,
		&i.SprintID,
		&i.KeyResultID,
		&i.EstimateUnit,
		&i.EstimateScheme,
		&i.EstimatedDurationMinutes,
		&i.MinimumFocusBlockMinutes,
		&i.AutoSchedulingEnabled,
		&i.AutoSchedulingLocked,
		&i.AutoSchedulingStatus,
		&i.AutoSchedulingReason,
		&i.AutoSchedulingUpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.ExternalCreationKey,
	)
	return i, err
}

const getStoryIDByCreationKey = `-- name: GetStoryIDByCreationKey :one
SELECT story.id
FROM public.stories AS story
WHERE story.workspace_id = $1
  AND story.external_creation_key = $2
ORDER BY story.id
LIMIT 1
`

type GetStoryIDByCreationKeyParams struct {
	WorkspaceID         uuid.UUID
	ExternalCreationKey *string
}

func (q *Queries) GetStoryIDByCreationKey(ctx context.Context, arg GetStoryIDByCreationKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getStoryIDByCreationKey, arg.WorkspaceID, arg.ExternalCreationKey)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getStoryMutationKeyResult = `-- name: GetStoryMutationKeyResult :one
SELECT
    key_result.objective_id,
    key_result.name
FROM public.key_results AS key_result
INNER JOIN public.objectives AS objective
    ON objective.objective_id = key_result.objective_id
WHERE key_result.id = $1
  AND objective.workspace_id = CAST($2 AS uuid)
`

type GetStoryMutationKeyResultParams struct {
	KeyResultID uuid.UUID
	WorkspaceID uuid.UUID
}

type GetStoryMutationKeyResultRow struct {
	ObjectiveID uuid.UUID
	Name        string
}

func (q *Queries) GetStoryMutationKeyResult(ctx context.Context, arg GetStoryMutationKeyResultParams) (GetStoryMutationKeyResultRow, error) {
	row := q.db.QueryRow(ctx, getStoryMutationKeyResult, arg.KeyResultID, arg.WorkspaceID)
	var i GetStoryMutationKeyResultRow
	err := row.Scan(&i.ObjectiveID, &i.Name)
	return i, err
}

const getStoryMutationSnapshot = `-- name: GetStoryMutationSnapshot :one

WITH target AS (
    SELECT story.id, story.sequence_id, story.team_id, story.title, story.description, story.description_html, story.parent_id, story.objective_id, story.status_id, story.assignee_id, story.blocked_by_id, story.blocking_id, story.related_id, story.reporter_id, story.priority, story.sprint_id, story.workspace_id, story.start_date, story.end_date, story.estimate, story.archived_at, story.is_draft, story.created_at, story.updated_at, story.deleted_at, story.search_vector, story.key_result_id, story.completed_at, story.estimate_unit, story.external_creation_key, story.estimated_duration_minutes, story.minimum_focus_block_minutes, story.auto_scheduling_enabled, story.auto_scheduling_locked, story.auto_scheduling_status, story.auto_scheduling_reason, story.auto_scheduling_updated_at
    FROM public.stories AS story
    WHERE story.id = $1
      AND story.workspace_id = $2
      AND story.deleted_at IS NULL
), authorized AS (
    SELECT target.id, target.sequence_id, target.team_id, target.title, target.description, target.description_html, target.parent_id, target.objective_id, target.status_id, target.assignee_id, target.blocked_by_id, target.blocking_id, target.related_id, target.reporter_id, target.priority, target.sprint_id, target.workspace_id, target.start_date, target.end_date, target.estimate, target.archived_at, target.is_draft, target.created_at, target.updated_at, target.deleted_at, target.search_vector, target.key_result_id, target.completed_at, target.estimate_unit, target.external_creation_key, target.estimated_duration_minutes, target.minimum_focus_block_minutes, target.auto_scheduling_enabled, target.auto_scheduling_locked, target.auto_scheduling_status, target.auto_scheduling_reason, target.auto_scheduling_updated_at
    FROM target
    WHERE (
        CAST($3 AS text) = 'system'
        AND EXISTS (
            SELECT 1
            FROM public.users AS system_actor
            WHERE system_actor.user_id = $4
              AND system_actor.is_active = TRUE
              AND system_actor.is_system = TRUE
        )
    ) OR (
        CAST($3 AS text) IN ('human_user', 'oauth_user')
        AND EXISTS (
            SELECT 1
            FROM public.users AS account
            INNER JOIN public.workspace_members AS workspace_member
                ON workspace_member.workspace_id = target.workspace_id
               AND workspace_member.user_id = account.user_id
            INNER JOIN public.team_members AS team_member
                ON team_member.team_id = target.team_id
               AND team_member.user_id = account.user_id
            WHERE account.user_id = $4
              AND account.is_active = TRUE
        )
    ) OR (
        CAST($3 AS text) = 'personal_token'
        AND EXISTS (
            SELECT 1
            FROM public.api_credentials AS credential
            INNER JOIN public.principals AS principal
                ON principal.principal_id = credential.principal_id
               AND principal.workspace_id = credential.workspace_id
            INNER JOIN public.users AS account
                ON account.user_id = principal.subject_user_id
               AND account.is_active = TRUE
            INNER JOIN public.workspace_members AS workspace_member
                ON workspace_member.workspace_id = target.workspace_id
               AND workspace_member.user_id = account.user_id
            INNER JOIN public.team_members AS team_member
                ON team_member.team_id = target.team_id
               AND team_member.user_id = account.user_id
            WHERE credential.credential_id = $5
              AND credential.workspace_id = target.workspace_id
              AND credential.kind = 'personal_access_token'
              AND credential.revoked_at IS NULL
              AND credential.expires_at > $6
              AND principal.status = 'active'
              AND principal.subject_user_id = $4
              AND EXISTS (
                  SELECT 1
                  FROM public.api_credential_scopes AS credential_scope
                  WHERE credential_scope.credential_id = credential.credential_id
                    AND credential_scope.scope = 'stories:write'
              )
              AND (
                  NOT EXISTS (
                      SELECT 1
                      FROM public.api_credential_team_restrictions AS restriction
                      WHERE restriction.credential_id = credential.credential_id
                  )
                  OR EXISTS (
                      SELECT 1
                      FROM public.api_credential_team_restrictions AS restriction
                      WHERE restriction.credential_id = credential.credential_id
                        AND restriction.workspace_id = target.workspace_id
                        AND restriction.team_id = target.team_id
                  )
              )
        )
    ) OR (
        CAST($3 AS text) = 'service_account'
        AND EXISTS (
            SELECT 1
            FROM public.principals AS principal
            INNER JOIN public.api_credentials AS credential
                ON credential.principal_id = principal.principal_id
               AND credential.workspace_id = principal.workspace_id
            WHERE principal.principal_id = $4
              AND principal.workspace_id = target.workspace_id
              AND principal.kind = 'service_account'
              AND principal.status = 'active'
              AND credential.credential_id = $5
              AND credential.kind = 'service_account_key'
              AND credential.revoked_at IS NULL
              AND credential.expires_at > $6
              AND EXISTS (
                  SELECT 1
                  FROM public.api_credential_scopes AS credential_scope
                  WHERE credential_scope.credential_id = credential.credential_id
                    AND credential_scope.scope = 'stories:write'
              )
              AND (
                  NOT EXISTS (
                      SELECT 1
                      FROM public.api_credential_team_restrictions AS restriction
                      WHERE restriction.credential_id = credential.credential_id
                  )
                  OR EXISTS (
                      SELECT 1
                      FROM public.api_credential_team_restrictions AS restriction
                      WHERE restriction.credential_id = credential.credential_id
                        AND restriction.workspace_id = target.workspace_id
                        AND restriction.team_id = target.team_id
                  )
              )
        )
    )
)
SELECT
    id,
    sequence_id,
    team_id,
    title,
    description,
    description_html,
    parent_id,
    objective_id,
    status_id,
    assignee_id,
    reporter_id,
    CAST(COALESCE(priority, 'No Priority') AS text) AS priority,
    sprint_id,
    key_result_id,
    estimate_unit,
    CAST(COALESCE((
        SELECT estimation.scheme
        FROM public.team_estimation_settings AS estimation
        WHERE estimation.team_id = authorized.team_id
          AND estimation.workspace_id = authorized.workspace_id
    ), 'tshirt') AS text) AS estimate_scheme,
    estimated_duration_minutes,
    minimum_focus_block_minutes,
    auto_scheduling_enabled,
    auto_scheduling_locked,
    auto_scheduling_status,
    auto_scheduling_reason,
    auto_scheduling_updated_at,
    start_date,
    end_date,
    completed_at,
    deleted_at,
    archived_at,
    created_at,
    updated_at,
    workspace_id,
    external_creation_key
FROM authorized
`

type GetStoryMutationSnapshotParams struct {
	StoryID           uuid.UUID
	WorkspaceID       uuid.UUID
	ActorKind         string
	ActorID           uuid.UUID
	ActorCredentialID uuid.UUID
	Now               time.Time
}

type GetStoryMutationSnapshotRow struct {
	ID                       uuid.UUID
	SequenceID               *int32
	TeamID                   uuid.UUID
	Title                    string
	Description              *string
	DescriptionHtml          *string
	ParentID                 *uuid.UUID
	ObjectiveID              *uuid.UUID
	StatusID                 *uuid.UUID
	AssigneeID               *uuid.UUID
	ReporterID               *uuid.UUID
	Priority                 string
	SprintID                 *uuid.UUID
	KeyResultID              *uuid.UUID
	EstimateUnit             *int16
	EstimateScheme           string
	EstimatedDurationMinutes *int32
	MinimumFocusBlockMinutes *int32
	AutoSchedulingEnabled    bool
	AutoSchedulingLocked     bool
	AutoSchedulingStatus     string
	AutoSchedulingReason     *string
	AutoSchedulingUpdatedAt  *time.Time
	StartDate                *time.Time
	EndDate                  *time.Time
	CompletedAt              *time.Time
	DeletedAt                *time.Time
	ArchivedAt               *time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
	WorkspaceID              uuid.UUID
	ExternalCreationKey      *string
}

// Story mutation queries deliberately repeat their authorization predicate.
// Credentials only narrow current product membership; they never replace it.
func (q *Queries) GetStoryMutationSnapshot(ctx context.Context, arg GetStoryMutationSnapshotParams) (GetStoryMutationSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getStoryMutationSnapshot,
		arg.StoryID,
		arg.WorkspaceID,
		arg.ActorKind,
		arg.ActorID,
		arg.ActorCredentialID,
		arg.Now,
	)
	var i GetStoryMutationSnapshotRow
	err := row.Scan(
		&i.ID,
		&i.SequenceID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.DescriptionHtml,
		&i.ParentID,
		&i.ObjectiveID,
		&i.StatusID,
		&i.AssigneeID,
		&i.ReporterID,
		&i.Priority,
		&i.SprintID,
		&i.KeyResultID,
		&i.EstimateUnit,
		&i.EstimateScheme,
		&i.EstimatedDurationMinutes,
		&i.MinimumFocusBlockMinutes,
		&i.AutoSchedulingEnabled,
		&i.AutoSchedulingLocked,
		&i.AutoSchedulingStatus,
		&i.AutoSchedulingReason,
		&i.AutoSchedulingUpdatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.ExternalCreationKey,
	)
	return i, err
}

const insertAuthorizedStoryLabels = `-- name: InsertAuthorizedStoryLabels :many
INSERT INTO public.story_labels (story_id, label_id)
SELECT
    $1,
    label.label_id
FROM public.labels AS label
WHERE label.label_id = ANY(CAST($2 AS uuid[]))
  AND label.workspace_id = $3
  AND (label.team_id = $4 OR label.team_id IS NULL)
ORDER BY label.label_id
ON CONFLICT (story_id, label_id) DO NOTHING
RETURNING label_id
`

type InsertAuthorizedStoryLabelsParams struct {
	StoryID     uuid.UUID
	LabelIds    []uuid.UUID
	WorkspaceID *uuid.UUID
	TeamID      *uuid.UUID
}

func (q *Queries) InsertAuthorizedStoryLabels(ctx context.Context, arg InsertAuthorizedStoryLabelsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, insertAuthorizedStoryLabels,
		arg.StoryID,
		arg.LabelIds,
		arg.WorkspaceID,
		arg.TeamID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var label_id uuid.UUID
		if err := rows.Scan(&label_id); err != nil {
			return nil, err
		}
		items = append(items, label_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertStoryMutationEvent = `-- name: InsertStoryMutationEvent :exec
INSERT INTO public.story_mutation_events (
    event_id,
    workspace_id,
    story_id,
    event_type,
    actor_kind,
    actor_id,
    actor_credential_id,
    payload,
    occurred_at,
    status,
    attempt_count,
    next_attempt_at,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    'pending',
    0,
    $10,
    $10,
    $10
)
`

type InsertStoryMutationEventParams struct {
	EventID           uuid.UUID
	WorkspaceID       uuid.UUID
	StoryID           uuid.UUID
	EventType         string
	ActorKind         string
	ActorID           uuid.UUID
	ActorCredentialID *uuid.UUID
	Payload           []byte
	OccurredAt        time.Time
	CreatedAt         time.Time
}

func (q *Queries) InsertStoryMutationEvent(ctx context.Context, arg InsertStoryMutationEventParams) error {
	_, err := q.db.Exec(ctx, insertStoryMutationEvent,
		arg.EventID,
		arg.WorkspaceID,
		arg.StoryID,
		arg.EventType,
		arg.ActorKind,
		arg.ActorID,
		arg.ActorCredentialID,
		arg.Payload,
		arg.OccurredAt,
		arg.CreatedAt,
	)
	return err
}

const lockStoryMediaLinks = `-- name: LockStoryMediaLinks :many
SELECT
    media.attachment_id,
    attachment.mime_type
FROM public.story_inline_attachments AS media
INNER JOIN public.attachments AS attachment
    ON attachment.attachment_id = media.attachment_id
   AND attachment.workspace_id = $1
WHERE media.story_id = $2
ORDER BY media.attachment_id
FOR UPDATE OF media, attachment
`

type LockStoryMediaLinksParams struct {
	WorkspaceID uuid.UUID
	StoryID     uuid.UUID
}

type LockStoryMediaLinksRow struct {
	AttachmentID uuid.UUID
	MimeType     string
}

func (q *Queries) LockStoryMediaLinks(ctx context.Context, arg LockStoryMediaLinksParams) ([]LockStoryMediaLinksRow, error) {
	rows, err := q.db.Query(ctx, lockStoryMediaLinks, arg.WorkspaceID, arg.StoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockStoryMediaLinksRow{}
	for rows.Next() {
		var i LockStoryMediaLinksRow
		if err := rows.Scan(&i.AttachmentID, &i.MimeType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextStorySequence = `-- name: NextStorySequence :one
INSERT INTO public.team_story_sequences (
    workspace_id,
    team_id,
    current_sequence
) VALUES (
    $1,
    $2,
    1
)
ON CONFLICT (workspace_id, team_id)
DO UPDATE SET current_sequence = team_story_sequences.current_sequence + 1
RETURNING current_sequence
`

type NextStorySequenceParams struct {
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
}

func (q *Queries) NextStorySequence(ctx context.Context, arg NextStorySequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextStorySequence, arg.WorkspaceID, arg.TeamID)
	var current_sequence int32
	err := row.Scan(&current_sequence)
	return current_sequence, err
}

const storyMediaAttachmentIsOrphaned = `-- name: StoryMediaAttachmentIsOrphaned :one
SELECT
    NOT EXISTS (
        SELECT 1
        FROM public.story_inline_attachments AS inline_attachment
        WHERE inline_attachment.attachment_id = $1
    )
    AND NOT EXISTS (
        SELECT 1
        FROM public.story_attachments AS story_attachment
        WHERE story_attachment.attachment_id = $1
    )
    AND NOT EXISTS (
        SELECT 1
        FROM public.document_attachments AS document_attachment
        WHERE document_attachment.attachment_id = $1
    ) AS orphaned
`

type StoryMediaAttachmentIsOrphanedParams struct {
	TargetAttachmentID uuid.UUID
}

func (q *Queries) StoryMediaAttachmentIsOrphaned(ctx context.Context, arg StoryMediaAttachmentIsOrphanedParams) (*bool, error) {
	row := q.db.QueryRow(ctx, storyMediaAttachmentIsOrphaned, arg.TargetAttachmentID)
	var orphaned *bool
	err := row.Scan(&orphaned)
	return orphaned, err
}

const synchronizeStorySequence = `-- name: SynchronizeStorySequence :exec
INSERT INTO public.team_story_sequences (
    workspace_id,
    team_id,
    current_sequence
)
SELECT
    $1,
    $2,
    CAST(COALESCE(MAX(story.sequence_id), 0) AS integer)
FROM public.stories AS story
WHERE story.workspace_id = $1
  AND story.team_id = $2
ON CONFLICT (workspace_id, team_id)
DO UPDATE SET current_sequence = GREATEST(
    team_story_sequences.current_sequence,
    EXCLUDED.current_sequence
)
`

type SynchronizeStorySequenceParams struct {
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
}

func (q *Queries) SynchronizeStorySequence(ctx context.Context, arg SynchronizeStorySequenceParams) error {
	_, err := q.db.Exec(ctx, synchronizeStorySequence, arg.WorkspaceID, arg.TeamID)
	return err
}

const upsertStoryMutationActivity = `-- name: UpsertStoryMutationActivity :one
WITH compacted AS (
    UPDATE public.story_activities AS activity
    SET
        current_value = $1,
        new_value = $2,
        reason = COALESCE($3, activity.reason),
        created_at = CAST($4 AS timestamp)
    WHERE activity.activity_id = (
        SELECT candidate.activity_id
        FROM public.story_activities AS candidate
        WHERE candidate.story_id = $5
          AND candidate.user_id = $6
          AND candidate.workspace_id = $7
          AND candidate.activity_type = $8
          AND candidate.field_changed = $9
          AND candidate.created_at >= CAST($4 AS timestamp) - INTERVAL '30 seconds'
        ORDER BY candidate.created_at DESC, candidate.activity_id DESC
        LIMIT 1
        FOR UPDATE
    )
      AND CAST($10 AS boolean)
    RETURNING activity.activity_id, activity.story_id, activity.activity_type, activity.field_changed, activity.current_value, activity.user_id, activity.created_at, activity.workspace_id, activity.old_value, activity.new_value, activity.reason
), inserted AS (
    INSERT INTO public.story_activities (
        activity_id,
        story_id,
        activity_type,
        field_changed,
        current_value,
        old_value,
        new_value,
        reason,
        user_id,
        workspace_id,
        created_at
    )
    SELECT
        $11,
        $5,
        $8,
        $9,
        $1,
        $12,
        $2,
        $3,
        $6,
        $7,
        CAST($4 AS timestamp)
    WHERE NOT EXISTS (SELECT 1 FROM compacted)
    RETURNING story_activities.activity_id, story_activities.story_id, story_activities.activity_type, story_activities.field_changed, story_activities.current_value, story_activities.user_id, story_activities.created_at, story_activities.workspace_id, story_activities.old_value, story_activities.new_value, story_activities.reason
)
SELECT activity_id, story_id, activity_type, field_changed, current_value, user_id, created_at, workspace_id, old_value, new_value, reason FROM compacted
UNION ALL
SELECT activity_id, story_id, activity_type, field_changed, current_value, user_id, created_at, workspace_id, old_value, new_value, reason FROM inserted
`

type UpsertStoryMutationActivityParams struct {
	CurrentValue string
	NewValue     []byte
	Reason       *string
	CreatedAt    time.Time
	StoryID      uuid.UUID
	UserID       uuid.UUID
	WorkspaceID  *uuid.UUID
	ActivityType string
	FieldChanged string
	Compact      bool
	ActivityID   uuid.UUID
	OldValue     []byte
}

type UpsertStoryMutationActivityRow struct {
	ActivityID   uuid.UUID
	StoryID      uuid.UUID
	ActivityType string
	FieldChanged string
	CurrentValue string
	UserID       uuid.UUID
	CreatedAt    time.Time
	WorkspaceID  *uuid.UUID
	OldValue     []byte
	NewValue     []byte
	Reason       *string
}

func (q *Queries) UpsertStoryMutationActivity(ctx context.Context, arg UpsertStoryMutationActivityParams) (UpsertStoryMutationActivityRow, error) {
	row := q.db.QueryRow(ctx, upsertStoryMutationActivity,
		arg.CurrentValue,
		arg.NewValue,
		arg.Reason,
		arg.CreatedAt,
		arg.StoryID,
		arg.UserID,
		arg.WorkspaceID,
		arg.ActivityType,
		arg.FieldChanged,
		arg.Compact,
		arg.ActivityID,
		arg.OldValue,
	)
	var i UpsertStoryMutationActivityRow
	err := row.Scan(
		&i.ActivityID,
		&i.StoryID,
		&i.ActivityType,
		&i.FieldChanged,
		&i.CurrentValue,
		&i.UserID,
		&i.CreatedAt,
		&i.WorkspaceID,
		&i.OldValue,
		&i.NewValue,
		&i.Reason,
	)
	return i, err
}
