// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule_transition.sql

package storyreadsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimStoryScheduleTransitions = `-- name: ClaimStoryScheduleTransitions :many
WITH candidates AS (
    SELECT outbox.schedule_transition_event_id
    FROM public.story_schedule_transition_outbox AS outbox
    WHERE (
        outbox.status IN ('pending', 'retrying')
        AND outbox.next_attempt_at <= CURRENT_TIMESTAMP
    ) OR (
        outbox.status = 'processing'
        AND outbox.claimed_at <= CURRENT_TIMESTAMP - make_interval(
            secs => CAST($1 AS double precision)
        )
    )
    ORDER BY COALESCE(outbox.next_attempt_at, outbox.claimed_at), outbox.created_at, outbox.schedule_transition_event_id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
UPDATE public.story_schedule_transition_outbox AS outbox
SET
    status = 'processing',
    attempt_count = outbox.attempt_count + 1,
    next_attempt_at = NULL,
    claim_token = gen_random_uuid(),
    claimed_at = CURRENT_TIMESTAMP,
    completed_at = NULL,
    last_error = NULL,
    updated_at = CURRENT_TIMESTAMP
FROM candidates
WHERE outbox.schedule_transition_event_id = candidates.schedule_transition_event_id
RETURNING
    outbox.schedule_transition_event_id,
    outbox.actor_id,
    outbox.story_id,
    outbox.workspace_id,
    outbox.semantic_fingerprint,
    outbox.transition_sequence,
    outbox.claim_token,
    outbox.attempt_count,
    outbox.event_payload,
    outbox.created_at
`

type ClaimStoryScheduleTransitionsParams struct {
	StaleAfterSeconds float64
	BatchSize         int32
}

type ClaimStoryScheduleTransitionsRow struct {
	ScheduleTransitionEventID uuid.UUID
	ActorID                   uuid.UUID
	StoryID                   uuid.UUID
	WorkspaceID               uuid.UUID
	SemanticFingerprint       string
	TransitionSequence        int64
	ClaimToken                *uuid.UUID
	AttemptCount              int32
	EventPayload              []byte
	CreatedAt                 time.Time
}

func (q *Queries) ClaimStoryScheduleTransitions(ctx context.Context, arg ClaimStoryScheduleTransitionsParams) ([]ClaimStoryScheduleTransitionsRow, error) {
	rows, err := q.db.Query(ctx, claimStoryScheduleTransitions, arg.StaleAfterSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimStoryScheduleTransitionsRow{}
	for rows.Next() {
		var i ClaimStoryScheduleTransitionsRow
		if err := rows.Scan(
			&i.ScheduleTransitionEventID,
			&i.ActorID,
			&i.StoryID,
			&i.WorkspaceID,
			&i.SemanticFingerprint,
			&i.TransitionSequence,
			&i.ClaimToken,
			&i.AttemptCount,
			&i.EventPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeStoryScheduleTransition = `-- name: CompleteStoryScheduleTransition :execrows
UPDATE public.story_schedule_transition_outbox
SET
    status = 'completed',
    next_attempt_at = NULL,
    claim_token = NULL,
    claimed_at = NULL,
    completed_at = CURRENT_TIMESTAMP,
    last_error = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE schedule_transition_event_id = $1
  AND claim_token = $2
  AND status = 'processing'
`

type CompleteStoryScheduleTransitionParams struct {
	EventID    uuid.UUID
	ClaimToken *uuid.UUID
}

func (q *Queries) CompleteStoryScheduleTransition(ctx context.Context, arg CompleteStoryScheduleTransitionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeStoryScheduleTransition, arg.EventID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCompletedStoryScheduleTransitions = `-- name: DeleteCompletedStoryScheduleTransitions :execrows
WITH expired AS (
    SELECT outbox.schedule_transition_event_id
    FROM public.story_schedule_transition_outbox AS outbox
    WHERE outbox.status = 'completed'
      AND outbox.completed_at < $1
    ORDER BY outbox.completed_at, outbox.schedule_transition_event_id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
DELETE FROM public.story_schedule_transition_outbox AS outbox
USING expired
WHERE outbox.schedule_transition_event_id = expired.schedule_transition_event_id
`

type DeleteCompletedStoryScheduleTransitionsParams struct {
	CompletedBefore *time.Time
	BatchSize       int32
}

func (q *Queries) DeleteCompletedStoryScheduleTransitions(ctx context.Context, arg DeleteCompletedStoryScheduleTransitionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompletedStoryScheduleTransitions, arg.CompletedBefore, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failStoryScheduleTransition = `-- name: FailStoryScheduleTransition :execrows
UPDATE public.story_schedule_transition_outbox
SET
    status = 'failed',
    next_attempt_at = NULL,
    claim_token = NULL,
    claimed_at = NULL,
    completed_at = NULL,
    last_error = LEFT(CAST($1 AS text), 4000),
    updated_at = CURRENT_TIMESTAMP
WHERE schedule_transition_event_id = $2
  AND claim_token = $3
  AND status = 'processing'
`

type FailStoryScheduleTransitionParams struct {
	LastError  string
	EventID    uuid.UUID
	ClaimToken *uuid.UUID
}

func (q *Queries) FailStoryScheduleTransition(ctx context.Context, arg FailStoryScheduleTransitionParams) (int64, error) {
	result, err := q.db.Exec(ctx, failStoryScheduleTransition, arg.LastError, arg.EventID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestStoryScheduleTransition = `-- name: GetLatestStoryScheduleTransition :one
SELECT
    outbox.semantic_fingerprint,
    outbox.transition_sequence
FROM public.story_schedule_transition_outbox AS outbox
WHERE outbox.story_id = $1
  AND outbox.workspace_id = $2
ORDER BY outbox.transition_sequence DESC, outbox.schedule_transition_event_id DESC
LIMIT 1
`

type GetLatestStoryScheduleTransitionParams struct {
	StoryID     uuid.UUID
	WorkspaceID uuid.UUID
}

type GetLatestStoryScheduleTransitionRow struct {
	SemanticFingerprint string
	TransitionSequence  int64
}

func (q *Queries) GetLatestStoryScheduleTransition(ctx context.Context, arg GetLatestStoryScheduleTransitionParams) (GetLatestStoryScheduleTransitionRow, error) {
	row := q.db.QueryRow(ctx, getLatestStoryScheduleTransition, arg.StoryID, arg.WorkspaceID)
	var i GetLatestStoryScheduleTransitionRow
	err := row.Scan(&i.SemanticFingerprint, &i.TransitionSequence)
	return i, err
}

const insertStoryScheduleTransition = `-- name: InsertStoryScheduleTransition :exec
INSERT INTO public.story_schedule_transition_outbox (
    schedule_transition_event_id,
    actor_id,
    story_id,
    workspace_id,
    event_type,
    event_payload,
    semantic_fingerprint,
    transition_sequence,
    status,
    attempt_count,
    next_attempt_at,
    claim_token,
    claimed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'story.updated',
    $5,
    $6,
    $7,
    CASE WHEN CAST($8 AS boolean) THEN 'processing' ELSE 'pending' END,
    CASE WHEN CAST($8 AS boolean) THEN 1 ELSE 0 END,
    CASE WHEN CAST($8 AS boolean) THEN NULL ELSE CURRENT_TIMESTAMP END,
    CASE
        WHEN CAST($8 AS boolean)
        THEN CAST($9 AS uuid)
        ELSE NULL
    END,
    CASE WHEN CAST($8 AS boolean) THEN CURRENT_TIMESTAMP ELSE NULL END
)
`

type InsertStoryScheduleTransitionParams struct {
	EventID             uuid.UUID
	ActorID             uuid.UUID
	StoryID             uuid.UUID
	WorkspaceID         uuid.UUID
	EventPayload        []byte
	SemanticFingerprint string
	TransitionSequence  int64
	ClaimImmediately    bool
	ClaimToken          *uuid.UUID
}

func (q *Queries) InsertStoryScheduleTransition(ctx context.Context, arg InsertStoryScheduleTransitionParams) error {
	_, err := q.db.Exec(ctx, insertStoryScheduleTransition,
		arg.EventID,
		arg.ActorID,
		arg.StoryID,
		arg.WorkspaceID,
		arg.EventPayload,
		arg.SemanticFingerprint,
		arg.TransitionSequence,
		arg.ClaimImmediately,
		arg.ClaimToken,
	)
	return err
}

const lockStoryForScheduleTransition = `-- name: LockStoryForScheduleTransition :one
SELECT
    story.auto_scheduling_status,
    story.auto_scheduling_reason,
    story.auto_scheduling_locked
FROM public.stories AS story
WHERE story.id = $1
  AND story.workspace_id = $2
  AND story.updated_at = $3
FOR UPDATE
`

type LockStoryForScheduleTransitionParams struct {
	StoryID           uuid.UUID
	WorkspaceID       uuid.UUID
	ExpectedUpdatedAt time.Time
}

type LockStoryForScheduleTransitionRow struct {
	AutoSchedulingStatus string
	AutoSchedulingReason *string
	AutoSchedulingLocked bool
}

func (q *Queries) LockStoryForScheduleTransition(ctx context.Context, arg LockStoryForScheduleTransitionParams) (LockStoryForScheduleTransitionRow, error) {
	row := q.db.QueryRow(ctx, lockStoryForScheduleTransition, arg.StoryID, arg.WorkspaceID, arg.ExpectedUpdatedAt)
	var i LockStoryForScheduleTransitionRow
	err := row.Scan(&i.AutoSchedulingStatus, &i.AutoSchedulingReason, &i.AutoSchedulingLocked)
	return i, err
}

const retryStoryScheduleTransition = `-- name: RetryStoryScheduleTransition :execrows
UPDATE public.story_schedule_transition_outbox
SET
    status = 'retrying',
    next_attempt_at = $1,
    claim_token = NULL,
    claimed_at = NULL,
    completed_at = NULL,
    last_error = LEFT(CAST($2 AS text), 4000),
    updated_at = CURRENT_TIMESTAMP
WHERE schedule_transition_event_id = $3
  AND claim_token = $4
  AND status = 'processing'
`

type RetryStoryScheduleTransitionParams struct {
	RetryAt    *time.Time
	LastError  string
	EventID    uuid.UUID
	ClaimToken *uuid.UUID
}

func (q *Queries) RetryStoryScheduleTransition(ctx context.Context, arg RetryStoryScheduleTransitionParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryStoryScheduleTransition,
		arg.RetryAt,
		arg.LastError,
		arg.EventID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStoryScheduleTransitionState = `-- name: UpdateStoryScheduleTransitionState :execrows
UPDATE public.stories AS story
SET
    auto_scheduling_status = $1,
    auto_scheduling_reason = $2,
    auto_scheduling_updated_at = $3,
    auto_scheduling_locked = CASE
        WHEN CAST($4 AS boolean)
        THEN CAST($5 AS boolean)
        ELSE story.auto_scheduling_locked
    END
WHERE story.id = $6
  AND story.workspace_id = $7
  AND story.updated_at = $8
`

type UpdateStoryScheduleTransitionStateParams struct {
	AutoSchedulingStatus    string
	AutoSchedulingReason    *string
	AutoSchedulingUpdatedAt *time.Time
	SetAutoSchedulingLocked bool
	AutoSchedulingLocked    bool
	StoryID                 uuid.UUID
	WorkspaceID             uuid.UUID
	ExpectedUpdatedAt       time.Time
}

func (q *Queries) UpdateStoryScheduleTransitionState(ctx context.Context, arg UpdateStoryScheduleTransitionStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStoryScheduleTransitionState,
		arg.AutoSchedulingStatus,
		arg.AutoSchedulingReason,
		arg.AutoSchedulingUpdatedAt,
		arg.SetAutoSchedulingLocked,
		arg.AutoSchedulingLocked,
		arg.StoryID,
		arg.WorkspaceID,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
