// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: support_reads.sql

package storyreadsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findVisibleFirstStatusByCategory = `-- name: FindVisibleFirstStatusByCategory :one
SELECT status.status_id
FROM public.statuses AS status
INNER JOIN public.teams AS team
    ON team.team_id = status.team_id
INNER JOIN public.users AS actor
    ON actor.user_id = $1
   AND actor.is_active = TRUE
INNER JOIN public.workspace_members AS workspace_member
    ON workspace_member.workspace_id = team.workspace_id
   AND workspace_member.user_id = actor.user_id
INNER JOIN public.team_members AS team_member
    ON team_member.team_id = team.team_id
   AND team_member.user_id = actor.user_id
WHERE status.team_id = $2
  AND team.workspace_id = $3
  AND status.category = $4
  AND (
      CAST($5 AS boolean)
      OR team.team_id = ANY(CAST($6 AS uuid[]))
  )
ORDER BY status.order_index, status.status_id
LIMIT 1
`

type FindVisibleFirstStatusByCategoryParams struct {
	ActorID                uuid.UUID
	TeamID                 uuid.UUID
	WorkspaceID            uuid.UUID
	Category               *string
	UnrestrictedTeamAccess bool
	AllowedTeamIds         []uuid.UUID
}

func (q *Queries) FindVisibleFirstStatusByCategory(ctx context.Context, arg FindVisibleFirstStatusByCategoryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findVisibleFirstStatusByCategory,
		arg.ActorID,
		arg.TeamID,
		arg.WorkspaceID,
		arg.Category,
		arg.UnrestrictedTeamAccess,
		arg.AllowedTeamIds,
	)
	var status_id uuid.UUID
	err := row.Scan(&status_id)
	return status_id, err
}

const getVisibleStoryStatusCategory = `-- name: GetVisibleStoryStatusCategory :one
SELECT CAST(status.category AS text) AS category
FROM public.statuses AS status
INNER JOIN public.teams AS team
    ON team.team_id = status.team_id
INNER JOIN public.users AS actor
    ON actor.user_id = $1
   AND actor.is_active = TRUE
INNER JOIN public.workspace_members AS workspace_member
    ON workspace_member.workspace_id = team.workspace_id
   AND workspace_member.user_id = actor.user_id
INNER JOIN public.team_members AS team_member
    ON team_member.team_id = team.team_id
   AND team_member.user_id = actor.user_id
WHERE status.status_id = $2
  AND team.workspace_id = $3
  AND (
      CAST($4 AS boolean)
      OR team.team_id = ANY(CAST($5 AS uuid[]))
  )
`

type GetVisibleStoryStatusCategoryParams struct {
	ActorID                uuid.UUID
	StatusID               uuid.UUID
	WorkspaceID            uuid.UUID
	UnrestrictedTeamAccess bool
	AllowedTeamIds         []uuid.UUID
}

func (q *Queries) GetVisibleStoryStatusCategory(ctx context.Context, arg GetVisibleStoryStatusCategoryParams) (string, error) {
	row := q.db.QueryRow(ctx, getVisibleStoryStatusCategory,
		arg.ActorID,
		arg.StatusID,
		arg.WorkspaceID,
		arg.UnrestrictedTeamAccess,
		arg.AllowedTeamIds,
	)
	var category string
	err := row.Scan(&category)
	return category, err
}

const getVisibleTeamEstimateScheme = `-- name: GetVisibleTeamEstimateScheme :one

SELECT CAST(COALESCE(estimation.scheme, 'tshirt') AS text) AS estimate_scheme
FROM public.teams AS team
INNER JOIN public.users AS actor
    ON actor.user_id = $1
   AND actor.is_active = TRUE
INNER JOIN public.workspace_members AS workspace_member
    ON workspace_member.workspace_id = team.workspace_id
   AND workspace_member.user_id = actor.user_id
INNER JOIN public.team_members AS team_member
    ON team_member.team_id = team.team_id
   AND team_member.user_id = actor.user_id
LEFT JOIN public.team_estimation_settings AS estimation
    ON estimation.team_id = team.team_id
   AND estimation.workspace_id = team.workspace_id
WHERE team.team_id = $2
  AND team.workspace_id = $3
  AND (
      CAST($4 AS boolean)
      OR team.team_id = ANY(CAST($5 AS uuid[]))
  )
`

type GetVisibleTeamEstimateSchemeParams struct {
	ActorID                uuid.UUID
	TeamID                 uuid.UUID
	WorkspaceID            uuid.UUID
	UnrestrictedTeamAccess bool
	AllowedTeamIds         []uuid.UUID
}

// Small story support reads stay explicit and tenant-scoped. The service has
// already resolved the caller's actor and team-access policy; these queries
// repeat current membership checks as a persistence-level tenant fence.
func (q *Queries) GetVisibleTeamEstimateScheme(ctx context.Context, arg GetVisibleTeamEstimateSchemeParams) (string, error) {
	row := q.db.QueryRow(ctx, getVisibleTeamEstimateScheme,
		arg.ActorID,
		arg.TeamID,
		arg.WorkspaceID,
		arg.UnrestrictedTeamAccess,
		arg.AllowedTeamIds,
	)
	var estimate_scheme string
	err := row.Scan(&estimate_scheme)
	return estimate_scheme, err
}

const listVisibleStoryActivities = `-- name: ListVisibleStoryActivities :many
SELECT
    activity.activity_id,
    activity.story_id,
    activity.user_id,
    activity.activity_type,
    activity.field_changed,
    activity.current_value,
    activity.old_value,
    activity.new_value,
    activity.reason,
    activity.created_at,
    activity.workspace_id,
    account.username,
    CAST(COALESCE(account.full_name, '') AS text) AS full_name,
    CAST(COALESCE(account.avatar_url, '') AS text) AS avatar_url,
    account.is_active,
    account.is_system
FROM public.story_activities AS activity
INNER JOIN public.stories AS story
    ON story.id = activity.story_id
   AND story.workspace_id = activity.workspace_id
INNER JOIN public.users AS account
    ON account.user_id = activity.user_id
INNER JOIN public.users AS actor
    ON actor.user_id = $1
   AND actor.is_active = TRUE
INNER JOIN public.workspace_members AS workspace_member
    ON workspace_member.workspace_id = story.workspace_id
   AND workspace_member.user_id = actor.user_id
INNER JOIN public.team_members AS team_member
    ON team_member.team_id = story.team_id
   AND team_member.user_id = actor.user_id
WHERE story.id = $2
  AND story.workspace_id = $3
  AND (
      CAST($4 AS boolean)
      OR story.team_id = ANY(CAST($5 AS uuid[]))
  )
ORDER BY activity.created_at DESC, activity.activity_id DESC
LIMIT $7
OFFSET $6
`

type ListVisibleStoryActivitiesParams struct {
	ActorID                uuid.UUID
	StoryID                uuid.UUID
	WorkspaceID            uuid.UUID
	UnrestrictedTeamAccess bool
	AllowedTeamIds         []uuid.UUID
	RowOffset              int32
	RowLimit               int32
}

type ListVisibleStoryActivitiesRow struct {
	ActivityID   uuid.UUID
	StoryID      uuid.UUID
	UserID       uuid.UUID
	ActivityType string
	FieldChanged string
	CurrentValue string
	OldValue     []byte
	NewValue     []byte
	Reason       *string
	CreatedAt    time.Time
	WorkspaceID  *uuid.UUID
	Username     string
	FullName     string
	AvatarURL    string
	IsActive     bool
	IsSystem     bool
}

func (q *Queries) ListVisibleStoryActivities(ctx context.Context, arg ListVisibleStoryActivitiesParams) ([]ListVisibleStoryActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listVisibleStoryActivities,
		arg.ActorID,
		arg.StoryID,
		arg.WorkspaceID,
		arg.UnrestrictedTeamAccess,
		arg.AllowedTeamIds,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleStoryActivitiesRow{}
	for rows.Next() {
		var i ListVisibleStoryActivitiesRow
		if err := rows.Scan(
			&i.ActivityID,
			&i.StoryID,
			&i.UserID,
			&i.ActivityType,
			&i.FieldChanged,
			&i.CurrentValue,
			&i.OldValue,
			&i.NewValue,
			&i.Reason,
			&i.CreatedAt,
			&i.WorkspaceID,
			&i.Username,
			&i.FullName,
			&i.AvatarURL,
			&i.IsActive,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleStoryLinks = `-- name: ListVisibleStoryLinks :many
SELECT
    story_link.link_id,
    story_link.title,
    story_link.url,
    story_link.story_id,
    story_link.created_at,
    story_link.updated_at
FROM public.story_links AS story_link
INNER JOIN public.stories AS story
    ON story.id = story_link.story_id
INNER JOIN public.users AS actor
    ON actor.user_id = $1
   AND actor.is_active = TRUE
INNER JOIN public.workspace_members AS workspace_member
    ON workspace_member.workspace_id = story.workspace_id
   AND workspace_member.user_id = actor.user_id
INNER JOIN public.team_members AS team_member
    ON team_member.team_id = story.team_id
   AND team_member.user_id = actor.user_id
WHERE story.id = $2
  AND story.workspace_id = $3
  AND story.deleted_at IS NULL
  AND (
      CAST($4 AS boolean)
      OR story.team_id = ANY(CAST($5 AS uuid[]))
  )
ORDER BY story_link.created_at, story_link.link_id
`

type ListVisibleStoryLinksParams struct {
	ActorID                uuid.UUID
	StoryID                uuid.UUID
	WorkspaceID            uuid.UUID
	UnrestrictedTeamAccess bool
	AllowedTeamIds         []uuid.UUID
}

type ListVisibleStoryLinksRow struct {
	LinkID    uuid.UUID
	Title     *string
	URL       string
	StoryID   uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListVisibleStoryLinks(ctx context.Context, arg ListVisibleStoryLinksParams) ([]ListVisibleStoryLinksRow, error) {
	rows, err := q.db.Query(ctx, listVisibleStoryLinks,
		arg.ActorID,
		arg.StoryID,
		arg.WorkspaceID,
		arg.UnrestrictedTeamAccess,
		arg.AllowedTeamIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleStoryLinksRow{}
	for rows.Next() {
		var i ListVisibleStoryLinksRow
		if err := rows.Scan(
			&i.LinkID,
			&i.Title,
			&i.URL,
			&i.StoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveVisibleStoryKeyResult = `-- name: ResolveVisibleStoryKeyResult :one
SELECT key_result.objective_id, key_result.name
FROM public.key_results AS key_result
INNER JOIN public.objectives AS objective
    ON objective.objective_id = key_result.objective_id
INNER JOIN public.users AS actor
    ON actor.user_id = $1
   AND actor.is_active = TRUE
INNER JOIN public.workspace_members AS workspace_member
    ON workspace_member.workspace_id = objective.workspace_id
   AND workspace_member.user_id = actor.user_id
WHERE key_result.id = $2
  AND objective.workspace_id = $3
`

type ResolveVisibleStoryKeyResultParams struct {
	ActorID     uuid.UUID
	KeyResultID uuid.UUID
	WorkspaceID *uuid.UUID
}

type ResolveVisibleStoryKeyResultRow struct {
	ObjectiveID uuid.UUID
	Name        string
}

func (q *Queries) ResolveVisibleStoryKeyResult(ctx context.Context, arg ResolveVisibleStoryKeyResultParams) (ResolveVisibleStoryKeyResultRow, error) {
	row := q.db.QueryRow(ctx, resolveVisibleStoryKeyResult, arg.ActorID, arg.KeyResultID, arg.WorkspaceID)
	var i ResolveVisibleStoryKeyResultRow
	err := row.Scan(&i.ObjectiveID, &i.Name)
	return i, err
}
