package architecture_test

import (
	"go/token"
	"strings"
	"testing"
)

func TestInspectGoSourceFindsLayerAndPersistenceDebt(t *testing.T) {
	t.Parallel()

	source := []byte(`package service

import (
	"github.com/jmoiron/sqlx"
	linkshttp "github.com/complexus-tech/projects-api/internal/modules/links/http"
	"github.com/complexus-tech/projects-api/internal/modules/stories/repository/sqlc"
	"github.com/complexus-tech/projects-api/pkg/web"
)

const updateStory = ` + "`UPDATE stories SET title = $1 WHERE id = $2`" + `

var _ = sqlx.DB{}
var _ = linkshttp.Config{}
var _ = sqlc.Queries{}
var _ = web.Middleware(nil)
`)

	findings := inspectFixture(t, "internal/modules/stories/service/update.go", source)
	assertRuleCount(t, findings, ruleSQLXImport, 1)
	assertRuleCount(t, findings, ruleDirectSQL, 1)
	assertRuleCount(t, findings, ruleGeneratedSQLCLeak, 1)
	assertRuleCount(t, findings, ruleRepositoryServiceHTTP, 2)
	assertRuleCount(t, findings, ruleCrossModuleHTTPImport, 1)
}

func TestInspectGoSourceFindsAliasedRawDatabaseRouteConfig(t *testing.T) {
	t.Parallel()

	source := []byte(`package storieshttp

import database "github.com/jmoiron/sqlx"

type Config struct {
	DB *database.DB
}
`)

	findings := inspectFixture(t, "internal/modules/stories/http/routes.go", source)
	assertRuleCount(t, findings, ruleRawDBRouteConfig, 1)
	assertRuleCount(t, findings, ruleSQLXImport, 1)
	if !strings.Contains(findingsForRule(findings, ruleRawDBRouteConfig)[0].Detail, "Config.DB") {
		t.Fatalf("raw DB finding is not actionable: %#v", findings)
	}
}

func TestInspectGoSourceAllowsOwnedPersistenceDetails(t *testing.T) {
	t.Parallel()

	source := []byte(`package repository

import "github.com/complexus-tech/projects-api/internal/modules/stories/repository/sqlc"

const query = ` + "`SELECT id FROM stories WHERE id = $1`" + `

var _ = sqlc.Queries{}
`)

	findings := inspectFixture(t, "internal/modules/stories/repository/queries.go", source)
	assertRuleCount(t, findings, ruleGeneratedSQLCLeak, 0)
	assertRuleCount(t, findings, ruleDirectSQL, 0)
}

func TestInspectGoSourceEnforcesPlatformGeneratedOwnership(t *testing.T) {
	t.Parallel()

	owned := []byte(`package repository

import "github.com/complexus-tech/projects-api/internal/platform/idempotency/repository/sqlc"

var _ = sqlc.Queries{}
`)
	findings := inspectFixture(t, "internal/platform/idempotency/repository/repository.go", owned)
	assertRuleCount(t, findings, ruleGeneratedSQLCLeak, 0)

	leaked := []byte(`package idempotency

import "github.com/complexus-tech/projects-api/internal/platform/idempotency/repository/sqlc"

var _ = sqlc.Queries{}
`)
	findings = inspectFixture(t, "internal/platform/idempotency/service.go", leaked)
	assertRuleCount(t, findings, ruleGeneratedSQLCLeak, 1)
}

func TestInspectGoSourceExemptsGeneratedFilesFromSizeGate(t *testing.T) {
	t.Parallel()

	generated := []byte("// Code generated by sqlc. DO NOT EDIT.\npackage sqlc\n" + strings.Repeat("// generated\n", handwrittenFileLineLimit+10))
	findings := inspectFixture(t, "internal/modules/stories/repository/sqlc/queries.sql.go", generated)
	if len(findings) != 0 {
		t.Fatalf("generated source produced findings: %#v", findings)
	}

	handwritten := []byte("package service\n" + strings.Repeat("// cohesive-ish legacy code\n", handwrittenFileLineLimit+1))
	findings = inspectFixture(t, "internal/modules/stories/service/large.go", handwritten)
	assertRuleCount(t, findings, ruleOversizedHandwrittenFile, 1)
}

func TestLooksLikeSQLRejectsProductCopy(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name  string
		value string
		want  bool
	}{
		{name: "select query", value: "SELECT id FROM stories WHERE id = $1", want: true},
		{name: "commented query", value: "-- name: UpdateStory :one\nUPDATE stories SET title = $1", want: true},
		{name: "aliased update", value: "UPDATE stories story SET title = $1", want: true},
		{name: "cte query", value: "WITH candidate AS (SELECT id FROM stories) SELECT id FROM candidate", want: true},
		{name: "recursive cte columns", value: "WITH RECURSIVE tree(id) AS (SELECT id FROM stories) SELECT id FROM tree", want: true},
		{name: "update copy", value: "Update a story, task, or issue", want: false},
		{name: "select copy", value: "Select *Retry remaining* to try again", want: false},
		{name: "error copy", value: "update optimized attachment metadata: %w", want: false},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			if got := looksLikeSQL(test.value); got != test.want {
				t.Fatalf("looksLikeSQL(%q) = %t, want %t", test.value, got, test.want)
			}
		})
	}
}

func TestApprovedSQLPathsAreNarrowAndExplicit(t *testing.T) {
	t.Parallel()

	for _, path := range []string{
		"internal/migrations/000001_users.up.sql",
		"internal/modules/stories/repository/queries/list.sql",
		"internal/platform/idempotency/repository/queries/receipts.sql",
		"internal/platform/idempotency/repository/sqlc/receipts.sql.go",
		"internal/platform/database/database.go",
		"internal/testkit/postgres.go",
		"internal/tools/migrationstate/main.go",
		"internal/tools/sqlccontract/queries/contract.sql",
	} {
		if !isApprovedSQLPath(path) {
			t.Errorf("expected %s to be an approved persistence/infrastructure SQL path", path)
		}
	}
	for _, path := range []string{
		"internal/modules/stories/http/stories.go",
		"internal/modules/stories/service/stories.go",
		"internal/platform/idempotency/queries/receipts.sql",
		"internal/platform/idempotency/service/receipts.go",
		"internal/taskhandlers/stories.go",
		"pkg/jobs/stories.go",
	} {
		if isApprovedSQLPath(path) {
			t.Errorf("application layer path %s must not be approved for direct SQL", path)
		}
	}
}

func TestCompareArchitectureDebtProducesActionableRatchetFailures(t *testing.T) {
	t.Parallel()

	baseline := emptyArchitectureBaseline()
	baseline.RulePathCounts[ruleSQLXImport]["internal/modules/stories/repository/repository.go"] = 1
	baseline.OversizedFiles["internal/modules/stories/service/stories.go"] = 900

	findings := []architectureFinding{
		{Rule: ruleSQLXImport, Path: "internal/modules/stories/repository/new.go", Line: 8, Detail: "imports transitional SQLx package"},
		{Rule: ruleOversizedHandwrittenFile, Path: "internal/modules/stories/service/stories.go", Line: 1, Detail: "handwritten file has 901 lines", Value: 901},
	}
	differences := compareArchitectureDebt(baseline, findings)
	joined := strings.Join(differences, "\n")
	for _, expected := range []string{
		"architecture debt grew for internal/modules/stories/repository/new.go",
		"internal/modules/stories/repository/new.go:8",
		"architecture debt grew for internal/modules/stories/service/stories.go",
		"Split the file by cohesive use case or capability",
		"module:stories",
	} {
		if !strings.Contains(joined, expected) {
			t.Errorf("comparison output does not contain %q:\n%s", expected, joined)
		}
	}
	if strings.Contains(joined, "repository/repository.go") {
		t.Errorf("debt reductions must not fail the gate:\n%s", joined)
	}
}

func TestValidateArchitectureBaselineRejectsIgnoredOrInvalidEntries(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name      string
		mutate    func(architectureBaseline)
		wantError string
	}{
		{
			name: "unknown rule",
			mutate: func(baseline architectureBaseline) {
				baseline.RulePathCounts["typo_rule"] = map[string]int{"internal/example.go": 1}
			},
			wantError: "unknown rule",
		},
		{
			name: "absolute path",
			mutate: func(baseline architectureBaseline) {
				baseline.RulePathCounts[ruleSQLXImport]["/tmp/example.go"] = 1
			},
			wantError: "clean, relative",
		},
		{
			name: "zero count",
			mutate: func(baseline architectureBaseline) {
				baseline.RulePathCounts[ruleSQLXImport]["internal/example.go"] = 0
			},
			wantError: "non-positive count",
		},
		{
			name: "file below gate",
			mutate: func(baseline architectureBaseline) {
				baseline.OversizedFiles["internal/example.go"] = handwrittenFileLineLimit
			},
			wantError: "entries must exceed",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			baseline := emptyArchitectureBaseline()
			test.mutate(baseline)
			err := validateArchitectureBaseline(baseline)
			if err == nil || !strings.Contains(err.Error(), test.wantError) {
				t.Fatalf("validateArchitectureBaseline() error = %v, want error containing %q", err, test.wantError)
			}
		})
	}
}

func TestCountedArchitectureRulesAreUniqueAndActionable(t *testing.T) {
	t.Parallel()

	seen := make(map[string]struct{}, len(countedArchitectureRules))
	previous := ""
	for _, rule := range countedArchitectureRules {
		if _, exists := seen[rule]; exists {
			t.Errorf("architecture rule %q is listed more than once", rule)
		}
		seen[rule] = struct{}{}
		if previous != "" && rule < previous {
			t.Errorf("architecture rules are not sorted: %q appears after %q", rule, previous)
		}
		previous = rule
		if strings.TrimSpace(ruleRemediation[rule]) == "" {
			t.Errorf("architecture rule %q has no remediation guidance", rule)
		}
	}
}

func inspectFixture(t *testing.T, path string, source []byte) []architectureFinding {
	t.Helper()
	findings, err := inspectGoSource(token.NewFileSet(), path, source)
	if err != nil {
		t.Fatalf("inspect fixture %s: %v", path, err)
	}
	return findings
}

func assertRuleCount(t *testing.T, findings []architectureFinding, rule string, want int) {
	t.Helper()
	got := len(findingsForRule(findings, rule))
	if got != want {
		t.Fatalf("rule %s produced %d findings, want %d: %#v", rule, got, want, findings)
	}
}

func findingsForRule(findings []architectureFinding, rule string) []architectureFinding {
	matching := make([]architectureFinding, 0)
	for _, finding := range findings {
		if finding.Rule == rule {
			matching = append(matching, finding)
		}
	}
	return matching
}

func emptyArchitectureBaseline() architectureBaseline {
	baseline := architectureBaseline{
		Version:        architectureBaselineVersion,
		RulePathCounts: make(map[string]map[string]int, len(countedArchitectureRules)),
		OversizedFiles: make(map[string]int),
	}
	for _, rule := range countedArchitectureRules {
		baseline.RulePathCounts[rule] = make(map[string]int)
	}
	return baseline
}
