package reports

import reportdomain "github.com/complexus-tech/projects-api/internal/modules/reports/domain"

type CoreStoryStats = reportdomain.CoreStoryStats
type StoryStatsFilters = reportdomain.StoryStatsFilters
type CoreContributionStats = reportdomain.CoreContributionStats
type CoreUserStats = reportdomain.CoreUserStats
type CoreStatusStats = reportdomain.CoreStatusStats
type CorePriorityStats = reportdomain.CorePriorityStats
type StatsFilters = reportdomain.StatsFilters
type ReportFilters = reportdomain.ReportFilters
type CoreWorkspaceAnalyticsEventInput = reportdomain.CoreWorkspaceAnalyticsEventInput
type CoreWorkspaceCommandCenterReport = reportdomain.CoreWorkspaceCommandCenterReport
type CoreWorkspaceCommandCenterSectionError = reportdomain.CoreWorkspaceCommandCenterSectionError
type CoreRequestSourceAnalytics = reportdomain.CoreRequestSourceAnalytics
type CoreRequestProviderPerformance = reportdomain.CoreRequestProviderPerformance
type CoreWorkspaceEngagementAnalytics = reportdomain.CoreWorkspaceEngagementAnalytics
type CoreWorkspaceEngagementCount = reportdomain.CoreWorkspaceEngagementCount
type CoreWorkspaceEngagementUser = reportdomain.CoreWorkspaceEngagementUser
type CoreWorkloadAnalysis = reportdomain.CoreWorkloadAnalysis
type CoreWorkloadSummary = reportdomain.CoreWorkloadSummary
type CoreMemberWorkload = reportdomain.CoreMemberWorkload
type CoreTeamWorkloadSummary = reportdomain.CoreTeamWorkloadSummary
type CoreUnassignedWorkload = reportdomain.CoreUnassignedWorkload
type CoreWorkloadRisks = reportdomain.CoreWorkloadRisks
type PulseRiskSeverity = reportdomain.PulseRiskSeverity
type PulseRiskKind = reportdomain.PulseRiskKind
type CorePulseReport = reportdomain.CorePulseReport
type CorePulseSummary = reportdomain.CorePulseSummary
type CorePulseStoryHealth = reportdomain.CorePulseStoryHealth
type CorePulseSprintHealth = reportdomain.CorePulseSprintHealth
type CorePulseObjectiveHealth = reportdomain.CorePulseObjectiveHealth
type CorePulseRequestHealth = reportdomain.CorePulseRequestHealth
type CorePulseRisk = reportdomain.CorePulseRisk
type CoreWorkspaceOverview = reportdomain.CoreWorkspaceOverview
type CoreWorkspaceMetrics = reportdomain.CoreWorkspaceMetrics
type CoreCompletionTrendPoint = reportdomain.CoreCompletionTrendPoint
type CoreVelocityTrendPoint = reportdomain.CoreVelocityTrendPoint
type CoreStoryAnalytics = reportdomain.CoreStoryAnalytics
type CoreStatusBreakdownItem = reportdomain.CoreStatusBreakdownItem
type CorePriorityDistributionItem = reportdomain.CorePriorityDistributionItem
type CoreTeamCompletionItem = reportdomain.CoreTeamCompletionItem
type CoreBurndownPoint = reportdomain.CoreBurndownPoint
type CoreObjectiveProgress = reportdomain.CoreObjectiveProgress
type CoreHealthDistributionItem = reportdomain.CoreHealthDistributionItem
type CoreObjectiveStatusItem = reportdomain.CoreObjectiveStatusItem
type CoreKeyResultProgressItem = reportdomain.CoreKeyResultProgressItem
type CoreObjectiveTeamProgressItem = reportdomain.CoreObjectiveTeamProgressItem
type CoreTeamPerformance = reportdomain.CoreTeamPerformance
type CoreTeamWorkloadItem = reportdomain.CoreTeamWorkloadItem
type CoreMemberContributionItem = reportdomain.CoreMemberContributionItem
type CoreTeamVelocityItem = reportdomain.CoreTeamVelocityItem
type CoreWorkloadTrendPoint = reportdomain.CoreWorkloadTrendPoint
type CoreSprintAnalyticsWorkspace = reportdomain.CoreSprintAnalyticsWorkspace
type CoreSprintProgressItem = reportdomain.CoreSprintProgressItem
type CoreCombinedBurndownPoint = reportdomain.CoreCombinedBurndownPoint
type CoreSprintTeamAllocation = reportdomain.CoreSprintTeamAllocation
type CoreSprintHealthItem = reportdomain.CoreSprintHealthItem
type CoreTimelineTrends = reportdomain.CoreTimelineTrends
type CoreStoryCompletionPoint = reportdomain.CoreStoryCompletionPoint
type CoreObjectiveProgressPoint = reportdomain.CoreObjectiveProgressPoint
type CoreTeamVelocityPoint = reportdomain.CoreTeamVelocityPoint
type CoreKeyMetricsTrendPoint = reportdomain.CoreKeyMetricsTrendPoint

const (
	PulseRiskSeverityHigh   = reportdomain.PulseRiskSeverityHigh
	PulseRiskSeverityMedium = reportdomain.PulseRiskSeverityMedium
	PulseRiskSeverityLow    = reportdomain.PulseRiskSeverityLow

	PulseRiskKindOverdueStories    = reportdomain.PulseRiskKindOverdueStories
	PulseRiskKindBlockedStories    = reportdomain.PulseRiskKindBlockedStories
	PulseRiskKindOverloadedMembers = reportdomain.PulseRiskKindOverloadedMembers
	PulseRiskKindAtRiskSprints     = reportdomain.PulseRiskKindAtRiskSprints
	PulseRiskKindAtRiskObjectives  = reportdomain.PulseRiskKindAtRiskObjectives
	PulseRiskKindPendingRequests   = reportdomain.PulseRiskKindPendingRequests
	PulseRiskKindUnassignedStories = reportdomain.PulseRiskKindUnassignedStories
)
