// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orderings.sql

package teamsql

import (
	"context"

	"github.com/google/uuid"
)

const actorCanOrderWorkspaceTeams = `-- name: ActorCanOrderWorkspaceTeams :one
SELECT EXISTS (
    SELECT 1
    FROM workspace_members AS actor_membership
    INNER JOIN users AS actor ON actor.user_id = actor_membership.user_id
    WHERE actor_membership.workspace_id = $1
      AND actor_membership.user_id = $2
      AND actor.is_active = TRUE
) AS allowed
`

type ActorCanOrderWorkspaceTeamsParams struct {
	WorkspaceID uuid.UUID
	ActorID     uuid.UUID
}

func (q *Queries) ActorCanOrderWorkspaceTeams(ctx context.Context, arg ActorCanOrderWorkspaceTeamsParams) (bool, error) {
	row := q.db.QueryRow(ctx, actorCanOrderWorkspaceTeams, arg.WorkspaceID, arg.ActorID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const deleteActorTeamOrdering = `-- name: DeleteActorTeamOrdering :exec
DELETE FROM user_team_orders
WHERE user_id = $1
  AND workspace_id = $2
`

type DeleteActorTeamOrderingParams struct {
	ActorID     uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteActorTeamOrdering(ctx context.Context, arg DeleteActorTeamOrderingParams) error {
	_, err := q.db.Exec(ctx, deleteActorTeamOrdering, arg.ActorID, arg.WorkspaceID)
	return err
}

const insertActorTeamOrder = `-- name: InsertActorTeamOrder :execrows
INSERT INTO user_team_orders (
    user_id,
    team_id,
    workspace_id,
    order_index
)
SELECT
    $1,
    team.team_id,
    team.workspace_id,
    CAST($2 AS integer)
FROM teams AS team
WHERE team.team_id = $3
  AND team.workspace_id = $4
  AND (
      EXISTS (
          SELECT 1
          FROM team_members AS actor_team_membership
          WHERE actor_team_membership.team_id = team.team_id
            AND actor_team_membership.user_id = $1
      )
      OR EXISTS (
          SELECT 1
          FROM workspace_members AS admin_membership
          WHERE admin_membership.workspace_id = team.workspace_id
            AND admin_membership.user_id = $1
            AND admin_membership.role = 'admin'
      )
  )
`

type InsertActorTeamOrderParams struct {
	ActorID     uuid.UUID
	OrderIndex  int32
	TeamID      uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) InsertActorTeamOrder(ctx context.Context, arg InsertActorTeamOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertActorTeamOrder,
		arg.ActorID,
		arg.OrderIndex,
		arg.TeamID,
		arg.WorkspaceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
