// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package attachmentssql

import (
	"time"

	"github.com/google/uuid"
)

type Attachment struct {
	AttachmentID               uuid.UUID
	Filename                   string
	Size                       int64
	MimeType                   string
	UploadedBy                 *uuid.UUID
	WorkspaceID                uuid.UUID
	CreatedAt                  time.Time
	BlobName                   string
	ScanStatus                 string
	ScanCompletedAt            *time.Time
	ScanFailureReason          *string
	OptimizationStatus         string
	OptimizationAttempts       int32
	OptimizationStartedAt      *time.Time
	OptimizationCompletedAt    *time.Time
	OptimizationLeaseExpiresAt *time.Time
	OptimizationLastError      *string
	UpdatedAt                  time.Time
}
