// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package developercredentialssql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertDeveloperCredentialAuditEvent = `-- name: InsertDeveloperCredentialAuditEvent :exec
INSERT INTO public.developer_credential_audit_events (
    event_id,
    workspace_id,
    actor_kind,
    actor_id,
    actor_credential_id,
    operation,
    subject_type,
    subject_id,
    result,
    reason_code,
    request_id,
    metadata,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    CAST($12 AS jsonb),
    $13
)
`

type InsertDeveloperCredentialAuditEventParams struct {
	EventID           uuid.UUID
	WorkspaceID       uuid.UUID
	ActorKind         string
	ActorID           uuid.UUID
	ActorCredentialID *uuid.UUID
	Operation         string
	SubjectType       string
	SubjectID         uuid.UUID
	Result            string
	ReasonCode        *string
	RequestID         *string
	Metadata          []byte
	CreatedAt         time.Time
}

func (q *Queries) InsertDeveloperCredentialAuditEvent(ctx context.Context, arg InsertDeveloperCredentialAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertDeveloperCredentialAuditEvent,
		arg.EventID,
		arg.WorkspaceID,
		arg.ActorKind,
		arg.ActorID,
		arg.ActorCredentialID,
		arg.Operation,
		arg.SubjectType,
		arg.SubjectID,
		arg.Result,
		arg.ReasonCode,
		arg.RequestID,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}
