// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package commentsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const appendCommentMutationEvent = `-- name: AppendCommentMutationEvent :many
WITH created_event AS (
    INSERT INTO public.outbound_webhook_events (
        event_id,
        workspace_id,
        event_type,
        payload_version,
        subject_type,
        subject_id,
        actor_kind,
        actor_id,
        actor_credential_id,
        payload,
        occurred_at,
        created_at
    ) VALUES (
        $3,
        $4,
        $2,
        1,
        'comment',
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        GREATEST(clock_timestamp(), CAST($10 AS timestamptz))
    )
    RETURNING event_id, workspace_id, created_at
)
INSERT INTO public.outbound_webhook_deliveries (
    delivery_id,
    workspace_id,
    event_id,
    endpoint_id,
    subscription_generation,
    payload_body,
    status,
    attempt_count,
    available_at,
    created_at,
    updated_at
)
SELECT
    gen_random_uuid(),
    endpoint.workspace_id,
    created_event.event_id,
    endpoint.endpoint_id,
    endpoint.subscription_generation,
    $1,
    'pending',
    0,
    created_event.created_at,
    created_event.created_at,
    created_event.created_at
FROM created_event
INNER JOIN public.outbound_webhook_endpoints AS endpoint
    ON endpoint.workspace_id = created_event.workspace_id
INNER JOIN public.outbound_webhook_subscriptions AS subscription
    ON subscription.endpoint_id = endpoint.endpoint_id
   AND subscription.workspace_id = endpoint.workspace_id
INNER JOIN public.principals AS principal
    ON principal.principal_id = endpoint.owner_principal_id
   AND principal.workspace_id = endpoint.workspace_id
LEFT JOIN public.users AS account
    ON account.user_id = principal.subject_user_id
LEFT JOIN public.workspace_members AS membership
    ON membership.workspace_id = principal.workspace_id
   AND membership.user_id = principal.subject_user_id
WHERE endpoint.status = 'active'
  AND subscription.event_type = $2
  AND principal.status = 'active'
  AND principal.kind = 'human_user'
  AND account.is_active = TRUE
  AND membership.user_id IS NOT NULL
RETURNING delivery_id
`

type AppendCommentMutationEventParams struct {
	PayloadBody       []byte
	EventType         string
	EventID           uuid.UUID
	WorkspaceID       uuid.UUID
	CommentID         uuid.UUID
	ActorKind         string
	ActorID           uuid.UUID
	ActorCredentialID *uuid.UUID
	Payload           []byte
	OccurredAt        time.Time
}

func (q *Queries) AppendCommentMutationEvent(ctx context.Context, arg AppendCommentMutationEventParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, appendCommentMutationEvent,
		arg.PayloadBody,
		arg.EventType,
		arg.EventID,
		arg.WorkspaceID,
		arg.CommentID,
		arg.ActorKind,
		arg.ActorID,
		arg.ActorCredentialID,
		arg.Payload,
		arg.OccurredAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var delivery_id uuid.UUID
		if err := rows.Scan(&delivery_id); err != nil {
			return nil, err
		}
		items = append(items, delivery_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCommentForActor = `-- name: CreateCommentForActor :one
WITH scoped_story AS (
    SELECT story.id
    FROM public.stories AS story
    INNER JOIN public.workspace_members AS actor_member
        ON actor_member.workspace_id = story.workspace_id
       AND actor_member.user_id = $2
    INNER JOIN public.users AS actor_user
        ON actor_user.user_id = actor_member.user_id
       AND actor_user.is_active = TRUE
    INNER JOIN public.team_members AS actor_team_member
        ON actor_team_member.team_id = story.team_id
       AND actor_team_member.user_id = actor_member.user_id
    WHERE story.id = $4
      AND story.workspace_id = $5
      AND story.deleted_at IS NULL
      AND (
          CAST($6 AS boolean)
          OR story.team_id = ANY(CAST($7 AS uuid[]))
      )
      AND (
          CAST($3 AS uuid) IS NULL
          OR EXISTS (
              SELECT 1
              FROM public.story_comments AS parent_comment
              WHERE parent_comment.comment_id = $3
                AND parent_comment.story_id = story.id
          )
      )
)
INSERT INTO public.story_comments (
    content,
    story_id,
    commenter_id,
    parent_id
)
SELECT
    $1,
    scoped_story.id,
    $2,
    $3
FROM scoped_story
RETURNING
    comment_id,
    story_id,
    parent_id,
    commenter_id,
    content,
    created_at,
    updated_at
`

type CreateCommentForActorParams struct {
	Content                string
	ActorID                uuid.UUID
	ParentID               *uuid.UUID
	StoryID                uuid.UUID
	WorkspaceID            uuid.UUID
	TeamAccessUnrestricted bool
	AllowedTeamIds         []uuid.UUID
}

type CreateCommentForActorRow struct {
	CommentID   uuid.UUID
	StoryID     uuid.UUID
	ParentID    *uuid.UUID
	CommenterID uuid.UUID
	Content     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateCommentForActor(ctx context.Context, arg CreateCommentForActorParams) (CreateCommentForActorRow, error) {
	row := q.db.QueryRow(ctx, createCommentForActor,
		arg.Content,
		arg.ActorID,
		arg.ParentID,
		arg.StoryID,
		arg.WorkspaceID,
		arg.TeamAccessUnrestricted,
		arg.AllowedTeamIds,
	)
	var i CreateCommentForActorRow
	err := row.Scan(
		&i.CommentID,
		&i.StoryID,
		&i.ParentID,
		&i.CommenterID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCommentForAuthor = `-- name: DeleteCommentForAuthor :one
DELETE FROM public.story_comments AS comment
USING public.stories AS story
WHERE comment.comment_id = $1
  AND comment.commenter_id = $2
  AND story.id = comment.story_id
  AND story.workspace_id = $3
  AND story.deleted_at IS NULL
  AND (
      CAST($4 AS boolean)
      OR story.team_id = ANY(CAST($5 AS uuid[]))
  )
  AND EXISTS (
      SELECT 1
      FROM public.workspace_members AS actor_member
      INNER JOIN public.users AS actor_user
          ON actor_user.user_id = actor_member.user_id
         AND actor_user.is_active = TRUE
      INNER JOIN public.team_members AS actor_team_member
          ON actor_team_member.team_id = story.team_id
         AND actor_team_member.user_id = actor_member.user_id
      WHERE actor_member.workspace_id = story.workspace_id
        AND actor_member.user_id = $2
  )
RETURNING
    comment.comment_id,
    comment.story_id,
    comment.parent_id,
    comment.commenter_id,
    comment.content,
    comment.created_at,
    CAST(GREATEST(clock_timestamp(), comment.updated_at) AS timestamptz) AS updated_at
`

type DeleteCommentForAuthorParams struct {
	CommentID              uuid.UUID
	ActorID                uuid.UUID
	WorkspaceID            uuid.UUID
	TeamAccessUnrestricted bool
	AllowedTeamIds         []uuid.UUID
}

type DeleteCommentForAuthorRow struct {
	CommentID   uuid.UUID
	StoryID     uuid.UUID
	ParentID    *uuid.UUID
	CommenterID uuid.UUID
	Content     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) DeleteCommentForAuthor(ctx context.Context, arg DeleteCommentForAuthorParams) (DeleteCommentForAuthorRow, error) {
	row := q.db.QueryRow(ctx, deleteCommentForAuthor,
		arg.CommentID,
		arg.ActorID,
		arg.WorkspaceID,
		arg.TeamAccessUnrestricted,
		arg.AllowedTeamIds,
	)
	var i DeleteCommentForAuthorRow
	err := row.Scan(
		&i.CommentID,
		&i.StoryID,
		&i.ParentID,
		&i.CommenterID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCommentMentionsForAuthor = `-- name: DeleteCommentMentionsForAuthor :one
WITH scoped_comment AS (
    SELECT comment.comment_id
    FROM public.story_comments AS comment
    INNER JOIN public.stories AS story ON story.id = comment.story_id
    WHERE comment.comment_id = $1
      AND comment.commenter_id = $2
      AND story.workspace_id = $3
      AND story.deleted_at IS NULL
      AND (
          CAST($4 AS boolean)
          OR story.team_id = ANY(CAST($5 AS uuid[]))
      )
      AND EXISTS (
          SELECT 1
          FROM public.workspace_members AS actor_member
          INNER JOIN public.users AS actor_user
              ON actor_user.user_id = actor_member.user_id
             AND actor_user.is_active = TRUE
          INNER JOIN public.team_members AS actor_team_member
              ON actor_team_member.team_id = story.team_id
             AND actor_team_member.user_id = actor_member.user_id
          WHERE actor_member.workspace_id = story.workspace_id
            AND actor_member.user_id = $2
      )
),
deleted_mention AS (
    DELETE FROM public.comment_mentions AS mention
    USING scoped_comment
    WHERE mention.comment_id = scoped_comment.comment_id
    RETURNING mention.comment_id
)
SELECT
    EXISTS(SELECT 1 FROM scoped_comment) AS comment_found,
    CAST((SELECT COUNT(*) FROM deleted_mention) AS bigint) AS deleted_count
`

type DeleteCommentMentionsForAuthorParams struct {
	CommentID              uuid.UUID
	ActorID                uuid.UUID
	WorkspaceID            uuid.UUID
	TeamAccessUnrestricted bool
	AllowedTeamIds         []uuid.UUID
}

type DeleteCommentMentionsForAuthorRow struct {
	CommentFound bool
	DeletedCount int64
}

func (q *Queries) DeleteCommentMentionsForAuthor(ctx context.Context, arg DeleteCommentMentionsForAuthorParams) (DeleteCommentMentionsForAuthorRow, error) {
	row := q.db.QueryRow(ctx, deleteCommentMentionsForAuthor,
		arg.CommentID,
		arg.ActorID,
		arg.WorkspaceID,
		arg.TeamAccessUnrestricted,
		arg.AllowedTeamIds,
	)
	var i DeleteCommentMentionsForAuthorRow
	err := row.Scan(&i.CommentFound, &i.DeletedCount)
	return i, err
}

const getCommentForWorkspace = `-- name: GetCommentForWorkspace :one
SELECT
    comment.comment_id,
    comment.story_id,
    comment.parent_id,
    comment.commenter_id,
    comment.content,
    comment.created_at,
    comment.updated_at
FROM public.story_comments AS comment
INNER JOIN public.stories AS story ON story.id = comment.story_id
WHERE comment.comment_id = $1
  AND story.workspace_id = $2
`

type GetCommentForWorkspaceParams struct {
	CommentID   uuid.UUID
	WorkspaceID uuid.UUID
}

type GetCommentForWorkspaceRow struct {
	CommentID   uuid.UUID
	StoryID     uuid.UUID
	ParentID    *uuid.UUID
	CommenterID uuid.UUID
	Content     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetCommentForWorkspace(ctx context.Context, arg GetCommentForWorkspaceParams) (GetCommentForWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getCommentForWorkspace, arg.CommentID, arg.WorkspaceID)
	var i GetCommentForWorkspaceRow
	err := row.Scan(
		&i.CommentID,
		&i.StoryID,
		&i.ParentID,
		&i.CommenterID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCommentMentionsForAuthor = `-- name: InsertCommentMentionsForAuthor :execrows
WITH requested_user AS (
    SELECT DISTINCT requested.user_id
    FROM unnest(CAST($6 AS uuid[])) AS requested(user_id)
)
INSERT INTO public.comment_mentions (
    comment_id,
    mentioned_user_id
)
SELECT
    comment.comment_id,
    requested_user.user_id
FROM public.story_comments AS comment
INNER JOIN public.stories AS story ON story.id = comment.story_id
INNER JOIN requested_user ON TRUE
INNER JOIN public.workspace_members AS member
    ON member.workspace_id = story.workspace_id
   AND member.user_id = requested_user.user_id
INNER JOIN public.users AS mentioned_user
    ON mentioned_user.user_id = member.user_id
   AND mentioned_user.is_active = TRUE
WHERE comment.comment_id = $1
  AND comment.commenter_id = $2
  AND story.workspace_id = $3
  AND story.deleted_at IS NULL
  AND (
      CAST($4 AS boolean)
      OR story.team_id = ANY(CAST($5 AS uuid[]))
  )
  AND EXISTS (
      SELECT 1
      FROM public.workspace_members AS actor_member
      INNER JOIN public.users AS actor_user
          ON actor_user.user_id = actor_member.user_id
         AND actor_user.is_active = TRUE
      INNER JOIN public.team_members AS actor_team_member
          ON actor_team_member.team_id = story.team_id
         AND actor_team_member.user_id = actor_member.user_id
      WHERE actor_member.workspace_id = story.workspace_id
        AND actor_member.user_id = $2
  )
`

type InsertCommentMentionsForAuthorParams struct {
	CommentID              uuid.UUID
	ActorID                uuid.UUID
	WorkspaceID            uuid.UUID
	TeamAccessUnrestricted bool
	AllowedTeamIds         []uuid.UUID
	MentionedUserIds       []uuid.UUID
}

func (q *Queries) InsertCommentMentionsForAuthor(ctx context.Context, arg InsertCommentMentionsForAuthorParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCommentMentionsForAuthor,
		arg.CommentID,
		arg.ActorID,
		arg.WorkspaceID,
		arg.TeamAccessUnrestricted,
		arg.AllowedTeamIds,
		arg.MentionedUserIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCommentForAuthor = `-- name: UpdateCommentForAuthor :one
UPDATE public.story_comments AS comment
SET
    content = $1,
    updated_at = GREATEST(clock_timestamp(), comment.updated_at + INTERVAL '1 microsecond')
FROM public.stories AS story
WHERE comment.comment_id = $2
  AND comment.commenter_id = $3
  AND story.id = comment.story_id
  AND story.workspace_id = $4
  AND story.deleted_at IS NULL
  AND (
      CAST($5 AS boolean)
      OR story.team_id = ANY(CAST($6 AS uuid[]))
  )
  AND EXISTS (
      SELECT 1
      FROM public.workspace_members AS actor_member
      INNER JOIN public.users AS actor_user
          ON actor_user.user_id = actor_member.user_id
         AND actor_user.is_active = TRUE
      INNER JOIN public.team_members AS actor_team_member
          ON actor_team_member.team_id = story.team_id
         AND actor_team_member.user_id = actor_member.user_id
      WHERE actor_member.workspace_id = story.workspace_id
        AND actor_member.user_id = $3
  )
RETURNING
    comment.comment_id,
    comment.story_id,
    comment.parent_id,
    comment.commenter_id,
    comment.content,
    comment.created_at,
    comment.updated_at
`

type UpdateCommentForAuthorParams struct {
	Content                string
	CommentID              uuid.UUID
	ActorID                uuid.UUID
	WorkspaceID            uuid.UUID
	TeamAccessUnrestricted bool
	AllowedTeamIds         []uuid.UUID
}

type UpdateCommentForAuthorRow struct {
	CommentID   uuid.UUID
	StoryID     uuid.UUID
	ParentID    *uuid.UUID
	CommenterID uuid.UUID
	Content     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdateCommentForAuthor(ctx context.Context, arg UpdateCommentForAuthorParams) (UpdateCommentForAuthorRow, error) {
	row := q.db.QueryRow(ctx, updateCommentForAuthor,
		arg.Content,
		arg.CommentID,
		arg.ActorID,
		arg.WorkspaceID,
		arg.TeamAccessUnrestricted,
		arg.AllowedTeamIds,
	)
	var i UpdateCommentForAuthorRow
	err := row.Scan(
		&i.CommentID,
		&i.StoryID,
		&i.ParentID,
		&i.CommenterID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
