package workpresetsrepository

import (
	"context"
	"errors"
	"testing"

	domain "github.com/complexus-tech/projects-api/internal/modules/workpresets/domain"
	sql "github.com/complexus-tech/projects-api/internal/modules/workpresets/repository/sqlc"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

type stubQueries struct {
	sql.Querier
	create      sql.CreatePresetForActorParams
	err         error
	archiveRows int64
}

func (s *stubQueries) CreatePresetForActor(_ context.Context, p sql.CreatePresetForActorParams) (sql.CreatePresetForActorRow, error) {
	s.create = p
	return sql.CreatePresetForActorRow{ID: uuid.New(), TeamID: p.TeamID, OwnerID: p.ActorID, Configuration: p.Configuration, CanEdit: true}, s.err
}

func (s *stubQueries) ArchivePresetForActor(_ context.Context, _ sql.ArchivePresetForActorParams) (int64, error) {
	return s.archiveRows, s.err
}

func TestAdapterForwardsScopeAndMapsHiddenTargets(t *testing.T) {
	queries := &stubQueries{}
	repo := &Repository{queries: queries}
	actor, workspace, team := uuid.New(), uuid.New(), uuid.New()
	preset, err := repo.Create(t.Context(), actor, workspace, domain.Input{TeamID: team, Kind: domain.View, Visibility: domain.Personal, Name: "Mine", Configuration: []byte(`{"version":1}`)})
	if err != nil || queries.create.ActorID != actor || queries.create.WorkspaceID != workspace || queries.create.TeamID != team {
		t.Fatalf("wrong scope: %+v %v", queries.create, err)
	}
	preset.Configuration[0] = 'x'
	if queries.create.Configuration[0] != '{' {
		t.Fatal("mapped configuration aliases generated bytes")
	}
	queries.err = pgx.ErrNoRows
	if _, err := repo.Create(t.Context(), actor, workspace, domain.Input{TeamID: team}); !errors.Is(err, domain.ErrNotFound) {
		t.Fatalf("got %v", err)
	}
	queries.err = nil
	if err := repo.Archive(t.Context(), actor, workspace, uuid.New()); !errors.Is(err, domain.ErrNotFound) {
		t.Fatalf("got %v", err)
	}
}
