// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mutations.sql

package statessql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countTeamStatesInCategory = `-- name: CountTeamStatesInCategory :one
SELECT CAST(COUNT(*) AS integer)
FROM public.statuses AS status
WHERE status.workspace_id = $1
  AND status.team_id = $2
  AND status.category = CAST($3 AS text)
`

type CountTeamStatesInCategoryParams struct {
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
	Category    string
}

func (q *Queries) CountTeamStatesInCategory(ctx context.Context, arg CountTeamStatesInCategoryParams) (int32, error) {
	row := q.db.QueryRow(ctx, countTeamStatesInCategory, arg.WorkspaceID, arg.TeamID, arg.Category)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countWorkspaceStoriesWithState = `-- name: CountWorkspaceStoriesWithState :one
SELECT CAST(COUNT(*) AS integer)
FROM public.stories AS story
WHERE story.workspace_id = $1
  AND story.status_id = CAST($2 AS uuid)
  AND story.deleted_at IS NULL
`

type CountWorkspaceStoriesWithStateParams struct {
	WorkspaceID uuid.UUID
	StatusID    uuid.UUID
}

func (q *Queries) CountWorkspaceStoriesWithState(ctx context.Context, arg CountWorkspaceStoriesWithStateParams) (int32, error) {
	row := q.db.QueryRow(ctx, countWorkspaceStoriesWithState, arg.WorkspaceID, arg.StatusID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteState = `-- name: DeleteState :execrows
DELETE FROM public.statuses
WHERE status_id = $1
  AND workspace_id = $2
`

type DeleteStateParams struct {
	StatusID    uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteState(ctx context.Context, arg DeleteStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteState, arg.StatusID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStateForDelete = `-- name: GetStateForDelete :one
SELECT status.team_id, status.category
FROM public.statuses AS status
INNER JOIN public.workspace_members AS membership
    ON membership.workspace_id = status.workspace_id
   AND membership.user_id = $1
INNER JOIN public.users AS actor
    ON actor.user_id = membership.user_id
   AND actor.is_active = TRUE
WHERE status.status_id = $2
  AND status.workspace_id = $3
FOR UPDATE OF status
`

type GetStateForDeleteParams struct {
	ActorID     uuid.UUID
	StatusID    uuid.UUID
	WorkspaceID uuid.UUID
}

type GetStateForDeleteRow struct {
	TeamID   uuid.UUID
	Category *string
}

func (q *Queries) GetStateForDelete(ctx context.Context, arg GetStateForDeleteParams) (GetStateForDeleteRow, error) {
	row := q.db.QueryRow(ctx, getStateForDelete, arg.ActorID, arg.StatusID, arg.WorkspaceID)
	var i GetStateForDeleteRow
	err := row.Scan(&i.TeamID, &i.Category)
	return i, err
}

const getStateTeamForMember = `-- name: GetStateTeamForMember :one
SELECT status.team_id
FROM public.statuses AS status
INNER JOIN public.workspace_members AS membership
    ON membership.workspace_id = status.workspace_id
   AND membership.user_id = $1
INNER JOIN public.users AS actor
    ON actor.user_id = membership.user_id
   AND actor.is_active = TRUE
WHERE status.status_id = $2
  AND status.workspace_id = $3
`

type GetStateTeamForMemberParams struct {
	ActorID     uuid.UUID
	StatusID    uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetStateTeamForMember(ctx context.Context, arg GetStateTeamForMemberParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getStateTeamForMember, arg.ActorID, arg.StatusID, arg.WorkspaceID)
	var team_id uuid.UUID
	err := row.Scan(&team_id)
	return team_id, err
}

const insertState = `-- name: InsertState :one
INSERT INTO public.statuses (
    name, category, order_index, color, team_id, workspace_id, is_default
) VALUES (
    $1, CAST($2 AS text), CAST($3 AS integer),
    CAST($4 AS text),
    $5, $6, $7
)
RETURNING status_id, name, category, order_index, team_id, workspace_id,
          is_default, color, created_at, updated_at
`

type InsertStateParams struct {
	Name        string
	Category    string
	OrderIndex  int32
	Color       string
	TeamID      uuid.UUID
	WorkspaceID uuid.UUID
	IsDefault   bool
}

type InsertStateRow struct {
	StatusID    uuid.UUID
	Name        string
	Category    *string
	OrderIndex  *int32
	TeamID      uuid.UUID
	WorkspaceID uuid.UUID
	IsDefault   bool
	Color       *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) InsertState(ctx context.Context, arg InsertStateParams) (InsertStateRow, error) {
	row := q.db.QueryRow(ctx, insertState,
		arg.Name,
		arg.Category,
		arg.OrderIndex,
		arg.Color,
		arg.TeamID,
		arg.WorkspaceID,
		arg.IsDefault,
	)
	var i InsertStateRow
	err := row.Scan(
		&i.StatusID,
		&i.Name,
		&i.Category,
		&i.OrderIndex,
		&i.TeamID,
		&i.WorkspaceID,
		&i.IsDefault,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockStateCategory = `-- name: LockStateCategory :exec
SELECT pg_advisory_xact_lock(
    hashtextextended(
        'states-delete:' || CAST(CAST($1 AS uuid) AS text) || ':' || CAST($2 AS text),
        0
    )
)
`

type LockStateCategoryParams struct {
	TeamID   uuid.UUID
	Category string
}

func (q *Queries) LockStateCategory(ctx context.Context, arg LockStateCategoryParams) error {
	_, err := q.db.Exec(ctx, lockStateCategory, arg.TeamID, arg.Category)
	return err
}

const lockStateDefaults = `-- name: LockStateDefaults :exec
SELECT pg_advisory_xact_lock(
    hashtextextended('states-default:' || CAST(CAST($1 AS uuid) AS text), 0)
)
`

type LockStateDefaultsParams struct {
	TeamID uuid.UUID
}

func (q *Queries) LockStateDefaults(ctx context.Context, arg LockStateDefaultsParams) error {
	_, err := q.db.Exec(ctx, lockStateDefaults, arg.TeamID)
	return err
}

const lockStateOrdering = `-- name: LockStateOrdering :exec
SELECT pg_advisory_xact_lock(
    hashtextextended(
        'states-order:' || CAST(CAST($1 AS uuid) AS text) || ':' || CAST($2 AS text),
        0
    )
)
`

type LockStateOrderingParams struct {
	WorkspaceID uuid.UUID
	Category    string
}

func (q *Queries) LockStateOrdering(ctx context.Context, arg LockStateOrderingParams) error {
	_, err := q.db.Exec(ctx, lockStateOrdering, arg.WorkspaceID, arg.Category)
	return err
}

const nextStateOrderIndex = `-- name: NextStateOrderIndex :one
SELECT CAST(COALESCE(MAX(status.order_index), -1) + 10 AS integer)
FROM public.statuses AS status
WHERE status.workspace_id = $1
  AND status.category = CAST($2 AS text)
`

type NextStateOrderIndexParams struct {
	WorkspaceID uuid.UUID
	Category    string
}

func (q *Queries) NextStateOrderIndex(ctx context.Context, arg NextStateOrderIndexParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextStateOrderIndex, arg.WorkspaceID, arg.Category)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const resetStateDefaults = `-- name: ResetStateDefaults :exec
UPDATE public.statuses
SET is_default = FALSE,
    updated_at = NOW()
WHERE workspace_id = $1
  AND team_id = $2
  AND is_default = TRUE
`

type ResetStateDefaultsParams struct {
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
}

func (q *Queries) ResetStateDefaults(ctx context.Context, arg ResetStateDefaultsParams) error {
	_, err := q.db.Exec(ctx, resetStateDefaults, arg.WorkspaceID, arg.TeamID)
	return err
}

const stateTeamExistsForMember = `-- name: StateTeamExistsForMember :one
SELECT EXISTS (
    SELECT 1
    FROM public.teams AS team
    INNER JOIN public.workspace_members AS membership
        ON membership.workspace_id = team.workspace_id
       AND membership.user_id = $1
    INNER JOIN public.users AS actor
        ON actor.user_id = membership.user_id
       AND actor.is_active = TRUE
    WHERE team.team_id = $2
      AND team.workspace_id = $3
)
`

type StateTeamExistsForMemberParams struct {
	ActorID     uuid.UUID
	TeamID      uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) StateTeamExistsForMember(ctx context.Context, arg StateTeamExistsForMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, stateTeamExistsForMember, arg.ActorID, arg.TeamID, arg.WorkspaceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateStateForMember = `-- name: UpdateStateForMember :one
UPDATE public.statuses AS status
SET name = CASE
        WHEN CAST($1 AS boolean) THEN CAST($2 AS text)
        ELSE status.name
    END,
    order_index = CASE
        WHEN CAST($3 AS boolean) THEN CAST($4 AS integer)
        ELSE status.order_index
    END,
    is_default = CASE
        WHEN CAST($5 AS boolean) THEN CAST($6 AS boolean)
        ELSE status.is_default
    END,
    color = CASE
        WHEN CAST($7 AS boolean) THEN CAST($8 AS text)
        ELSE status.color
    END,
    updated_at = NOW()
WHERE status.status_id = $9
  AND status.workspace_id = $10
  AND EXISTS (
      SELECT 1
      FROM public.workspace_members AS membership
      INNER JOIN public.users AS actor
          ON actor.user_id = membership.user_id
         AND actor.is_active = TRUE
      WHERE membership.workspace_id = status.workspace_id
        AND membership.user_id = $11
  )
RETURNING status_id, name, category, order_index, team_id, workspace_id,
          is_default, color, created_at, updated_at
`

type UpdateStateForMemberParams struct {
	SetName       bool
	Name          string
	SetOrderIndex bool
	OrderIndex    int32
	SetIsDefault  bool
	IsDefault     bool
	SetColor      bool
	Color         string
	StatusID      uuid.UUID
	WorkspaceID   uuid.UUID
	ActorID       uuid.UUID
}

type UpdateStateForMemberRow struct {
	StatusID    uuid.UUID
	Name        string
	Category    *string
	OrderIndex  *int32
	TeamID      uuid.UUID
	WorkspaceID uuid.UUID
	IsDefault   bool
	Color       *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdateStateForMember(ctx context.Context, arg UpdateStateForMemberParams) (UpdateStateForMemberRow, error) {
	row := q.db.QueryRow(ctx, updateStateForMember,
		arg.SetName,
		arg.Name,
		arg.SetOrderIndex,
		arg.OrderIndex,
		arg.SetIsDefault,
		arg.IsDefault,
		arg.SetColor,
		arg.Color,
		arg.StatusID,
		arg.WorkspaceID,
		arg.ActorID,
	)
	var i UpdateStateForMemberRow
	err := row.Scan(
		&i.StatusID,
		&i.Name,
		&i.Category,
		&i.OrderIndex,
		&i.TeamID,
		&i.WorkspaceID,
		&i.IsDefault,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
