// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: validation.sql

package integrationrequestssql

import (
	"context"

	"github.com/google/uuid"
)

const countAvailableIntegrationRequestLabels = `-- name: CountAvailableIntegrationRequestLabels :one
SELECT COUNT(*)
FROM public.labels
WHERE workspace_id = $1
  AND (team_id = $2 OR team_id IS NULL)
  AND label_id = ANY(CAST($3 AS uuid[]))
`

type CountAvailableIntegrationRequestLabelsParams struct {
	WorkspaceID *uuid.UUID
	TeamID      *uuid.UUID
	LabelIds    []uuid.UUID
}

func (q *Queries) CountAvailableIntegrationRequestLabels(ctx context.Context, arg CountAvailableIntegrationRequestLabelsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAvailableIntegrationRequestLabels, arg.WorkspaceID, arg.TeamID, arg.LabelIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const integrationRequestAssigneeAvailable = `-- name: IntegrationRequestAssigneeAvailable :one
SELECT EXISTS (
    SELECT 1
    FROM public.team_members AS team_member
    INNER JOIN public.users AS actor_user
        ON actor_user.user_id = team_member.user_id
       AND actor_user.is_active = TRUE
    INNER JOIN public.workspace_members AS workspace_member
        ON workspace_member.user_id = team_member.user_id
       AND workspace_member.workspace_id = $1
    WHERE team_member.team_id = $2
      AND team_member.user_id = $3
)
`

type IntegrationRequestAssigneeAvailableParams struct {
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
	AssigneeID  uuid.UUID
}

func (q *Queries) IntegrationRequestAssigneeAvailable(ctx context.Context, arg IntegrationRequestAssigneeAvailableParams) (bool, error) {
	row := q.db.QueryRow(ctx, integrationRequestAssigneeAvailable, arg.WorkspaceID, arg.TeamID, arg.AssigneeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const integrationRequestKeyResultAvailable = `-- name: IntegrationRequestKeyResultAvailable :one
SELECT EXISTS (
    SELECT 1
    FROM public.key_results AS key_result
    INNER JOIN public.objectives AS objective
        ON objective.objective_id = key_result.objective_id
    WHERE key_result.id = $1
      AND key_result.objective_id = $2
      AND objective.workspace_id = $3
      AND objective.team_id = $4
)
`

type IntegrationRequestKeyResultAvailableParams struct {
	KeyResultID uuid.UUID
	ObjectiveID uuid.UUID
	WorkspaceID *uuid.UUID
	TeamID      *uuid.UUID
}

func (q *Queries) IntegrationRequestKeyResultAvailable(ctx context.Context, arg IntegrationRequestKeyResultAvailableParams) (bool, error) {
	row := q.db.QueryRow(ctx, integrationRequestKeyResultAvailable,
		arg.KeyResultID,
		arg.ObjectiveID,
		arg.WorkspaceID,
		arg.TeamID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const integrationRequestObjectiveAvailable = `-- name: IntegrationRequestObjectiveAvailable :one
SELECT EXISTS (
    SELECT 1
    FROM public.objectives
    WHERE objective_id = $1
      AND workspace_id = $2
      AND team_id = $3
)
`

type IntegrationRequestObjectiveAvailableParams struct {
	ObjectiveID uuid.UUID
	WorkspaceID *uuid.UUID
	TeamID      *uuid.UUID
}

func (q *Queries) IntegrationRequestObjectiveAvailable(ctx context.Context, arg IntegrationRequestObjectiveAvailableParams) (bool, error) {
	row := q.db.QueryRow(ctx, integrationRequestObjectiveAvailable, arg.ObjectiveID, arg.WorkspaceID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const integrationRequestSprintAvailable = `-- name: IntegrationRequestSprintAvailable :one
SELECT EXISTS (
    SELECT 1
    FROM public.sprints
    WHERE sprint_id = $1
      AND workspace_id = $2
      AND team_id = $3
)
`

type IntegrationRequestSprintAvailableParams struct {
	SprintID    uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
}

func (q *Queries) IntegrationRequestSprintAvailable(ctx context.Context, arg IntegrationRequestSprintAvailableParams) (bool, error) {
	row := q.db.QueryRow(ctx, integrationRequestSprintAvailable, arg.SprintID, arg.WorkspaceID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const integrationRequestStatusAvailable = `-- name: IntegrationRequestStatusAvailable :one
SELECT EXISTS (
    SELECT 1
    FROM public.statuses
    WHERE status_id = $1
      AND workspace_id = $2
      AND team_id = $3
)
`

type IntegrationRequestStatusAvailableParams struct {
	StatusID    uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
}

func (q *Queries) IntegrationRequestStatusAvailable(ctx context.Context, arg IntegrationRequestStatusAvailableParams) (bool, error) {
	row := q.db.QueryRow(ctx, integrationRequestStatusAvailable, arg.StatusID, arg.WorkspaceID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
