// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package teamsettingssql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AdvanceSprintAutomationCounter(ctx context.Context, arg AdvanceSprintAutomationCounterParams) (int64, error)
	CountUpcomingSprintsForAutomation(ctx context.Context, arg CountUpcomingSprintsForAutomationParams) (int32, error)
	CreateAutomatedSprint(ctx context.Context, arg CreateAutomatedSprintParams) (uuid.UUID, error)
	DisableSprintAutomationIfInactive(ctx context.Context, arg DisableSprintAutomationIfInactiveParams) (int64, error)
	EnsureEstimationSettings(ctx context.Context, arg EnsureEstimationSettingsParams) (int64, error)
	EnsureSprintSettings(ctx context.Context, arg EnsureSprintSettingsParams) (int64, error)
	EnsureStoryAutomationSettings(ctx context.Context, arg EnsureStoryAutomationSettingsParams) (int64, error)
	FindCustomSprintScheduleConflict(ctx context.Context, arg FindCustomSprintScheduleConflictParams) (FindCustomSprintScheduleConflictRow, error)
	GetActiveSprintEnd(ctx context.Context, arg GetActiveSprintEndParams) (time.Time, error)
	GetDatabaseDate(ctx context.Context) (time.Time, error)
	GetEstimationSettings(ctx context.Context, arg GetEstimationSettingsParams) (TeamEstimationSetting, error)
	GetSprintAutomationInactivitySnapshot(ctx context.Context, arg GetSprintAutomationInactivitySnapshotParams) (GetSprintAutomationInactivitySnapshotRow, error)
	GetSprintAutomationScheduleBoundary(ctx context.Context, arg GetSprintAutomationScheduleBoundaryParams) (time.Time, error)
	GetSprintSettings(ctx context.Context, arg GetSprintSettingsParams) (GetSprintSettingsRow, error)
	GetStoryAutomationSettings(ctx context.Context, arg GetStoryAutomationSettingsParams) (TeamStoryAutomationSetting, error)
	InsertSprintAutomationAuditEvent(ctx context.Context, arg InsertSprintAutomationAuditEventParams) error
	InsertTeamSettingsAuditEvent(ctx context.Context, arg InsertTeamSettingsAuditEventParams) error
	IsActiveTeamMember(ctx context.Context, arg IsActiveTeamMemberParams) (bool, error)
	ListManagedFutureSprintsForUpdate(ctx context.Context, arg ListManagedFutureSprintsForUpdateParams) ([]ListManagedFutureSprintsForUpdateRow, error)
	ListSprintAutomationInactivityCandidates(ctx context.Context, arg ListSprintAutomationInactivityCandidatesParams) ([]ListSprintAutomationInactivityCandidatesRow, error)
	ListSprintAutomationTeams(ctx context.Context, arg ListSprintAutomationTeamsParams) ([]ListSprintAutomationTeamsRow, error)
	LockSprintAutomation(ctx context.Context, arg LockSprintAutomationParams) error
	LockSprintSettings(ctx context.Context, arg LockSprintSettingsParams) (LockSprintSettingsRow, error)
	UpdateEstimationSettings(ctx context.Context, arg UpdateEstimationSettingsParams) (TeamEstimationSetting, error)
	UpdateManagedSprintSchedule(ctx context.Context, arg UpdateManagedSprintScheduleParams) (int64, error)
	UpdateSprintSettings(ctx context.Context, arg UpdateSprintSettingsParams) (UpdateSprintSettingsRow, error)
	UpdateStoryAutomationSettings(ctx context.Context, arg UpdateStoryAutomationSettingsParams) (TeamStoryAutomationSetting, error)
}

var _ Querier = (*Queries)(nil)
