import {
  AnalyticsIcon,
  ApiKeyIcon,
  AttachmentIcon,
  BankIcon,
  BookIcon,
  Building03Icon,
  Calculator01Icon,
  CalendarIcon,
  CallIcon,
  ChatIcon,
  CheckListIcon,
  ClockIcon,
  CodeIcon,
  Coins01Icon,
  CommentIcon,
  CreditCardIcon,
  DashboardIcon,
  DocsIcon,
  EmailIcon,
  EstimateIcon,
  GoalIcon,
  HandshakeIcon,
  HealthIcon,
  HelpIcon,
  HistoryIcon,
  HomeIcon,
  ImageIcon,
  InfoIcon,
  InternetIcon,
  Invoice01Icon,
  KanbanIcon,
  LinkIcon,
  ListIcon,
  LockIcon,
  Megaphone01Icon,
  MicrophoneIcon,
  Money01Icon,
  ObjectiveIcon,
  PackageIcon,
  PercentIcon,
  PiggyBankIcon,
  PinIcon,
  RoadmapIcon,
  RobotIcon,
  ShareIcon,
  ShoppingCart01Icon,
  SprintsIcon,
  StarIcon,
  Store01Icon,
  StrategyIcon,
  TagsIcon,
  TargetDollarIcon,
  TeamIcon,
  ThumbsUpIcon,
  UserIcon,
  Video02Icon,
  Wallet01Icon,
  WarningIcon,
  WorkIcon,
  WorkflowIcon,
  WorkspaceIcon,
} from "icons";
import type { CustomField, CustomFieldIconKey, CustomFieldType } from "./types";

export { customFieldIconKeys } from "./types";

export const customFieldIconGroups = [
  "Essentials",
  "Finance",
  "People & business",
  "Content & communication",
  "Workflow & insights",
] as const;

export const customFieldIconOptions = [
  {
    value: "text",
    label: "Text",
    Icon: DocsIcon,
    group: "Essentials",
    keywords: ["document", "notes", "description"],
  },
  {
    value: "number",
    label: "Number",
    Icon: EstimateIcon,
    group: "Essentials",
    keywords: ["amount", "quantity", "count", "value"],
  },
  {
    value: "calendar",
    label: "Calendar",
    Icon: CalendarIcon,
    group: "Essentials",
    keywords: ["date", "deadline", "due"],
  },
  {
    value: "clock",
    label: "Clock",
    Icon: ClockIcon,
    group: "Essentials",
    keywords: ["time", "duration", "hours"],
  },
  {
    value: "list",
    label: "List",
    Icon: ListIcon,
    group: "Essentials",
    keywords: ["select", "options", "category"],
  },
  {
    value: "checklist",
    label: "Checklist",
    Icon: CheckListIcon,
    group: "Essentials",
    keywords: ["check", "done", "requirements"],
  },
  {
    value: "tag",
    label: "Tag",
    Icon: TagsIcon,
    group: "Essentials",
    keywords: ["label", "segment", "category"],
  },
  {
    value: "pin",
    label: "Pin",
    Icon: PinIcon,
    group: "Essentials",
    keywords: ["location", "important", "bookmark"],
  },
  {
    value: "star",
    label: "Star",
    Icon: StarIcon,
    group: "Essentials",
    keywords: ["rating", "favorite", "score"],
  },
  {
    value: "attachment",
    label: "Attachment",
    Icon: AttachmentIcon,
    group: "Essentials",
    keywords: ["file", "document", "asset"],
  },
  {
    value: "link",
    label: "Link",
    Icon: LinkIcon,
    group: "Essentials",
    keywords: ["url", "website", "reference"],
  },
  {
    value: "person",
    label: "Person",
    Icon: UserIcon,
    group: "People & business",
    keywords: ["user", "contact", "customer", "client"],
  },
  {
    value: "team",
    label: "Team",
    Icon: TeamIcon,
    group: "People & business",
    keywords: ["people", "group", "department"],
  },
  {
    value: "workspace",
    label: "Workspace",
    Icon: WorkspaceIcon,
    group: "People & business",
    keywords: ["company", "organization", "account"],
  },
  {
    value: "work",
    label: "Work",
    Icon: WorkIcon,
    group: "People & business",
    keywords: ["task", "deal", "project", "contract"],
  },
  {
    value: "goal",
    label: "Goal",
    Icon: GoalIcon,
    group: "People & business",
    keywords: ["target", "objective", "quota"],
  },
  {
    value: "objective",
    label: "Objective",
    Icon: ObjectiveIcon,
    group: "People & business",
    keywords: ["milestone", "outcome", "plan"],
  },
  {
    value: "strategy",
    label: "Strategy",
    Icon: StrategyIcon,
    group: "People & business",
    keywords: ["direction", "initiative", "business"],
  },
  {
    value: "roadmap",
    label: "Roadmap",
    Icon: RoadmapIcon,
    group: "People & business",
    keywords: ["launch", "plan", "timeline"],
  },
  {
    value: "home",
    label: "Home",
    Icon: HomeIcon,
    group: "People & business",
    keywords: ["office", "address", "property"],
  },
  {
    value: "health",
    label: "Health",
    Icon: HealthIcon,
    group: "People & business",
    keywords: ["confidence", "progress", "pulse"],
  },
  {
    value: "approval",
    label: "Approval",
    Icon: ThumbsUpIcon,
    group: "People & business",
    keywords: ["approved", "review", "signoff"],
  },
  {
    value: "email",
    label: "Email",
    Icon: EmailIcon,
    group: "Content & communication",
    keywords: ["mail", "message", "outreach"],
  },
  {
    value: "chat",
    label: "Chat",
    Icon: ChatIcon,
    group: "Content & communication",
    keywords: ["conversation", "discussion", "channel"],
  },
  {
    value: "comment",
    label: "Comment",
    Icon: CommentIcon,
    group: "Content & communication",
    keywords: ["feedback", "note", "reply"],
  },
  {
    value: "globe",
    label: "Globe",
    Icon: InternetIcon,
    group: "Content & communication",
    keywords: ["web", "country", "region", "language"],
  },
  {
    value: "share",
    label: "Share",
    Icon: ShareIcon,
    group: "Content & communication",
    keywords: ["social", "distribution", "campaign", "referral"],
  },
  {
    value: "image",
    label: "Image",
    Icon: ImageIcon,
    group: "Content & communication",
    keywords: ["photo", "creative", "design", "content"],
  },
  {
    value: "video",
    label: "Video",
    Icon: Video02Icon,
    group: "Content & communication",
    keywords: ["recording", "meeting", "content"],
  },
  {
    value: "microphone",
    label: "Microphone",
    Icon: MicrophoneIcon,
    group: "Content & communication",
    keywords: ["audio", "podcast", "voice"],
  },
  {
    value: "book",
    label: "Book",
    Icon: BookIcon,
    group: "Content & communication",
    keywords: ["knowledge", "guide", "research"],
  },
  {
    value: "help",
    label: "Help",
    Icon: HelpIcon,
    group: "Content & communication",
    keywords: ["question", "support", "request"],
  },
  {
    value: "info",
    label: "Information",
    Icon: InfoIcon,
    group: "Content & communication",
    keywords: ["details", "context", "brief"],
  },
  {
    value: "analytics",
    label: "Analytics",
    Icon: AnalyticsIcon,
    group: "Workflow & insights",
    keywords: ["metric", "report", "conversion", "performance"],
  },
  {
    value: "dashboard",
    label: "Pie chart",
    Icon: DashboardIcon,
    group: "Workflow & insights",
    keywords: ["chart", "percentage", "share", "distribution"],
  },
  {
    value: "workflow",
    label: "Workflow",
    Icon: WorkflowIcon,
    group: "Workflow & insights",
    keywords: ["process", "stage", "pipeline"],
  },
  {
    value: "kanban",
    label: "Board",
    Icon: KanbanIcon,
    group: "Workflow & insights",
    keywords: ["kanban", "status", "stage"],
  },
  {
    value: "sprint",
    label: "Sprint",
    Icon: SprintsIcon,
    group: "Workflow & insights",
    keywords: ["cycle", "iteration", "delivery"],
  },
  {
    value: "automation",
    label: "Automation",
    Icon: RobotIcon,
    group: "Workflow & insights",
    keywords: ["rule", "bot", "automatic"],
  },
  {
    value: "history",
    label: "History",
    Icon: HistoryIcon,
    group: "Workflow & insights",
    keywords: ["activity", "change", "renewal"],
  },
  {
    value: "lock",
    label: "Lock",
    Icon: LockIcon,
    group: "Workflow & insights",
    keywords: ["private", "security", "access"],
  },
  {
    value: "key",
    label: "Key",
    Icon: ApiKeyIcon,
    group: "Workflow & insights",
    keywords: ["identifier", "reference", "credential"],
  },
  {
    value: "code",
    label: "Code",
    Icon: CodeIcon,
    group: "Workflow & insights",
    keywords: ["technical", "development", "integration"],
  },
  {
    value: "warning",
    label: "Warning",
    Icon: WarningIcon,
    group: "Workflow & insights",
    keywords: ["risk", "blocked", "attention"],
  },
  {
    value: "money",
    label: "Money",
    Icon: Money01Icon,
    group: "Finance",
    keywords: ["cash", "amount", "budget", "revenue", "deal"],
  },
  {
    value: "coins",
    label: "Coins",
    Icon: Coins01Icon,
    group: "Finance",
    keywords: ["savings", "cost", "balance"],
  },
  {
    value: "wallet",
    label: "Wallet",
    Icon: Wallet01Icon,
    group: "Finance",
    keywords: ["balance", "account", "spending"],
  },
  {
    value: "credit-card",
    label: "Credit card",
    Icon: CreditCardIcon,
    group: "Finance",
    keywords: ["payment", "billing", "purchase"],
  },
  {
    value: "bank",
    label: "Bank",
    Icon: BankIcon,
    group: "Finance",
    keywords: ["finance", "institution", "account"],
  },
  {
    value: "invoice",
    label: "Invoice",
    Icon: Invoice01Icon,
    group: "Finance",
    keywords: ["bill", "receipt", "payment", "contract"],
  },
  {
    value: "percent",
    label: "Percent",
    Icon: PercentIcon,
    group: "Finance",
    keywords: ["discount", "rate", "margin", "commission"],
  },
  {
    value: "calculator",
    label: "Calculator",
    Icon: Calculator01Icon,
    group: "Finance",
    keywords: ["estimate", "cost", "forecast"],
  },
  {
    value: "piggy-bank",
    label: "Savings",
    Icon: PiggyBankIcon,
    group: "Finance",
    keywords: ["piggy bank", "budget", "reserve"],
  },
  {
    value: "target-money",
    label: "Revenue target",
    Icon: TargetDollarIcon,
    group: "Finance",
    keywords: ["quota", "sales", "forecast", "money"],
  },
  {
    value: "building",
    label: "Company",
    Icon: Building03Icon,
    group: "People & business",
    keywords: ["business", "organization", "account", "office"],
  },
  {
    value: "megaphone",
    label: "Campaign",
    Icon: Megaphone01Icon,
    group: "Content & communication",
    keywords: ["announcement", "marketing", "advertising", "launch"],
  },
  {
    value: "store",
    label: "Store",
    Icon: Store01Icon,
    group: "People & business",
    keywords: ["shop", "retail", "merchant"],
  },
  {
    value: "package",
    label: "Package",
    Icon: PackageIcon,
    group: "People & business",
    keywords: ["product", "inventory", "delivery", "shipping"],
  },
  {
    value: "phone",
    label: "Phone",
    Icon: CallIcon,
    group: "Content & communication",
    keywords: ["call", "contact", "customer", "sales"],
  },
  {
    value: "handshake",
    label: "Partnership",
    Icon: HandshakeIcon,
    group: "People & business",
    keywords: ["agreement", "deal", "contract", "partner"],
  },
  {
    value: "shopping-cart",
    label: "Shopping cart",
    Icon: ShoppingCart01Icon,
    group: "People & business",
    keywords: ["order", "purchase", "commerce"],
  },
] as const satisfies readonly {
  value: CustomFieldIconKey;
  label: string;
  Icon: typeof DocsIcon;
  group: (typeof customFieldIconGroups)[number];
  keywords: readonly string[];
}[];

const TYPE_ICONS = {
  text: "text",
  number: "number",
  money: "money",
  date: "calendar",
  select: "list",
  person: "person",
} as const satisfies Record<CustomFieldType, CustomFieldIconKey>;

type IconField = Pick<CustomField, "type" | "icon">;

export const getCustomFieldIconKey = (field: IconField): CustomFieldIconKey =>
  field.icon ?? TYPE_ICONS[field.type];

export const CustomFieldIcon = ({
  field,
  className,
}: {
  field: IconField;
  className?: string;
}) => {
  const key = getCustomFieldIconKey(field);
  const Icon =
    customFieldIconOptions.find((option) => option.value === key)?.Icon ??
    DocsIcon;
  return <Icon aria-hidden className={className} focusable="false" />;
};
