// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reads.sql

package adminsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAdminDashboardSummary = `-- name: GetAdminDashboardSummary :one
SELECT
    CAST((SELECT COUNT(*) FROM workspaces AS active_workspace WHERE active_workspace.deleted_at IS NULL) AS bigint) AS total_workspaces,
    CAST((SELECT COUNT(*) FROM workspaces AS trial_workspace WHERE trial_workspace.deleted_at IS NULL AND trial_workspace.trial_ends_on > CAST($1 AS timestamptz)) AS bigint) AS active_trials,
    CAST((SELECT COUNT(*) FROM workspaces AS expired_workspace WHERE expired_workspace.deleted_at IS NULL AND expired_workspace.trial_ends_on IS NOT NULL AND expired_workspace.trial_ends_on <= CAST($1 AS timestamptz)) AS bigint) AS expired_trials,
    CAST((
        SELECT COUNT(DISTINCT paid_subscription.workspace_id)
        FROM workspace_subscriptions AS paid_subscription
        WHERE paid_subscription.subscription_status IN ('active', 'trialing', 'past_due')
          AND COALESCE(CAST(paid_subscription.subscription_tier AS text), 'free') <> 'free'
    ) AS bigint) AS paid_workspaces,
    CAST((SELECT COUNT(*) FROM workspaces AS deleted_workspace WHERE deleted_workspace.deleted_at IS NOT NULL) AS bigint) AS deleted_workspaces,
    CAST((SELECT COUNT(*) FROM users AS counted_user) AS bigint) AS total_users,
    CAST((SELECT COUNT(*) FROM users AS internal_user WHERE internal_user.is_internal = TRUE) AS bigint) AS internal_users,
    CAST((
        SELECT COUNT(*)
        FROM workspace_subscriptions AS active_subscription
        WHERE active_subscription.subscription_status IN ('active', 'trialing', 'past_due')
    ) AS bigint) AS active_subscriptions,
    CAST((SELECT COUNT(*) FROM slack_workspaces AS slack_installation WHERE slack_installation.is_active = TRUE) AS bigint) AS slack_installations,
    CAST((SELECT COUNT(*) FROM github_installations AS github_installation WHERE github_installation.is_active = TRUE) AS bigint) AS github_installations,
    CAST((
        SELECT COUNT(*)
        FROM admin_audit_logs AS recent_audit
        WHERE recent_audit.created_at >= CAST($1 AS timestamptz) - INTERVAL '30 days'
    ) AS bigint) AS recent_admin_audit_logs
`

type GetAdminDashboardSummaryParams struct {
	NowAt time.Time
}

type GetAdminDashboardSummaryRow struct {
	TotalWorkspaces      int64
	ActiveTrials         int64
	ExpiredTrials        int64
	PaidWorkspaces       int64
	DeletedWorkspaces    int64
	TotalUsers           int64
	InternalUsers        int64
	ActiveSubscriptions  int64
	SlackInstallations   int64
	GithubInstallations  int64
	RecentAdminAuditLogs int64
}

func (q *Queries) GetAdminDashboardSummary(ctx context.Context, arg GetAdminDashboardSummaryParams) (GetAdminDashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAdminDashboardSummary, arg.NowAt)
	var i GetAdminDashboardSummaryRow
	err := row.Scan(
		&i.TotalWorkspaces,
		&i.ActiveTrials,
		&i.ExpiredTrials,
		&i.PaidWorkspaces,
		&i.DeletedWorkspaces,
		&i.TotalUsers,
		&i.InternalUsers,
		&i.ActiveSubscriptions,
		&i.SlackInstallations,
		&i.GithubInstallations,
		&i.RecentAdminAuditLogs,
	)
	return i, err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT
    target.user_id,
    target.username,
    target.email,
    target.full_name,
    target.avatar_url,
    target.is_active,
    target.is_system,
    target.is_internal,
    target.login_reactivation_policy,
    target.last_login_at,
    target.last_used_workspace_id,
    last_workspace.name AS last_used_workspace,
    target.github_username,
    CAST((
        SELECT COUNT(*)
        FROM workspace_members AS membership
        WHERE membership.user_id = target.user_id
    ) AS bigint) AS workspace_count,
    target.created_at,
    target.updated_at
FROM users AS target
LEFT JOIN workspaces AS last_workspace
  ON last_workspace.workspace_id = target.last_used_workspace_id
WHERE target.user_id = CAST($1 AS uuid)
`

type GetAdminUserParams struct {
	UserID uuid.UUID
}

type GetAdminUserRow struct {
	UserID                  uuid.UUID
	Username                string
	Email                   string
	FullName                *string
	AvatarURL               *string
	IsActive                bool
	IsSystem                bool
	IsInternal              bool
	LoginReactivationPolicy string
	LastLoginAt             *time.Time
	LastUsedWorkspaceID     *uuid.UUID
	LastUsedWorkspace       *string
	GithubUsername          *string
	WorkspaceCount          int64
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

func (q *Queries) GetAdminUser(ctx context.Context, arg GetAdminUserParams) (GetAdminUserRow, error) {
	row := q.db.QueryRow(ctx, getAdminUser, arg.UserID)
	var i GetAdminUserRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.AvatarURL,
		&i.IsActive,
		&i.IsSystem,
		&i.IsInternal,
		&i.LoginReactivationPolicy,
		&i.LastLoginAt,
		&i.LastUsedWorkspaceID,
		&i.LastUsedWorkspace,
		&i.GithubUsername,
		&i.WorkspaceCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminWorkspace = `-- name: GetAdminWorkspace :one
WITH latest_subscription AS (
    SELECT DISTINCT ON (candidate.workspace_id)
        candidate.workspace_id,
        candidate.subscription_tier,
        candidate.subscription_status,
        candidate.seat_count,
        candidate.stripe_customer_id,
        candidate.stripe_subscription_id
    FROM workspace_subscriptions AS candidate
    ORDER BY candidate.workspace_id, candidate.updated_at DESC NULLS LAST, candidate.stripe_subscription_id DESC
)
SELECT
    workspace.workspace_id,
    workspace.name,
    workspace.slug,
    workspace.avatar_url,
    workspace.color AS workspace_color,
    workspace.team_size AS workspace_team_size,
    workspace.trial_ends_on,
    workspace.deleted_at,
    workspace.last_accessed_at,
    workspace.created_by,
    creator.email AS created_by_email,
    creator.full_name AS created_by_name,
    CAST((SELECT COUNT(*) FROM workspace_members WHERE workspace_id = workspace.workspace_id) AS bigint) AS member_count,
    CAST((SELECT COUNT(*) FROM teams WHERE workspace_id = workspace.workspace_id) AS bigint) AS team_count,
    CAST((SELECT COUNT(*) FROM stories WHERE workspace_id = workspace.workspace_id AND deleted_at IS NULL) AS bigint) AS story_count,
    subscription.subscription_tier,
    subscription.subscription_status,
    subscription.seat_count AS subscription_seats,
    subscription.stripe_customer_id,
    subscription.stripe_subscription_id,
    EXISTS (
        SELECT 1 FROM slack_workspaces
        WHERE workspace_id = workspace.workspace_id AND is_active = TRUE
    ) AS slack_installed,
    EXISTS (
        SELECT 1 FROM github_installations
        WHERE workspace_id = workspace.workspace_id AND is_active = TRUE
    ) AS github_installed,
    workspace.created_at,
    workspace.updated_at
FROM workspaces AS workspace
LEFT JOIN users AS creator ON creator.user_id = workspace.created_by
LEFT JOIN latest_subscription AS subscription
  ON subscription.workspace_id = workspace.workspace_id
WHERE workspace.workspace_id = CAST($1 AS uuid)
`

type GetAdminWorkspaceParams struct {
	WorkspaceID uuid.UUID
}

type GetAdminWorkspaceRow struct {
	WorkspaceID          uuid.UUID
	Name                 string
	Slug                 string
	AvatarURL            *string
	WorkspaceColor       string
	WorkspaceTeamSize    string
	TrialEndsOn          *time.Time
	DeletedAt            *time.Time
	LastAccessedAt       *time.Time
	CreatedBy            *uuid.UUID
	CreatedByEmail       *string
	CreatedByName        *string
	MemberCount          int64
	TeamCount            int64
	StoryCount           int64
	SubscriptionTier     *SubscriptionTierEnum
	SubscriptionStatus   *string
	SubscriptionSeats    *int32
	StripeCustomerID     *string
	StripeSubscriptionID *string
	SlackInstalled       bool
	GithubInstalled      bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetAdminWorkspace(ctx context.Context, arg GetAdminWorkspaceParams) (GetAdminWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getAdminWorkspace, arg.WorkspaceID)
	var i GetAdminWorkspaceRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.AvatarURL,
		&i.WorkspaceColor,
		&i.WorkspaceTeamSize,
		&i.TrialEndsOn,
		&i.DeletedAt,
		&i.LastAccessedAt,
		&i.CreatedBy,
		&i.CreatedByEmail,
		&i.CreatedByName,
		&i.MemberCount,
		&i.TeamCount,
		&i.StoryCount,
		&i.SubscriptionTier,
		&i.SubscriptionStatus,
		&i.SubscriptionSeats,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SlackInstalled,
		&i.GithubInstalled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminUserMemberships = `-- name: ListAdminUserMemberships :many
SELECT
    workspace.workspace_id,
    workspace.name AS workspace_name,
    workspace.slug AS workspace_slug,
    CAST(membership.role AS text) AS role,
    membership.created_at AS joined_at
FROM workspace_members AS membership
JOIN workspaces AS workspace ON workspace.workspace_id = membership.workspace_id
WHERE membership.user_id = CAST($1 AS uuid)
ORDER BY membership.created_at DESC, workspace.workspace_id DESC
`

type ListAdminUserMembershipsParams struct {
	UserID uuid.UUID
}

type ListAdminUserMembershipsRow struct {
	WorkspaceID   uuid.UUID
	WorkspaceName string
	WorkspaceSlug string
	Role          string
	JoinedAt      time.Time
}

func (q *Queries) ListAdminUserMemberships(ctx context.Context, arg ListAdminUserMembershipsParams) ([]ListAdminUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listAdminUserMemberships, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUserMembershipsRow{}
	for rows.Next() {
		var i ListAdminUserMembershipsRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.WorkspaceName,
			&i.WorkspaceSlug,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT
    target.user_id,
    target.username,
    target.email,
    target.full_name,
    target.avatar_url,
    target.is_active,
    target.is_system,
    target.is_internal,
    target.login_reactivation_policy,
    target.last_login_at,
    target.last_used_workspace_id,
    last_workspace.name AS last_used_workspace,
    target.github_username,
    CAST((SELECT COUNT(*) FROM workspace_members WHERE user_id = target.user_id) AS bigint) AS workspace_count,
    target.created_at,
    target.updated_at,
    CAST(COUNT(*) OVER () AS bigint) AS total_count
FROM users AS target
LEFT JOIN workspaces AS last_workspace ON last_workspace.workspace_id = target.last_used_workspace_id
WHERE CAST($1 AS text) = ''
   OR target.email ILIKE '%' || CAST($1 AS text) || '%'
   OR target.username ILIKE '%' || CAST($1 AS text) || '%'
   OR target.full_name ILIKE '%' || CAST($1 AS text) || '%'
ORDER BY target.created_at DESC, target.user_id DESC
LIMIT CAST($3 AS integer)
OFFSET CAST($2 AS integer)
`

type ListAdminUsersParams struct {
	SearchText string
	RowOffset  int32
	RowLimit   int32
}

type ListAdminUsersRow struct {
	UserID                  uuid.UUID
	Username                string
	Email                   string
	FullName                *string
	AvatarURL               *string
	IsActive                bool
	IsSystem                bool
	IsInternal              bool
	LoginReactivationPolicy string
	LastLoginAt             *time.Time
	LastUsedWorkspaceID     *uuid.UUID
	LastUsedWorkspace       *string
	GithubUsername          *string
	WorkspaceCount          int64
	CreatedAt               time.Time
	UpdatedAt               time.Time
	TotalCount              int64
}

func (q *Queries) ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers, arg.SearchText, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.AvatarURL,
			&i.IsActive,
			&i.IsSystem,
			&i.IsInternal,
			&i.LoginReactivationPolicy,
			&i.LastLoginAt,
			&i.LastUsedWorkspaceID,
			&i.LastUsedWorkspace,
			&i.GithubUsername,
			&i.WorkspaceCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminWorkspaceMembers = `-- name: ListAdminWorkspaceMembers :many
SELECT
    member.user_id,
    member.email,
    member.full_name,
    CAST(membership.role AS text) AS role,
    member.is_internal,
    membership.created_at AS joined_at
FROM workspace_members AS membership
JOIN users AS member ON member.user_id = membership.user_id
WHERE membership.workspace_id = CAST($1 AS uuid)
ORDER BY
    CASE CAST(membership.role AS text) WHEN 'admin' THEN 0 ELSE 1 END,
    member.full_name NULLS LAST,
    member.email,
    member.user_id
`

type ListAdminWorkspaceMembersParams struct {
	WorkspaceID uuid.UUID
}

type ListAdminWorkspaceMembersRow struct {
	UserID     uuid.UUID
	Email      string
	FullName   *string
	Role       string
	IsInternal bool
	JoinedAt   time.Time
}

func (q *Queries) ListAdminWorkspaceMembers(ctx context.Context, arg ListAdminWorkspaceMembersParams) ([]ListAdminWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listAdminWorkspaceMembers, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminWorkspaceMembersRow{}
	for rows.Next() {
		var i ListAdminWorkspaceMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.IsInternal,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminWorkspaces = `-- name: ListAdminWorkspaces :many
WITH latest_subscription AS (
    SELECT DISTINCT ON (candidate.workspace_id)
        candidate.workspace_id,
        candidate.subscription_tier,
        candidate.subscription_status,
        candidate.seat_count,
        candidate.stripe_customer_id,
        candidate.stripe_subscription_id
    FROM workspace_subscriptions AS candidate
    ORDER BY candidate.workspace_id, candidate.updated_at DESC NULLS LAST, candidate.stripe_subscription_id DESC
)
SELECT
    workspace.workspace_id,
    workspace.name,
    workspace.slug,
    workspace.avatar_url,
    workspace.color,
    workspace.team_size,
    workspace.trial_ends_on,
    workspace.deleted_at,
    workspace.last_accessed_at,
    workspace.created_by,
    creator.email AS created_by_email,
    creator.full_name AS created_by_name,
    CAST((SELECT COUNT(*) FROM workspace_members WHERE workspace_id = workspace.workspace_id) AS bigint) AS member_count,
    CAST((SELECT COUNT(*) FROM teams WHERE workspace_id = workspace.workspace_id) AS bigint) AS team_count,
    CAST((SELECT COUNT(*) FROM stories WHERE workspace_id = workspace.workspace_id AND deleted_at IS NULL) AS bigint) AS story_count,
    subscription.subscription_tier,
    subscription.subscription_status,
    subscription.seat_count AS subscription_seats,
    subscription.stripe_customer_id,
    subscription.stripe_subscription_id,
    EXISTS (
        SELECT 1 FROM slack_workspaces
        WHERE workspace_id = workspace.workspace_id AND is_active = TRUE
    ) AS slack_installed,
    EXISTS (
        SELECT 1 FROM github_installations
        WHERE workspace_id = workspace.workspace_id AND is_active = TRUE
    ) AS github_installed,
    workspace.created_at,
    workspace.updated_at,
    CAST(COUNT(*) OVER () AS bigint) AS total_count
FROM workspaces AS workspace
LEFT JOIN users AS creator ON creator.user_id = workspace.created_by
LEFT JOIN latest_subscription AS subscription
  ON subscription.workspace_id = workspace.workspace_id
WHERE (
    CAST($1 AS text) = ''
    OR workspace.name ILIKE '%' || CAST($1 AS text) || '%'
    OR workspace.slug ILIKE '%' || CAST($1 AS text) || '%'
    OR creator.email ILIKE '%' || CAST($1 AS text) || '%'
)
AND (
    CAST($2 AS text) = ''
    OR (CAST($2 AS text) = 'active' AND workspace.deleted_at IS NULL)
    OR (CAST($2 AS text) = 'trialing' AND workspace.deleted_at IS NULL AND workspace.trial_ends_on > CAST($3 AS timestamptz))
    OR (CAST($2 AS text) = 'expired' AND workspace.deleted_at IS NULL AND workspace.trial_ends_on IS NOT NULL AND workspace.trial_ends_on <= CAST($3 AS timestamptz))
    OR (CAST($2 AS text) = 'expiring' AND workspace.deleted_at IS NULL AND workspace.trial_ends_on > CAST($3 AS timestamptz) AND workspace.trial_ends_on <= CAST($3 AS timestamptz) + INTERVAL '7 days')
    OR (CAST($2 AS text) = 'paid' AND workspace.deleted_at IS NULL AND subscription.subscription_status IN ('active', 'trialing', 'past_due') AND COALESCE(CAST(subscription.subscription_tier AS text), 'free') <> 'free')
    OR (CAST($2 AS text) = 'past_due' AND workspace.deleted_at IS NULL AND subscription.subscription_status = 'past_due')
    OR (CAST($2 AS text) = 'deleted' AND workspace.deleted_at IS NOT NULL)
)
ORDER BY workspace.created_at DESC, workspace.workspace_id DESC
LIMIT CAST($5 AS integer)
OFFSET CAST($4 AS integer)
`

type ListAdminWorkspacesParams struct {
	SearchText   string
	StatusFilter string
	NowAt        time.Time
	RowOffset    int32
	RowLimit     int32
}

type ListAdminWorkspacesRow struct {
	WorkspaceID          uuid.UUID
	Name                 string
	Slug                 string
	AvatarURL            *string
	Color                string
	TeamSize             string
	TrialEndsOn          *time.Time
	DeletedAt            *time.Time
	LastAccessedAt       *time.Time
	CreatedBy            *uuid.UUID
	CreatedByEmail       *string
	CreatedByName        *string
	MemberCount          int64
	TeamCount            int64
	StoryCount           int64
	SubscriptionTier     *SubscriptionTierEnum
	SubscriptionStatus   *string
	SubscriptionSeats    *int32
	StripeCustomerID     *string
	StripeSubscriptionID *string
	SlackInstalled       bool
	GithubInstalled      bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
	TotalCount           int64
}

func (q *Queries) ListAdminWorkspaces(ctx context.Context, arg ListAdminWorkspacesParams) ([]ListAdminWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, listAdminWorkspaces,
		arg.SearchText,
		arg.StatusFilter,
		arg.NowAt,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminWorkspacesRow{}
	for rows.Next() {
		var i ListAdminWorkspacesRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.AvatarURL,
			&i.Color,
			&i.TeamSize,
			&i.TrialEndsOn,
			&i.DeletedAt,
			&i.LastAccessedAt,
			&i.CreatedBy,
			&i.CreatedByEmail,
			&i.CreatedByName,
			&i.MemberCount,
			&i.TeamCount,
			&i.StoryCount,
			&i.SubscriptionTier,
			&i.SubscriptionStatus,
			&i.SubscriptionSeats,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.SlackInstalled,
			&i.GithubInstalled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
