// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_deletion.sql

package calendarsql

import (
	"context"

	"github.com/google/uuid"
)

const accountCalendarCleanupPending = `-- name: AccountCalendarCleanupPending :one
SELECT EXISTS (
    SELECT 1 FROM calendar_connections
    WHERE user_id = CAST($1 AS uuid)
)
`

type AccountCalendarCleanupPendingParams struct {
	UserID uuid.UUID
}

func (q *Queries) AccountCalendarCleanupPending(ctx context.Context, arg AccountCalendarCleanupPendingParams) (bool, error) {
	row := q.db.QueryRow(ctx, accountCalendarCleanupPending, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteRevokedAccountCalendarConnections = `-- name: DeleteRevokedAccountCalendarConnections :exec
DELETE FROM calendar_connections
WHERE user_id = CAST($1 AS uuid)
  AND revoked_at IS NOT NULL
`

type DeleteRevokedAccountCalendarConnectionsParams struct {
	UserID uuid.UUID
}

func (q *Queries) DeleteRevokedAccountCalendarConnections(ctx context.Context, arg DeleteRevokedAccountCalendarConnectionsParams) error {
	_, err := q.db.Exec(ctx, deleteRevokedAccountCalendarConnections, arg.UserID)
	return err
}

const scrubAccountCalendarCleanup = `-- name: ScrubAccountCalendarCleanup :exec
UPDATE calendar_connections
SET connected_email = '', provider_account_id = '', timezone = 'UTC',
    sync_error = NULL, sync_token = NULL,
    notification_channel_id = NULL, notification_resource_id = NULL,
    notification_expires_at = NULL
WHERE user_id = CAST($1 AS uuid)
  AND cleanup_pending_at IS NOT NULL
`

type ScrubAccountCalendarCleanupParams struct {
	UserID uuid.UUID
}

func (q *Queries) ScrubAccountCalendarCleanup(ctx context.Context, arg ScrubAccountCalendarCleanupParams) error {
	_, err := q.db.Exec(ctx, scrubAccountCalendarCleanup, arg.UserID)
	return err
}

const scrubAccountCalendarOutbox = `-- name: ScrubAccountCalendarOutbox :exec
UPDATE calendar_schedule_event_outbox
SET payload = CAST('{}' AS jsonb), last_error = NULL
WHERE user_id = CAST($1 AS uuid)
`

type ScrubAccountCalendarOutboxParams struct {
	UserID uuid.UUID
}

func (q *Queries) ScrubAccountCalendarOutbox(ctx context.Context, arg ScrubAccountCalendarOutboxParams) error {
	_, err := q.db.Exec(ctx, scrubAccountCalendarOutbox, arg.UserID)
	return err
}
