// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package calendarsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteCalendarBusyWindows = `-- name: DeleteCalendarBusyWindows :exec
DELETE FROM calendar_busy_windows
WHERE connection_id = $1
`

type DeleteCalendarBusyWindowsParams struct {
	ConnectionID uuid.UUID
}

func (q *Queries) DeleteCalendarBusyWindows(ctx context.Context, arg DeleteCalendarBusyWindowsParams) error {
	_, err := q.db.Exec(ctx, deleteCalendarBusyWindows, arg.ConnectionID)
	return err
}

const deleteChangedCalendarBusyWindow = `-- name: DeleteChangedCalendarBusyWindow :exec
DELETE FROM calendar_busy_windows
WHERE connection_id = $1
  AND provider_event_id = $2
`

type DeleteChangedCalendarBusyWindowParams struct {
	ConnectionID    uuid.UUID
	ProviderEventID string
}

func (q *Queries) DeleteChangedCalendarBusyWindow(ctx context.Context, arg DeleteChangedCalendarBusyWindowParams) error {
	_, err := q.db.Exec(ctx, deleteChangedCalendarBusyWindow, arg.ConnectionID, arg.ProviderEventID)
	return err
}

const deleteChangedCalendarEvent = `-- name: DeleteChangedCalendarEvent :exec
DELETE FROM calendar_events
WHERE connection_id = $1
  AND calendar_id = 'primary'
  AND provider_event_id = $2
`

type DeleteChangedCalendarEventParams struct {
	ConnectionID    uuid.UUID
	ProviderEventID string
}

func (q *Queries) DeleteChangedCalendarEvent(ctx context.Context, arg DeleteChangedCalendarEventParams) error {
	_, err := q.db.Exec(ctx, deleteChangedCalendarEvent, arg.ConnectionID, arg.ProviderEventID)
	return err
}

const deleteStaleCalendarEvents = `-- name: DeleteStaleCalendarEvents :exec
DELETE FROM calendar_events
WHERE connection_id = $1
  AND sync_generation <> $2
`

type DeleteStaleCalendarEventsParams struct {
	ConnectionID   uuid.UUID
	SyncGeneration uuid.UUID
}

func (q *Queries) DeleteStaleCalendarEvents(ctx context.Context, arg DeleteStaleCalendarEventsParams) error {
	_, err := q.db.Exec(ctx, deleteStaleCalendarEvents, arg.ConnectionID, arg.SyncGeneration)
	return err
}

const getCalendarEvent = `-- name: GetCalendarEvent :one
SELECT event.event_id, event.connection_id, event.workspace_id, event.user_id, event.provider, event.calendar_id, event.provider_event_id, event.title, event.description, event.location, event.meeting_url, event.html_link, event.organizer, event.attendees, event.attendees_omitted, event.is_all_day, event.start_date, event.end_date, event.start_at, event.end_at, event.visibility, event.is_private, event.source_hash, event.sync_generation, event.created_at, event.updated_at
FROM calendar_events event
INNER JOIN calendar_connections connection ON
    connection.connection_id = event.connection_id
    AND connection.user_id = event.user_id
    AND connection.revoked_at IS NULL
    AND connection.cleanup_pending_at IS NULL
    AND (
        (connection.provider = $1
            AND CAST($2 AS text) = ANY(connection.scopes))
        OR (connection.provider = $3
            AND CAST($4 AS text) = ANY(connection.scopes))
    )
WHERE event.user_id = $5
  AND event.event_id = $6
LIMIT 1
`

type GetCalendarEventParams struct {
	GoogleProvider     string
	GoogleReadScope    string
	MicrosoftProvider  string
	MicrosoftReadScope string
	UserID             uuid.UUID
	EventID            uuid.UUID
}

func (q *Queries) GetCalendarEvent(ctx context.Context, arg GetCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, getCalendarEvent,
		arg.GoogleProvider,
		arg.GoogleReadScope,
		arg.MicrosoftProvider,
		arg.MicrosoftReadScope,
		arg.UserID,
		arg.EventID,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.EventID,
		&i.ConnectionID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Provider,
		&i.CalendarID,
		&i.ProviderEventID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.MeetingURL,
		&i.HtmlLink,
		&i.Organizer,
		&i.Attendees,
		&i.AttendeesOmitted,
		&i.IsAllDay,
		&i.StartDate,
		&i.EndDate,
		&i.StartAt,
		&i.EndAt,
		&i.Visibility,
		&i.IsPrivate,
		&i.SourceHash,
		&i.SyncGeneration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCalendarBusyWindow = `-- name: InsertCalendarBusyWindow :exec
INSERT INTO calendar_busy_windows (
    connection_id,
    workspace_id,
    user_id,
    provider,
    provider_event_id,
    calendar_id,
    title,
    start_at,
    end_at,
    status,
    transparency,
    is_private,
    source_hash,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    CURRENT_TIMESTAMP
)
`

type InsertCalendarBusyWindowParams struct {
	ConnectionID    uuid.UUID
	WorkspaceID     uuid.UUID
	UserID          uuid.UUID
	Provider        string
	ProviderEventID string
	CalendarID      *string
	Title           *string
	StartAt         time.Time
	EndAt           time.Time
	Status          string
	Transparency    string
	IsPrivate       bool
	SourceHash      string
}

func (q *Queries) InsertCalendarBusyWindow(ctx context.Context, arg InsertCalendarBusyWindowParams) error {
	_, err := q.db.Exec(ctx, insertCalendarBusyWindow,
		arg.ConnectionID,
		arg.WorkspaceID,
		arg.UserID,
		arg.Provider,
		arg.ProviderEventID,
		arg.CalendarID,
		arg.Title,
		arg.StartAt,
		arg.EndAt,
		arg.Status,
		arg.Transparency,
		arg.IsPrivate,
		arg.SourceHash,
	)
	return err
}

const invalidateChangedManagedScheduleEvent = `-- name: InvalidateChangedManagedScheduleEvent :exec
UPDATE calendar_schedule_blocks
SET external_sync_hash = NULL,
    external_synced_at = NULL
WHERE block_id = $1
`

type InvalidateChangedManagedScheduleEventParams struct {
	BlockID uuid.UUID
}

func (q *Queries) InvalidateChangedManagedScheduleEvent(ctx context.Context, arg InvalidateChangedManagedScheduleEventParams) error {
	_, err := q.db.Exec(ctx, invalidateChangedManagedScheduleEvent, arg.BlockID)
	return err
}

const invalidateDeletedManagedScheduleEvent = `-- name: InvalidateDeletedManagedScheduleEvent :exec
UPDATE calendar_schedule_blocks
SET external_sync_hash = NULL,
    external_synced_at = NULL
WHERE user_id = $1
  AND external_provider = CAST($2 AS text)
  AND external_event_id = CAST($3 AS text)
`

type InvalidateDeletedManagedScheduleEventParams struct {
	UserID   uuid.UUID
	Provider string
	EventID  string
}

func (q *Queries) InvalidateDeletedManagedScheduleEvent(ctx context.Context, arg InvalidateDeletedManagedScheduleEventParams) error {
	_, err := q.db.Exec(ctx, invalidateDeletedManagedScheduleEvent, arg.UserID, arg.Provider, arg.EventID)
	return err
}

const listCalendarEvents = `-- name: ListCalendarEvents :many
SELECT
    event.event_id,
    event.connection_id,
    event.provider,
    event.calendar_id,
    event.provider_event_id,
    event.title,
    event.location,
    event.meeting_url,
    event.html_link,
    event.start_at,
    event.end_at,
    event.is_all_day,
    event.start_date,
    event.end_date,
    event.is_private,
    event.created_at,
    event.updated_at
FROM calendar_events event
INNER JOIN calendar_connections connection ON
    connection.connection_id = event.connection_id
    AND connection.user_id = event.user_id
    AND connection.revoked_at IS NULL
    AND connection.cleanup_pending_at IS NULL
    AND (
        (connection.provider = $1
            AND CAST($2 AS text) = ANY(connection.scopes))
        OR (connection.provider = $3
            AND CAST($4 AS text) = ANY(connection.scopes))
    )
WHERE event.user_id = $5
  AND event.start_at < $6
  AND event.end_at > $7
ORDER BY event.start_at ASC, event.event_id ASC
`

type ListCalendarEventsParams struct {
	GoogleProvider     string
	GoogleReadScope    string
	MicrosoftProvider  string
	MicrosoftReadScope string
	UserID             uuid.UUID
	EndAt              time.Time
	StartAt            time.Time
}

type ListCalendarEventsRow struct {
	EventID         uuid.UUID
	ConnectionID    uuid.UUID
	Provider        string
	CalendarID      string
	ProviderEventID string
	Title           *string
	Location        *string
	MeetingURL      *string
	HtmlLink        *string
	StartAt         time.Time
	EndAt           time.Time
	IsAllDay        bool
	StartDate       *time.Time
	EndDate         *time.Time
	IsPrivate       bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListCalendarEvents(ctx context.Context, arg ListCalendarEventsParams) ([]ListCalendarEventsRow, error) {
	rows, err := q.db.Query(ctx, listCalendarEvents,
		arg.GoogleProvider,
		arg.GoogleReadScope,
		arg.MicrosoftProvider,
		arg.MicrosoftReadScope,
		arg.UserID,
		arg.EndAt,
		arg.StartAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCalendarEventsRow{}
	for rows.Next() {
		var i ListCalendarEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.ConnectionID,
			&i.Provider,
			&i.CalendarID,
			&i.ProviderEventID,
			&i.Title,
			&i.Location,
			&i.MeetingURL,
			&i.HtmlLink,
			&i.StartAt,
			&i.EndAt,
			&i.IsAllDay,
			&i.StartDate,
			&i.EndDate,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCalendarConnectionForIncrementalSync = `-- name: LockCalendarConnectionForIncrementalSync :one
SELECT connection.connection_id
FROM calendar_connections connection
WHERE connection.connection_id = $1
  AND connection.workspace_id = $2
  AND connection.credential_generation = $3
  AND connection.revoked_at IS NULL
  AND connection.cleanup_pending_at IS NULL
FOR UPDATE
`

type LockCalendarConnectionForIncrementalSyncParams struct {
	ConnectionID         uuid.UUID
	WorkspaceID          uuid.UUID
	CredentialGeneration uuid.UUID
}

func (q *Queries) LockCalendarConnectionForIncrementalSync(ctx context.Context, arg LockCalendarConnectionForIncrementalSyncParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockCalendarConnectionForIncrementalSync, arg.ConnectionID, arg.WorkspaceID, arg.CredentialGeneration)
	var connection_id uuid.UUID
	err := row.Scan(&connection_id)
	return connection_id, err
}

const lockChangedManagedScheduleEvent = `-- name: LockChangedManagedScheduleEvent :one
SELECT block.block_id,
       block.workspace_id,
       block.story_id,
       block.title,
       block.start_at,
       block.end_at
FROM calendar_schedule_blocks block
WHERE block.user_id = $1
  AND block.external_provider = CAST($2 AS text)
  AND block.external_event_id = CAST($3 AS text)
  AND block.completed_at IS NULL
FOR UPDATE
`

type LockChangedManagedScheduleEventParams struct {
	UserID   uuid.UUID
	Provider string
	EventID  string
}

type LockChangedManagedScheduleEventRow struct {
	BlockID     uuid.UUID
	WorkspaceID uuid.UUID
	StoryID     *uuid.UUID
	Title       string
	StartAt     time.Time
	EndAt       time.Time
}

func (q *Queries) LockChangedManagedScheduleEvent(ctx context.Context, arg LockChangedManagedScheduleEventParams) (LockChangedManagedScheduleEventRow, error) {
	row := q.db.QueryRow(ctx, lockChangedManagedScheduleEvent, arg.UserID, arg.Provider, arg.EventID)
	var i LockChangedManagedScheduleEventRow
	err := row.Scan(
		&i.BlockID,
		&i.WorkspaceID,
		&i.StoryID,
		&i.Title,
		&i.StartAt,
		&i.EndAt,
	)
	return i, err
}

const storeIncrementalCalendarSyncToken = `-- name: StoreIncrementalCalendarSyncToken :exec
UPDATE calendar_connections
SET sync_token = NULLIF(CAST($1 AS text), ''),
    updated_at = CURRENT_TIMESTAMP
WHERE connection_id = $2
`

type StoreIncrementalCalendarSyncTokenParams struct {
	SyncToken    string
	ConnectionID uuid.UUID
}

func (q *Queries) StoreIncrementalCalendarSyncToken(ctx context.Context, arg StoreIncrementalCalendarSyncTokenParams) error {
	_, err := q.db.Exec(ctx, storeIncrementalCalendarSyncToken, arg.SyncToken, arg.ConnectionID)
	return err
}

const upsertCalendarEvent = `-- name: UpsertCalendarEvent :exec
INSERT INTO calendar_events (
    connection_id,
    workspace_id,
    user_id,
    provider,
    calendar_id,
    provider_event_id,
    title,
    description,
    location,
    meeting_url,
    html_link,
    organizer,
    attendees,
    attendees_omitted,
    is_all_day,
    start_date,
    end_date,
    start_at,
    end_at,
    visibility,
    is_private,
    source_hash,
    sync_generation,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    CAST($12 AS jsonb),
    CAST($13 AS jsonb),
    $14,
    $15,
    CAST($16 AS date),
    CAST($17 AS date),
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    CURRENT_TIMESTAMP
)
ON CONFLICT (connection_id, calendar_id, provider_event_id)
DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    location = EXCLUDED.location,
    meeting_url = EXCLUDED.meeting_url,
    html_link = EXCLUDED.html_link,
    organizer = EXCLUDED.organizer,
    attendees = EXCLUDED.attendees,
    attendees_omitted = EXCLUDED.attendees_omitted,
    is_all_day = EXCLUDED.is_all_day,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    start_at = EXCLUDED.start_at,
    end_at = EXCLUDED.end_at,
    visibility = EXCLUDED.visibility,
    is_private = EXCLUDED.is_private,
    source_hash = EXCLUDED.source_hash,
    sync_generation = EXCLUDED.sync_generation,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertCalendarEventParams struct {
	ConnectionID     uuid.UUID
	WorkspaceID      uuid.UUID
	UserID           uuid.UUID
	Provider         string
	CalendarID       string
	ProviderEventID  string
	Title            *string
	Description      *string
	Location         *string
	MeetingURL       *string
	HtmlLink         *string
	Organizer        []byte
	Attendees        []byte
	AttendeesOmitted bool
	IsAllDay         bool
	StartDate        *time.Time
	EndDate          *time.Time
	StartAt          time.Time
	EndAt            time.Time
	Visibility       string
	IsPrivate        bool
	SourceHash       string
	SyncGeneration   uuid.UUID
}

func (q *Queries) UpsertCalendarEvent(ctx context.Context, arg UpsertCalendarEventParams) error {
	_, err := q.db.Exec(ctx, upsertCalendarEvent,
		arg.ConnectionID,
		arg.WorkspaceID,
		arg.UserID,
		arg.Provider,
		arg.CalendarID,
		arg.ProviderEventID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.MeetingURL,
		arg.HtmlLink,
		arg.Organizer,
		arg.Attendees,
		arg.AttendeesOmitted,
		arg.IsAllDay,
		arg.StartDate,
		arg.EndDate,
		arg.StartAt,
		arg.EndAt,
		arg.Visibility,
		arg.IsPrivate,
		arg.SourceHash,
		arg.SyncGeneration,
	)
	return err
}
