// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconciliation.sql

package calendarsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMayaScheduleSegment = `-- name: CreateMayaScheduleSegment :exec
INSERT INTO calendar_schedule_blocks (
    block_id,
    workspace_id,
    user_id,
    story_id,
    block_type,
    title,
    start_at,
    end_at,
    is_locked,
    source,
    segment_index,
    external_provider,
    external_calendar_id,
    external_event_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'work',
    $5,
    $6,
    $7,
    $8,
    'maya',
    $9,
    CAST($10 AS text),
    'primary',
    CAST($11 AS text)
)
`

type CreateMayaScheduleSegmentParams struct {
	BlockID          uuid.UUID
	WorkspaceID      uuid.UUID
	UserID           uuid.UUID
	StoryID          *uuid.UUID
	Title            string
	StartAt          time.Time
	EndAt            time.Time
	IsLocked         bool
	SegmentIndex     int32
	ExternalProvider string
	ExternalEventID  string
}

func (q *Queries) CreateMayaScheduleSegment(ctx context.Context, arg CreateMayaScheduleSegmentParams) error {
	_, err := q.db.Exec(ctx, createMayaScheduleSegment,
		arg.BlockID,
		arg.WorkspaceID,
		arg.UserID,
		arg.StoryID,
		arg.Title,
		arg.StartAt,
		arg.EndAt,
		arg.IsLocked,
		arg.SegmentIndex,
		arg.ExternalProvider,
		arg.ExternalEventID,
	)
	return err
}

const deleteMayaScheduleSegment = `-- name: DeleteMayaScheduleSegment :exec
DELETE FROM calendar_schedule_blocks
WHERE block_id = $1
`

type DeleteMayaScheduleSegmentParams struct {
	BlockID uuid.UUID
}

func (q *Queries) DeleteMayaScheduleSegment(ctx context.Context, arg DeleteMayaScheduleSegmentParams) error {
	_, err := q.db.Exec(ctx, deleteMayaScheduleSegment, arg.BlockID)
	return err
}

const listCalendarWriteDestinations = `-- name: ListCalendarWriteDestinations :many
SELECT connection.provider,
       connection.is_primary,
       CASE
           WHEN connection.provider = 'google'
               THEN CAST($1 AS text) = ANY(connection.scopes)
                    AND CAST($2 AS text) = ANY(connection.scopes)
           WHEN connection.provider = 'microsoft'
               THEN CAST($3 AS text) = ANY(connection.scopes)
           ELSE FALSE
       END AS can_write
FROM calendar_connections connection
WHERE connection.user_id = $4
  AND connection.revoked_at IS NULL
  AND connection.cleanup_pending_at IS NULL
ORDER BY connection.is_primary DESC, connection.created_at, connection.connection_id
`

type ListCalendarWriteDestinationsParams struct {
	GoogleReadScope     string
	GoogleOwnedScope    string
	MicrosoftWriteScope string
	UserID              uuid.UUID
}

type ListCalendarWriteDestinationsRow struct {
	Provider  string
	IsPrimary bool
	CanWrite  bool
}

func (q *Queries) ListCalendarWriteDestinations(ctx context.Context, arg ListCalendarWriteDestinationsParams) ([]ListCalendarWriteDestinationsRow, error) {
	rows, err := q.db.Query(ctx, listCalendarWriteDestinations,
		arg.GoogleReadScope,
		arg.GoogleOwnedScope,
		arg.MicrosoftWriteScope,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCalendarWriteDestinationsRow{}
	for rows.Next() {
		var i ListCalendarWriteDestinationsRow
		if err := rows.Scan(&i.Provider, &i.IsPrimary, &i.CanWrite); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExistingMayaScheduleSegments = `-- name: ListExistingMayaScheduleSegments :many
SELECT block.block_id,
       block.segment_index,
       block.title,
       block.start_at,
       block.end_at,
       block.is_locked,
       block.external_provider,
       block.external_calendar_id,
       block.external_event_id,
       block.external_sync_hash,
       block.manual_override_at,
       block.manual_override_by
FROM calendar_schedule_blocks block
WHERE block.workspace_id = $1
  AND block.user_id = $2
  AND block.story_id = $3
  AND block.source = 'maya'
  AND block.completed_at IS NULL
FOR UPDATE
`

type ListExistingMayaScheduleSegmentsParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	StoryID     *uuid.UUID
}

type ListExistingMayaScheduleSegmentsRow struct {
	BlockID            uuid.UUID
	SegmentIndex       int32
	Title              string
	StartAt            time.Time
	EndAt              time.Time
	IsLocked           bool
	ExternalProvider   *string
	ExternalCalendarID *string
	ExternalEventID    *string
	ExternalSyncHash   *string
	ManualOverrideAt   *time.Time
	ManualOverrideBy   *uuid.UUID
}

func (q *Queries) ListExistingMayaScheduleSegments(ctx context.Context, arg ListExistingMayaScheduleSegmentsParams) ([]ListExistingMayaScheduleSegmentsRow, error) {
	rows, err := q.db.Query(ctx, listExistingMayaScheduleSegments, arg.WorkspaceID, arg.UserID, arg.StoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExistingMayaScheduleSegmentsRow{}
	for rows.Next() {
		var i ListExistingMayaScheduleSegmentsRow
		if err := rows.Scan(
			&i.BlockID,
			&i.SegmentIndex,
			&i.Title,
			&i.StartAt,
			&i.EndAt,
			&i.IsLocked,
			&i.ExternalProvider,
			&i.ExternalCalendarID,
			&i.ExternalEventID,
			&i.ExternalSyncHash,
			&i.ManualOverrideAt,
			&i.ManualOverrideBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEligibleMayaScheduleStory = `-- name: LockEligibleMayaScheduleStory :one
SELECT story.id
FROM stories story
INNER JOIN statuses status ON
    status.status_id = story.status_id
INNER JOIN users selected_user ON
    selected_user.user_id = $1
    AND selected_user.is_active = TRUE
INNER JOIN workspace_members membership ON
    membership.workspace_id = story.workspace_id
    AND membership.user_id = $1
INNER JOIN team_members team_membership ON
    team_membership.team_id = story.team_id
    AND team_membership.user_id = $1
WHERE story.workspace_id = $2
  AND story.id = $3
  AND story.auto_scheduling_enabled = TRUE
  AND story.deleted_at IS NULL
  AND story.archived_at IS NULL
  AND story.completed_at IS NULL
  AND status.category NOT IN ('completed', 'cancelled')
FOR UPDATE OF story
FOR SHARE OF status, selected_user, membership, team_membership
`

type LockEligibleMayaScheduleStoryParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	StoryID     uuid.UUID
}

func (q *Queries) LockEligibleMayaScheduleStory(ctx context.Context, arg LockEligibleMayaScheduleStoryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockEligibleMayaScheduleStory, arg.UserID, arg.WorkspaceID, arg.StoryID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockMayaScheduleStoryVersion = `-- name: LockMayaScheduleStoryVersion :one
SELECT story.id
FROM stories story
WHERE story.workspace_id = $1
  AND story.id = $2
  AND story.updated_at = $3
FOR UPDATE OF story
`

type LockMayaScheduleStoryVersionParams struct {
	WorkspaceID       uuid.UUID
	StoryID           uuid.UUID
	ExpectedUpdatedAt time.Time
}

func (q *Queries) LockMayaScheduleStoryVersion(ctx context.Context, arg LockMayaScheduleStoryVersionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockMayaScheduleStoryVersion, arg.WorkspaceID, arg.StoryID, arg.ExpectedUpdatedAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const mayaScheduleSegmentConflicts = `-- name: MayaScheduleSegmentConflicts :one
SELECT EXISTS (
    SELECT 1
    FROM calendar_schedule_blocks block
    WHERE block.user_id = $1
      AND block.completed_at IS NULL
      AND block.start_at < $2
      AND block.end_at > $3
      AND NOT (block.block_id = ANY(CAST($4 AS uuid[])))
    UNION ALL
    SELECT 1
    FROM calendar_busy_windows busy
    INNER JOIN calendar_connections connection ON
        connection.connection_id = busy.connection_id
        AND connection.user_id = busy.user_id
        AND connection.revoked_at IS NULL
        AND connection.cleanup_pending_at IS NULL
    WHERE busy.user_id = $1
      AND busy.start_at < $2
      AND busy.end_at > $3
)
`

type MayaScheduleSegmentConflictsParams struct {
	UserID           uuid.UUID
	EndAt            time.Time
	StartAt          time.Time
	ExcludedBlockIds []uuid.UUID
}

func (q *Queries) MayaScheduleSegmentConflicts(ctx context.Context, arg MayaScheduleSegmentConflictsParams) (bool, error) {
	row := q.db.QueryRow(ctx, mayaScheduleSegmentConflicts,
		arg.UserID,
		arg.EndAt,
		arg.StartAt,
		arg.ExcludedBlockIds,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const releaseMayaScheduleOwnership = `-- name: ReleaseMayaScheduleOwnership :exec
DELETE FROM calendar_maya_schedule_ownerships
WHERE workspace_id = $1
  AND story_id = $2
  AND user_id = $3
`

type ReleaseMayaScheduleOwnershipParams struct {
	WorkspaceID uuid.UUID
	StoryID     uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) ReleaseMayaScheduleOwnership(ctx context.Context, arg ReleaseMayaScheduleOwnershipParams) error {
	_, err := q.db.Exec(ctx, releaseMayaScheduleOwnership, arg.WorkspaceID, arg.StoryID, arg.UserID)
	return err
}

const retainMayaScheduleOwnership = `-- name: RetainMayaScheduleOwnership :exec
INSERT INTO calendar_maya_schedule_ownerships (
    workspace_id,
    story_id,
    user_id
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (workspace_id, story_id)
DO UPDATE SET
    user_id = EXCLUDED.user_id,
    updated_at = CURRENT_TIMESTAMP,
    recovery_attempted_at = NULL
`

type RetainMayaScheduleOwnershipParams struct {
	WorkspaceID uuid.UUID
	StoryID     uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) RetainMayaScheduleOwnership(ctx context.Context, arg RetainMayaScheduleOwnershipParams) error {
	_, err := q.db.Exec(ctx, retainMayaScheduleOwnership, arg.WorkspaceID, arg.StoryID, arg.UserID)
	return err
}

const updateMayaScheduleSegment = `-- name: UpdateMayaScheduleSegment :exec
UPDATE calendar_schedule_blocks
SET title = CAST($1 AS text),
    start_at = $2,
    end_at = $3,
    is_locked = $4,
    external_provider = CAST($5 AS text),
    external_calendar_id = 'primary',
    external_event_id = CAST($6 AS text),
    updated_at = CASE
        WHEN title <> CAST($1 AS text)
          OR start_at <> $2
          OR end_at <> $3
          OR is_locked <> $4
            THEN CURRENT_TIMESTAMP
        ELSE updated_at
    END
WHERE workspace_id = $7
  AND user_id = $8
  AND story_id = $9
  AND segment_index = $10
  AND source = 'maya'
`

type UpdateMayaScheduleSegmentParams struct {
	Title            string
	StartAt          time.Time
	EndAt            time.Time
	IsLocked         bool
	ExternalProvider string
	ExternalEventID  string
	WorkspaceID      uuid.UUID
	UserID           uuid.UUID
	StoryID          *uuid.UUID
	SegmentIndex     int32
}

func (q *Queries) UpdateMayaScheduleSegment(ctx context.Context, arg UpdateMayaScheduleSegmentParams) error {
	_, err := q.db.Exec(ctx, updateMayaScheduleSegment,
		arg.Title,
		arg.StartAt,
		arg.EndAt,
		arg.IsLocked,
		arg.ExternalProvider,
		arg.ExternalEventID,
		arg.WorkspaceID,
		arg.UserID,
		arg.StoryID,
		arg.SegmentIndex,
	)
	return err
}
