// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package usersql

import (
	"context"
)

type Querier interface {
	AcquireExternalIdentityLock(ctx context.Context, arg AcquireExternalIdentityLockParams) error
	AcquireVerificationTokenIssueLock(ctx context.Context, arg AcquireVerificationTokenIssueLockParams) error
	ConsumeVerificationToken(ctx context.Context, arg ConsumeVerificationTokenParams) (ConsumeVerificationTokenRow, error)
	CountRecentVerificationTokenIssues(ctx context.Context, arg CountRecentVerificationTokenIssuesParams) (int32, error)
	CreateExternalIdentityUser(ctx context.Context, arg CreateExternalIdentityUserParams) (CreateExternalIdentityUserRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserMemoryForMember(ctx context.Context, arg CreateUserMemoryForMemberParams) (CreateUserMemoryForMemberRow, error)
	CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (CreateVerificationTokenRow, error)
	DeactivateInactiveUsers(ctx context.Context, arg DeactivateInactiveUsersParams) (int64, error)
	DeactivateUser(ctx context.Context, arg DeactivateUserParams) (int64, error)
	DeleteUserMemoryForOwner(ctx context.Context, arg DeleteUserMemoryForOwnerParams) (int64, error)
	GetActiveBrowserSessionVersion(ctx context.Context, arg GetActiveBrowserSessionVersionParams) (int64, error)
	GetActiveUserByEmail(ctx context.Context, arg GetActiveUserByEmailParams) (GetActiveUserByEmailRow, error)
	GetActiveUserByID(ctx context.Context, arg GetActiveUserByIDParams) (GetActiveUserByIDRow, error)
	GetEligibleUserInactivityWarningCandidate(ctx context.Context, arg GetEligibleUserInactivityWarningCandidateParams) (GetEligibleUserInactivityWarningCandidateRow, error)
	GetOrCreateAutomationPreferencesForMember(ctx context.Context, arg GetOrCreateAutomationPreferencesForMemberParams) (GetOrCreateAutomationPreferencesForMemberRow, error)
	GetOrCreateOnboardingTourProgressForMember(ctx context.Context, arg GetOrCreateOnboardingTourProgressForMemberParams) (UserOnboardingTourProgress, error)
	GetUserByEmailAnyStatus(ctx context.Context, arg GetUserByEmailAnyStatusParams) (GetUserByEmailAnyStatusRow, error)
	GetUserByExternalIdentity(ctx context.Context, arg GetUserByExternalIdentityParams) (GetUserByExternalIdentityRow, error)
	InvalidateVerificationTokens(ctx context.Context, arg InvalidateVerificationTokensParams) (int64, error)
	LinkExternalIdentity(ctx context.Context, arg LinkExternalIdentityParams) error
	ListUserInactivityWarningCandidates(ctx context.Context, arg ListUserInactivityWarningCandidatesParams) ([]ListUserInactivityWarningCandidatesRow, error)
	ListUserMemoriesForOwner(ctx context.Context, arg ListUserMemoriesForOwnerParams) ([]ListUserMemoriesForOwnerRow, error)
	ListUsersByIDs(ctx context.Context, arg ListUsersByIDsParams) ([]ListUsersByIDsRow, error)
	ListWorkspaceUsers(ctx context.Context, arg ListWorkspaceUsersParams) ([]ListWorkspaceUsersRow, error)
	MarkUserInactivityWarningSent(ctx context.Context, arg MarkUserInactivityWarningSentParams) (int64, error)
	PurgeExpiredVerificationTokens(ctx context.Context, arg PurgeExpiredVerificationTokensParams) (int64, error)
	ReactivateUserForVerifiedSignIn(ctx context.Context, arg ReactivateUserForVerifiedSignInParams) (ReactivateUserForVerifiedSignInRow, error)
	TouchExternalIdentity(ctx context.Context, arg TouchExternalIdentityParams) (int64, error)
	UpdateActiveUser(ctx context.Context, arg UpdateActiveUserParams) (UpdateActiveUserRow, error)
	UpdateLastUsedWorkspaceForMember(ctx context.Context, arg UpdateLastUsedWorkspaceForMemberParams) (int64, error)
	UpdateUserMemoryForOwner(ctx context.Context, arg UpdateUserMemoryForOwnerParams) (int64, error)
	UpsertAutomationPreferencesForMember(ctx context.Context, arg UpsertAutomationPreferencesForMemberParams) (int64, error)
	UpsertOnboardingTourProgressForMember(ctx context.Context, arg UpsertOnboardingTourProgressForMemberParams) (UserOnboardingTourProgress, error)
}

var _ Querier = (*Queries)(nil)
