// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_tokens.sql

package usersql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acquireVerificationTokenIssueLock = `-- name: AcquireVerificationTokenIssueLock :exec
SELECT pg_advisory_xact_lock(
    hashtextextended(
        CAST($1 AS text),
        hashtextextended(CAST($2 AS text), 0)
    )
)
`

type AcquireVerificationTokenIssueLockParams struct {
	Email     string
	TokenType string
}

func (q *Queries) AcquireVerificationTokenIssueLock(ctx context.Context, arg AcquireVerificationTokenIssueLockParams) error {
	_, err := q.db.Exec(ctx, acquireVerificationTokenIssueLock, arg.Email, arg.TokenType)
	return err
}

const consumeVerificationToken = `-- name: ConsumeVerificationToken :one
WITH digest_candidate AS (
    SELECT
        (CAST($2 AS bytea[]))[candidate_index] AS token_digest,
        (CAST($3 AS text[]))[candidate_index] AS token_key_id,
        (CAST($4 AS smallint[]))[candidate_index] AS token_version
    FROM generate_subscripts(
        CAST($2 AS bytea[]),
        1
    ) AS candidate_index
),
candidate AS (
    SELECT verification_token.id
    FROM public.verification_tokens AS verification_token
    WHERE verification_token.email = CAST($5 AS text)
      AND CAST(verification_token.token_type AS text) = ANY(CAST($6 AS text[]))
      AND verification_token.expires_at > CAST($1 AS timestamptz)
      AND verification_token.used_at IS NULL
      AND (
          (
              EXISTS (
                  SELECT 1
                  FROM digest_candidate
                  WHERE digest_candidate.token_digest = verification_token.token_digest
                    AND digest_candidate.token_key_id = verification_token.token_key_id
                    AND digest_candidate.token_version = verification_token.token_version
              )
          )
          OR (
              verification_token.token_digest IS NULL
              AND verification_token.token = CAST($7 AS text)
          )
      )
    ORDER BY verification_token.created_at DESC, verification_token.id DESC
    FOR UPDATE
    LIMIT 1
)
UPDATE public.verification_tokens AS verification_token
SET
    used_at = CAST($1 AS timestamptz),
    updated_at = CAST($1 AS timestamptz)
FROM candidate
WHERE verification_token.id = candidate.id
  AND verification_token.used_at IS NULL
RETURNING
    verification_token.id,
    verification_token.email,
    verification_token.user_id,
    verification_token.expires_at,
    verification_token.used_at,
    CAST(verification_token.token_type AS text) AS token_type,
    verification_token.token_key_id,
    verification_token.token_version,
    verification_token.created_at,
    verification_token.updated_at
`

type ConsumeVerificationTokenParams struct {
	ConsumedAt    time.Time
	TokenDigests  [][]byte
	TokenKeyIds   []string
	TokenVersions []int16
	Email         string
	TokenTypes    []string
	LegacyToken   string
}

type ConsumeVerificationTokenRow struct {
	ID           uuid.UUID
	Email        string
	UserID       *uuid.UUID
	ExpiresAt    time.Time
	UsedAt       *time.Time
	TokenType    string
	TokenKeyID   *string
	TokenVersion *int16
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) ConsumeVerificationToken(ctx context.Context, arg ConsumeVerificationTokenParams) (ConsumeVerificationTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeVerificationToken,
		arg.ConsumedAt,
		arg.TokenDigests,
		arg.TokenKeyIds,
		arg.TokenVersions,
		arg.Email,
		arg.TokenTypes,
		arg.LegacyToken,
	)
	var i ConsumeVerificationTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.TokenType,
		&i.TokenKeyID,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countRecentVerificationTokenIssues = `-- name: CountRecentVerificationTokenIssues :one
SELECT COUNT(*)::integer
FROM public.verification_tokens
WHERE email = CAST($1 AS text)
  AND token_type = CAST($2 AS public.token_type)
  AND created_at >= $3
`

type CountRecentVerificationTokenIssuesParams struct {
	Email          string
	TokenType      TokenType
	RateLimitSince time.Time
}

func (q *Queries) CountRecentVerificationTokenIssues(ctx context.Context, arg CountRecentVerificationTokenIssuesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentVerificationTokenIssues, arg.Email, arg.TokenType, arg.RateLimitSince)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createVerificationToken = `-- name: CreateVerificationToken :one
INSERT INTO public.verification_tokens (
    token,
    email,
    expires_at,
    token_type,
    token_digest,
    token_key_id,
    token_version,
    created_at,
    updated_at
)
VALUES (
    NULL,
    CAST($1 AS text),
    $2,
    CAST($3 AS public.token_type),
    $4,
    CAST($5 AS text),
    CAST($6 AS smallint),
    $7,
    $7
)
RETURNING
    id,
    email,
    user_id,
    expires_at,
    used_at,
    CAST(token_type AS text) AS token_type,
    token_key_id,
    token_version,
    created_at,
    updated_at
`

type CreateVerificationTokenParams struct {
	Email        string
	ExpiresAt    time.Time
	TokenType    TokenType
	TokenDigest  []byte
	TokenKeyID   string
	TokenVersion int16
	IssuedAt     time.Time
}

type CreateVerificationTokenRow struct {
	ID           uuid.UUID
	Email        string
	UserID       *uuid.UUID
	ExpiresAt    time.Time
	UsedAt       *time.Time
	TokenType    string
	TokenKeyID   *string
	TokenVersion *int16
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (CreateVerificationTokenRow, error) {
	row := q.db.QueryRow(ctx, createVerificationToken,
		arg.Email,
		arg.ExpiresAt,
		arg.TokenType,
		arg.TokenDigest,
		arg.TokenKeyID,
		arg.TokenVersion,
		arg.IssuedAt,
	)
	var i CreateVerificationTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.TokenType,
		&i.TokenKeyID,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const invalidateVerificationTokens = `-- name: InvalidateVerificationTokens :execrows
UPDATE public.verification_tokens
SET
    used_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE email = CAST($1 AS text)
  AND used_at IS NULL
`

type InvalidateVerificationTokensParams struct {
	Email string
}

func (q *Queries) InvalidateVerificationTokens(ctx context.Context, arg InvalidateVerificationTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateVerificationTokens, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
