// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collaboration.sql

package documentssql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const authorizePublicDocumentMedia = `-- name: AuthorizePublicDocumentMedia :one
SELECT media.attachment_id
FROM public.document_attachments AS media
JOIN public.documents AS document ON document.document_id = media.document_id
JOIN public.workspaces AS workspace ON workspace.workspace_id = document.workspace_id
WHERE document.public_token = $1
  AND document.archived_at IS NULL AND workspace.deleted_at IS NULL
  AND media.attachment_id = $2
  AND position(CAST(media.attachment_id AS text) in document.content_html) > 0
`

type AuthorizePublicDocumentMediaParams struct {
	PublicToken  *string
	AttachmentID uuid.UUID
}

func (q *Queries) AuthorizePublicDocumentMedia(ctx context.Context, arg AuthorizePublicDocumentMediaParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, authorizePublicDocumentMedia, arg.PublicToken, arg.AttachmentID)
	var attachment_id uuid.UUID
	err := row.Scan(&attachment_id)
	return attachment_id, err
}

const createDocumentCollaborationSession = `-- name: CreateDocumentCollaborationSession :exec
INSERT INTO public.document_collaboration_sessions
    (token_hash, document_id, user_id, session_version, epoch, expires_at)
SELECT $1, document.document_id, actor.user_id,
       actor.auth_session_version, document.collaboration_epoch, CURRENT_TIMESTAMP + interval '1 hour'
FROM public.documents AS document, public.users AS actor
WHERE document.document_id = $2 AND actor.user_id = $3
`

type CreateDocumentCollaborationSessionParams struct {
	TokenHash  string
	DocumentID uuid.UUID
	ActorID    uuid.UUID
}

func (q *Queries) CreateDocumentCollaborationSession(ctx context.Context, arg CreateDocumentCollaborationSessionParams) error {
	_, err := q.db.Exec(ctx, createDocumentCollaborationSession, arg.TokenHash, arg.DocumentID, arg.ActorID)
	return err
}

const deleteExpiredDocumentCollaborationSessions = `-- name: DeleteExpiredDocumentCollaborationSessions :exec
DELETE FROM public.document_collaboration_sessions WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredDocumentCollaborationSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredDocumentCollaborationSessions)
	return err
}

const documentMediaHasHistory = `-- name: DocumentMediaHasHistory :one
SELECT EXISTS (SELECT 1 FROM public.document_revisions
    WHERE document_id = $1
      AND position(CAST($2 AS text) in content_html) > 0) AS retained
`

type DocumentMediaHasHistoryParams struct {
	DocumentID   uuid.UUID
	AttachmentID string
}

func (q *Queries) DocumentMediaHasHistory(ctx context.Context, arg DocumentMediaHasHistoryParams) (bool, error) {
	row := q.db.QueryRow(ctx, documentMediaHasHistory, arg.DocumentID, arg.AttachmentID)
	var retained bool
	err := row.Scan(&retained)
	return retained, err
}

const getDocumentEditingMetadata = `-- name: GetDocumentEditingMetadata :one
SELECT revision, collaboration_epoch, CAST(collaboration_state IS NOT NULL AS boolean) AS collaborative,
       CAST(COALESCE(CASE WHEN created_by = $1 THEN public_token ELSE NULL END, '') AS text) AS public_token
FROM public.documents WHERE document_id = $2
`

type GetDocumentEditingMetadataParams struct {
	ActorID    uuid.UUID
	DocumentID uuid.UUID
}

type GetDocumentEditingMetadataRow struct {
	Revision           int64
	CollaborationEpoch int64
	Collaborative      bool
	PublicToken        string
}

// Access is checked with GetAccessibleDocument in the same serializable transaction.
func (q *Queries) GetDocumentEditingMetadata(ctx context.Context, arg GetDocumentEditingMetadataParams) (GetDocumentEditingMetadataRow, error) {
	row := q.db.QueryRow(ctx, getDocumentEditingMetadata, arg.ActorID, arg.DocumentID)
	var i GetDocumentEditingMetadataRow
	err := row.Scan(
		&i.Revision,
		&i.CollaborationEpoch,
		&i.Collaborative,
		&i.PublicToken,
	)
	return i, err
}

const getDocumentRevision = `-- name: GetDocumentRevision :one
SELECT revision, title, content_html, content_text, edited_by, created_at
FROM public.document_revisions
WHERE document_id = $1 AND revision = $2
`

type GetDocumentRevisionParams struct {
	DocumentID uuid.UUID
	Revision   int64
}

type GetDocumentRevisionRow struct {
	Revision    int64
	Title       string
	ContentHtml string
	ContentText string
	EditedBy    *uuid.UUID
	CreatedAt   time.Time
}

func (q *Queries) GetDocumentRevision(ctx context.Context, arg GetDocumentRevisionParams) (GetDocumentRevisionRow, error) {
	row := q.db.QueryRow(ctx, getDocumentRevision, arg.DocumentID, arg.Revision)
	var i GetDocumentRevisionRow
	err := row.Scan(
		&i.Revision,
		&i.Title,
		&i.ContentHtml,
		&i.ContentText,
		&i.EditedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicDocument = `-- name: GetPublicDocument :one
SELECT document.document_id, document.workspace_id, document.title, document.content_html,
       document.content_text, document.updated_at
FROM public.documents AS document
JOIN public.workspaces AS workspace ON workspace.workspace_id = document.workspace_id
WHERE document.public_token = $1
  AND document.archived_at IS NULL AND workspace.deleted_at IS NULL
`

type GetPublicDocumentParams struct {
	PublicToken *string
}

type GetPublicDocumentRow struct {
	DocumentID  uuid.UUID
	WorkspaceID uuid.UUID
	Title       string
	ContentHtml string
	ContentText string
	UpdatedAt   time.Time
}

func (q *Queries) GetPublicDocument(ctx context.Context, arg GetPublicDocumentParams) (GetPublicDocumentRow, error) {
	row := q.db.QueryRow(ctx, getPublicDocument, arg.PublicToken)
	var i GetPublicDocumentRow
	err := row.Scan(
		&i.DocumentID,
		&i.WorkspaceID,
		&i.Title,
		&i.ContentHtml,
		&i.ContentText,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentRevisions = `-- name: ListDocumentRevisions :many
SELECT revision, title, edited_by, created_at
FROM public.document_revisions
WHERE document_id = $1
  AND (CAST($2 AS bigint) = 0 OR revision < $2)
ORDER BY revision DESC LIMIT 50
`

type ListDocumentRevisionsParams struct {
	DocumentID     uuid.UUID
	BeforeRevision int64
}

type ListDocumentRevisionsRow struct {
	Revision  int64
	Title     string
	EditedBy  *uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) ListDocumentRevisions(ctx context.Context, arg ListDocumentRevisionsParams) ([]ListDocumentRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentRevisions, arg.DocumentID, arg.BeforeRevision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentRevisionsRow{}
	for rows.Next() {
		var i ListDocumentRevisionsRow
		if err := rows.Scan(
			&i.Revision,
			&i.Title,
			&i.EditedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreDocumentRevision = `-- name: RestoreDocumentRevision :one
UPDATE public.documents AS document
SET title = snapshot.title, content_html = snapshot.content_html, content_text = snapshot.content_text,
    collaboration_state = NULL,
    collaboration_epoch = document.collaboration_epoch + 1, updated_by = $1
FROM public.document_revisions AS snapshot
WHERE document.document_id = $2
  AND document.revision = $3
  AND snapshot.document_id = document.document_id AND snapshot.revision = $4
RETURNING document.document_id
`

type RestoreDocumentRevisionParams struct {
	ActorID          uuid.UUID
	DocumentID       uuid.UUID
	ExpectedRevision int64
	Revision         int64
}

func (q *Queries) RestoreDocumentRevision(ctx context.Context, arg RestoreDocumentRevisionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, restoreDocumentRevision,
		arg.ActorID,
		arg.DocumentID,
		arg.ExpectedRevision,
		arg.Revision,
	)
	var document_id uuid.UUID
	err := row.Scan(&document_id)
	return document_id, err
}

const setDocumentPublicToken = `-- name: SetDocumentPublicToken :exec
UPDATE public.documents SET public_token = $1
WHERE document_id = $2
`

type SetDocumentPublicTokenParams struct {
	PublicToken *string
	DocumentID  uuid.UUID
}

func (q *Queries) SetDocumentPublicToken(ctx context.Context, arg SetDocumentPublicTokenParams) error {
	_, err := q.db.Exec(ctx, setDocumentPublicToken, arg.PublicToken, arg.DocumentID)
	return err
}
