// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: strategy.sql

package objectivessql

import (
	"context"

	"github.com/google/uuid"
)

const alignObjective = `-- name: AlignObjective :one
INSERT INTO public.strategy_objective_alignments (workspace_id, objective_id, pillar_id)
SELECT $1, objective.objective_id, pillar.pillar_id
FROM public.objectives AS objective
INNER JOIN public.strategic_pillars AS pillar
    ON pillar.pillar_id = $2
   AND pillar.workspace_id = objective.workspace_id
INNER JOIN public.workspace_members AS membership
    ON membership.workspace_id = objective.workspace_id
   AND membership.user_id = $3
INNER JOIN public.team_members AS team_membership
    ON team_membership.team_id = objective.team_id
   AND team_membership.user_id = membership.user_id
INNER JOIN public.users AS actor
    ON actor.user_id = membership.user_id
   AND actor.is_active = TRUE
WHERE objective.objective_id = $4
  AND objective.workspace_id = $1
  AND membership.role IN ('member', 'admin')
ON CONFLICT (objective_id) DO UPDATE SET
    pillar_id = EXCLUDED.pillar_id,
    workspace_id = EXCLUDED.workspace_id,
    updated_at = GREATEST(clock_timestamp(), strategy_objective_alignments.updated_at + INTERVAL '1 microsecond')
RETURNING objective_id
`

type AlignObjectiveParams struct {
	WorkspaceID uuid.UUID
	PillarID    uuid.UUID
	ActorID     uuid.UUID
	ObjectiveID uuid.UUID
}

func (q *Queries) AlignObjective(ctx context.Context, arg AlignObjectiveParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, alignObjective,
		arg.WorkspaceID,
		arg.PillarID,
		arg.ActorID,
		arg.ObjectiveID,
	)
	var objective_id uuid.UUID
	err := row.Scan(&objective_id)
	return objective_id, err
}

const canReadObjectiveStrategy = `-- name: CanReadObjectiveStrategy :one
SELECT EXISTS (
    SELECT 1
    FROM public.workspace_members AS membership
    INNER JOIN public.users AS actor
        ON actor.user_id = membership.user_id
       AND actor.is_active = TRUE
    WHERE membership.workspace_id = $1
      AND membership.user_id = $2
	  AND membership.role IN ('member', 'admin')
) AS can_read
`

type CanReadObjectiveStrategyParams struct {
	WorkspaceID uuid.UUID
	ActorID     uuid.UUID
}

func (q *Queries) CanReadObjectiveStrategy(ctx context.Context, arg CanReadObjectiveStrategyParams) (bool, error) {
	row := q.db.QueryRow(ctx, canReadObjectiveStrategy, arg.WorkspaceID, arg.ActorID)
	var can_read bool
	err := row.Scan(&can_read)
	return can_read, err
}

const createStrategicPillar = `-- name: CreateStrategicPillar :one
INSERT INTO public.strategic_pillars (workspace_id, name, description, order_index)
SELECT $1, $2, CAST($3 AS text), $4
WHERE EXISTS (
    SELECT 1
    FROM public.workspace_members AS membership
    INNER JOIN public.users AS actor
        ON actor.user_id = membership.user_id
       AND actor.is_active = TRUE
    WHERE membership.workspace_id = $1
      AND membership.user_id = $5
      AND membership.role IN ('member', 'admin')
)
RETURNING pillar_id, name, description, order_index
`

type CreateStrategicPillarParams struct {
	WorkspaceID uuid.UUID
	Name        string
	Description *string
	OrderIndex  int32
	ActorID     uuid.UUID
}

type CreateStrategicPillarRow struct {
	PillarID    uuid.UUID
	Name        string
	Description *string
	OrderIndex  int32
}

func (q *Queries) CreateStrategicPillar(ctx context.Context, arg CreateStrategicPillarParams) (CreateStrategicPillarRow, error) {
	row := q.db.QueryRow(ctx, createStrategicPillar,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.OrderIndex,
		arg.ActorID,
	)
	var i CreateStrategicPillarRow
	err := row.Scan(
		&i.PillarID,
		&i.Name,
		&i.Description,
		&i.OrderIndex,
	)
	return i, err
}

const deleteObjectiveAlignment = `-- name: DeleteObjectiveAlignment :one
WITH authorized_objective AS (
    SELECT objective.objective_id
    FROM public.objectives AS objective
    INNER JOIN public.workspace_members AS membership
        ON membership.workspace_id = objective.workspace_id
       AND membership.user_id = $1
    INNER JOIN public.team_members AS team_membership
        ON team_membership.team_id = objective.team_id
       AND team_membership.user_id = membership.user_id
    INNER JOIN public.users AS actor
        ON actor.user_id = membership.user_id
       AND actor.is_active = TRUE
    WHERE objective.workspace_id = $2
      AND objective.objective_id = $3
      AND membership.role IN ('member', 'admin')
), deleted_alignment AS (
    DELETE FROM public.strategy_objective_alignments AS alignment
    USING authorized_objective
    WHERE alignment.workspace_id = $2
      AND alignment.objective_id = authorized_objective.objective_id
    RETURNING alignment.objective_id
)
SELECT objective_id FROM authorized_objective
`

type DeleteObjectiveAlignmentParams struct {
	ActorID     uuid.UUID
	WorkspaceID *uuid.UUID
	ObjectiveID uuid.UUID
}

func (q *Queries) DeleteObjectiveAlignment(ctx context.Context, arg DeleteObjectiveAlignmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteObjectiveAlignment, arg.ActorID, arg.WorkspaceID, arg.ObjectiveID)
	var objective_id uuid.UUID
	err := row.Scan(&objective_id)
	return objective_id, err
}

const deleteStrategicPillar = `-- name: DeleteStrategicPillar :one
DELETE FROM public.strategic_pillars AS pillar
USING public.workspace_members AS membership, public.users AS actor
WHERE pillar.workspace_id = $1
  AND pillar.pillar_id = $2
  AND membership.workspace_id = pillar.workspace_id
  AND membership.user_id = $3
  AND membership.role IN ('member', 'admin')
  AND actor.user_id = membership.user_id
  AND actor.is_active = TRUE
RETURNING pillar.pillar_id
`

type DeleteStrategicPillarParams struct {
	WorkspaceID uuid.UUID
	PillarID    uuid.UUID
	ActorID     uuid.UUID
}

func (q *Queries) DeleteStrategicPillar(ctx context.Context, arg DeleteStrategicPillarParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteStrategicPillar, arg.WorkspaceID, arg.PillarID, arg.ActorID)
	var pillar_id uuid.UUID
	err := row.Scan(&pillar_id)
	return pillar_id, err
}

const getWorkspaceStrategy = `-- name: GetWorkspaceStrategy :one
SELECT strategy.ultimate_goal, strategy.description
FROM public.workspace_strategies AS strategy
WHERE strategy.workspace_id = $1
  AND EXISTS (
	  SELECT 1
	  FROM public.workspace_members AS membership
	  INNER JOIN public.users AS actor
		  ON actor.user_id = membership.user_id
		 AND actor.is_active = TRUE
	  WHERE membership.workspace_id = $1
		AND membership.user_id = $2
		AND membership.role IN ('member', 'admin')
  )
`

type GetWorkspaceStrategyParams struct {
	WorkspaceID uuid.UUID
	ActorID     uuid.UUID
}

type GetWorkspaceStrategyRow struct {
	UltimateGoal string
	Description  *string
}

func (q *Queries) GetWorkspaceStrategy(ctx context.Context, arg GetWorkspaceStrategyParams) (GetWorkspaceStrategyRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceStrategy, arg.WorkspaceID, arg.ActorID)
	var i GetWorkspaceStrategyRow
	err := row.Scan(&i.UltimateGoal, &i.Description)
	return i, err
}

const listStrategicPillars = `-- name: ListStrategicPillars :many
SELECT pillar.pillar_id, pillar.name, pillar.description, pillar.order_index
FROM public.strategic_pillars AS pillar
WHERE pillar.workspace_id = $1
  AND EXISTS (
	  SELECT 1
	  FROM public.workspace_members AS membership
	  INNER JOIN public.users AS actor
		  ON actor.user_id = membership.user_id
		 AND actor.is_active = TRUE
	  WHERE membership.workspace_id = $1
		AND membership.user_id = $2
		AND membership.role IN ('member', 'admin')
  )
ORDER BY pillar.order_index, pillar.created_at, pillar.pillar_id
`

type ListStrategicPillarsParams struct {
	WorkspaceID uuid.UUID
	ActorID     uuid.UUID
}

type ListStrategicPillarsRow struct {
	PillarID    uuid.UUID
	Name        string
	Description *string
	OrderIndex  int32
}

func (q *Queries) ListStrategicPillars(ctx context.Context, arg ListStrategicPillarsParams) ([]ListStrategicPillarsRow, error) {
	rows, err := q.db.Query(ctx, listStrategicPillars, arg.WorkspaceID, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStrategicPillarsRow{}
	for rows.Next() {
		var i ListStrategicPillarsRow
		if err := rows.Scan(
			&i.PillarID,
			&i.Name,
			&i.Description,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleStrategyAlignments = `-- name: ListVisibleStrategyAlignments :many
SELECT alignment.pillar_id, alignment.objective_id
FROM public.strategy_objective_alignments AS alignment
INNER JOIN public.objectives AS objective
    ON objective.objective_id = alignment.objective_id
   AND objective.workspace_id = alignment.workspace_id
INNER JOIN public.team_members AS team_membership
    ON team_membership.team_id = objective.team_id
   AND team_membership.user_id = $1
INNER JOIN public.workspace_members AS membership
	ON membership.workspace_id = objective.workspace_id
	AND membership.user_id = team_membership.user_id
INNER JOIN public.users AS actor
	ON actor.user_id = membership.user_id
	AND actor.is_active = TRUE
WHERE alignment.workspace_id = $2
  AND membership.role IN ('member', 'admin')
ORDER BY alignment.pillar_id, alignment.objective_id
`

type ListVisibleStrategyAlignmentsParams struct {
	ActorID     uuid.UUID
	WorkspaceID uuid.UUID
}

type ListVisibleStrategyAlignmentsRow struct {
	PillarID    uuid.UUID
	ObjectiveID uuid.UUID
}

func (q *Queries) ListVisibleStrategyAlignments(ctx context.Context, arg ListVisibleStrategyAlignmentsParams) ([]ListVisibleStrategyAlignmentsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleStrategyAlignments, arg.ActorID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleStrategyAlignmentsRow{}
	for rows.Next() {
		var i ListVisibleStrategyAlignmentsRow
		if err := rows.Scan(&i.PillarID, &i.ObjectiveID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStrategicPillar = `-- name: UpdateStrategicPillar :one
UPDATE public.strategic_pillars AS pillar
SET
    name = CASE WHEN CAST($1 AS boolean) THEN $2 ELSE pillar.name END,
    description = CASE WHEN CAST($3 AS boolean) THEN CAST($4 AS text) ELSE pillar.description END,
    order_index = CASE WHEN CAST($5 AS boolean) THEN $6 ELSE pillar.order_index END,
    updated_at = GREATEST(clock_timestamp(), pillar.updated_at + INTERVAL '1 microsecond')
WHERE pillar.workspace_id = $7
  AND pillar.pillar_id = $8
  AND EXISTS (
      SELECT 1
      FROM public.workspace_members AS membership
      INNER JOIN public.users AS actor
          ON actor.user_id = membership.user_id
         AND actor.is_active = TRUE
      WHERE membership.workspace_id = pillar.workspace_id
        AND membership.user_id = $9
        AND membership.role IN ('member', 'admin')
  )
RETURNING pillar_id, name, description, order_index
`

type UpdateStrategicPillarParams struct {
	SetName        bool
	Name           string
	SetDescription bool
	Description    *string
	SetOrderIndex  bool
	OrderIndex     int32
	WorkspaceID    uuid.UUID
	PillarID       uuid.UUID
	ActorID        uuid.UUID
}

type UpdateStrategicPillarRow struct {
	PillarID    uuid.UUID
	Name        string
	Description *string
	OrderIndex  int32
}

func (q *Queries) UpdateStrategicPillar(ctx context.Context, arg UpdateStrategicPillarParams) (UpdateStrategicPillarRow, error) {
	row := q.db.QueryRow(ctx, updateStrategicPillar,
		arg.SetName,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.SetOrderIndex,
		arg.OrderIndex,
		arg.WorkspaceID,
		arg.PillarID,
		arg.ActorID,
	)
	var i UpdateStrategicPillarRow
	err := row.Scan(
		&i.PillarID,
		&i.Name,
		&i.Description,
		&i.OrderIndex,
	)
	return i, err
}

const updateWorkspaceStrategy = `-- name: UpdateWorkspaceStrategy :one
INSERT INTO public.workspace_strategies (workspace_id, ultimate_goal, description)
SELECT $1, $2, CAST($3 AS text)
WHERE EXISTS (
    SELECT 1
    FROM public.workspace_members AS membership
    INNER JOIN public.users AS actor
        ON actor.user_id = membership.user_id
       AND actor.is_active = TRUE
    WHERE membership.workspace_id = $1
      AND membership.user_id = $4
      AND membership.role IN ('member', 'admin')
)
ON CONFLICT (workspace_id) DO UPDATE SET
    ultimate_goal = EXCLUDED.ultimate_goal,
    description = EXCLUDED.description,
    updated_at = GREATEST(clock_timestamp(), workspace_strategies.updated_at + INTERVAL '1 microsecond')
RETURNING workspace_id
`

type UpdateWorkspaceStrategyParams struct {
	WorkspaceID  uuid.UUID
	UltimateGoal string
	Description  *string
	ActorID      uuid.UUID
}

func (q *Queries) UpdateWorkspaceStrategy(ctx context.Context, arg UpdateWorkspaceStrategyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceStrategy,
		arg.WorkspaceID,
		arg.UltimateGoal,
		arg.Description,
		arg.ActorID,
	)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}
