import type { ErrorEvent, StackFrame, Stacktrace } from "@sentry/react-native";

const safeIdentifier = (value: string | undefined) =>
  value && /^[\w.$<>:[\]/ -]{1,200}$/.test(value) ? value : undefined;

// Keep source locations for symbolication without URL credentials, query strings,
// local account names, or source-code snippets that may contain application data.
const sourceLocation = (value: string | undefined) => {
  if (!value || /[<>\r\n]/.test(value)) return undefined;
  const location = value.split(/[?#]/, 1)[0];
  if (/^(?:https?|file):\/\//i.test(location)) {
    try {
      const url = new URL(location);
      if (url.protocol === "file:") return url.pathname.split("/").pop();
      url.username = "";
      url.password = "";
      return url.toString();
    } catch {
      return undefined;
    }
  }
  if (/^(?:\/Users\/|\/home\/|[A-Za-z]:\\)/.test(location))
    return location.split(/[/\\]/).pop();
  return location;
};

const scrubFrame = (frame: StackFrame): StackFrame => ({
  filename: sourceLocation(frame.filename),
  abs_path: sourceLocation(frame.abs_path),
  function: safeIdentifier(frame.function),
  module: safeIdentifier(frame.module),
  lineno: frame.lineno,
  colno: frame.colno,
  in_app: frame.in_app,
  instruction_addr: frame.instruction_addr,
  platform: frame.platform,
});

const scrubStack = (stack: Stacktrace | undefined): Stacktrace | undefined =>
  stack ? { frames: stack.frames?.map(scrubFrame) } : undefined;

/** Allowlist crash diagnostics: error messages can contain API bodies and HTML. */
export const scrubErrorEvent = (event: ErrorEvent): ErrorEvent => ({
  type: undefined,
  event_id: event.event_id,
  timestamp: event.timestamp,
  platform: event.platform,
  level: event.level,
  release: event.release,
  dist: event.dist,
  environment: event.environment,
  // Debug IDs are generated by Metro/native builds and identify symbol files.
  debug_meta: event.debug_meta,
  exception: event.exception
    ? {
        values: event.exception.values?.map((exception) => ({
          type: safeIdentifier(exception.type) ?? "Error",
          value: "Exception details omitted for privacy",
          stacktrace: scrubStack(exception.stacktrace),
          mechanism: exception.mechanism
            ? {
                type: safeIdentifier(exception.mechanism.type) ?? "generic",
                handled: exception.mechanism.handled,
                synthetic: exception.mechanism.synthetic,
              }
            : undefined,
        })),
      }
    : undefined,
  threads: event.threads
    ? {
        values: event.threads.values?.map((thread) => ({
          id: thread.id,
          current: thread.current,
          crashed: thread.crashed,
          stacktrace: scrubStack(thread.stacktrace),
        })),
      }
    : undefined,
  contexts: {
    os: event.contexts?.os
      ? {
          name: event.contexts.os.name,
          version: event.contexts.os.version,
          build: event.contexts.os.build,
        }
      : undefined,
    device: event.contexts?.device
      ? {
          family: event.contexts.device.family,
          model: event.contexts.device.model,
          arch: event.contexts.device.arch,
          simulator: event.contexts.device.simulator,
        }
      : undefined,
  },
  tags: { surface: "mobile" },
});
