package github

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/complexus-tech/projects-api/internal/platform/codehost"
)

func (s *Service) SyncStoryFromFortyOne(ctx context.Context, input CoreStorySyncInput) error {
	if !s.canUseAppAPI() {
		s.log.Warn(
			ctx,
			"skipping github story sync because github app api is not configured",
			append([]any{"story_id", input.StoryID}, s.appAPIConfigDiagnostics()...)...,
		)
		return nil
	}

	link, err := s.repo.FindBidirectionalIssueSyncLinkByTeamID(ctx, input.WorkspaceID, input.TeamID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			s.log.Info(ctx, "skipping github story sync because team has no bidirectional github issue link", "story_id", input.StoryID, "team_id", input.TeamID)
			return nil
		}
		return err
	}

	desiredState := "open"
	if input.StatusID != nil {
		category, err := s.repo.GetStatusCategory(ctx, *input.StatusID)
		if err != nil && !errors.Is(err, sql.ErrNoRows) {
			return err
		}
		if category == "completed" {
			desiredState = "closed"
		}
	}

	issueBody := issueBodyFromStoryDescription(input.Description)
	syncHash := githubIssueSyncHash(input.Title, issueBody, desiredState)
	existingLink, err := s.repo.FindIssueStoryLinkByStoryID(ctx, input.WorkspaceID, input.StoryID, link.RepositoryID)
	switch {
	case err == nil:
		s.log.Info(ctx, "syncing story state to github issue", "story_id", input.StoryID, "github_issue_number", existingLink.GitHubNumber, "desired_state", desiredState)
		issue, err := s.updateIssue(ctx, link.GitHubInstallationID, link.OwnerLogin, link.RepositorySlug, existingLink.GitHubNumber, input.Title, issueBody, desiredState)
		if err != nil {
			return err
		}
		if err := s.repo.UpsertStoryLink(ctx, input.WorkspaceID, input.StoryID, link.RepositoryID, "issue", issue.ID, issue.Number, nil, issue.HTMLURL, issue.Title, issue.State, issue); err != nil {
			return err
		}
		if err := s.repo.UpdateStoryLinkSyncState(ctx, existingLink.ID, githubSyncSourceFortyOne, syncHash); err != nil {
			return err
		}
		return s.repo.EnsureStoryLink(ctx, input.StoryID, githubIssueStoryLinkTitle(issue.Number), issue.HTMLURL)
	case !errors.Is(err, sql.ErrNoRows):
		return err
	}

	s.log.Info(ctx, "creating github issue for story during bidirectional sync", "story_id", input.StoryID, "desired_state", desiredState)
	issue, err := s.createIssue(ctx, link.GitHubInstallationID, link.OwnerLogin, link.RepositorySlug, input.Title, issueBody)
	if err != nil {
		return err
	}
	if desiredState == "closed" {
		issue, err = s.updateIssue(ctx, link.GitHubInstallationID, link.OwnerLogin, link.RepositorySlug, issue.Number, input.Title, issueBody, desiredState)
		if err != nil {
			return err
		}
	}
	if err := s.repo.UpsertStoryLink(ctx, input.WorkspaceID, input.StoryID, link.RepositoryID, "issue", issue.ID, issue.Number, nil, issue.HTMLURL, issue.Title, issue.State, issue); err != nil {
		return err
	}
	createdLink, err := s.repo.FindIssueStoryLinkByStoryID(ctx, input.WorkspaceID, input.StoryID, link.RepositoryID)
	if err != nil {
		return err
	}
	if err := s.repo.UpdateStoryLinkSyncState(ctx, createdLink.ID, githubSyncSourceFortyOne, syncHash); err != nil {
		return err
	}
	return s.repo.EnsureStoryLink(ctx, input.StoryID, githubIssueStoryLinkTitle(issue.Number), issue.HTMLURL)
}

func (s *Service) processWebhook(ctx context.Context, eventName string, payload webhookEnvelope) error {
	repository, err := s.repo.FindRepositoryByExternalID(ctx, payload.Repository.ID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}
		return fmt.Errorf("resolve GitHub webhook repository: %w", err)
	}

	switch eventName {
	case "issues":
		return s.handleIssueEvent(ctx, repository, payload)
	case "pull_request":
		return s.handlePullRequestEvent(ctx, repository, payload)
	case "pull_request_review":
		return s.handlePullRequestReviewEvent(ctx, repository, payload)
	case "issue_comment":
		return s.handleIssueCommentEvent(ctx, repository, payload)
	case "check_run":
		return s.handleCheckRunEvent(ctx, repository, payload)
	case "create":
		return s.handleCreateEvent(ctx, repository, payload)
	case "push":
		return s.handlePushEvent(ctx, repository, payload)
	default:
		return nil
	}
}

func (s *Service) handleIssueEvent(ctx context.Context, repository repositoryRecord, payload webhookEnvelope) error {
	if s.stories == nil {
		return errors.New("stories service is not configured")
	}
	// Ignore issue events generated by our own GitHub App actor to avoid
	// status bounce-back loops for outbound FortyOne -> GitHub sync.
	if s.isAppSender(payload.Sender.Login) {
		return nil
	}

	link, err := s.repo.FindIssueSyncLinkByRepositoryID(ctx, repository.ID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}
		return fmt.Errorf("resolve GitHub issue sync link: %w", err)
	}

	issueDescription := githubString(payload.Issue.Body)
	labelNames := make([]string, 0, len(payload.Issue.Labels))
	for _, label := range payload.Issue.Labels {
		labelNames = append(labelNames, label.Name)
	}
	incomingSyncHash := githubIssueSyncHash(payload.Issue.Title, payload.Issue.Body, payload.Issue.State)
	var story singleStory
	var getErr error
	storyLink, err := s.repo.FindIssueStoryLinkByExternalID(ctx, repository.ID, payload.Issue.ID)
	switch {
	case err == nil:
		if shouldIgnoreFortyOneIssueEcho(payload.Action, stringValue(storyLink.LastSyncedFrom), stringValue(storyLink.LastSyncHash), incomingSyncHash) {
			if err := s.repo.UpsertStoryLink(ctx, repository.WorkspaceID, storyLink.StoryID, repository.ID, "issue", payload.Issue.ID, payload.Issue.Number, nil, payload.Issue.HTMLURL, payload.Issue.Title, payload.Issue.State, payload.Issue); err != nil {
				return err
			}
			return s.repo.EnsureStoryLink(ctx, storyLink.StoryID, githubIssueStoryLinkTitle(payload.Issue.Number), payload.Issue.HTMLURL)
		}

		story, getErr = s.stories.Get(ctx, storyLink.StoryID, repository.WorkspaceID)
		if getErr != nil {
			return getErr
		}
		updates := map[string]any{
			"title":       payload.Issue.Title,
			"description": issueDescription,
		}
		if priority, hasPriorityLabel := githubPriorityUpdateFromLabelNames(labelNames); hasPriorityLabel {
			updates["priority"] = priority
		}
		if updateErr := s.stories.UpdateExternalWithReason(ctx, s.cfg.GitHubUserID, story.ID, repository.WorkspaceID, updates, githubIssueSyncReason()); updateErr != nil {
			return updateErr
		}
	case errors.Is(err, sql.ErrNoRows):
		return s.upsertIssueIntegrationRequest(ctx, repository, link.TeamID, payload)
	default:
		return err
	}

	linkCreated, err := s.upsertStoryLink(ctx, repository.WorkspaceID, storyLink.StoryID, repository.ID, "issue", payload.Issue.ID, payload.Issue.Number, nil, payload.Issue.HTMLURL, payload.Issue.Title, payload.Issue.State, payload.Issue)
	if err != nil {
		return err
	}
	if err := s.repo.EnsureStoryLink(ctx, storyLink.StoryID, githubIssueStoryLinkTitle(payload.Issue.Number), payload.Issue.HTMLURL); err != nil {
		return err
	}
	if linkCreated {
		if err := s.recordLinkActivity(ctx, repository.WorkspaceID, storyLink.StoryID, "github_issue", fmt.Sprintf("issue %d", payload.Issue.Number), payload.Issue.HTMLURL); err != nil {
			return err
		}
	}
	if payload.Action == "opened" {
		if err := s.ensureIssueImportComment(ctx, repository, payload.Issue.Number, story); err != nil {
			return err
		}
	}
	switch payload.Action {
	case "opened":
		err = s.moveStoryByRule(ctx, repository.WorkspaceID, link.TeamID, storyLink.StoryID, EventIssueOpen, nil)
	case "reopened":
		alreadyReflected, stateErr := s.issueStateAlreadyReflectedByStory(ctx, payload.Action, story)
		if stateErr != nil {
			return stateErr
		}
		if alreadyReflected {
			err = nil
			break
		}
		err = s.moveStoryByRule(ctx, repository.WorkspaceID, link.TeamID, storyLink.StoryID, EventIssueReopen, nil)
	case "closed":
		alreadyReflected, stateErr := s.issueStateAlreadyReflectedByStory(ctx, payload.Action, story)
		if stateErr != nil {
			return stateErr
		}
		if alreadyReflected {
			err = nil
			break
		}
		err = s.moveStoryByRule(ctx, repository.WorkspaceID, link.TeamID, storyLink.StoryID, EventIssueClose, nil)
	case "edited":
		err = nil
	default:
		err = nil
	}
	if err != nil {
		return err
	}
	return s.repo.UpdateStoryLinkSyncState(ctx, storyLink.ID, githubSyncSourceGitHub, incomingSyncHash)
}

func githubIssueSyncHash(title, body, state string) string {
	return codehost.WorkItemRevision(codehost.WorkItemSnapshot{
		Title: title,
		Body:  body,
		State: codehost.WorkItemState(state),
	})
}

func shouldIgnoreFortyOneIssueEcho(action, lastSyncedFrom, lastSyncHash, incomingSyncHash string) bool {
	if !isFortyOneIssueEchoAction(action) {
		return false
	}
	return codehost.ShouldSuppressEcho(codehost.ReconciliationState{
		LastOrigin:   codehost.SyncOrigin(lastSyncedFrom),
		LastRevision: lastSyncHash,
	}, incomingSyncHash)
}

func isFortyOneIssueEchoAction(action string) bool {
	switch action {
	case "opened", "edited", "closed", "reopened":
		return true
	default:
		return false
	}
}

func stringValue(value *string) string {
	if value == nil {
		return ""
	}
	return *value
}

func (s *Service) issueStateAlreadyReflectedByStory(ctx context.Context, action string, story singleStory) (bool, error) {
	if story.Status == nil {
		return false, nil
	}
	category, err := s.repo.GetStatusCategory(ctx, *story.Status)
	if err != nil {
		return false, fmt.Errorf("resolve story status category for GitHub sync: %w", err)
	}
	return issueActionMatchesStoryStatusCategory(action, category), nil
}

func issueActionMatchesStoryStatusCategory(action, category string) bool {
	switch action {
	case "closed":
		return category == "completed"
	case "reopened":
		return category != "" && category != "completed" && category != "cancelled"
	default:
		return false
	}
}
