-- name: CreateOAuthAuditEvent :exec
INSERT INTO public.oauth_audit_events (
    event_id,
    application_id,
    grant_id,
    user_id,
    workspace_id,
    installation_id,
    principal_id,
    secret_id,
    actor_kind,
    actor_id,
    actor_credential_id,
    request_id,
    subject_type,
    subject_id,
    operation,
    result,
    reason_code,
    metadata,
    created_at
) VALUES (
    sqlc.arg(event_id),
    sqlc.narg(application_id),
    sqlc.narg(grant_id),
    sqlc.narg(user_id),
    sqlc.narg(workspace_id),
    sqlc.narg(installation_id),
    sqlc.narg(principal_id),
    sqlc.narg(secret_id),
    sqlc.narg(actor_kind),
    sqlc.narg(actor_id),
    sqlc.narg(actor_credential_id),
    sqlc.narg(request_id),
    sqlc.narg(subject_type),
    sqlc.narg(subject_id),
    sqlc.arg(operation),
    sqlc.arg(result),
    sqlc.narg(reason_code),
    CAST(sqlc.arg(metadata) AS jsonb),
    sqlc.arg(created_at)
);
