// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package messagingsql

import (
	"time"

	"github.com/google/uuid"
)

type MessagingEmailActionProposal struct {
	ID                    uuid.UUID
	ThreadID              uuid.UUID
	WorkspaceID           uuid.UUID
	UserID                uuid.UUID
	SourceMessageID       uuid.UUID
	IdempotencyKey        string
	ActionKind            string
	EntityType            string
	EntityID              uuid.UUID
	ExpectedEntityVersion string
	ProposedDiff          []byte
	Status                string
	ApplyAttempt          int32
	Result                []byte
	LastError             *string
	ExpiresAt             time.Time
	ConfirmedAt           *time.Time
	ApplyingAt            *time.Time
	AppliedAt             *time.Time
	FailedAt              *time.Time
	CancelledAt           *time.Time
	ExpiredAt             *time.Time
	SupersededAt          *time.Time
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type MessagingEmailThread struct {
	ID                      uuid.UUID
	WorkspaceID             uuid.UUID
	UserID                  uuid.UUID
	Provider                string
	RecipientEmail          string
	ExternalThreadID        string
	RootInternetMessageID   string
	LatestInternetMessageID string
	Context                 []byte
	Summary                 string
	SummaryThroughSequence  int64
	NextMessageSequence     int64
	CreatedAt               time.Time
	UpdatedAt               time.Time
}
