// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: story_mutation_confirmations.sql

package messagingsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeStoryMutationApply = `-- name: CompleteStoryMutationApply :execrows
UPDATE messaging_story_mutation_confirmations
SET result = CAST($1 AS jsonb),
    proposal = NULL,
    last_error = NULL,
    updated_at = NOW()
WHERE confirmation_id = $2
  AND status = 'applied'
`

type CompleteStoryMutationApplyParams struct {
	Result         []byte
	ConfirmationID uuid.UUID
}

func (q *Queries) CompleteStoryMutationApply(ctx context.Context, arg CompleteStoryMutationApplyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeStoryMutationApply, arg.Result, arg.ConfirmationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertStoryMutationConfirmation = `-- name: InsertStoryMutationConfirmation :exec
INSERT INTO messaging_story_mutation_confirmations (
    confirmation_id,
    workspace_id,
    user_id,
    team_id,
    operation,
    token_hash,
    proposal,
    status,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    CAST(NULLIF(CAST($7 AS text), '') AS jsonb),
    'pending',
    $8
)
`

type InsertStoryMutationConfirmationParams struct {
	ConfirmationID uuid.UUID
	WorkspaceID    uuid.UUID
	UserID         uuid.UUID
	TeamID         uuid.UUID
	Operation      string
	TokenHash      []byte
	Proposal       string
	ExpiresAt      time.Time
}

func (q *Queries) InsertStoryMutationConfirmation(ctx context.Context, arg InsertStoryMutationConfirmationParams) error {
	_, err := q.db.Exec(ctx, insertStoryMutationConfirmation,
		arg.ConfirmationID,
		arg.WorkspaceID,
		arg.UserID,
		arg.TeamID,
		arg.Operation,
		arg.TokenHash,
		arg.Proposal,
		arg.ExpiresAt,
	)
	return err
}

const loadStoryMutationConfirmation = `-- name: LoadStoryMutationConfirmation :one
SELECT team_id,
       operation,
       proposal,
       status,
       COALESCE(result, CAST('null' AS jsonb)) AS result,
       last_error
FROM messaging_story_mutation_confirmations
WHERE confirmation_id = $1
  AND workspace_id = $2
  AND user_id = $3
  AND token_hash = $4
`

type LoadStoryMutationConfirmationParams struct {
	ConfirmationID uuid.UUID
	WorkspaceID    uuid.UUID
	UserID         uuid.UUID
	TokenHash      []byte
}

type LoadStoryMutationConfirmationRow struct {
	TeamID    uuid.UUID
	Operation string
	Proposal  []byte
	Status    string
	Result    []byte
	LastError *string
}

func (q *Queries) LoadStoryMutationConfirmation(ctx context.Context, arg LoadStoryMutationConfirmationParams) (LoadStoryMutationConfirmationRow, error) {
	row := q.db.QueryRow(ctx, loadStoryMutationConfirmation,
		arg.ConfirmationID,
		arg.WorkspaceID,
		arg.UserID,
		arg.TokenHash,
	)
	var i LoadStoryMutationConfirmationRow
	err := row.Scan(
		&i.TeamID,
		&i.Operation,
		&i.Proposal,
		&i.Status,
		&i.Result,
		&i.LastError,
	)
	return i, err
}

const lockStoryMutationConfirmation = `-- name: LockStoryMutationConfirmation :one
SELECT status,
       COALESCE(result, CAST('null' AS jsonb)) AS result,
       last_error,
       CAST(proposal IS NOT NULL AS boolean) AS has_proposal,
       expires_at
FROM messaging_story_mutation_confirmations
WHERE confirmation_id = $1
  AND workspace_id = $2
  AND user_id = $3
  AND token_hash = $4
FOR UPDATE
`

type LockStoryMutationConfirmationParams struct {
	ConfirmationID uuid.UUID
	WorkspaceID    uuid.UUID
	UserID         uuid.UUID
	TokenHash      []byte
}

type LockStoryMutationConfirmationRow struct {
	Status      string
	Result      []byte
	LastError   *string
	HasProposal bool
	ExpiresAt   time.Time
}

func (q *Queries) LockStoryMutationConfirmation(ctx context.Context, arg LockStoryMutationConfirmationParams) (LockStoryMutationConfirmationRow, error) {
	row := q.db.QueryRow(ctx, lockStoryMutationConfirmation,
		arg.ConfirmationID,
		arg.WorkspaceID,
		arg.UserID,
		arg.TokenHash,
	)
	var i LockStoryMutationConfirmationRow
	err := row.Scan(
		&i.Status,
		&i.Result,
		&i.LastError,
		&i.HasProposal,
		&i.ExpiresAt,
	)
	return i, err
}

const recordStoryMutationApplyFailure = `-- name: RecordStoryMutationApplyFailure :exec
UPDATE messaging_story_mutation_confirmations
SET result = COALESCE(
        CAST(NULLIF(CAST($1 AS text), '') AS jsonb),
        result
    ),
    last_error = $2,
    updated_at = NOW()
WHERE confirmation_id = $3
  AND status = 'applied'
`

type RecordStoryMutationApplyFailureParams struct {
	Result         string
	LastError      *string
	ConfirmationID uuid.UUID
}

func (q *Queries) RecordStoryMutationApplyFailure(ctx context.Context, arg RecordStoryMutationApplyFailureParams) error {
	_, err := q.db.Exec(ctx, recordStoryMutationApplyFailure, arg.Result, arg.LastError, arg.ConfirmationID)
	return err
}

const transitionStoryMutationConfirmation = `-- name: TransitionStoryMutationConfirmation :execrows
UPDATE messaging_story_mutation_confirmations
SET status = $1,
    applied_at = CASE WHEN $1 = 'applied' THEN $2 ELSE NULL END,
    cancelled_at = CASE WHEN $1 = 'cancelled' THEN $2 ELSE NULL END,
    expired_at = CASE WHEN $1 = 'expired' THEN $2 ELSE NULL END,
    proposal = CASE
        WHEN $1 IN ('cancelled', 'expired') THEN NULL
        ELSE proposal
    END,
    updated_at = NOW()
WHERE confirmation_id = $3
  AND status = $4
`

type TransitionStoryMutationConfirmationParams struct {
	Status         string
	Now            *time.Time
	ConfirmationID uuid.UUID
	CurrentStatus  string
}

func (q *Queries) TransitionStoryMutationConfirmation(ctx context.Context, arg TransitionStoryMutationConfirmationParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionStoryMutationConfirmation,
		arg.Status,
		arg.Now,
		arg.ConfirmationID,
		arg.CurrentStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
