// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package figmasql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeOAuthState = `-- name: ConsumeOAuthState :one
UPDATE public.figma_oauth_states
SET consumed_at = $1
WHERE state_hash = $2
  AND consumed_at IS NULL
  AND expires_at > $1
RETURNING state_hash, workspace_id, user_id, workspace_slug, code_verifier, expires_at
`

type ConsumeOAuthStateParams struct {
	ConsumedAt *time.Time
	StateHash  string
}

type ConsumeOAuthStateRow struct {
	StateHash     string
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
	WorkspaceSlug string
	CodeVerifier  string
	ExpiresAt     time.Time
}

func (q *Queries) ConsumeOAuthState(ctx context.Context, arg ConsumeOAuthStateParams) (ConsumeOAuthStateRow, error) {
	row := q.db.QueryRow(ctx, consumeOAuthState, arg.ConsumedAt, arg.StateHash)
	var i ConsumeOAuthStateRow
	err := row.Scan(
		&i.StateHash,
		&i.WorkspaceID,
		&i.UserID,
		&i.WorkspaceSlug,
		&i.CodeVerifier,
		&i.ExpiresAt,
	)
	return i, err
}

const saveOAuthState = `-- name: SaveOAuthState :execrows
INSERT INTO public.figma_oauth_states (
    state_hash,
    workspace_id,
    user_id,
    workspace_slug,
    code_verifier,
    expires_at
)
SELECT
    $1,
    workspace.workspace_id,
    member.user_id,
    workspace.slug,
    $2,
    $3
FROM public.workspaces AS workspace
INNER JOIN public.workspace_members AS member
    ON member.workspace_id = workspace.workspace_id
   AND member.user_id = $4
INNER JOIN public.users AS account
    ON account.user_id = member.user_id
   AND account.is_active = TRUE
WHERE workspace.workspace_id = $5
  AND workspace.slug = $6
  AND workspace.deleted_at IS NULL
`

type SaveOAuthStateParams struct {
	StateHash     string
	CodeVerifier  string
	ExpiresAt     time.Time
	UserID        uuid.UUID
	WorkspaceID   uuid.UUID
	WorkspaceSlug string
}

func (q *Queries) SaveOAuthState(ctx context.Context, arg SaveOAuthStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveOAuthState,
		arg.StateHash,
		arg.CodeVerifier,
		arg.ExpiresAt,
		arg.UserID,
		arg.WorkspaceID,
		arg.WorkspaceSlug,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
