// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digest.sql

package feedbacksql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advanceFeedbackDigestSubscriptionCursors = `-- name: AdvanceFeedbackDigestSubscriptionCursors :execrows
UPDATE feedback_board_subscriptions subscription
SET last_digest_sent_at = $1,
    last_digest_cursor_at = $2,
    updated_at = NOW()
FROM feedback_boards board
INNER JOIN teams team ON team.team_id = board.team_id AND team.workspace_id = board.workspace_id
INNER JOIN team_members team_member ON team_member.team_id = board.team_id AND team_member.user_id = $3
INNER JOIN workspace_members workspace_member
    ON workspace_member.workspace_id = board.workspace_id
   AND workspace_member.user_id = $3
   AND workspace_member.role IN ('admin', 'member')
INNER JOIN users account
    ON account.user_id = workspace_member.user_id
   AND account.is_active = true
   AND account.is_system = false
WHERE subscription.board_id = board.id
  AND subscription.user_id = $3
  AND board.workspace_id = $4
  AND subscription.board_id = ANY(CAST($5 AS uuid[]))
`

type AdvanceFeedbackDigestSubscriptionCursorsParams struct {
	DeliveryAt  *time.Time
	WindowEnd   *time.Time
	RecipientID uuid.UUID
	WorkspaceID uuid.UUID
	BoardIds    []uuid.UUID
}

func (q *Queries) AdvanceFeedbackDigestSubscriptionCursors(ctx context.Context, arg AdvanceFeedbackDigestSubscriptionCursorsParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceFeedbackDigestSubscriptionCursors,
		arg.DeliveryAt,
		arg.WindowEnd,
		arg.RecipientID,
		arg.WorkspaceID,
		arg.BoardIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimFeedbackDigestDelivery = `-- name: ClaimFeedbackDigestDelivery :one
INSERT INTO feedback_digest_deliveries (
    workspace_id,
    recipient_id,
    local_date,
    status,
    window_start,
    window_end
)
SELECT workspace.workspace_id,
       account.user_id,
       $1,
       'processing',
       $2,
       $3
FROM workspaces workspace
INNER JOIN workspace_members workspace_member
    ON workspace_member.workspace_id = workspace.workspace_id
   AND workspace_member.user_id = $4
   AND workspace_member.role IN ('admin', 'member')
INNER JOIN users account
    ON account.user_id = workspace_member.user_id
   AND account.is_active = true
   AND account.is_system = false
WHERE workspace.workspace_id = $5
  AND workspace.deleted_at IS NULL
ON CONFLICT (workspace_id, recipient_id, local_date)
DO UPDATE SET status = 'processing',
              window_start = EXCLUDED.window_start,
              window_end = EXCLUDED.window_end,
              item_count = 0,
              sent_at = NULL,
              last_error = NULL,
              updated_at = NOW()
WHERE feedback_digest_deliveries.status = 'failed'
   OR (
       feedback_digest_deliveries.status = 'processing'
       AND feedback_digest_deliveries.updated_at < $6
   )
RETURNING id
`

type ClaimFeedbackDigestDeliveryParams struct {
	LocalDate   time.Time
	WindowStart time.Time
	WindowEnd   time.Time
	RecipientID uuid.UUID
	WorkspaceID uuid.UUID
	StaleBefore time.Time
}

func (q *Queries) ClaimFeedbackDigestDelivery(ctx context.Context, arg ClaimFeedbackDigestDeliveryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimFeedbackDigestDelivery,
		arg.LocalDate,
		arg.WindowStart,
		arg.WindowEnd,
		arg.RecipientID,
		arg.WorkspaceID,
		arg.StaleBefore,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const completeFeedbackDigestDelivery = `-- name: CompleteFeedbackDigestDelivery :execrows
UPDATE feedback_digest_deliveries
SET status = $1,
    item_count = $2,
    sent_at = CAST($3 AS timestamptz),
    last_error = NULL,
    updated_at = NOW()
WHERE id = $4
  AND workspace_id = $5
  AND recipient_id = $6
  AND status = 'processing'
`

type CompleteFeedbackDigestDeliveryParams struct {
	Status      string
	ItemCount   int32
	SentAt      *time.Time
	DeliveryID  uuid.UUID
	WorkspaceID uuid.UUID
	RecipientID uuid.UUID
}

func (q *Queries) CompleteFeedbackDigestDelivery(ctx context.Context, arg CompleteFeedbackDigestDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeFeedbackDigestDelivery,
		arg.Status,
		arg.ItemCount,
		arg.SentAt,
		arg.DeliveryID,
		arg.WorkspaceID,
		arg.RecipientID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failFeedbackDigestDelivery = `-- name: FailFeedbackDigestDelivery :execrows
UPDATE feedback_digest_deliveries
SET status = 'failed',
    last_error = LEFT($1, 2000),
    updated_at = NOW()
WHERE id = $2
  AND status = 'processing'
`

type FailFeedbackDigestDeliveryParams struct {
	Failure    string
	DeliveryID uuid.UUID
}

func (q *Queries) FailFeedbackDigestDelivery(ctx context.Context, arg FailFeedbackDigestDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, failFeedbackDigestDelivery, arg.Failure, arg.DeliveryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFeedbackDigestItems = `-- name: ListFeedbackDigestItems :many
WITH board_windows AS (
    SELECT boards.board_id, starts.window_start
    FROM UNNEST(CAST($2 AS uuid[])) WITH ORDINALITY boards(board_id, ordinal)
    INNER JOIN UNNEST(CAST($3 AS timestamptz[])) WITH ORDINALITY starts(window_start, ordinal)
        ON starts.ordinal = boards.ordinal
), eligible_items AS (
    SELECT item.id,
           board.team_id,
           item.title,
           item.description,
           CAST(COALESCE(
               NULLIF(TRIM(author.full_name), ''),
               NULLIF(TRIM(author.username), ''),
               NULLIF(TRIM(author.email), ''),
               'Customer'
           ) AS text) AS author_name,
           team.name AS team_name,
           item.status,
           item.created_at
    FROM board_windows board_window
    INNER JOIN feedback_items item ON item.board_id = board_window.board_id
    INNER JOIN feedback_boards board ON board.id = item.board_id AND board.workspace_id = item.workspace_id
    INNER JOIN feedback_board_subscriptions subscription ON subscription.board_id = board.id AND subscription.user_id = $4
    INNER JOIN teams team ON team.team_id = board.team_id AND team.workspace_id = board.workspace_id
    INNER JOIN team_members team_member ON team_member.team_id = board.team_id AND team_member.user_id = subscription.user_id
    INNER JOIN workspace_members workspace_member
        ON workspace_member.workspace_id = board.workspace_id
       AND workspace_member.user_id = subscription.user_id
       AND workspace_member.role IN ('admin', 'member')
    INNER JOIN users recipient
        ON recipient.user_id = subscription.user_id
       AND recipient.is_active = true
       AND recipient.is_system = false
    LEFT JOIN users author ON author.user_id = item.author_id
    WHERE item.workspace_id = $5
      AND item.deleted_at IS NULL
      AND item.submission_source IN ('portal', 'widget', 'integration')
      AND item.created_at > board_window.window_start
      AND item.created_at <= $6
)
SELECT eligible_items.id,
       eligible_items.team_id,
       eligible_items.title,
       eligible_items.description,
       eligible_items.author_name,
       eligible_items.team_name,
       eligible_items.status,
       eligible_items.created_at,
       CAST(COUNT(*) OVER () AS integer) AS total_count,
       CAST(COUNT(*) FILTER (WHERE eligible_items.status IN ('pending', 'reviewing')) OVER () AS integer) AS pending_review_count
FROM eligible_items
ORDER BY eligible_items.created_at DESC, eligible_items.id DESC
LIMIT $1
`

type ListFeedbackDigestItemsParams struct {
	RowLimit     int32
	BoardIds     []uuid.UUID
	WindowStarts []time.Time
	RecipientID  uuid.UUID
	WorkspaceID  uuid.UUID
	WindowEnd    time.Time
}

type ListFeedbackDigestItemsRow struct {
	ID                 uuid.UUID
	TeamID             uuid.UUID
	Title              string
	Description        string
	AuthorName         string
	TeamName           string
	Status             string
	CreatedAt          time.Time
	TotalCount         int32
	PendingReviewCount int32
}

func (q *Queries) ListFeedbackDigestItems(ctx context.Context, arg ListFeedbackDigestItemsParams) ([]ListFeedbackDigestItemsRow, error) {
	rows, err := q.db.Query(ctx, listFeedbackDigestItems,
		arg.RowLimit,
		arg.BoardIds,
		arg.WindowStarts,
		arg.RecipientID,
		arg.WorkspaceID,
		arg.WindowEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedbackDigestItemsRow{}
	for rows.Next() {
		var i ListFeedbackDigestItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Title,
			&i.Description,
			&i.AuthorName,
			&i.TeamName,
			&i.Status,
			&i.CreatedAt,
			&i.TotalCount,
			&i.PendingReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedbackDigestRecipients = `-- name: ListFeedbackDigestRecipients :many
SELECT DISTINCT account.user_id,
       account.email AS user_email,
       COALESCE(NULLIF(TRIM(account.full_name), ''), NULLIF(TRIM(account.username), ''), account.email) AS user_name,
       CAST(COALESCE(NULLIF(TRIM(account.timezone), ''), 'UTC') AS text) AS timezone,
       workspace.workspace_id,
       workspace.name AS workspace_name,
       workspace.slug AS workspace_slug
FROM feedback_board_subscriptions subscription
INNER JOIN feedback_boards board ON board.id = subscription.board_id
INNER JOIN teams team ON team.team_id = board.team_id AND team.workspace_id = board.workspace_id
INNER JOIN team_members team_member ON team_member.team_id = board.team_id AND team_member.user_id = subscription.user_id
INNER JOIN workspace_members workspace_member
    ON workspace_member.workspace_id = board.workspace_id
   AND workspace_member.user_id = subscription.user_id
   AND workspace_member.role IN ('admin', 'member')
INNER JOIN users account
    ON account.user_id = subscription.user_id
   AND account.is_active = true
   AND account.is_system = false
INNER JOIN workspaces workspace
    ON workspace.workspace_id = board.workspace_id
   AND workspace.deleted_at IS NULL
WHERE subscription.email_frequency IN ('daily', 'weekly')
  AND NULLIF(TRIM(account.email), '') IS NOT NULL
  AND (
      NOT CAST($1 AS boolean)
      OR workspace.workspace_id > $2
      OR (
          workspace.workspace_id = $2
          AND account.user_id > $3
      )
  )
ORDER BY workspace.workspace_id, account.user_id
LIMIT $4
`

type ListFeedbackDigestRecipientsParams struct {
	HasCursor        bool
	AfterWorkspaceID uuid.UUID
	AfterUserID      uuid.UUID
	RowLimit         int32
}

type ListFeedbackDigestRecipientsRow struct {
	UserID        uuid.UUID
	UserEmail     string
	UserName      string
	Timezone      string
	WorkspaceID   uuid.UUID
	WorkspaceName string
	WorkspaceSlug string
}

func (q *Queries) ListFeedbackDigestRecipients(ctx context.Context, arg ListFeedbackDigestRecipientsParams) ([]ListFeedbackDigestRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listFeedbackDigestRecipients,
		arg.HasCursor,
		arg.AfterWorkspaceID,
		arg.AfterUserID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedbackDigestRecipientsRow{}
	for rows.Next() {
		var i ListFeedbackDigestRecipientsRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserEmail,
			&i.UserName,
			&i.Timezone,
			&i.WorkspaceID,
			&i.WorkspaceName,
			&i.WorkspaceSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedbackDigestSubscriptions = `-- name: ListFeedbackDigestSubscriptions :many
SELECT subscription.board_id,
       board.team_id,
       CAST(subscription.email_frequency AS text) AS email_frequency,
       subscription.created_at,
       subscription.last_digest_sent_at,
       subscription.last_digest_cursor_at
FROM feedback_board_subscriptions subscription
INNER JOIN feedback_boards board ON board.id = subscription.board_id
INNER JOIN teams team ON team.team_id = board.team_id AND team.workspace_id = board.workspace_id
INNER JOIN team_members team_member ON team_member.team_id = board.team_id AND team_member.user_id = subscription.user_id
INNER JOIN workspace_members workspace_member
    ON workspace_member.workspace_id = board.workspace_id
   AND workspace_member.user_id = subscription.user_id
   AND workspace_member.role IN ('admin', 'member')
INNER JOIN users account
    ON account.user_id = subscription.user_id
   AND account.is_active = true
   AND account.is_system = false
INNER JOIN workspaces workspace
    ON workspace.workspace_id = board.workspace_id
   AND workspace.deleted_at IS NULL
WHERE subscription.user_id = $1
  AND board.workspace_id = $2
  AND subscription.email_frequency IN ('daily', 'weekly')
ORDER BY subscription.board_id
`

type ListFeedbackDigestSubscriptionsParams struct {
	RecipientID uuid.UUID
	WorkspaceID uuid.UUID
}

type ListFeedbackDigestSubscriptionsRow struct {
	BoardID            uuid.UUID
	TeamID             uuid.UUID
	EmailFrequency     string
	CreatedAt          time.Time
	LastDigestSentAt   *time.Time
	LastDigestCursorAt *time.Time
}

func (q *Queries) ListFeedbackDigestSubscriptions(ctx context.Context, arg ListFeedbackDigestSubscriptionsParams) ([]ListFeedbackDigestSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listFeedbackDigestSubscriptions, arg.RecipientID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedbackDigestSubscriptionsRow{}
	for rows.Next() {
		var i ListFeedbackDigestSubscriptionsRow
		if err := rows.Scan(
			&i.BoardID,
			&i.TeamID,
			&i.EmailFrequency,
			&i.CreatedAt,
			&i.LastDigestSentAt,
			&i.LastDigestCursorAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
