// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package feedbacksql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAnonymousFeedbackContributor = `-- name: CreateAnonymousFeedbackContributor :one
INSERT INTO feedback_contributors (portal_id, kind)
SELECT fp.id, 'anonymous'
FROM feedback_portals fp
WHERE fp.id = $1
  AND fp.is_public = true
RETURNING id
`

type CreateAnonymousFeedbackContributorParams struct {
	PortalID uuid.UUID
}

func (q *Queries) CreateAnonymousFeedbackContributor(ctx context.Context, arg CreateAnonymousFeedbackContributorParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAnonymousFeedbackContributor, arg.PortalID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createFeedbackItem = `-- name: CreateFeedbackItem :one
INSERT INTO feedback_items (
    workspace_id,
    portal_id,
    board_id,
    contributor_id,
    author_id,
    title,
    description,
    slug,
    submission_source
)
SELECT fp.workspace_id,
       fp.id,
       fb.id,
       contributor.id,
       contributor.user_id,
       $1,
       $2,
       $3,
       $4
FROM feedback_portals fp
INNER JOIN feedback_boards fb
    ON fb.portal_id = fp.id
   AND fb.workspace_id = fp.workspace_id
   AND fb.id = $5
INNER JOIN feedback_contributors contributor
    ON contributor.portal_id = fp.id
   AND contributor.id = $6
   AND contributor.blocked_at IS NULL
WHERE fp.workspace_id = $7
  AND fp.id = $8
  AND (
      NOT CAST($9 AS boolean)
      OR (
          contributor.kind = 'account'
          AND contributor.user_id = $10
          AND EXISTS (
              SELECT 1
              FROM workspace_members wm
              INNER JOIN team_members tm
                  ON tm.team_id = fb.team_id
                 AND tm.user_id = wm.user_id
              INNER JOIN users current_actor
                  ON current_actor.user_id = wm.user_id
                 AND current_actor.is_active = true
                 AND current_actor.is_system = false
              WHERE wm.workspace_id = fp.workspace_id
                AND wm.user_id = $10
                AND wm.role IN ('admin', 'member')
          )
      )
  )
RETURNING id
`

type CreateFeedbackItemParams struct {
	Title            string
	Description      string
	Slug             string
	SubmissionSource string
	BoardID          uuid.UUID
	ContributorID    uuid.UUID
	WorkspaceID      uuid.UUID
	PortalID         uuid.UUID
	RequireActor     bool
	ActorID          *uuid.UUID
}

func (q *Queries) CreateFeedbackItem(ctx context.Context, arg CreateFeedbackItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createFeedbackItem,
		arg.Title,
		arg.Description,
		arg.Slug,
		arg.SubmissionSource,
		arg.BoardID,
		arg.ContributorID,
		arg.WorkspaceID,
		arg.PortalID,
		arg.RequireActor,
		arg.ActorID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const feedbackItemStoryManaged = `-- name: FeedbackItemStoryManaged :one
SELECT EXISTS (
    SELECT 1
    FROM feedback_story_links fsl
    WHERE fsl.workspace_id = $1
      AND fsl.item_id = $2
      AND fsl.is_primary = true
)
`

type FeedbackItemStoryManagedParams struct {
	WorkspaceID uuid.UUID
	ItemID      uuid.UUID
}

func (q *Queries) FeedbackItemStoryManaged(ctx context.Context, arg FeedbackItemStoryManagedParams) (bool, error) {
	row := q.db.QueryRow(ctx, feedbackItemStoryManaged, arg.WorkspaceID, arg.ItemID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFeedbackItemProtection = `-- name: GetFeedbackItemProtection :one
SELECT EXISTS (
           SELECT 1
           FROM feedback_items item
           WHERE item.workspace_id = $1
             AND item.id = $2
             AND (
                 item.merged_into_item_id IS NOT NULL
                 OR EXISTS (
                     SELECT 1
                     FROM feedback_items merged_source
                     WHERE merged_source.workspace_id = item.workspace_id
                       AND merged_source.portal_id = item.portal_id
                       AND merged_source.merged_into_item_id = item.id
                 )
             )
       ) AS merge_protected,
       EXISTS (
           SELECT 1
           FROM feedback_story_links fsl
           WHERE fsl.workspace_id = $1
             AND fsl.item_id = $2
             AND fsl.is_primary = true
       ) AS story_managed
`

type GetFeedbackItemProtectionParams struct {
	WorkspaceID uuid.UUID
	ItemID      uuid.UUID
}

type GetFeedbackItemProtectionRow struct {
	MergeProtected bool
	StoryManaged   bool
}

func (q *Queries) GetFeedbackItemProtection(ctx context.Context, arg GetFeedbackItemProtectionParams) (GetFeedbackItemProtectionRow, error) {
	row := q.db.QueryRow(ctx, getFeedbackItemProtection, arg.WorkspaceID, arg.ItemID)
	var i GetFeedbackItemProtectionRow
	err := row.Scan(&i.MergeProtected, &i.StoryManaged)
	return i, err
}

const getOrCreateAccountFeedbackContributor = `-- name: GetOrCreateAccountFeedbackContributor :one
INSERT INTO feedback_contributors (portal_id, user_id, kind)
SELECT fp.id, account.user_id, 'account'
FROM feedback_portals fp
INNER JOIN users account
    ON account.user_id = $1
   AND account.is_active = true
   AND account.is_system = false
WHERE fp.id = $2
ON CONFLICT (portal_id, user_id) WHERE user_id IS NOT NULL
DO UPDATE SET updated_at = NOW()
RETURNING id, portal_id, user_id, CAST(kind AS text) AS kind, created_at
`

type GetOrCreateAccountFeedbackContributorParams struct {
	UserID   uuid.UUID
	PortalID uuid.UUID
}

type GetOrCreateAccountFeedbackContributorRow struct {
	ID        uuid.UUID
	PortalID  uuid.UUID
	UserID    *uuid.UUID
	Kind      string
	CreatedAt time.Time
}

func (q *Queries) GetOrCreateAccountFeedbackContributor(ctx context.Context, arg GetOrCreateAccountFeedbackContributorParams) (GetOrCreateAccountFeedbackContributorRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateAccountFeedbackContributor, arg.UserID, arg.PortalID)
	var i GetOrCreateAccountFeedbackContributorRow
	err := row.Scan(
		&i.ID,
		&i.PortalID,
		&i.UserID,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicFeedbackItem = `-- name: GetPublicFeedbackItem :one
SELECT fi.id,
       fi.workspace_id,
       fi.portal_id,
       fi.board_id,
       fi.contributor_id,
       fi.author_id,
       CAST(CASE
           WHEN contributor.kind = 'anonymous'
             OR (contributor.kind IN ('verified_guest', 'external') AND (contributor.public_masked OR portal.guest_identity_policy = 'always_mask_guests')) THEN 'Anonymous'
           WHEN contributor.kind IN ('verified_guest', 'external') THEN COALESCE(NULLIF(TRIM(contributor.display_name), ''), 'Guest')
           ELSE COALESCE(NULLIF(TRIM(account.full_name), ''), NULLIF(TRIM(account.username), ''), 'Anonymous')
       END AS text) AS author_name,
       CAST(CASE WHEN contributor.kind = 'account' THEN COALESCE(account.email, '') ELSE COALESCE(contributor.email, '') END AS text) AS author_email,
       CAST(COALESCE(CASE
           WHEN contributor.kind = 'anonymous'
             OR (contributor.kind IN ('verified_guest', 'external') AND (contributor.public_masked OR portal.guest_identity_policy = 'always_mask_guests')) THEN ''
           WHEN contributor.kind = 'account' THEN account.avatar_url
           ELSE contributor.avatar_url
       END, '') AS text) AS author_avatar,
       CAST(contributor.kind AS text) AS participant_kind,
       CAST((contributor.kind = 'anonymous' OR (contributor.kind IN ('verified_guest', 'external') AND (contributor.public_masked OR portal.guest_identity_policy = 'always_mask_guests'))) AS boolean) AS author_masked,
       fi.merged_into_item_id,
       fi.merged_at,
       fi.merged_by_user_id,
       false AS following,
       fi.title,
       fi.description,
       fi.slug,
       CAST(CASE
           WHEN projected_story.id IS NULL THEN fi.status
           WHEN projected_story.deleted_at IS NOT NULL THEN 'closed'
           WHEN projected_state.category = 'backlog' THEN 'reviewing'
           WHEN projected_state.category = 'unstarted' THEN 'planned'
           WHEN projected_state.category = 'started' THEN 'in_progress'
           WHEN projected_state.category = 'paused' THEN 'planned'
           WHEN projected_state.category = 'completed' THEN 'completed'
           WHEN projected_state.category = 'cancelled' THEN 'closed'
           ELSE fi.status
       END AS text) AS status,
       CAST(COALESCE((SELECT SUM(fv.direction) FROM feedback_votes fv WHERE fv.item_id = fi.id), 0) AS integer) AS vote_count,
       CAST((SELECT COUNT(*) FROM feedback_votes fv WHERE fv.item_id = fi.id AND fv.direction = 1) AS integer) AS upvote_count,
       CAST((SELECT COUNT(*) FROM feedback_votes fv WHERE fv.item_id = fi.id AND fv.direction = -1) AS integer) AS downvote_count,
       CAST((SELECT COUNT(*) FROM feedback_comments fc WHERE fc.item_id = fi.id) AS integer) AS comment_count,
       fi.roadmap_summary,
       fb.team_id AS board_team_id,
       fb.name AS board_name,
       fb.slug AS board_slug,
       fb.color AS board_color,
       fb.order_index AS board_order_index,
       fb.created_at AS board_created_at,
       fb.updated_at AS board_updated_at,
       COALESCE(primary_link.id, CAST('00000000-0000-0000-0000-000000000000' AS uuid)) AS primary_link_id,
       COALESCE(primary_link.story_id, CAST('00000000-0000-0000-0000-000000000000' AS uuid)) AS primary_story_id,
       projected_story.title AS primary_story_title,
       COALESCE(primary_link.relationship, '') AS primary_relationship,
       primary_link.created_by_user_id AS primary_created_by_user_id,
       COALESCE(primary_link.created_at, CAST('0001-01-01T00:00:00Z' AS timestamptz)) AS primary_created_at,
       CAST(NULL AS timestamptz) AS read_at,
       fi.deleted_at,
       fi.created_at,
       fi.updated_at
FROM feedback_items fi
INNER JOIN feedback_contributors contributor ON contributor.id = fi.contributor_id AND contributor.portal_id = fi.portal_id
INNER JOIN feedback_portals portal ON portal.id = fi.portal_id AND portal.is_public = true
LEFT JOIN users account ON account.user_id = fi.author_id
INNER JOIN feedback_boards fb ON fb.id = fi.board_id AND fb.workspace_id = fi.workspace_id AND fb.portal_id = fi.portal_id
LEFT JOIN LATERAL (
    SELECT fsl.id, fsl.story_id, fsl.relationship, fsl.created_by_user_id, fsl.created_at
    FROM feedback_story_links fsl
    WHERE fsl.item_id = fi.id AND fsl.is_primary = true
    ORDER BY fsl.created_at, fsl.id
    LIMIT 1
) primary_link ON true
LEFT JOIN stories projected_story ON projected_story.id = primary_link.story_id
LEFT JOIN statuses projected_state ON projected_state.status_id = projected_story.status_id
WHERE fi.portal_id = $1
  AND fi.id = $2
  AND fi.deleted_at IS NULL
  AND fi.merged_into_item_id IS NULL
`

type GetPublicFeedbackItemParams struct {
	PortalID uuid.UUID
	ItemID   uuid.UUID
}

type GetPublicFeedbackItemRow struct {
	ID                     uuid.UUID
	WorkspaceID            uuid.UUID
	PortalID               uuid.UUID
	BoardID                uuid.UUID
	ContributorID          uuid.UUID
	AuthorID               *uuid.UUID
	AuthorName             string
	AuthorEmail            string
	AuthorAvatar           string
	ParticipantKind        string
	AuthorMasked           bool
	MergedIntoItemID       *uuid.UUID
	MergedAt               *time.Time
	MergedByUserID         *uuid.UUID
	Following              bool
	Title                  string
	Description            string
	Slug                   string
	Status                 string
	VoteCount              int32
	UpvoteCount            int32
	DownvoteCount          int32
	CommentCount           int32
	RoadmapSummary         *string
	BoardTeamID            uuid.UUID
	BoardName              string
	BoardSlug              string
	BoardColor             string
	BoardOrderIndex        int32
	BoardCreatedAt         time.Time
	BoardUpdatedAt         time.Time
	PrimaryLinkID          uuid.UUID
	PrimaryStoryID         uuid.UUID
	PrimaryStoryTitle      *string
	PrimaryRelationship    string
	PrimaryCreatedByUserID *uuid.UUID
	PrimaryCreatedAt       time.Time
	ReadAt                 *time.Time
	DeletedAt              *time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) GetPublicFeedbackItem(ctx context.Context, arg GetPublicFeedbackItemParams) (GetPublicFeedbackItemRow, error) {
	row := q.db.QueryRow(ctx, getPublicFeedbackItem, arg.PortalID, arg.ItemID)
	var i GetPublicFeedbackItemRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PortalID,
		&i.BoardID,
		&i.ContributorID,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorAvatar,
		&i.ParticipantKind,
		&i.AuthorMasked,
		&i.MergedIntoItemID,
		&i.MergedAt,
		&i.MergedByUserID,
		&i.Following,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Status,
		&i.VoteCount,
		&i.UpvoteCount,
		&i.DownvoteCount,
		&i.CommentCount,
		&i.RoadmapSummary,
		&i.BoardTeamID,
		&i.BoardName,
		&i.BoardSlug,
		&i.BoardColor,
		&i.BoardOrderIndex,
		&i.BoardCreatedAt,
		&i.BoardUpdatedAt,
		&i.PrimaryLinkID,
		&i.PrimaryStoryID,
		&i.PrimaryStoryTitle,
		&i.PrimaryRelationship,
		&i.PrimaryCreatedByUserID,
		&i.PrimaryCreatedAt,
		&i.ReadAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceFeedbackItem = `-- name: GetWorkspaceFeedbackItem :one
SELECT fi.id,
       fi.workspace_id,
       fi.portal_id,
       fi.board_id,
       fi.contributor_id,
       fi.author_id,
       CAST(CASE
           WHEN contributor.kind = 'anonymous'
             OR (contributor.kind IN ('verified_guest', 'external') AND (contributor.public_masked OR portal.guest_identity_policy = 'always_mask_guests')) THEN 'Anonymous'
           WHEN contributor.kind IN ('verified_guest', 'external') THEN COALESCE(NULLIF(TRIM(contributor.display_name), ''), 'Guest')
           ELSE COALESCE(NULLIF(TRIM(account.full_name), ''), NULLIF(TRIM(account.username), ''), 'Anonymous')
       END AS text) AS author_name,
       CAST(CASE WHEN contributor.kind = 'account' THEN COALESCE(account.email, '') ELSE COALESCE(contributor.email, '') END AS text) AS author_email,
       CAST(COALESCE(CASE
           WHEN contributor.kind = 'anonymous'
             OR (contributor.kind IN ('verified_guest', 'external') AND (contributor.public_masked OR portal.guest_identity_policy = 'always_mask_guests')) THEN ''
           WHEN contributor.kind = 'account' THEN account.avatar_url
           ELSE contributor.avatar_url
       END, '') AS text) AS author_avatar,
       CAST(contributor.kind AS text) AS participant_kind,
       CAST((contributor.kind = 'anonymous' OR (contributor.kind IN ('verified_guest', 'external') AND (contributor.public_masked OR portal.guest_identity_policy = 'always_mask_guests'))) AS boolean) AS author_masked,
       fi.merged_into_item_id,
       fi.merged_at,
       fi.merged_by_user_id,
       false AS following,
       fi.title,
       fi.description,
       fi.slug,
       CAST(CASE
           WHEN projected_story.id IS NULL THEN fi.status
           WHEN projected_story.deleted_at IS NOT NULL THEN 'closed'
           WHEN projected_state.category = 'backlog' THEN 'reviewing'
           WHEN projected_state.category = 'unstarted' THEN 'planned'
           WHEN projected_state.category = 'started' THEN 'in_progress'
           WHEN projected_state.category = 'paused' THEN 'planned'
           WHEN projected_state.category = 'completed' THEN 'completed'
           WHEN projected_state.category = 'cancelled' THEN 'closed'
           ELSE fi.status
       END AS text) AS status,
       CAST(COALESCE((SELECT SUM(fv.direction) FROM feedback_votes fv WHERE fv.item_id = fi.id), 0) AS integer) AS vote_count,
       CAST((SELECT COUNT(*) FROM feedback_votes fv WHERE fv.item_id = fi.id AND fv.direction = 1) AS integer) AS upvote_count,
       CAST((SELECT COUNT(*) FROM feedback_votes fv WHERE fv.item_id = fi.id AND fv.direction = -1) AS integer) AS downvote_count,
       CAST((SELECT COUNT(*) FROM feedback_comments fc WHERE fc.item_id = fi.id) AS integer) AS comment_count,
       fi.roadmap_summary,
       fb.team_id AS board_team_id,
       fb.name AS board_name,
       fb.slug AS board_slug,
       fb.color AS board_color,
       fb.order_index AS board_order_index,
       fb.created_at AS board_created_at,
       fb.updated_at AS board_updated_at,
       COALESCE(primary_link.id, CAST('00000000-0000-0000-0000-000000000000' AS uuid)) AS primary_link_id,
       COALESCE(primary_link.story_id, CAST('00000000-0000-0000-0000-000000000000' AS uuid)) AS primary_story_id,
       projected_story.title AS primary_story_title,
       COALESCE(primary_link.relationship, '') AS primary_relationship,
       primary_link.created_by_user_id AS primary_created_by_user_id,
       COALESCE(primary_link.created_at, CAST('0001-01-01T00:00:00Z' AS timestamptz)) AS primary_created_at,
       CAST(NULL AS timestamptz) AS read_at,
       fi.deleted_at,
       fi.created_at,
       fi.updated_at
FROM feedback_items fi
INNER JOIN feedback_contributors contributor ON contributor.id = fi.contributor_id AND contributor.portal_id = fi.portal_id
INNER JOIN feedback_portals portal ON portal.id = fi.portal_id
LEFT JOIN users account ON account.user_id = fi.author_id
INNER JOIN feedback_boards fb ON fb.id = fi.board_id AND fb.workspace_id = fi.workspace_id AND fb.portal_id = fi.portal_id
LEFT JOIN LATERAL (
    SELECT fsl.id, fsl.story_id, fsl.relationship, fsl.created_by_user_id, fsl.created_at
    FROM feedback_story_links fsl
    WHERE fsl.item_id = fi.id AND fsl.is_primary = true
    ORDER BY fsl.created_at, fsl.id
    LIMIT 1
) primary_link ON true
LEFT JOIN stories projected_story ON projected_story.id = primary_link.story_id
LEFT JOIN statuses projected_state ON projected_state.status_id = projected_story.status_id
WHERE fi.workspace_id = $1
  AND fi.id = $2
  AND fi.deleted_at IS NULL
`

type GetWorkspaceFeedbackItemParams struct {
	WorkspaceID uuid.UUID
	ItemID      uuid.UUID
}

type GetWorkspaceFeedbackItemRow struct {
	ID                     uuid.UUID
	WorkspaceID            uuid.UUID
	PortalID               uuid.UUID
	BoardID                uuid.UUID
	ContributorID          uuid.UUID
	AuthorID               *uuid.UUID
	AuthorName             string
	AuthorEmail            string
	AuthorAvatar           string
	ParticipantKind        string
	AuthorMasked           bool
	MergedIntoItemID       *uuid.UUID
	MergedAt               *time.Time
	MergedByUserID         *uuid.UUID
	Following              bool
	Title                  string
	Description            string
	Slug                   string
	Status                 string
	VoteCount              int32
	UpvoteCount            int32
	DownvoteCount          int32
	CommentCount           int32
	RoadmapSummary         *string
	BoardTeamID            uuid.UUID
	BoardName              string
	BoardSlug              string
	BoardColor             string
	BoardOrderIndex        int32
	BoardCreatedAt         time.Time
	BoardUpdatedAt         time.Time
	PrimaryLinkID          uuid.UUID
	PrimaryStoryID         uuid.UUID
	PrimaryStoryTitle      *string
	PrimaryRelationship    string
	PrimaryCreatedByUserID *uuid.UUID
	PrimaryCreatedAt       time.Time
	ReadAt                 *time.Time
	DeletedAt              *time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) GetWorkspaceFeedbackItem(ctx context.Context, arg GetWorkspaceFeedbackItemParams) (GetWorkspaceFeedbackItemRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceFeedbackItem, arg.WorkspaceID, arg.ItemID)
	var i GetWorkspaceFeedbackItemRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PortalID,
		&i.BoardID,
		&i.ContributorID,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorAvatar,
		&i.ParticipantKind,
		&i.AuthorMasked,
		&i.MergedIntoItemID,
		&i.MergedAt,
		&i.MergedByUserID,
		&i.Following,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Status,
		&i.VoteCount,
		&i.UpvoteCount,
		&i.DownvoteCount,
		&i.CommentCount,
		&i.RoadmapSummary,
		&i.BoardTeamID,
		&i.BoardName,
		&i.BoardSlug,
		&i.BoardColor,
		&i.BoardOrderIndex,
		&i.BoardCreatedAt,
		&i.BoardUpdatedAt,
		&i.PrimaryLinkID,
		&i.PrimaryStoryID,
		&i.PrimaryStoryTitle,
		&i.PrimaryRelationship,
		&i.PrimaryCreatedByUserID,
		&i.PrimaryCreatedAt,
		&i.ReadAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeedbackItems = `-- name: ListFeedbackItems :many
SELECT fi.id,
       fi.workspace_id,
       fi.portal_id,
       fi.board_id,
       fi.contributor_id,
       fi.author_id,
       CAST(CASE
           WHEN contributor.kind = 'anonymous'
             OR (
                 contributor.kind IN ('verified_guest', 'external')
                 AND (
                     contributor.public_masked
                     OR portal.guest_identity_policy = 'always_mask_guests'
                 )
             ) THEN 'Anonymous'
           WHEN contributor.kind IN ('verified_guest', 'external')
               THEN COALESCE(NULLIF(TRIM(contributor.display_name), ''), 'Guest')
           ELSE COALESCE(NULLIF(TRIM(account.full_name), ''), NULLIF(TRIM(account.username), ''), 'Anonymous')
       END AS text) AS author_name,
       CAST(CASE
           WHEN contributor.kind = 'account' THEN COALESCE(account.email, '')
           ELSE COALESCE(contributor.email, '')
       END AS text) AS author_email,
       CAST(COALESCE(CASE
           WHEN contributor.kind = 'anonymous'
             OR (
                 contributor.kind IN ('verified_guest', 'external')
                 AND (
                     contributor.public_masked
                     OR portal.guest_identity_policy = 'always_mask_guests'
                 )
             ) THEN ''
           WHEN contributor.kind = 'account' THEN account.avatar_url
           ELSE contributor.avatar_url
       END, '') AS text) AS author_avatar,
       CAST(contributor.kind AS text) AS participant_kind,
       CAST((
           contributor.kind = 'anonymous'
           OR (
               contributor.kind IN ('verified_guest', 'external')
               AND (
                   contributor.public_masked
                   OR portal.guest_identity_policy = 'always_mask_guests'
               )
           )
       ) AS boolean) AS author_masked,
       fi.merged_into_item_id,
       fi.merged_at,
       fi.merged_by_user_id,
       false AS following,
       fi.title,
       fi.description,
       fi.slug,
       CAST(CASE
           WHEN projected_story.id IS NULL THEN fi.status
           WHEN projected_story.deleted_at IS NOT NULL THEN 'closed'
           WHEN projected_state.category = 'backlog' THEN 'reviewing'
           WHEN projected_state.category = 'unstarted' THEN 'planned'
           WHEN projected_state.category = 'started' THEN 'in_progress'
           WHEN projected_state.category = 'paused' THEN 'planned'
           WHEN projected_state.category = 'completed' THEN 'completed'
           WHEN projected_state.category = 'cancelled' THEN 'closed'
           ELSE fi.status
       END AS text) AS status,
       CAST(COALESCE((SELECT SUM(fv.direction) FROM feedback_votes fv WHERE fv.item_id = fi.id), 0) AS integer) AS vote_count,
       CAST((SELECT COUNT(*) FROM feedback_votes fv WHERE fv.item_id = fi.id AND fv.direction = 1) AS integer) AS upvote_count,
       CAST((SELECT COUNT(*) FROM feedback_votes fv WHERE fv.item_id = fi.id AND fv.direction = -1) AS integer) AS downvote_count,
       CAST((SELECT COUNT(*) FROM feedback_comments fc WHERE fc.item_id = fi.id) AS integer) AS comment_count,
       fi.roadmap_summary,
       fb.team_id AS board_team_id,
       fb.name AS board_name,
       fb.slug AS board_slug,
       fb.color AS board_color,
       fb.order_index AS board_order_index,
       fb.created_at AS board_created_at,
       fb.updated_at AS board_updated_at,
       COALESCE(primary_link.id, CAST('00000000-0000-0000-0000-000000000000' AS uuid)) AS primary_link_id,
       COALESCE(primary_link.story_id, CAST('00000000-0000-0000-0000-000000000000' AS uuid)) AS primary_story_id,
       projected_story.title AS primary_story_title,
       COALESCE(primary_link.relationship, '') AS primary_relationship,
       primary_link.created_by_user_id AS primary_created_by_user_id,
       COALESCE(primary_link.created_at, CAST('0001-01-01T00:00:00Z' AS timestamptz)) AS primary_created_at,
       feedback_read.read_at,
       fi.deleted_at,
       fi.created_at,
       fi.updated_at
FROM feedback_items fi
INNER JOIN feedback_contributors contributor
    ON contributor.id = fi.contributor_id
   AND contributor.portal_id = fi.portal_id
INNER JOIN feedback_portals portal ON portal.id = fi.portal_id
LEFT JOIN users account ON account.user_id = fi.author_id
INNER JOIN feedback_boards fb
    ON fb.id = fi.board_id
   AND fb.workspace_id = fi.workspace_id
   AND fb.portal_id = fi.portal_id
LEFT JOIN LATERAL (
    SELECT fsl.id,
           fsl.story_id,
           fsl.relationship,
           fsl.created_by_user_id,
           fsl.created_at
    FROM feedback_story_links fsl
    WHERE fsl.item_id = fi.id
      AND fsl.is_primary = true
    ORDER BY fsl.created_at, fsl.id
    LIMIT 1
) primary_link ON true
LEFT JOIN stories projected_story ON projected_story.id = primary_link.story_id
LEFT JOIN statuses projected_state ON projected_state.status_id = projected_story.status_id
LEFT JOIN feedback_item_reads feedback_read
    ON feedback_read.item_id = fi.id
   AND feedback_read.user_id = CAST($1 AS uuid)
WHERE (NOT CAST($2 AS boolean) OR fi.portal_id = $3)
  AND (NOT CAST($4 AS boolean) OR fi.id = $5)
  AND (NOT CAST($6 AS boolean) OR (
      fi.workspace_id = $7
      AND fb.team_id = $8
  ))
  AND (
      (
          CAST($9 AS boolean)
          AND fi.deleted_at IS NOT NULL
          AND fi.deleted_at >= $10
          AND fi.merged_into_item_id IS NULL
      )
      OR (
          NOT CAST($9 AS boolean)
          AND fi.deleted_at IS NULL
          AND fi.merged_into_item_id IS NULL
      )
  )
  AND (
      CAST($11 AS smallint) = 0
      OR (
          CAST($11 AS smallint) = 1
          AND CAST(CASE
              WHEN projected_story.id IS NULL THEN fi.status
              WHEN projected_story.deleted_at IS NOT NULL THEN 'closed'
              WHEN projected_state.category = 'backlog' THEN 'reviewing'
              WHEN projected_state.category = 'unstarted' THEN 'planned'
              WHEN projected_state.category = 'started' THEN 'in_progress'
              WHEN projected_state.category = 'paused' THEN 'planned'
              WHEN projected_state.category = 'completed' THEN 'completed'
              WHEN projected_state.category = 'cancelled' THEN 'closed'
              ELSE fi.status
          END AS text) IN ('pending', 'reviewing', 'planned', 'in_progress')
      )
      OR (
          CAST($11 AS smallint) = 2
          AND CAST(CASE
              WHEN projected_story.id IS NULL THEN fi.status
              WHEN projected_story.deleted_at IS NOT NULL THEN 'closed'
              WHEN projected_state.category = 'backlog' THEN 'reviewing'
              WHEN projected_state.category = 'unstarted' THEN 'planned'
              WHEN projected_state.category = 'started' THEN 'in_progress'
              WHEN projected_state.category = 'paused' THEN 'planned'
              WHEN projected_state.category = 'completed' THEN 'completed'
              WHEN projected_state.category = 'cancelled' THEN 'closed'
              ELSE fi.status
          END AS text) = CAST($12 AS text)
      )
  )
  AND (NOT CAST($13 AS boolean) OR fi.board_id = $14)
  AND (NOT CAST($15 AS boolean) OR fi.author_id = $16)
  AND (
      NOT CAST($17 AS boolean)
      OR to_tsvector('english', fi.title || ' ' || fi.description || ' ' || fi.slug)
         @@ websearch_to_tsquery('english', $18)
  )
  AND (
      NOT CAST($19 AS boolean)
      OR EXISTS (
          SELECT 1
          FROM workspace_members wm
          INNER JOIN team_members tm
              ON tm.team_id = fb.team_id
             AND tm.user_id = wm.user_id
          INNER JOIN users current_actor
              ON current_actor.user_id = wm.user_id
             AND current_actor.is_active = true
             AND current_actor.is_system = false
          WHERE wm.workspace_id = fi.workspace_id
            AND wm.user_id = $20
            AND wm.role IN ('admin', 'member')
            AND (
                CAST($21 AS boolean)
                OR fb.team_id = ANY(CAST($22 AS uuid[]))
            )
      )
  )
ORDER BY
    CASE WHEN CAST($23 AS text) = 'newest' THEN fi.created_at END DESC,
    CASE WHEN CAST($23 AS text) = 'oldest' THEN fi.created_at END ASC,
    CASE WHEN CAST($23 AS text) = 'top' THEN CAST(COALESCE((SELECT SUM(v.direction) FROM feedback_votes v WHERE v.item_id = fi.id), 0) AS integer) END DESC,
    fi.created_at DESC,
    fi.id DESC
LIMIT $25
OFFSET $24
`

type ListFeedbackItemsParams struct {
	ViewerID          *uuid.UUID
	FilterPortal      bool
	PortalID          uuid.UUID
	FilterItem        bool
	ItemID            uuid.UUID
	FilterTeam        bool
	WorkspaceID       uuid.UUID
	TeamID            uuid.UUID
	DeletedOnly       bool
	RecoveryCutoff    *time.Time
	StatusMode        int16
	Status            string
	FilterBoard       bool
	BoardID           uuid.UUID
	FilterAuthor      bool
	AuthorID          *uuid.UUID
	FilterSearch      bool
	Search            string
	RequireMember     bool
	ActorID           uuid.UUID
	AllTeams          bool
	CredentialTeamIds []uuid.UUID
	SortKey           string
	RowOffset         int32
	RowLimit          int32
}

type ListFeedbackItemsRow struct {
	ID                     uuid.UUID
	WorkspaceID            uuid.UUID
	PortalID               uuid.UUID
	BoardID                uuid.UUID
	ContributorID          uuid.UUID
	AuthorID               *uuid.UUID
	AuthorName             string
	AuthorEmail            string
	AuthorAvatar           string
	ParticipantKind        string
	AuthorMasked           bool
	MergedIntoItemID       *uuid.UUID
	MergedAt               *time.Time
	MergedByUserID         *uuid.UUID
	Following              bool
	Title                  string
	Description            string
	Slug                   string
	Status                 string
	VoteCount              int32
	UpvoteCount            int32
	DownvoteCount          int32
	CommentCount           int32
	RoadmapSummary         *string
	BoardTeamID            uuid.UUID
	BoardName              string
	BoardSlug              string
	BoardColor             string
	BoardOrderIndex        int32
	BoardCreatedAt         time.Time
	BoardUpdatedAt         time.Time
	PrimaryLinkID          uuid.UUID
	PrimaryStoryID         uuid.UUID
	PrimaryStoryTitle      *string
	PrimaryRelationship    string
	PrimaryCreatedByUserID *uuid.UUID
	PrimaryCreatedAt       time.Time
	ReadAt                 *time.Time
	DeletedAt              *time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) ListFeedbackItems(ctx context.Context, arg ListFeedbackItemsParams) ([]ListFeedbackItemsRow, error) {
	rows, err := q.db.Query(ctx, listFeedbackItems,
		arg.ViewerID,
		arg.FilterPortal,
		arg.PortalID,
		arg.FilterItem,
		arg.ItemID,
		arg.FilterTeam,
		arg.WorkspaceID,
		arg.TeamID,
		arg.DeletedOnly,
		arg.RecoveryCutoff,
		arg.StatusMode,
		arg.Status,
		arg.FilterBoard,
		arg.BoardID,
		arg.FilterAuthor,
		arg.AuthorID,
		arg.FilterSearch,
		arg.Search,
		arg.RequireMember,
		arg.ActorID,
		arg.AllTeams,
		arg.CredentialTeamIds,
		arg.SortKey,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedbackItemsRow{}
	for rows.Next() {
		var i ListFeedbackItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PortalID,
			&i.BoardID,
			&i.ContributorID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorAvatar,
			&i.ParticipantKind,
			&i.AuthorMasked,
			&i.MergedIntoItemID,
			&i.MergedAt,
			&i.MergedByUserID,
			&i.Following,
			&i.Title,
			&i.Description,
			&i.Slug,
			&i.Status,
			&i.VoteCount,
			&i.UpvoteCount,
			&i.DownvoteCount,
			&i.CommentCount,
			&i.RoadmapSummary,
			&i.BoardTeamID,
			&i.BoardName,
			&i.BoardSlug,
			&i.BoardColor,
			&i.BoardOrderIndex,
			&i.BoardCreatedAt,
			&i.BoardUpdatedAt,
			&i.PrimaryLinkID,
			&i.PrimaryStoryID,
			&i.PrimaryStoryTitle,
			&i.PrimaryRelationship,
			&i.PrimaryCreatedByUserID,
			&i.PrimaryCreatedAt,
			&i.ReadAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimilarFeedbackItems = `-- name: ListSimilarFeedbackItems :many
WITH input AS (
    SELECT COALESCE(STRING_AGG(token, ' ' ORDER BY token_order), '') AS normalized_title
    FROM UNNEST(regexp_split_to_array(LOWER($2), '[^a-z0-9]+')) WITH ORDINALITY AS tokens(token, token_order)
    WHERE token <> ''
      AND token NOT IN ('a', 'add', 'an', 'build', 'create', 'fix', 'for', 'implement', 'make', 'new', 'please', 'story', 'support', 'task', 'the', 'to', 'update')
), ranked AS (
    SELECT fi.id,
           fi.slug,
           fi.title,
           CASE WHEN contributor.kind = 'account' THEN fi.author_id ELSE CAST(NULL AS uuid) END AS author_id,
           CAST(CASE
               WHEN contributor.kind = 'anonymous'
                 OR (contributor.kind IN ('verified_guest', 'external') AND (contributor.public_masked OR portal.guest_identity_policy = 'always_mask_guests')) THEN 'Anonymous'
               WHEN contributor.kind IN ('verified_guest', 'external') THEN COALESCE(NULLIF(TRIM(contributor.display_name), ''), 'Guest')
               ELSE COALESCE(NULLIF(TRIM(account.full_name), ''), NULLIF(TRIM(account.username), ''), 'Anonymous')
           END AS text) AS author_name,
           CAST(COALESCE(CASE
               WHEN contributor.kind = 'anonymous'
                 OR (contributor.kind IN ('verified_guest', 'external') AND (contributor.public_masked OR portal.guest_identity_policy = 'always_mask_guests')) THEN ''
               WHEN contributor.kind = 'account' THEN account.avatar_url
               ELSE contributor.avatar_url
           END, '') AS text) AS author_avatar,
           CAST(CASE
               WHEN projected_story.id IS NULL THEN fi.status
               WHEN projected_story.deleted_at IS NOT NULL THEN 'closed'
               WHEN projected_state.category = 'backlog' THEN 'reviewing'
               WHEN projected_state.category = 'unstarted' THEN 'planned'
               WHEN projected_state.category = 'started' THEN 'in_progress'
               WHEN projected_state.category = 'paused' THEN 'planned'
               WHEN projected_state.category = 'completed' THEN 'completed'
               WHEN projected_state.category = 'cancelled' THEN 'closed'
               ELSE fi.status
           END AS text) AS status,
           CAST(COALESCE((SELECT SUM(fv.direction) FROM feedback_votes fv WHERE fv.item_id = fi.id), 0) AS integer) AS vote_count,
           CAST((SELECT COUNT(*) FROM feedback_comments fc WHERE fc.item_id = fi.id) AS integer) AS comment_count,
           CAST(GREATEST(
               similarity(normalized.normalized_title, input.normalized_title),
               CASE WHEN normalized.normalized_title = input.normalized_title THEN 1.0 ELSE 0.0 END,
               CASE
                   WHEN CAST($3 AS text) <> ''
                       THEN similarity(LOWER(normalized.normalized_title || ' ' || fi.description), LOWER(input.normalized_title || ' ' || CAST($3 AS text)))
                   ELSE 0.0
               END
           ) AS double precision) AS confidence
    FROM feedback_items fi
    INNER JOIN feedback_contributors contributor ON contributor.id = fi.contributor_id
    INNER JOIN feedback_portals portal ON portal.id = fi.portal_id AND portal.is_public = true
    LEFT JOIN users account ON account.user_id = fi.author_id
    LEFT JOIN LATERAL (
        SELECT fsl.id, fsl.story_id
        FROM feedback_story_links fsl
        WHERE fsl.item_id = fi.id AND fsl.is_primary = true
        ORDER BY fsl.created_at, fsl.id
        LIMIT 1
    ) primary_link ON true
    LEFT JOIN stories projected_story ON projected_story.id = primary_link.story_id
    LEFT JOIN statuses projected_state ON projected_state.status_id = projected_story.status_id
    CROSS JOIN input
    CROSS JOIN LATERAL (
        SELECT COALESCE(STRING_AGG(token, ' ' ORDER BY token_order), '') AS normalized_title
        FROM UNNEST(regexp_split_to_array(LOWER(fi.title), '[^a-z0-9]+')) WITH ORDINALITY AS tokens(token, token_order)
        WHERE token <> ''
          AND token NOT IN ('a', 'add', 'an', 'build', 'create', 'fix', 'for', 'implement', 'make', 'new', 'please', 'story', 'support', 'task', 'the', 'to', 'update')
    ) normalized
    WHERE fi.portal_id = $4
      AND fi.deleted_at IS NULL
      AND fi.merged_into_item_id IS NULL
      AND input.normalized_title <> ''
      AND normalized.normalized_title <> ''
)
SELECT ranked.id,
       ranked.slug,
       ranked.title,
       ranked.author_id,
       ranked.author_name,
       ranked.author_avatar,
       ranked.status,
       ranked.vote_count,
       ranked.comment_count,
       ranked.confidence
FROM ranked
WHERE ranked.confidence >= 0.45
ORDER BY ranked.confidence DESC, ranked.vote_count DESC, ranked.title ASC, ranked.id ASC
LIMIT $1
`

type ListSimilarFeedbackItemsParams struct {
	RowLimit    int32
	Title       string
	Description string
	PortalID    uuid.UUID
}

type ListSimilarFeedbackItemsRow struct {
	ID           uuid.UUID
	Slug         string
	Title        string
	AuthorID     uuid.UUID
	AuthorName   string
	AuthorAvatar string
	Status       string
	VoteCount    int32
	CommentCount int32
	Confidence   float64
}

func (q *Queries) ListSimilarFeedbackItems(ctx context.Context, arg ListSimilarFeedbackItemsParams) ([]ListSimilarFeedbackItemsRow, error) {
	rows, err := q.db.Query(ctx, listSimilarFeedbackItems,
		arg.RowLimit,
		arg.Title,
		arg.Description,
		arg.PortalID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSimilarFeedbackItemsRow{}
	for rows.Next() {
		var i ListSimilarFeedbackItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.Status,
			&i.VoteCount,
			&i.CommentCount,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCanonicalFeedbackItem = `-- name: ResolveCanonicalFeedbackItem :one
SELECT canonical.id AS item_id,
       canonical.slug AS item_slug,
       CAST(source.merged_into_item_id IS NOT NULL AS boolean) AS merged
FROM feedback_items source
INNER JOIN feedback_items canonical
    ON canonical.id = COALESCE(source.merged_into_item_id, source.id)
   AND canonical.portal_id = source.portal_id
INNER JOIN feedback_portals portal
    ON portal.id = source.portal_id
   AND portal.is_public = true
WHERE source.portal_id = $1
  AND (
      source.id = CASE
          WHEN CAST($2 AS text) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
              THEN CAST($2 AS uuid)
          ELSE CAST(NULL AS uuid)
      END
      OR source.slug = CAST($2 AS text)
  )
  AND source.deleted_at IS NULL
  AND canonical.deleted_at IS NULL
`

type ResolveCanonicalFeedbackItemParams struct {
	PortalID      uuid.UUID
	ItemReference string
}

type ResolveCanonicalFeedbackItemRow struct {
	ItemID   uuid.UUID
	ItemSlug string
	Merged   bool
}

func (q *Queries) ResolveCanonicalFeedbackItem(ctx context.Context, arg ResolveCanonicalFeedbackItemParams) (ResolveCanonicalFeedbackItemRow, error) {
	row := q.db.QueryRow(ctx, resolveCanonicalFeedbackItem, arg.PortalID, arg.ItemReference)
	var i ResolveCanonicalFeedbackItemRow
	err := row.Scan(&i.ItemID, &i.ItemSlug, &i.Merged)
	return i, err
}

const restoreFeedbackItem = `-- name: RestoreFeedbackItem :execrows
UPDATE feedback_items fi
SET deleted_at = NULL,
    updated_at = NOW()
FROM feedback_boards fb,
     workspace_members wm,
     team_members tm,
     users current_actor
WHERE fb.id = fi.board_id
  AND fb.workspace_id = fi.workspace_id
  AND wm.workspace_id = fi.workspace_id
  AND wm.user_id = $1
  AND wm.role IN ('admin', 'member')
  AND tm.team_id = fb.team_id
  AND tm.user_id = wm.user_id
  AND current_actor.user_id = wm.user_id
  AND current_actor.is_active = true
  AND current_actor.is_system = false
  AND fi.workspace_id = $2
  AND fi.id = $3
  AND fi.deleted_at IS NOT NULL
  AND fi.merged_into_item_id IS NULL
  AND fi.deleted_at >= $4
`

type RestoreFeedbackItemParams struct {
	ActorID        uuid.UUID
	WorkspaceID    uuid.UUID
	ItemID         uuid.UUID
	RecoveryCutoff *time.Time
}

func (q *Queries) RestoreFeedbackItem(ctx context.Context, arg RestoreFeedbackItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreFeedbackItem,
		arg.ActorID,
		arg.WorkspaceID,
		arg.ItemID,
		arg.RecoveryCutoff,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trashFeedbackItem = `-- name: TrashFeedbackItem :execrows
UPDATE feedback_items fi
SET deleted_at = NOW(),
    updated_at = NOW()
FROM feedback_boards fb,
     workspace_members wm,
     team_members tm,
     users current_actor
WHERE fb.id = fi.board_id
  AND fb.workspace_id = fi.workspace_id
  AND wm.workspace_id = fi.workspace_id
  AND wm.user_id = $1
  AND wm.role IN ('admin', 'member')
  AND tm.team_id = fb.team_id
  AND tm.user_id = wm.user_id
  AND current_actor.user_id = wm.user_id
  AND current_actor.is_active = true
  AND current_actor.is_system = false
  AND fi.workspace_id = $2
  AND fi.id = $3
  AND fi.deleted_at IS NULL
  AND fi.merged_into_item_id IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM feedback_items merged_source
      WHERE merged_source.workspace_id = fi.workspace_id
        AND merged_source.portal_id = fi.portal_id
        AND merged_source.merged_into_item_id = fi.id
  )
  AND NOT EXISTS (
      SELECT 1
      FROM feedback_story_links fsl
      WHERE fsl.item_id = fi.id
        AND fsl.is_primary = true
  )
`

type TrashFeedbackItemParams struct {
	ActorID     uuid.UUID
	WorkspaceID uuid.UUID
	ItemID      uuid.UUID
}

func (q *Queries) TrashFeedbackItem(ctx context.Context, arg TrashFeedbackItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, trashFeedbackItem, arg.ActorID, arg.WorkspaceID, arg.ItemID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFeedbackItemStatus = `-- name: UpdateFeedbackItemStatus :one
WITH previous AS (
    SELECT fi.id, fi.status
    FROM feedback_items fi
    INNER JOIN feedback_boards fb ON fb.id = fi.board_id AND fb.workspace_id = fi.workspace_id
    INNER JOIN workspace_members wm
        ON wm.workspace_id = fi.workspace_id
       AND wm.user_id = $1
       AND wm.role IN ('admin', 'member')
    INNER JOIN team_members tm
        ON tm.team_id = fb.team_id
       AND tm.user_id = wm.user_id
    INNER JOIN users current_actor
        ON current_actor.user_id = wm.user_id
       AND current_actor.is_active = true
       AND current_actor.is_system = false
    WHERE fi.workspace_id = $2
      AND fi.id = $3
      AND fi.deleted_at IS NULL
      AND fi.merged_into_item_id IS NULL
      AND (
          CAST($4 AS boolean)
          OR NOT EXISTS (
              SELECT 1
              FROM feedback_story_links fsl
              WHERE fsl.item_id = fi.id
                AND fsl.is_primary = true
          )
      )
      AND (
          NOT CAST($5 AS boolean)
          OR fi.updated_at = $6
      )
    FOR UPDATE OF fi
), updated AS (
    UPDATE feedback_items fi
    SET status = $7,
        roadmap_summary = COALESCE(CAST($8 AS text), fi.roadmap_summary),
        updated_at = NOW()
    FROM previous
    WHERE fi.id = previous.id
    RETURNING fi.id, previous.status AS previous_status, fi.status
)
SELECT updated.id,
       updated.previous_status IS DISTINCT FROM updated.status AS status_changed
FROM updated
`

type UpdateFeedbackItemStatusParams struct {
	ActorID           uuid.UUID
	WorkspaceID       uuid.UUID
	ItemID            uuid.UUID
	AllowLinked       bool
	RequireUnchanged  bool
	ExpectedUpdatedAt time.Time
	Status            string
	RoadmapSummary    *string
}

type UpdateFeedbackItemStatusRow struct {
	ID            uuid.UUID
	StatusChanged bool
}

func (q *Queries) UpdateFeedbackItemStatus(ctx context.Context, arg UpdateFeedbackItemStatusParams) (UpdateFeedbackItemStatusRow, error) {
	row := q.db.QueryRow(ctx, updateFeedbackItemStatus,
		arg.ActorID,
		arg.WorkspaceID,
		arg.ItemID,
		arg.AllowLinked,
		arg.RequireUnchanged,
		arg.ExpectedUpdatedAt,
		arg.Status,
		arg.RoadmapSummary,
	)
	var i UpdateFeedbackItemStatusRow
	err := row.Scan(&i.ID, &i.StatusChanged)
	return i, err
}
