// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: widgets.sql

package feedbacksql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeFeedbackWidgetAssertionNonce = `-- name: ConsumeFeedbackWidgetAssertionNonce :exec
INSERT INTO feedback_widget_assertion_nonces (
    portal_id,
    widget_key_id,
    signing_secret_version,
    nonce_hash,
    parent_origin,
    expires_at
)
SELECT settings.portal_id,
       settings.widget_key_id,
       $1,
       $2,
       $3,
       $4
FROM feedback_widget_settings settings
INNER JOIN feedback_portals portal ON portal.id = settings.portal_id AND portal.is_public = true
WHERE settings.portal_id = $5
  AND settings.widget_key_id = $6
  AND settings.enabled = true
`

type ConsumeFeedbackWidgetAssertionNonceParams struct {
	SigningSecretVersion int32
	NonceHash            []byte
	ParentOrigin         string
	ExpiresAt            time.Time
	PortalID             uuid.UUID
	WidgetKeyID          uuid.UUID
}

func (q *Queries) ConsumeFeedbackWidgetAssertionNonce(ctx context.Context, arg ConsumeFeedbackWidgetAssertionNonceParams) error {
	_, err := q.db.Exec(ctx, consumeFeedbackWidgetAssertionNonce,
		arg.SigningSecretVersion,
		arg.NonceHash,
		arg.ParentOrigin,
		arg.ExpiresAt,
		arg.PortalID,
		arg.WidgetKeyID,
	)
	return err
}

const ensureFeedbackWidgetSettings = `-- name: EnsureFeedbackWidgetSettings :exec
INSERT INTO feedback_widget_settings (portal_id, enabled, allowed_origins)
SELECT portal.id, false, CAST('{}' AS text[])
FROM feedback_portals portal
INNER JOIN workspace_members wm
    ON wm.workspace_id = portal.workspace_id
   AND wm.user_id = $1
   AND wm.role IN ('admin', 'member')
INNER JOIN users current_actor
    ON current_actor.user_id = wm.user_id
   AND current_actor.is_active = true
   AND current_actor.is_system = false
WHERE portal.workspace_id = $2
  AND portal.id = $3
ON CONFLICT (portal_id) DO NOTHING
`

type EnsureFeedbackWidgetSettingsParams struct {
	ActorID     uuid.UUID
	WorkspaceID uuid.UUID
	PortalID    uuid.UUID
}

func (q *Queries) EnsureFeedbackWidgetSettings(ctx context.Context, arg EnsureFeedbackWidgetSettingsParams) error {
	_, err := q.db.Exec(ctx, ensureFeedbackWidgetSettings, arg.ActorID, arg.WorkspaceID, arg.PortalID)
	return err
}

const getCurrentFeedbackWidgetSigningSecret = `-- name: GetCurrentFeedbackWidgetSigningSecret :one
SELECT settings.signing_secret_encrypted
FROM feedback_widget_settings settings
INNER JOIN feedback_portals portal ON portal.id = settings.portal_id AND portal.is_public = true
WHERE settings.portal_id = $1
  AND settings.widget_key_id = $2
  AND settings.signing_secret_version = $3
  AND settings.enabled = true
  AND settings.signing_secret_encrypted IS NOT NULL
`

type GetCurrentFeedbackWidgetSigningSecretParams struct {
	PortalID             uuid.UUID
	WidgetKeyID          uuid.UUID
	SigningSecretVersion int32
}

func (q *Queries) GetCurrentFeedbackWidgetSigningSecret(ctx context.Context, arg GetCurrentFeedbackWidgetSigningSecretParams) (*string, error) {
	row := q.db.QueryRow(ctx, getCurrentFeedbackWidgetSigningSecret, arg.PortalID, arg.WidgetKeyID, arg.SigningSecretVersion)
	var signing_secret_encrypted *string
	err := row.Scan(&signing_secret_encrypted)
	return signing_secret_encrypted, err
}

const getFeedbackWidgetSettings = `-- name: GetFeedbackWidgetSettings :one
SELECT settings.portal_id,
       settings.enabled,
       settings.widget_key_id,
       settings.allowed_origins,
       settings.signing_secret_encrypted,
       settings.signing_secret_version,
       CAST(COALESCE((
           SELECT MAX(rotation.grace_expires_at)
           FROM feedback_widget_signing_secret_rotations rotation
           WHERE rotation.portal_id = settings.portal_id
             AND rotation.retired_at IS NULL
             AND rotation.grace_expires_at > NOW()
       ), CAST('0001-01-01T00:00:00Z' AS timestamptz)) AS timestamptz) AS previous_version_expires_at,
       settings.created_at,
       settings.updated_at
FROM feedback_widget_settings settings
INNER JOIN feedback_portals portal ON portal.id = settings.portal_id
INNER JOIN workspace_members wm
    ON wm.workspace_id = portal.workspace_id
   AND wm.user_id = $1
   AND wm.role IN ('admin', 'member')
INNER JOIN users current_actor
    ON current_actor.user_id = wm.user_id
   AND current_actor.is_active = true
   AND current_actor.is_system = false
WHERE portal.workspace_id = $2
  AND settings.portal_id = $3
`

type GetFeedbackWidgetSettingsParams struct {
	ActorID     uuid.UUID
	WorkspaceID uuid.UUID
	PortalID    uuid.UUID
}

type GetFeedbackWidgetSettingsRow struct {
	PortalID                 uuid.UUID
	Enabled                  bool
	WidgetKeyID              uuid.UUID
	AllowedOrigins           []string
	SigningSecretEncrypted   *string
	SigningSecretVersion     int32
	PreviousVersionExpiresAt time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

func (q *Queries) GetFeedbackWidgetSettings(ctx context.Context, arg GetFeedbackWidgetSettingsParams) (GetFeedbackWidgetSettingsRow, error) {
	row := q.db.QueryRow(ctx, getFeedbackWidgetSettings, arg.ActorID, arg.WorkspaceID, arg.PortalID)
	var i GetFeedbackWidgetSettingsRow
	err := row.Scan(
		&i.PortalID,
		&i.Enabled,
		&i.WidgetKeyID,
		&i.AllowedOrigins,
		&i.SigningSecretEncrypted,
		&i.SigningSecretVersion,
		&i.PreviousVersionExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreviousFeedbackWidgetSigningSecret = `-- name: GetPreviousFeedbackWidgetSigningSecret :one
SELECT rotation.signing_secret_encrypted
FROM feedback_widget_signing_secret_rotations rotation
INNER JOIN feedback_widget_settings settings ON settings.portal_id = rotation.portal_id
INNER JOIN feedback_portals portal ON portal.id = settings.portal_id AND portal.is_public = true
WHERE rotation.portal_id = $1
  AND settings.widget_key_id = $2
  AND settings.enabled = true
  AND rotation.signing_secret_version = $3
  AND rotation.retired_at IS NULL
  AND rotation.grace_expires_at > NOW()
`

type GetPreviousFeedbackWidgetSigningSecretParams struct {
	PortalID             uuid.UUID
	WidgetKeyID          uuid.UUID
	SigningSecretVersion int32
}

func (q *Queries) GetPreviousFeedbackWidgetSigningSecret(ctx context.Context, arg GetPreviousFeedbackWidgetSigningSecretParams) (string, error) {
	row := q.db.QueryRow(ctx, getPreviousFeedbackWidgetSigningSecret, arg.PortalID, arg.WidgetKeyID, arg.SigningSecretVersion)
	var signing_secret_encrypted string
	err := row.Scan(&signing_secret_encrypted)
	return signing_secret_encrypted, err
}

const getPublicFeedbackWidgetSettings = `-- name: GetPublicFeedbackWidgetSettings :one
SELECT settings.portal_id,
       settings.enabled,
       settings.widget_key_id,
       settings.allowed_origins,
       settings.signing_secret_encrypted,
       settings.signing_secret_version,
       CAST(COALESCE((
           SELECT MAX(rotation.grace_expires_at)
           FROM feedback_widget_signing_secret_rotations rotation
           WHERE rotation.portal_id = settings.portal_id
             AND rotation.retired_at IS NULL
             AND rotation.grace_expires_at > NOW()
       ), CAST('0001-01-01T00:00:00Z' AS timestamptz)) AS timestamptz) AS previous_version_expires_at,
       settings.created_at,
       settings.updated_at
FROM feedback_widget_settings settings
INNER JOIN feedback_portals portal
    ON portal.id = settings.portal_id
   AND portal.is_public = true
WHERE settings.portal_id = $1
`

type GetPublicFeedbackWidgetSettingsParams struct {
	PortalID uuid.UUID
}

type GetPublicFeedbackWidgetSettingsRow struct {
	PortalID                 uuid.UUID
	Enabled                  bool
	WidgetKeyID              uuid.UUID
	AllowedOrigins           []string
	SigningSecretEncrypted   *string
	SigningSecretVersion     int32
	PreviousVersionExpiresAt time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

func (q *Queries) GetPublicFeedbackWidgetSettings(ctx context.Context, arg GetPublicFeedbackWidgetSettingsParams) (GetPublicFeedbackWidgetSettingsRow, error) {
	row := q.db.QueryRow(ctx, getPublicFeedbackWidgetSettings, arg.PortalID)
	var i GetPublicFeedbackWidgetSettingsRow
	err := row.Scan(
		&i.PortalID,
		&i.Enabled,
		&i.WidgetKeyID,
		&i.AllowedOrigins,
		&i.SigningSecretEncrypted,
		&i.SigningSecretVersion,
		&i.PreviousVersionExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockFeedbackWidgetSettings = `-- name: LockFeedbackWidgetSettings :one
SELECT settings.portal_id,
       settings.enabled,
       settings.widget_key_id,
       settings.allowed_origins,
       settings.signing_secret_encrypted,
       settings.signing_secret_version,
       CAST(NULL AS timestamptz) AS previous_version_expires_at,
       settings.created_at,
       settings.updated_at
FROM feedback_widget_settings settings
INNER JOIN feedback_portals portal ON portal.id = settings.portal_id
INNER JOIN workspace_members wm
    ON wm.workspace_id = portal.workspace_id
   AND wm.user_id = $1
   AND wm.role IN ('admin', 'member')
INNER JOIN users current_actor
    ON current_actor.user_id = wm.user_id
   AND current_actor.is_active = true
   AND current_actor.is_system = false
WHERE portal.workspace_id = $2
  AND settings.portal_id = $3
FOR UPDATE OF settings
`

type LockFeedbackWidgetSettingsParams struct {
	ActorID     uuid.UUID
	WorkspaceID uuid.UUID
	PortalID    uuid.UUID
}

type LockFeedbackWidgetSettingsRow struct {
	PortalID                 uuid.UUID
	Enabled                  bool
	WidgetKeyID              uuid.UUID
	AllowedOrigins           []string
	SigningSecretEncrypted   *string
	SigningSecretVersion     int32
	PreviousVersionExpiresAt *time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

func (q *Queries) LockFeedbackWidgetSettings(ctx context.Context, arg LockFeedbackWidgetSettingsParams) (LockFeedbackWidgetSettingsRow, error) {
	row := q.db.QueryRow(ctx, lockFeedbackWidgetSettings, arg.ActorID, arg.WorkspaceID, arg.PortalID)
	var i LockFeedbackWidgetSettingsRow
	err := row.Scan(
		&i.PortalID,
		&i.Enabled,
		&i.WidgetKeyID,
		&i.AllowedOrigins,
		&i.SigningSecretEncrypted,
		&i.SigningSecretVersion,
		&i.PreviousVersionExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const savePreviousFeedbackWidgetSecret = `-- name: SavePreviousFeedbackWidgetSecret :exec
INSERT INTO feedback_widget_signing_secret_rotations (
    portal_id,
    signing_secret_version,
    signing_secret_encrypted,
    activated_at,
    grace_expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type SavePreviousFeedbackWidgetSecretParams struct {
	PortalID               uuid.UUID
	SigningSecretVersion   int32
	SigningSecretEncrypted string
	ActivatedAt            time.Time
	GraceExpiresAt         time.Time
}

func (q *Queries) SavePreviousFeedbackWidgetSecret(ctx context.Context, arg SavePreviousFeedbackWidgetSecretParams) error {
	_, err := q.db.Exec(ctx, savePreviousFeedbackWidgetSecret,
		arg.PortalID,
		arg.SigningSecretVersion,
		arg.SigningSecretEncrypted,
		arg.ActivatedAt,
		arg.GraceExpiresAt,
	)
	return err
}

const setInitialFeedbackWidgetSecret = `-- name: SetInitialFeedbackWidgetSecret :one
WITH target AS (
    SELECT portal.id
    FROM feedback_portals portal
    INNER JOIN workspace_members wm
        ON wm.workspace_id = portal.workspace_id
       AND wm.user_id = $1
       AND wm.role IN ('admin', 'member')
    INNER JOIN users current_actor
        ON current_actor.user_id = wm.user_id
       AND current_actor.is_active = true
       AND current_actor.is_system = false
    WHERE portal.workspace_id = $2
      AND portal.id = $3
), updated AS (
    INSERT INTO feedback_widget_settings (
        portal_id,
        enabled,
        widget_key_id,
        allowed_origins,
        signing_secret_encrypted,
        signing_secret_version
    )
    SELECT target.id,
           false,
           $4,
           CAST('{}' AS text[]),
           $5,
           $6
    FROM target
    ON CONFLICT (portal_id) DO UPDATE
    SET widget_key_id = EXCLUDED.widget_key_id,
        signing_secret_encrypted = EXCLUDED.signing_secret_encrypted,
        signing_secret_version = EXCLUDED.signing_secret_version,
        updated_at = NOW()
    WHERE feedback_widget_settings.signing_secret_encrypted IS NULL
    RETURNING portal_id,
              enabled,
              widget_key_id,
              allowed_origins,
              signing_secret_encrypted,
              signing_secret_version,
              created_at,
              updated_at
)
SELECT updated.portal_id,
       updated.enabled,
       updated.widget_key_id,
       updated.allowed_origins,
       updated.signing_secret_encrypted,
       updated.signing_secret_version,
       CAST(NULL AS timestamptz) AS previous_version_expires_at,
       updated.created_at,
       updated.updated_at
FROM updated
`

type SetInitialFeedbackWidgetSecretParams struct {
	ActorID                uuid.UUID
	WorkspaceID            uuid.UUID
	PortalID               uuid.UUID
	WidgetKeyID            uuid.UUID
	SigningSecretEncrypted *string
	SigningSecretVersion   int32
}

type SetInitialFeedbackWidgetSecretRow struct {
	PortalID                 uuid.UUID
	Enabled                  bool
	WidgetKeyID              uuid.UUID
	AllowedOrigins           []string
	SigningSecretEncrypted   *string
	SigningSecretVersion     int32
	PreviousVersionExpiresAt *time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

func (q *Queries) SetInitialFeedbackWidgetSecret(ctx context.Context, arg SetInitialFeedbackWidgetSecretParams) (SetInitialFeedbackWidgetSecretRow, error) {
	row := q.db.QueryRow(ctx, setInitialFeedbackWidgetSecret,
		arg.ActorID,
		arg.WorkspaceID,
		arg.PortalID,
		arg.WidgetKeyID,
		arg.SigningSecretEncrypted,
		arg.SigningSecretVersion,
	)
	var i SetInitialFeedbackWidgetSecretRow
	err := row.Scan(
		&i.PortalID,
		&i.Enabled,
		&i.WidgetKeyID,
		&i.AllowedOrigins,
		&i.SigningSecretEncrypted,
		&i.SigningSecretVersion,
		&i.PreviousVersionExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFeedbackWidgetSecret = `-- name: UpdateFeedbackWidgetSecret :execrows
UPDATE feedback_widget_settings
SET signing_secret_encrypted = $1,
    signing_secret_version = $2,
    updated_at = NOW()
WHERE portal_id = $3
  AND signing_secret_version = $4
`

type UpdateFeedbackWidgetSecretParams struct {
	SigningSecretEncrypted *string
	SigningSecretVersion   int32
	PortalID               uuid.UUID
	PreviousVersion        int32
}

func (q *Queries) UpdateFeedbackWidgetSecret(ctx context.Context, arg UpdateFeedbackWidgetSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFeedbackWidgetSecret,
		arg.SigningSecretEncrypted,
		arg.SigningSecretVersion,
		arg.PortalID,
		arg.PreviousVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertFeedbackWidgetSettings = `-- name: UpsertFeedbackWidgetSettings :one
WITH target AS (
    SELECT portal.id,
           settings.widget_key_id,
           settings.signing_secret_encrypted,
           settings.signing_secret_version
    FROM feedback_portals portal
    INNER JOIN workspace_members wm
        ON wm.workspace_id = portal.workspace_id
       AND wm.user_id = $1
       AND wm.role IN ('admin', 'member')
    INNER JOIN users current_actor
        ON current_actor.user_id = wm.user_id
       AND current_actor.is_active = true
       AND current_actor.is_system = false
    LEFT JOIN feedback_widget_settings settings ON settings.portal_id = portal.id
    WHERE portal.workspace_id = $2
      AND portal.id = $3
), updated AS (
    INSERT INTO feedback_widget_settings (
        portal_id,
        enabled,
        widget_key_id,
        allowed_origins,
        signing_secret_encrypted,
        signing_secret_version
    )
    SELECT target.id,
           $4,
           COALESCE(target.widget_key_id, gen_random_uuid()),
           CAST($5 AS text[]),
           target.signing_secret_encrypted,
           COALESCE(target.signing_secret_version, 0)
    FROM target
    ON CONFLICT (portal_id) DO UPDATE
    SET enabled = EXCLUDED.enabled,
        allowed_origins = EXCLUDED.allowed_origins,
        updated_at = NOW()
    RETURNING portal_id,
              enabled,
              widget_key_id,
              allowed_origins,
              signing_secret_encrypted,
              signing_secret_version,
              created_at,
              updated_at
)
SELECT updated.portal_id,
       updated.enabled,
       updated.widget_key_id,
       updated.allowed_origins,
       updated.signing_secret_encrypted,
       updated.signing_secret_version,
       CAST(COALESCE((
           SELECT MAX(rotation.grace_expires_at)
           FROM feedback_widget_signing_secret_rotations rotation
           WHERE rotation.portal_id = updated.portal_id
             AND rotation.retired_at IS NULL
             AND rotation.grace_expires_at > NOW()
       ), CAST('0001-01-01T00:00:00Z' AS timestamptz)) AS timestamptz) AS previous_version_expires_at,
       updated.created_at,
       updated.updated_at
FROM updated
`

type UpsertFeedbackWidgetSettingsParams struct {
	ActorID        uuid.UUID
	WorkspaceID    uuid.UUID
	PortalID       uuid.UUID
	Enabled        bool
	AllowedOrigins []string
}

type UpsertFeedbackWidgetSettingsRow struct {
	PortalID                 uuid.UUID
	Enabled                  bool
	WidgetKeyID              uuid.UUID
	AllowedOrigins           []string
	SigningSecretEncrypted   *string
	SigningSecretVersion     int32
	PreviousVersionExpiresAt time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

func (q *Queries) UpsertFeedbackWidgetSettings(ctx context.Context, arg UpsertFeedbackWidgetSettingsParams) (UpsertFeedbackWidgetSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertFeedbackWidgetSettings,
		arg.ActorID,
		arg.WorkspaceID,
		arg.PortalID,
		arg.Enabled,
		arg.AllowedOrigins,
	)
	var i UpsertFeedbackWidgetSettingsRow
	err := row.Scan(
		&i.PortalID,
		&i.Enabled,
		&i.WidgetKeyID,
		&i.AllowedOrigins,
		&i.SigningSecretEncrypted,
		&i.SigningSecretVersion,
		&i.PreviousVersionExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
