package chatsessions

import chatsessionsdomain "github.com/complexus-tech/projects-api/internal/modules/chatsessions/domain"

type MutationApprovalExecutionState = chatsessionsdomain.MutationApprovalExecutionState
type MessageWriteOperation = chatsessionsdomain.MessageWriteOperation

const (
	MutationApprovalExecutionClaimed    = chatsessionsdomain.MutationApprovalExecutionClaimed
	MutationApprovalExecutionStarted    = chatsessionsdomain.MutationApprovalExecutionStarted
	MutationApprovalExecutionReady      = chatsessionsdomain.MutationApprovalExecutionReady
	MutationApprovalExecutionExecuting  = chatsessionsdomain.MutationApprovalExecutionExecuting
	MutationApprovalExecutionInProgress = chatsessionsdomain.MutationApprovalExecutionInProgress
	MutationApprovalExecutionCompleted  = chatsessionsdomain.MutationApprovalExecutionCompleted
	MutationApprovalExecutionFailed     = chatsessionsdomain.MutationApprovalExecutionFailed

	MessageWriteAppend     = chatsessionsdomain.MessageWriteAppend
	MessageWriteRegenerate = chatsessionsdomain.MessageWriteRegenerate
	MessageWriteApproval   = chatsessionsdomain.MessageWriteApproval
)

type MutationApprovalReconciliationResolution = chatsessionsdomain.MutationApprovalReconciliationResolution

const (
	MutationApprovalReconciliationVerifiedCompleted  = chatsessionsdomain.MutationApprovalReconciliationVerifiedCompleted
	MutationApprovalReconciliationVerifiedNotApplied = chatsessionsdomain.MutationApprovalReconciliationVerifiedNotApplied
)

type MutationApprovalReconciliationEvidenceKind = chatsessionsdomain.MutationApprovalReconciliationEvidenceKind

const (
	MutationApprovalReconciliationEvidenceIdempotencyLookup = chatsessionsdomain.MutationApprovalReconciliationEvidenceIdempotencyLookup
	MutationApprovalReconciliationEvidenceWorkspaceProbe    = chatsessionsdomain.MutationApprovalReconciliationEvidenceWorkspaceProbe
)

type CoreChatSession = chatsessionsdomain.CoreChatSession
type CoreNewChatSession = chatsessionsdomain.CoreNewChatSession
type BeginMessageWriteParams = chatsessionsdomain.BeginMessageWriteParams
type CoreMessageWriteReservation = chatsessionsdomain.CoreMessageWriteReservation
type FinalizeMessageWriteParams = chatsessionsdomain.FinalizeMessageWriteParams
type CoreMessageWriteResult = chatsessionsdomain.CoreMessageWriteResult
type RecoverMutationApprovalOutputParams = chatsessionsdomain.RecoverMutationApprovalOutputParams
type CoreMutationApprovalExecution = chatsessionsdomain.CoreMutationApprovalExecution
type MutationApprovalExecutionParams = chatsessionsdomain.MutationApprovalExecutionParams
type MutationApprovalReconciliationEvidence = chatsessionsdomain.MutationApprovalReconciliationEvidence
type MutationApprovalReconciliation = chatsessionsdomain.MutationApprovalReconciliation
