// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package workspacesecuritysql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const appendSecurityAudit = `-- name: AppendSecurityAudit :exec
INSERT INTO public.workspace_security_audit_events (event_id, workspace_id, actor_id, resource_type, resource_id, operation, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type AppendSecurityAuditParams struct {
	EventID      uuid.UUID
	WorkspaceID  uuid.UUID
	ActorID      uuid.UUID
	ResourceType string
	ResourceID   uuid.UUID
	Operation    string
	Metadata     []byte
}

func (q *Queries) AppendSecurityAudit(ctx context.Context, arg AppendSecurityAuditParams) error {
	_, err := q.db.Exec(ctx, appendSecurityAudit,
		arg.EventID,
		arg.WorkspaceID,
		arg.ActorID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Operation,
		arg.Metadata,
	)
	return err
}

const authorizeWorkspaceAdmin = `-- name: AuthorizeWorkspaceAdmin :one
SELECT account.email
FROM public.workspace_members AS member
JOIN public.users AS account ON account.user_id = member.user_id
JOIN public.workspaces AS workspace ON workspace.workspace_id = member.workspace_id
WHERE member.workspace_id = $1 AND member.user_id = $2
  AND member.role = 'admin' AND account.is_active = TRUE AND workspace.deleted_at IS NULL
`

type AuthorizeWorkspaceAdminParams struct {
	WorkspaceID uuid.UUID
	ActorID     uuid.UUID
}

func (q *Queries) AuthorizeWorkspaceAdmin(ctx context.Context, arg AuthorizeWorkspaceAdminParams) (string, error) {
	row := q.db.QueryRow(ctx, authorizeWorkspaceAdmin, arg.WorkspaceID, arg.ActorID)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getPolicy = `-- name: GetPolicy :one
SELECT COALESCE(policy.allowed_domains, CAST('{}' AS text[])) AS allowed_domains,
    COALESCE(policy.allow_guests, TRUE) AS allow_guests,
    COALESCE(policy.max_session_age_hours, 0) AS max_session_age_hours,
    COALESCE(policy.version, CAST(0 AS bigint)) AS version, policy.updated_at
FROM public.workspaces AS workspace
LEFT JOIN public.workspace_security_policies AS policy ON policy.workspace_id = workspace.workspace_id
WHERE workspace.workspace_id = $1 AND workspace.deleted_at IS NULL
`

type GetPolicyParams struct {
	WorkspaceID uuid.UUID
}

type GetPolicyRow struct {
	AllowedDomains     []string
	AllowGuests        bool
	MaxSessionAgeHours int32
	Version            int64
	UpdatedAt          *time.Time
}

func (q *Queries) GetPolicy(ctx context.Context, arg GetPolicyParams) (GetPolicyRow, error) {
	row := q.db.QueryRow(ctx, getPolicy, arg.WorkspaceID)
	var i GetPolicyRow
	err := row.Scan(
		&i.AllowedDomains,
		&i.AllowGuests,
		&i.MaxSessionAgeHours,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const listBrowserSessions = `-- name: ListBrowserSessions :many
SELECT session.session_id, session.user_id, account.full_name, account.email, CAST(member.role AS text) AS role,
    session.authenticated_at, session.last_seen_at, session.expires_at, session.revoked_at, epoch.revoked_before
FROM public.workspace_browser_sessions AS session
JOIN public.workspace_members AS member ON member.workspace_id = session.workspace_id AND member.user_id = session.user_id
JOIN public.users AS account ON account.user_id = member.user_id
LEFT JOIN public.workspace_member_session_epochs AS epoch ON epoch.workspace_id = session.workspace_id AND epoch.user_id = session.user_id
WHERE session.workspace_id = $1
  AND (CAST($2 AS uuid) IS NULL OR session.user_id = $2)
  AND (CAST($3 AS boolean) OR (session.revoked_at IS NULL AND session.expires_at > CURRENT_TIMESTAMP AND (epoch.revoked_before IS NULL OR session.authenticated_at > epoch.revoked_before)))
ORDER BY session.last_seen_at DESC, session.session_id DESC LIMIT 501
`

type ListBrowserSessionsParams struct {
	WorkspaceID    uuid.UUID
	UserID         *uuid.UUID
	IncludeRevoked bool
}

type ListBrowserSessionsRow struct {
	SessionID       uuid.UUID
	UserID          uuid.UUID
	FullName        *string
	Email           string
	Role            string
	AuthenticatedAt time.Time
	LastSeenAt      time.Time
	ExpiresAt       time.Time
	RevokedAt       *time.Time
	RevokedBefore   *time.Time
}

func (q *Queries) ListBrowserSessions(ctx context.Context, arg ListBrowserSessionsParams) ([]ListBrowserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listBrowserSessions, arg.WorkspaceID, arg.UserID, arg.IncludeRevoked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBrowserSessionsRow{}
	for rows.Next() {
		var i ListBrowserSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.FullName,
			&i.Email,
			&i.Role,
			&i.AuthenticatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedBefore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBrowserSession = `-- name: LockBrowserSession :one
SELECT user_id, revoked_at FROM public.workspace_browser_sessions
WHERE workspace_id = $1 AND session_id = $2
FOR UPDATE
`

type LockBrowserSessionParams struct {
	WorkspaceID uuid.UUID
	SessionID   uuid.UUID
}

type LockBrowserSessionRow struct {
	UserID    uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) LockBrowserSession(ctx context.Context, arg LockBrowserSessionParams) (LockBrowserSessionRow, error) {
	row := q.db.QueryRow(ctx, lockBrowserSession, arg.WorkspaceID, arg.SessionID)
	var i LockBrowserSessionRow
	err := row.Scan(&i.UserID, &i.RevokedAt)
	return i, err
}

const lockTargetMember = `-- name: LockTargetMember :one
SELECT member.user_id FROM public.workspace_members AS member
WHERE member.workspace_id = $1 AND member.user_id = $2
FOR SHARE OF member
`

type LockTargetMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) LockTargetMember(ctx context.Context, arg LockTargetMemberParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockTargetMember, arg.WorkspaceID, arg.UserID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const lockWorkspaceAdmin = `-- name: LockWorkspaceAdmin :one
SELECT account.email
FROM public.workspace_members AS member
JOIN public.users AS account ON account.user_id = member.user_id
JOIN public.workspaces AS workspace ON workspace.workspace_id = member.workspace_id
WHERE member.workspace_id = $1 AND member.user_id = $2
  AND member.role = 'admin' AND account.is_active = TRUE AND workspace.deleted_at IS NULL
FOR UPDATE OF workspace FOR SHARE OF member, account
`

type LockWorkspaceAdminParams struct {
	WorkspaceID uuid.UUID
	ActorID     uuid.UUID
}

func (q *Queries) LockWorkspaceAdmin(ctx context.Context, arg LockWorkspaceAdminParams) (string, error) {
	row := q.db.QueryRow(ctx, lockWorkspaceAdmin, arg.WorkspaceID, arg.ActorID)
	var email string
	err := row.Scan(&email)
	return email, err
}

const putPolicy = `-- name: PutPolicy :one
INSERT INTO public.workspace_security_policies (workspace_id, allowed_domains, allow_guests, max_session_age_hours, version)
VALUES ($1, $2, $3, $4, 1)
ON CONFLICT (workspace_id) DO UPDATE SET
    allowed_domains = EXCLUDED.allowed_domains, allow_guests = EXCLUDED.allow_guests,
    max_session_age_hours = EXCLUDED.max_session_age_hours, version = workspace_security_policies.version + 1, updated_at = CURRENT_TIMESTAMP
RETURNING allowed_domains, allow_guests, max_session_age_hours, version, updated_at
`

type PutPolicyParams struct {
	WorkspaceID        uuid.UUID
	AllowedDomains     []string
	AllowGuests        bool
	MaxSessionAgeHours int32
}

type PutPolicyRow struct {
	AllowedDomains     []string
	AllowGuests        bool
	MaxSessionAgeHours int32
	Version            int64
	UpdatedAt          time.Time
}

func (q *Queries) PutPolicy(ctx context.Context, arg PutPolicyParams) (PutPolicyRow, error) {
	row := q.db.QueryRow(ctx, putPolicy,
		arg.WorkspaceID,
		arg.AllowedDomains,
		arg.AllowGuests,
		arg.MaxSessionAgeHours,
	)
	var i PutPolicyRow
	err := row.Scan(
		&i.AllowedDomains,
		&i.AllowGuests,
		&i.MaxSessionAgeHours,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeBrowserSession = `-- name: RevokeBrowserSession :execrows
UPDATE public.workspace_browser_sessions SET revoked_at = CURRENT_TIMESTAMP
WHERE workspace_id = $1 AND session_id = $2 AND revoked_at IS NULL
`

type RevokeBrowserSessionParams struct {
	WorkspaceID uuid.UUID
	SessionID   uuid.UUID
}

func (q *Queries) RevokeBrowserSession(ctx context.Context, arg RevokeBrowserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeBrowserSession, arg.WorkspaceID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeMemberSessions = `-- name: RevokeMemberSessions :one
INSERT INTO public.workspace_member_session_epochs (workspace_id, user_id, revoked_before)
VALUES ($1, $2, CURRENT_TIMESTAMP)
ON CONFLICT (workspace_id, user_id) DO UPDATE
SET revoked_before = GREATEST(workspace_member_session_epochs.revoked_before, EXCLUDED.revoked_before)
RETURNING revoked_before
`

type RevokeMemberSessionsParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) RevokeMemberSessions(ctx context.Context, arg RevokeMemberSessionsParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, revokeMemberSessions, arg.WorkspaceID, arg.UserID)
	var revoked_before time.Time
	err := row.Scan(&revoked_before)
	return revoked_before, err
}

const sessionAccessState = `-- name: SessionAccessState :one
SELECT account.email, CAST(member.role AS text) AS role,
    COALESCE(policy.allowed_domains, CAST('{}' AS text[])) AS allowed_domains,
    COALESCE(policy.allow_guests, TRUE) AS allow_guests,
    COALESCE(policy.max_session_age_hours, 0) AS max_session_age_hours,
    epoch.revoked_before, session.revoked_at
FROM public.workspace_members AS member
JOIN public.users AS account ON account.user_id = member.user_id
JOIN public.workspaces AS workspace ON workspace.workspace_id = member.workspace_id
LEFT JOIN public.workspace_security_policies AS policy ON policy.workspace_id = member.workspace_id
LEFT JOIN public.workspace_member_session_epochs AS epoch ON epoch.workspace_id = member.workspace_id AND epoch.user_id = member.user_id
LEFT JOIN public.workspace_browser_sessions AS session ON session.workspace_id = member.workspace_id AND session.user_id = member.user_id AND session.session_id = $1
WHERE member.workspace_id = $2 AND member.user_id = $3
  AND account.is_active = TRUE AND workspace.deleted_at IS NULL
FOR SHARE OF workspace, member, account
`

type SessionAccessStateParams struct {
	SessionID   uuid.UUID
	WorkspaceID uuid.UUID
	ActorID     uuid.UUID
}

type SessionAccessStateRow struct {
	Email              string
	Role               string
	AllowedDomains     []string
	AllowGuests        bool
	MaxSessionAgeHours int32
	RevokedBefore      *time.Time
	RevokedAt          *time.Time
}

func (q *Queries) SessionAccessState(ctx context.Context, arg SessionAccessStateParams) (SessionAccessStateRow, error) {
	row := q.db.QueryRow(ctx, sessionAccessState, arg.SessionID, arg.WorkspaceID, arg.ActorID)
	var i SessionAccessStateRow
	err := row.Scan(
		&i.Email,
		&i.Role,
		&i.AllowedDomains,
		&i.AllowGuests,
		&i.MaxSessionAgeHours,
		&i.RevokedBefore,
		&i.RevokedAt,
	)
	return i, err
}

const trackBrowserSession = `-- name: TrackBrowserSession :execrows
INSERT INTO public.workspace_browser_sessions (workspace_id, session_id, user_id, authenticated_at, last_seen_at, expires_at)
VALUES ($1, $2, $3, $4, GREATEST(CURRENT_TIMESTAMP, CAST($4 AS timestamptz)), $5)
ON CONFLICT (workspace_id, session_id) DO UPDATE SET
    last_seen_at = CASE WHEN workspace_browser_sessions.last_seen_at < CURRENT_TIMESTAMP - INTERVAL '1 minute' THEN CURRENT_TIMESTAMP ELSE workspace_browser_sessions.last_seen_at END,
    expires_at = EXCLUDED.expires_at
WHERE workspace_browser_sessions.user_id = EXCLUDED.user_id
  AND workspace_browser_sessions.authenticated_at = EXCLUDED.authenticated_at
  AND workspace_browser_sessions.revoked_at IS NULL
`

type TrackBrowserSessionParams struct {
	WorkspaceID     uuid.UUID
	SessionID       uuid.UUID
	ActorID         uuid.UUID
	AuthenticatedAt time.Time
	ExpiresAt       time.Time
}

func (q *Queries) TrackBrowserSession(ctx context.Context, arg TrackBrowserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, trackBrowserSession,
		arg.WorkspaceID,
		arg.SessionID,
		arg.ActorID,
		arg.AuthenticatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
