// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workload.sql

package reportssql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUnassignedWorkload = `-- name: GetUnassignedWorkload :one
WITH workload_stories AS (
    SELECT
        story.id,
        story.assignee_id,
        story.priority,
        story.end_date,
        story.estimate_unit,
        status.category
    FROM stories AS story
    INNER JOIN teams AS team
        ON team.team_id = story.team_id
       AND team.workspace_id = $1::uuid
    LEFT JOIN statuses AS status ON status.status_id = story.status_id
    WHERE story.workspace_id = $1::uuid
      AND story.deleted_at IS NULL
      AND story.archived_at IS NULL
      AND story.is_draft = FALSE
      AND (cardinality($2::uuid[]) = 0 OR story.team_id = ANY($2::uuid[]))
      AND (cardinality($3::uuid[]) = 0 OR story.assignee_id = ANY($3::uuid[]))
      AND (cardinality($4::uuid[]) = 0 OR story.sprint_id = ANY($4::uuid[]))
      AND (cardinality($5::uuid[]) = 0 OR story.objective_id = ANY($5::uuid[]))
      AND ($6::timestamptz IS NULL OR story.created_at >= $6)
      AND ($7::timestamptz IS NULL OR story.created_at <= $7)
)
SELECT
    CAST(COUNT(*) FILTER (WHERE category IS NULL OR category NOT IN ('completed', 'cancelled')) AS int) AS stories,
    CAST(COALESCE(SUM(estimate_unit) FILTER (WHERE category IS NULL OR category NOT IN ('completed', 'cancelled')), 0) AS int) AS estimate_total,
    CAST(COUNT(*) FILTER (WHERE (category IS NULL OR category NOT IN ('completed', 'cancelled')) AND end_date < CURRENT_DATE) AS int) AS overdue_stories,
    CAST(COUNT(*) FILTER (WHERE (category IS NULL OR category NOT IN ('completed', 'cancelled')) AND priority = 'Urgent') AS int) AS urgent_stories,
    CAST(COUNT(*) FILTER (WHERE (category IS NULL OR category NOT IN ('completed', 'cancelled')) AND priority = 'High') AS int) AS high_priority_stories,
    CAST(COUNT(*) FILTER (WHERE (category IS NULL OR category NOT IN ('completed', 'cancelled')) AND estimate_unit IS NULL) AS int) AS unestimated_stories
FROM workload_stories
WHERE assignee_id IS NULL
`

type GetUnassignedWorkloadParams struct {
	WorkspaceID  uuid.UUID
	TeamIds      []uuid.UUID
	AssigneeIds  []uuid.UUID
	SprintIds    []uuid.UUID
	ObjectiveIds []uuid.UUID
	StartDate    *time.Time
	EndDate      *time.Time
}

type GetUnassignedWorkloadRow struct {
	Stories             int32
	EstimateTotal       int32
	OverdueStories      int32
	UrgentStories       int32
	HighPriorityStories int32
	UnestimatedStories  int32
}

func (q *Queries) GetUnassignedWorkload(ctx context.Context, arg GetUnassignedWorkloadParams) (GetUnassignedWorkloadRow, error) {
	row := q.db.QueryRow(ctx, getUnassignedWorkload,
		arg.WorkspaceID,
		arg.TeamIds,
		arg.AssigneeIds,
		arg.SprintIds,
		arg.ObjectiveIds,
		arg.StartDate,
		arg.EndDate,
	)
	var i GetUnassignedWorkloadRow
	err := row.Scan(
		&i.Stories,
		&i.EstimateTotal,
		&i.OverdueStories,
		&i.UrgentStories,
		&i.HighPriorityStories,
		&i.UnestimatedStories,
	)
	return i, err
}

const getWorkloadSummary = `-- name: GetWorkloadSummary :one
WITH workload_stories AS (
    SELECT
        story.id,
        story.team_id,
        team.name AS team_name,
        team.code AS team_code,
        story.assignee_id,
        story.priority,
        story.end_date,
        story.estimate_unit,
        status.category
    FROM stories AS story
    INNER JOIN teams AS team
        ON team.team_id = story.team_id
       AND team.workspace_id = $1::uuid
    LEFT JOIN statuses AS status ON status.status_id = story.status_id
    WHERE story.workspace_id = $1::uuid
      AND story.deleted_at IS NULL
      AND story.archived_at IS NULL
      AND story.is_draft = FALSE
      AND (cardinality($2::uuid[]) = 0 OR story.team_id = ANY($2::uuid[]))
      AND (cardinality($3::uuid[]) = 0 OR story.assignee_id = ANY($3::uuid[]))
      AND (cardinality($4::uuid[]) = 0 OR story.sprint_id = ANY($4::uuid[]))
      AND (cardinality($5::uuid[]) = 0 OR story.objective_id = ANY($5::uuid[]))
      AND ($6::timestamptz IS NULL OR story.created_at >= $6)
      AND ($7::timestamptz IS NULL OR story.created_at <= $7)
)
SELECT
    CAST(COUNT(*) FILTER (WHERE category IS NULL OR category NOT IN ('completed', 'cancelled')) AS int) AS total_open_stories,
    CAST(COALESCE(SUM(estimate_unit) FILTER (WHERE category IS NULL OR category NOT IN ('completed', 'cancelled')), 0) AS int) AS total_estimate,
    CAST(COUNT(*) FILTER (WHERE (category IS NULL OR category NOT IN ('completed', 'cancelled')) AND end_date < CURRENT_DATE) AS int) AS overdue_stories,
    CAST(COUNT(*) FILTER (WHERE (category IS NULL OR category NOT IN ('completed', 'cancelled')) AND priority = 'Urgent') AS int) AS urgent_stories,
    CAST(COUNT(*) FILTER (WHERE (category IS NULL OR category NOT IN ('completed', 'cancelled')) AND priority = 'High') AS int) AS high_priority_stories,
    CAST(COUNT(*) FILTER (WHERE (category IS NULL OR category NOT IN ('completed', 'cancelled')) AND estimate_unit IS NULL) AS int) AS unestimated_stories,
    CAST(COUNT(*) FILTER (WHERE (category IS NULL OR category NOT IN ('completed', 'cancelled')) AND assignee_id IS NULL) AS int) AS unassigned_stories
FROM workload_stories
`

type GetWorkloadSummaryParams struct {
	WorkspaceID  uuid.UUID
	TeamIds      []uuid.UUID
	AssigneeIds  []uuid.UUID
	SprintIds    []uuid.UUID
	ObjectiveIds []uuid.UUID
	StartDate    *time.Time
	EndDate      *time.Time
}

type GetWorkloadSummaryRow struct {
	TotalOpenStories    int32
	TotalEstimate       int32
	OverdueStories      int32
	UrgentStories       int32
	HighPriorityStories int32
	UnestimatedStories  int32
	UnassignedStories   int32
}

func (q *Queries) GetWorkloadSummary(ctx context.Context, arg GetWorkloadSummaryParams) (GetWorkloadSummaryRow, error) {
	row := q.db.QueryRow(ctx, getWorkloadSummary,
		arg.WorkspaceID,
		arg.TeamIds,
		arg.AssigneeIds,
		arg.SprintIds,
		arg.ObjectiveIds,
		arg.StartDate,
		arg.EndDate,
	)
	var i GetWorkloadSummaryRow
	err := row.Scan(
		&i.TotalOpenStories,
		&i.TotalEstimate,
		&i.OverdueStories,
		&i.UrgentStories,
		&i.HighPriorityStories,
		&i.UnestimatedStories,
		&i.UnassignedStories,
	)
	return i, err
}

const listMemberWorkload = `-- name: ListMemberWorkload :many
WITH workload_stories AS (
    SELECT
        story.id,
        story.team_id,
        story.assignee_id,
        story.priority,
        story.end_date,
        story.estimate_unit,
        story.updated_at,
        status.category
    FROM stories AS story
    INNER JOIN teams AS team
        ON team.team_id = story.team_id
       AND team.workspace_id = $1::uuid
    LEFT JOIN statuses AS status ON status.status_id = story.status_id
    WHERE story.workspace_id = $1::uuid
      AND story.deleted_at IS NULL
      AND story.archived_at IS NULL
      AND story.is_draft = FALSE
      AND (cardinality($2::uuid[]) = 0 OR story.team_id = ANY($2::uuid[]))
      AND (cardinality($3::uuid[]) = 0 OR story.assignee_id = ANY($3::uuid[]))
      AND (cardinality($4::uuid[]) = 0 OR story.sprint_id = ANY($4::uuid[]))
      AND (cardinality($5::uuid[]) = 0 OR story.objective_id = ANY($5::uuid[]))
      AND ($6::timestamptz IS NULL OR story.created_at >= $6)
      AND ($7::timestamptz IS NULL OR story.created_at <= $7)
)
SELECT
    account.user_id,
    COALESCE(account.full_name, '') AS full_name,
    account.username,
    COALESCE(account.avatar_url, '') AS avatar_url,
    CAST(COALESCE(MAX(membership.ai_role_title), '') AS text) AS team_ai_role_title,
    CAST(COALESCE(MAX(membership.ai_role_description), '') AS text) AS team_ai_role_description,
    CAST(COUNT(*) FILTER (WHERE story.category IS NULL OR story.category NOT IN ('completed', 'cancelled')) AS int) AS open_stories,
    CAST(COUNT(*) FILTER (WHERE story.category = 'started') AS int) AS started_stories,
    CAST(COUNT(*) FILTER (WHERE story.category = 'paused') AS int) AS paused_stories,
    CAST(COUNT(*) FILTER (WHERE story.category = 'completed') AS int) AS completed_stories,
    CAST(COUNT(*) FILTER (WHERE (story.category IS NULL OR story.category NOT IN ('completed', 'cancelled')) AND story.end_date < CURRENT_DATE) AS int) AS overdue_stories,
    CAST(COUNT(*) FILTER (WHERE (story.category IS NULL OR story.category NOT IN ('completed', 'cancelled')) AND story.priority = 'Urgent') AS int) AS urgent_stories,
    CAST(COUNT(*) FILTER (WHERE (story.category IS NULL OR story.category NOT IN ('completed', 'cancelled')) AND story.priority = 'High') AS int) AS high_priority_stories,
    CAST(COUNT(*) FILTER (WHERE (story.category IS NULL OR story.category NOT IN ('completed', 'cancelled')) AND story.estimate_unit IS NULL) AS int) AS unestimated_stories,
    CAST(COALESCE(SUM(story.estimate_unit) FILTER (WHERE story.category IS NULL OR story.category NOT IN ('completed', 'cancelled')), 0) AS int) AS estimate_total,
    CAST(MAX(story.updated_at) AS timestamptz) AS last_story_activity_at
FROM workload_stories AS story
INNER JOIN users AS account
    ON account.user_id = story.assignee_id
   AND account.is_active = TRUE
INNER JOIN team_members AS membership
    ON membership.team_id = story.team_id
   AND membership.user_id = account.user_id
WHERE story.assignee_id IS NOT NULL
GROUP BY account.user_id, account.full_name, account.username, account.avatar_url
ORDER BY estimate_total DESC, open_stories DESC, account.username, account.user_id
`

type ListMemberWorkloadParams struct {
	WorkspaceID  uuid.UUID
	TeamIds      []uuid.UUID
	AssigneeIds  []uuid.UUID
	SprintIds    []uuid.UUID
	ObjectiveIds []uuid.UUID
	StartDate    *time.Time
	EndDate      *time.Time
}

type ListMemberWorkloadRow struct {
	UserID                uuid.UUID
	FullName              string
	Username              string
	AvatarURL             string
	TeamAiRoleTitle       string
	TeamAiRoleDescription string
	OpenStories           int32
	StartedStories        int32
	PausedStories         int32
	CompletedStories      int32
	OverdueStories        int32
	UrgentStories         int32
	HighPriorityStories   int32
	UnestimatedStories    int32
	EstimateTotal         int32
	LastStoryActivityAt   time.Time
}

func (q *Queries) ListMemberWorkload(ctx context.Context, arg ListMemberWorkloadParams) ([]ListMemberWorkloadRow, error) {
	rows, err := q.db.Query(ctx, listMemberWorkload,
		arg.WorkspaceID,
		arg.TeamIds,
		arg.AssigneeIds,
		arg.SprintIds,
		arg.ObjectiveIds,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberWorkloadRow{}
	for rows.Next() {
		var i ListMemberWorkloadRow
		if err := rows.Scan(
			&i.UserID,
			&i.FullName,
			&i.Username,
			&i.AvatarURL,
			&i.TeamAiRoleTitle,
			&i.TeamAiRoleDescription,
			&i.OpenStories,
			&i.StartedStories,
			&i.PausedStories,
			&i.CompletedStories,
			&i.OverdueStories,
			&i.UrgentStories,
			&i.HighPriorityStories,
			&i.UnestimatedStories,
			&i.EstimateTotal,
			&i.LastStoryActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamWorkloadSummary = `-- name: ListTeamWorkloadSummary :many
WITH workload_stories AS (
    SELECT
        story.id,
        story.team_id,
        team.name AS team_name,
        team.code AS team_code,
        story.assignee_id,
        story.end_date,
        story.estimate_unit,
        status.category
    FROM stories AS story
    INNER JOIN teams AS team
        ON team.team_id = story.team_id
       AND team.workspace_id = $1::uuid
    LEFT JOIN statuses AS status ON status.status_id = story.status_id
    WHERE story.workspace_id = $1::uuid
      AND story.deleted_at IS NULL
      AND story.archived_at IS NULL
      AND story.is_draft = FALSE
      AND (cardinality($2::uuid[]) = 0 OR story.team_id = ANY($2::uuid[]))
      AND (cardinality($3::uuid[]) = 0 OR story.assignee_id = ANY($3::uuid[]))
      AND (cardinality($4::uuid[]) = 0 OR story.sprint_id = ANY($4::uuid[]))
      AND (cardinality($5::uuid[]) = 0 OR story.objective_id = ANY($5::uuid[]))
      AND ($6::timestamptz IS NULL OR story.created_at >= $6)
      AND ($7::timestamptz IS NULL OR story.created_at <= $7)
)
SELECT
    team_id,
    team_name,
    team_code,
    CAST(COUNT(*) FILTER (WHERE category IS NULL OR category NOT IN ('completed', 'cancelled')) AS int) AS open_stories,
    CAST(COALESCE(SUM(estimate_unit) FILTER (WHERE category IS NULL OR category NOT IN ('completed', 'cancelled')), 0) AS int) AS estimate_total,
    CAST(COUNT(*) FILTER (WHERE (category IS NULL OR category NOT IN ('completed', 'cancelled')) AND end_date < CURRENT_DATE) AS int) AS overdue_stories,
    CAST(COUNT(*) FILTER (WHERE (category IS NULL OR category NOT IN ('completed', 'cancelled')) AND assignee_id IS NULL) AS int) AS unassigned_stories,
    CAST(COUNT(*) FILTER (WHERE (category IS NULL OR category NOT IN ('completed', 'cancelled')) AND estimate_unit IS NULL) AS int) AS unestimated_stories
FROM workload_stories
GROUP BY team_id, team_name, team_code
ORDER BY team_name, team_id
`

type ListTeamWorkloadSummaryParams struct {
	WorkspaceID  uuid.UUID
	TeamIds      []uuid.UUID
	AssigneeIds  []uuid.UUID
	SprintIds    []uuid.UUID
	ObjectiveIds []uuid.UUID
	StartDate    *time.Time
	EndDate      *time.Time
}

type ListTeamWorkloadSummaryRow struct {
	TeamID             uuid.UUID
	TeamName           string
	TeamCode           string
	OpenStories        int32
	EstimateTotal      int32
	OverdueStories     int32
	UnassignedStories  int32
	UnestimatedStories int32
}

func (q *Queries) ListTeamWorkloadSummary(ctx context.Context, arg ListTeamWorkloadSummaryParams) ([]ListTeamWorkloadSummaryRow, error) {
	rows, err := q.db.Query(ctx, listTeamWorkloadSummary,
		arg.WorkspaceID,
		arg.TeamIds,
		arg.AssigneeIds,
		arg.SprintIds,
		arg.ObjectiveIds,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamWorkloadSummaryRow{}
	for rows.Next() {
		var i ListTeamWorkloadSummaryRow
		if err := rows.Scan(
			&i.TeamID,
			&i.TeamName,
			&i.TeamCode,
			&i.OpenStories,
			&i.EstimateTotal,
			&i.OverdueStories,
			&i.UnassignedStories,
			&i.UnestimatedStories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
