import type { Options as SanitizeOptions } from "rehype-sanitize";

export const REASONING_SANITIZE_SCHEMA = {
  ancestors: {
    tbody: ["table"],
    td: ["table"],
    th: ["table"],
    thead: ["table"],
    tr: ["table"],
  },
  attributes: {
    a: ["href", "title"],
    details: ["open"],
    img: ["alt", "height", "src", "title", "width"],
    input: [
      ["checked", true],
      ["disabled", true],
      ["type", "checkbox"],
    ],
    ol: ["start"],
    td: ["align", "colSpan", "rowSpan"],
    th: ["align", "colSpan", "rowSpan"],
  },
  clobber: ["id", "name"],
  clobberPrefix: "user-content-",
  protocols: {
    href: ["http", "https", "mailto"],
    src: ["http", "https"],
  },
  required: {
    input: { disabled: true, type: "checkbox" },
  },
  strip: ["embed", "iframe", "object", "script", "style", "template"],
  tagNames: [
    "a",
    "blockquote",
    "br",
    "code",
    "del",
    "details",
    "em",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hr",
    "img",
    "input",
    "kbd",
    "li",
    "ol",
    "p",
    "pre",
    "strong",
    "sub",
    "summary",
    "sup",
    "table",
    "tbody",
    "td",
    "th",
    "thead",
    "tr",
    "ul",
  ],
} satisfies SanitizeOptions;
