// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notificationssql

import (
	"database/sql/driver"
	"fmt"
)

type EntityType string

const (
	EntityTypeStory     EntityType = "story"
	EntityTypeComment   EntityType = "comment"
	EntityTypeObjective EntityType = "objective"
	EntityTypeKeyResult EntityType = "key_result"
	EntityTypeFeedback  EntityType = "feedback"
	EntityTypeStrategy  EntityType = "strategy"
)

func (e *EntityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntityType(s)
	case string:
		*e = EntityType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntityType: %T", src)
	}
	return nil
}

type NullEntityType struct {
	EntityType EntityType
	Valid      bool // Valid is true if EntityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntityType) Scan(value interface{}) error {
	if value == nil {
		ns.EntityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntityType), nil
}

func (e EntityType) Valid() bool {
	switch e {
	case EntityTypeStory,
		EntityTypeComment,
		EntityTypeObjective,
		EntityTypeKeyResult,
		EntityTypeFeedback,
		EntityTypeStrategy:
		return true
	}
	return false
}

type NotificationType string

const (
	NotificationTypeStoryUpdate             NotificationType = "story_update"
	NotificationTypeStoryComment            NotificationType = "story_comment"
	NotificationTypeCommentReply            NotificationType = "comment_reply"
	NotificationTypeObjectiveUpdate         NotificationType = "objective_update"
	NotificationTypeKeyResultUpdate         NotificationType = "key_result_update"
	NotificationTypeMention                 NotificationType = "mention"
	NotificationTypeFeedbackComment         NotificationType = "feedback_comment"
	NotificationTypeFeedbackStatusUpdate    NotificationType = "feedback_status_update"
	NotificationTypeStrategyUpdate          NotificationType = "strategy_update"
	NotificationTypeFeedbackUpdatePublished NotificationType = "feedback_update_published"
	NotificationTypeFeedbackItemMerged      NotificationType = "feedback_item_merged"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType
	Valid            bool // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

func (e NotificationType) Valid() bool {
	switch e {
	case NotificationTypeStoryUpdate,
		NotificationTypeStoryComment,
		NotificationTypeCommentReply,
		NotificationTypeObjectiveUpdate,
		NotificationTypeKeyResultUpdate,
		NotificationTypeMention,
		NotificationTypeFeedbackComment,
		NotificationTypeFeedbackStatusUpdate,
		NotificationTypeStrategyUpdate,
		NotificationTypeFeedbackUpdatePublished,
		NotificationTypeFeedbackItemMerged:
		return true
	}
	return false
}
