// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portal.sql

package notificationssql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnreadPortalFeedbackNotifications = `-- name: CountUnreadPortalFeedbackNotifications :one
WITH portal_scope AS (
    SELECT portal.id, portal.workspace_id
    FROM public.users AS actor
    INNER JOIN public.feedback_contributors AS contributor
        ON contributor.user_id = actor.user_id
       AND contributor.kind = 'account'
       AND contributor.blocked_at IS NULL
    INNER JOIN public.feedback_portals AS portal
        ON portal.id = contributor.portal_id
       AND portal.is_public = TRUE
    INNER JOIN public.workspaces AS workspace
        ON workspace.workspace_id = portal.workspace_id
       AND workspace.slug = CAST($2 AS text)
       AND workspace.deleted_at IS NULL
    WHERE actor.user_id = CAST($1 AS uuid)
      AND actor.is_active = TRUE
)
SELECT COUNT(*)
FROM public.notifications AS notification
INNER JOIN public.feedback_items AS feedback_item
    ON feedback_item.id = notification.entity_id
   AND feedback_item.workspace_id = notification.workspace_id
   AND feedback_item.deleted_at IS NULL
INNER JOIN portal_scope AS scope
    ON scope.id = feedback_item.portal_id
   AND scope.workspace_id = notification.workspace_id
WHERE notification.recipient_id = CAST($1 AS uuid)
  AND CAST(notification.entity_type AS text) = 'feedback'
  AND CAST(notification.type AS text) IN (
      'feedback_comment',
      'feedback_status_update',
      'feedback_update_published',
      'feedback_item_merged'
  )
  AND notification.in_app_enabled = TRUE
  AND notification.read_at IS NULL
`

type CountUnreadPortalFeedbackNotificationsParams struct {
	ActorID    uuid.UUID
	PortalSlug string
}

func (q *Queries) CountUnreadPortalFeedbackNotifications(ctx context.Context, arg CountUnreadPortalFeedbackNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadPortalFeedbackNotifications, arg.ActorID, arg.PortalSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPortalFeedbackNotifications = `-- name: ListPortalFeedbackNotifications :many
WITH portal_scope AS (
    SELECT portal.id, portal.workspace_id
    FROM public.users AS actor
    INNER JOIN public.feedback_contributors AS contributor
        ON contributor.user_id = actor.user_id
       AND contributor.kind = 'account'
       AND contributor.blocked_at IS NULL
    INNER JOIN public.feedback_portals AS portal
        ON portal.id = contributor.portal_id
       AND portal.is_public = TRUE
    INNER JOIN public.workspaces AS workspace
        ON workspace.workspace_id = portal.workspace_id
       AND workspace.slug = CAST($3 AS text)
       AND workspace.deleted_at IS NULL
    WHERE actor.user_id = CAST($4 AS uuid)
      AND actor.is_active = TRUE
), visible_notifications AS (
    SELECT
        notification.notification_id,
        feedback_item.title AS feedback_title,
        feedback_item.slug AS feedback_slug
    FROM public.notifications AS notification
    INNER JOIN public.feedback_items AS feedback_item
        ON feedback_item.id = notification.entity_id
       AND feedback_item.workspace_id = notification.workspace_id
       AND feedback_item.deleted_at IS NULL
    INNER JOIN portal_scope AS scope
        ON scope.id = feedback_item.portal_id
       AND scope.workspace_id = notification.workspace_id
    WHERE notification.recipient_id = CAST($4 AS uuid)
      AND CAST(notification.entity_type AS text) = 'feedback'
      AND CAST(notification.type AS text) IN (
          'feedback_comment',
          'feedback_status_update',
          'feedback_update_published',
          'feedback_item_merged'
      )
      AND notification.in_app_enabled = TRUE
      AND (
          NOT CAST($5 AS boolean)
          OR notification.read_at IS NULL
      )
)
SELECT
    notification.notification_id,
    notification.recipient_id,
    notification.workspace_id,
    notification.type,
    notification.entity_type,
    notification.entity_id,
    notification.actor_id,
    notification.title,
    notification.message,
    notification.in_app_enabled,
    notification.created_at,
    notification.read_at,
    COALESCE(
        NULLIF(actor.full_name, ''),
        NULLIF(actor.username, ''),
        actor.email,
        'Someone'
    ) AS actor_name,
    actor.avatar_url AS actor_avatar,
    visible.feedback_title,
    visible.feedback_slug
FROM public.notifications AS notification
INNER JOIN visible_notifications AS visible
    ON visible.notification_id = notification.notification_id
LEFT JOIN public.users AS actor
    ON actor.user_id = notification.actor_id
ORDER BY notification.created_at DESC NULLS LAST, notification.notification_id DESC
LIMIT CAST($2 AS integer)
OFFSET CAST($1 AS integer)
`

type ListPortalFeedbackNotificationsParams struct {
	ResultOffset int32
	ResultLimit  int32
	PortalSlug   string
	ActorID      uuid.UUID
	UnreadOnly   bool
}

type ListPortalFeedbackNotificationsRow struct {
	NotificationID uuid.UUID
	RecipientID    uuid.UUID
	WorkspaceID    uuid.UUID
	Type           NotificationType
	EntityType     EntityType
	EntityID       uuid.UUID
	ActorID        uuid.UUID
	Title          string
	Message        []byte
	InAppEnabled   bool
	CreatedAt      *time.Time
	ReadAt         *time.Time
	ActorName      string
	ActorAvatar    *string
	FeedbackTitle  string
	FeedbackSlug   string
}

// ListPortalFeedbackNotifications keeps the public portal inbox isolated from
// workspace membership. Access instead requires an active account contributor
// that has not been blocked from the exact public portal.
func (q *Queries) ListPortalFeedbackNotifications(ctx context.Context, arg ListPortalFeedbackNotificationsParams) ([]ListPortalFeedbackNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listPortalFeedbackNotifications,
		arg.ResultOffset,
		arg.ResultLimit,
		arg.PortalSlug,
		arg.ActorID,
		arg.UnreadOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPortalFeedbackNotificationsRow{}
	for rows.Next() {
		var i ListPortalFeedbackNotificationsRow
		if err := rows.Scan(
			&i.NotificationID,
			&i.RecipientID,
			&i.WorkspaceID,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.ActorID,
			&i.Title,
			&i.Message,
			&i.InAppEnabled,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ActorName,
			&i.ActorAvatar,
			&i.FeedbackTitle,
			&i.FeedbackSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllPortalFeedbackNotificationsRead = `-- name: MarkAllPortalFeedbackNotificationsRead :one
WITH portal_scope AS (
    SELECT portal.id, portal.workspace_id
    FROM public.users AS actor
    INNER JOIN public.feedback_contributors AS contributor
        ON contributor.user_id = actor.user_id
       AND contributor.kind = 'account'
       AND contributor.blocked_at IS NULL
    INNER JOIN public.feedback_portals AS portal
        ON portal.id = contributor.portal_id
       AND portal.is_public = TRUE
    INNER JOIN public.workspaces AS workspace
        ON workspace.workspace_id = portal.workspace_id
       AND workspace.slug = CAST($1 AS text)
       AND workspace.deleted_at IS NULL
    WHERE actor.user_id = CAST($2 AS uuid)
      AND actor.is_active = TRUE
), authorized_notifications AS (
    SELECT notification.notification_id
    FROM public.notifications AS notification
    INNER JOIN public.feedback_items AS feedback_item
        ON feedback_item.id = notification.entity_id
       AND feedback_item.workspace_id = notification.workspace_id
       AND feedback_item.deleted_at IS NULL
    INNER JOIN portal_scope AS scope
        ON scope.id = feedback_item.portal_id
       AND scope.workspace_id = notification.workspace_id
    WHERE notification.recipient_id = CAST($2 AS uuid)
      AND CAST(notification.entity_type AS text) = 'feedback'
      AND CAST(notification.type AS text) IN (
          'feedback_comment',
          'feedback_status_update',
          'feedback_update_published',
          'feedback_item_merged'
      )
      AND notification.in_app_enabled = TRUE
      AND notification.read_at IS NULL
), updated_notifications AS (
    UPDATE public.notifications AS notification
    SET read_at = CAST($3 AS timestamptz)
    FROM authorized_notifications AS authorized
    WHERE notification.notification_id = authorized.notification_id
    RETURNING notification.notification_id
)
SELECT CAST(COUNT(*) AS bigint) AS affected_count
FROM updated_notifications
`

type MarkAllPortalFeedbackNotificationsReadParams struct {
	PortalSlug string
	ActorID    uuid.UUID
	ReadAt     time.Time
}

func (q *Queries) MarkAllPortalFeedbackNotificationsRead(ctx context.Context, arg MarkAllPortalFeedbackNotificationsReadParams) (int64, error) {
	row := q.db.QueryRow(ctx, markAllPortalFeedbackNotificationsRead, arg.PortalSlug, arg.ActorID, arg.ReadAt)
	var affected_count int64
	err := row.Scan(&affected_count)
	return affected_count, err
}

const markPortalFeedbackNotificationRead = `-- name: MarkPortalFeedbackNotificationRead :one
WITH portal_scope AS (
    SELECT portal.id, portal.workspace_id
    FROM public.users AS actor
    INNER JOIN public.feedback_contributors AS contributor
        ON contributor.user_id = actor.user_id
       AND contributor.kind = 'account'
       AND contributor.blocked_at IS NULL
    INNER JOIN public.feedback_portals AS portal
        ON portal.id = contributor.portal_id
       AND portal.is_public = TRUE
    INNER JOIN public.workspaces AS workspace
        ON workspace.workspace_id = portal.workspace_id
       AND workspace.slug = CAST($2 AS text)
       AND workspace.deleted_at IS NULL
    WHERE actor.user_id = CAST($3 AS uuid)
      AND actor.is_active = TRUE
), authorized_notification AS (
    SELECT notification.notification_id
    FROM public.notifications AS notification
    INNER JOIN public.feedback_items AS feedback_item
        ON feedback_item.id = notification.entity_id
       AND feedback_item.workspace_id = notification.workspace_id
       AND feedback_item.deleted_at IS NULL
    INNER JOIN portal_scope AS scope
        ON scope.id = feedback_item.portal_id
       AND scope.workspace_id = notification.workspace_id
    WHERE notification.notification_id = CAST($4 AS uuid)
      AND notification.recipient_id = CAST($3 AS uuid)
      AND CAST(notification.entity_type AS text) = 'feedback'
      AND CAST(notification.type AS text) IN (
          'feedback_comment',
          'feedback_status_update',
          'feedback_update_published',
          'feedback_item_merged'
      )
      AND notification.in_app_enabled = TRUE
)
UPDATE public.notifications AS notification
SET read_at = COALESCE(notification.read_at, CAST($1 AS timestamptz))
FROM authorized_notification AS authorized
WHERE notification.notification_id = authorized.notification_id
RETURNING notification.notification_id
`

type MarkPortalFeedbackNotificationReadParams struct {
	ReadAt         time.Time
	PortalSlug     string
	ActorID        uuid.UUID
	NotificationID uuid.UUID
}

func (q *Queries) MarkPortalFeedbackNotificationRead(ctx context.Context, arg MarkPortalFeedbackNotificationReadParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markPortalFeedbackNotificationRead,
		arg.ReadAt,
		arg.PortalSlug,
		arg.ActorID,
		arg.NotificationID,
	)
	var notification_id uuid.UUID
	err := row.Scan(&notification_id)
	return notification_id, err
}

const portalNotificationActorAuthorized = `-- name: PortalNotificationActorAuthorized :one
SELECT EXISTS (
    SELECT 1
    FROM public.users AS actor
    INNER JOIN public.feedback_contributors AS contributor
        ON contributor.user_id = actor.user_id
       AND contributor.kind = 'account'
       AND contributor.blocked_at IS NULL
    INNER JOIN public.feedback_portals AS portal
        ON portal.id = contributor.portal_id
       AND portal.is_public = TRUE
    INNER JOIN public.workspaces AS workspace
        ON workspace.workspace_id = portal.workspace_id
       AND workspace.slug = CAST($1 AS text)
       AND workspace.deleted_at IS NULL
    WHERE actor.user_id = CAST($2 AS uuid)
      AND actor.is_active = TRUE
)
`

type PortalNotificationActorAuthorizedParams struct {
	PortalSlug string
	ActorID    uuid.UUID
}

func (q *Queries) PortalNotificationActorAuthorized(ctx context.Context, arg PortalNotificationActorAuthorizedParams) (bool, error) {
	row := q.db.QueryRow(ctx, portalNotificationActorAuthorized, arg.PortalSlug, arg.ActorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
