// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package notificationssql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
WITH authorized_actor AS (
    SELECT actor.user_id, workspace.workspace_id
    FROM public.users AS actor
    INNER JOIN public.workspace_members AS membership
        ON membership.user_id = actor.user_id
       AND membership.workspace_id = CAST($1 AS uuid)
       AND membership.role IN ('admin', 'member', 'guest')
    INNER JOIN public.workspaces AS workspace
        ON workspace.workspace_id = membership.workspace_id
       AND workspace.deleted_at IS NULL
    WHERE actor.user_id = CAST($2 AS uuid)
      AND actor.is_active = TRUE
), inserted_preferences AS (
    INSERT INTO public.notification_preferences (
        user_id,
        workspace_id,
        preferences
    )
    SELECT
        authorized.user_id,
        authorized.workspace_id,
        CAST($3 AS jsonb)
    FROM authorized_actor AS authorized
    ON CONFLICT (user_id, workspace_id) DO NOTHING
    RETURNING
        preference_id,
        user_id,
        workspace_id,
        preferences,
        created_at,
        updated_at
)
SELECT
    inserted.preference_id,
    inserted.user_id,
    inserted.workspace_id,
    inserted.preferences,
    inserted.created_at,
    inserted.updated_at
FROM inserted_preferences AS inserted
UNION ALL
SELECT
    preference.preference_id,
    preference.user_id,
    preference.workspace_id,
    preference.preferences,
    preference.created_at,
    preference.updated_at
FROM public.notification_preferences AS preference
INNER JOIN authorized_actor AS authorized
    ON authorized.user_id = preference.user_id
   AND authorized.workspace_id = preference.workspace_id
WHERE NOT EXISTS (SELECT 1 FROM inserted_preferences)
LIMIT 1
`

type GetNotificationPreferencesParams struct {
	WorkspaceID        uuid.UUID
	ActorID            uuid.UUID
	DefaultPreferences []byte
}

type GetNotificationPreferencesRow struct {
	PreferenceID uuid.UUID
	UserID       uuid.UUID
	WorkspaceID  uuid.UUID
	Preferences  []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// GetNotificationPreferences creates the typed default document on first read,
// but only for an active workspace member in a live workspace.
func (q *Queries) GetNotificationPreferences(ctx context.Context, arg GetNotificationPreferencesParams) (GetNotificationPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, arg.WorkspaceID, arg.ActorID, arg.DefaultPreferences)
	var i GetNotificationPreferencesRow
	err := row.Scan(
		&i.PreferenceID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationPreference = `-- name: UpdateNotificationPreference :one
WITH authorized_actor AS (
    SELECT actor.user_id, workspace.workspace_id
    FROM public.users AS actor
    INNER JOIN public.workspace_members AS membership
        ON membership.user_id = actor.user_id
       AND membership.workspace_id = CAST($1 AS uuid)
       AND membership.role IN ('admin', 'member', 'guest')
    INNER JOIN public.workspaces AS workspace
        ON workspace.workspace_id = membership.workspace_id
       AND workspace.deleted_at IS NULL
    WHERE actor.user_id = CAST($2 AS uuid)
      AND actor.is_active = TRUE
), desired_channels AS (
    SELECT
        authorized.user_id,
        authorized.workspace_id,
        CAST($3 AS jsonb) AS defaults,
        CAST($4 AS text) AS preference_type
    FROM authorized_actor AS authorized
), inserted_or_updated AS (
    INSERT INTO public.notification_preferences (
        user_id,
        workspace_id,
        preferences,
        updated_at
    )
    SELECT
        desired.user_id,
        desired.workspace_id,
        desired.defaults || jsonb_build_object(
            desired.preference_type,
            COALESCE(desired.defaults -> desired.preference_type, CAST('{}' AS jsonb))
                || jsonb_build_object(
                    'email', CASE
                        WHEN CAST($5 AS boolean)
                            THEN CAST($6 AS boolean)
                        ELSE COALESCE(
                            CAST(desired.defaults -> desired.preference_type ->> 'email' AS boolean),
                            TRUE
                        )
                    END,
                    'in_app', CASE
                        WHEN NOT CAST($7 AS boolean) THEN FALSE
                        WHEN CAST($8 AS boolean)
                            THEN CAST($9 AS boolean)
                        ELSE COALESCE(
                            CAST(desired.defaults -> desired.preference_type ->> 'in_app' AS boolean),
                            TRUE
                        )
                    END
                )
        ),
        CAST($10 AS timestamptz)
    FROM desired_channels AS desired
    ON CONFLICT (user_id, workspace_id) DO UPDATE
    SET
        preferences = notification_preferences.preferences || jsonb_build_object(
            CAST($4 AS text),
            COALESCE(
                notification_preferences.preferences -> CAST($4 AS text),
                CAST($3 AS jsonb) -> CAST($4 AS text),
                CAST('{}' AS jsonb)
            ) || jsonb_build_object(
                'email', CASE
                    WHEN CAST($5 AS boolean)
                        THEN CAST($6 AS boolean)
                    ELSE COALESCE(
                        CAST(
                            notification_preferences.preferences
                                -> CAST($4 AS text)
                                ->> 'email'
                            AS boolean
                        ),
                        CAST(
                            CAST($3 AS jsonb)
                                -> CAST($4 AS text)
                                ->> 'email'
                            AS boolean
                        ),
                        TRUE
                    )
                END,
                'in_app', CASE
                    WHEN NOT CAST($7 AS boolean) THEN FALSE
                    WHEN CAST($8 AS boolean)
                        THEN CAST($9 AS boolean)
                    ELSE COALESCE(
                        CAST(
                            notification_preferences.preferences
                                -> CAST($4 AS text)
                                ->> 'in_app'
                            AS boolean
                        ),
                        CAST(
                            CAST($3 AS jsonb)
                                -> CAST($4 AS text)
                                ->> 'in_app'
                            AS boolean
                        ),
                        TRUE
                    )
                END
            )
        ),
        updated_at = CAST($10 AS timestamptz)
    RETURNING
        preference_id,
        user_id,
        workspace_id,
        preferences,
        created_at,
        updated_at
)
SELECT
    result.preference_id,
    result.user_id,
    result.workspace_id,
    result.preferences,
    result.created_at,
    result.updated_at
FROM inserted_or_updated AS result
`

type UpdateNotificationPreferenceParams struct {
	WorkspaceID        uuid.UUID
	ActorID            uuid.UUID
	DefaultPreferences []byte
	PreferenceType     string
	EmailPresent       bool
	EmailEnabled       bool
	SupportsInApp      bool
	InAppPresent       bool
	InAppEnabled       bool
	UpdatedAt          time.Time
}

type UpdateNotificationPreferenceRow struct {
	PreferenceID uuid.UUID
	UserID       uuid.UUID
	WorkspaceID  uuid.UUID
	Preferences  []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// UpdateNotificationPreference applies one presence-aware channel patch inside
// PostgreSQL. Concurrent updates to different preference types or channels do
// not overwrite the rest of the JSON document.
func (q *Queries) UpdateNotificationPreference(ctx context.Context, arg UpdateNotificationPreferenceParams) (UpdateNotificationPreferenceRow, error) {
	row := q.db.QueryRow(ctx, updateNotificationPreference,
		arg.WorkspaceID,
		arg.ActorID,
		arg.DefaultPreferences,
		arg.PreferenceType,
		arg.EmailPresent,
		arg.EmailEnabled,
		arg.SupportsInApp,
		arg.InAppPresent,
		arg.InAppEnabled,
		arg.UpdatedAt,
	)
	var i UpdateNotificationPreferenceRow
	err := row.Scan(
		&i.PreferenceID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
