// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routine.sql

package notificationssql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimRoutineEmail = `-- name: ClaimRoutineEmail :one
INSERT INTO routine_email_deliveries (
    recipient_id, workspace_id, delivery_key, kind, local_date, status, claimed_at
)
VALUES (
    $1, $2, $3,
    $4, $5, 'processing', $6
)
ON CONFLICT (recipient_id, workspace_id, delivery_key) DO UPDATE
SET id = gen_random_uuid(), status = 'processing',
    claimed_at = EXCLUDED.claimed_at, local_date = EXCLUDED.local_date
WHERE routine_email_deliveries.status = 'failed'
    OR (routine_email_deliveries.status = 'processing'
        AND routine_email_deliveries.claimed_at <= $7)
RETURNING id
`

type ClaimRoutineEmailParams struct {
	RecipientID uuid.UUID
	WorkspaceID uuid.UUID
	DeliveryKey string
	Kind        string
	LocalDate   time.Time
	Now         time.Time
	StaleBefore time.Time
}

func (q *Queries) ClaimRoutineEmail(ctx context.Context, arg ClaimRoutineEmailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimRoutineEmail,
		arg.RecipientID,
		arg.WorkspaceID,
		arg.DeliveryKey,
		arg.Kind,
		arg.LocalDate,
		arg.Now,
		arg.StaleBefore,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const completeRoutineEmail = `-- name: CompleteRoutineEmail :execrows
UPDATE routine_email_deliveries
SET status = $1, completed_at = $2
WHERE id = $3
    AND recipient_id = $4
    AND workspace_id = $5
    AND status = 'processing'
`

type CompleteRoutineEmailParams struct {
	Status      string
	Now         *time.Time
	ID          uuid.UUID
	RecipientID uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) CompleteRoutineEmail(ctx context.Context, arg CompleteRoutineEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeRoutineEmail,
		arg.Status,
		arg.Now,
		arg.ID,
		arg.RecipientID,
		arg.WorkspaceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failRoutineEmail = `-- name: FailRoutineEmail :execrows
UPDATE routine_email_deliveries SET status = 'failed'
WHERE id = $1 AND status = 'processing'
`

type FailRoutineEmailParams struct {
	ID uuid.UUID
}

func (q *Queries) FailRoutineEmail(ctx context.Context, arg FailRoutineEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, failRoutineEmail, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoutineEmailRecipient = `-- name: GetRoutineEmailRecipient :one
SELECT
    account.user_id,
    workspace.workspace_id,
    account.email,
    COALESCE(NULLIF(account.full_name, ''), account.username) AS name,
    workspace.name AS workspace_name,
    workspace.slug AS workspace_slug,
    CAST(COALESCE(NULLIF(account.timezone, ''), 'UTC') AS text) AS timezone,
    CAST(COALESCE(preference.preferences -> 'weekly_digest' ->> 'email', 'true') AS boolean) AS weekly_enabled
FROM users AS account
JOIN workspace_members AS member
    ON member.user_id = account.user_id AND member.role IN ('admin', 'member', 'guest')
JOIN workspaces AS workspace
    ON workspace.workspace_id = member.workspace_id AND workspace.deleted_at IS NULL
LEFT JOIN notification_preferences AS preference
    ON preference.user_id = account.user_id AND preference.workspace_id = workspace.workspace_id
WHERE account.is_active
    AND NOT account.is_system
    AND NULLIF(TRIM(account.email), '') IS NOT NULL
    AND account.user_id = $1
    AND workspace.workspace_id = $2
`

type GetRoutineEmailRecipientParams struct {
	RecipientID uuid.UUID
	WorkspaceID uuid.UUID
}

type GetRoutineEmailRecipientRow struct {
	UserID        uuid.UUID
	WorkspaceID   uuid.UUID
	Email         string
	Name          string
	WorkspaceName string
	WorkspaceSlug string
	Timezone      string
	WeeklyEnabled bool
}

func (q *Queries) GetRoutineEmailRecipient(ctx context.Context, arg GetRoutineEmailRecipientParams) (GetRoutineEmailRecipientRow, error) {
	row := q.db.QueryRow(ctx, getRoutineEmailRecipient, arg.RecipientID, arg.WorkspaceID)
	var i GetRoutineEmailRecipientRow
	err := row.Scan(
		&i.UserID,
		&i.WorkspaceID,
		&i.Email,
		&i.Name,
		&i.WorkspaceName,
		&i.WorkspaceSlug,
		&i.Timezone,
		&i.WeeklyEnabled,
	)
	return i, err
}

const hasActiveRoutineEmailClaim = `-- name: HasActiveRoutineEmailClaim :one
SELECT EXISTS (
    SELECT 1 FROM routine_email_deliveries
    WHERE recipient_id = $1
        AND status = 'processing'
        AND claimed_at > $2
)
`

type HasActiveRoutineEmailClaimParams struct {
	RecipientID uuid.UUID
	StaleBefore time.Time
}

func (q *Queries) HasActiveRoutineEmailClaim(ctx context.Context, arg HasActiveRoutineEmailClaimParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveRoutineEmailClaim, arg.RecipientID, arg.StaleBefore)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasRoutineEmailGuidance = `-- name: HasRoutineEmailGuidance :one
SELECT EXISTS (
    SELECT 1 FROM routine_email_deliveries
    WHERE recipient_id = $1
        AND workspace_id = $2
        AND delivery_key = $3
        AND status = 'sent'
)
`

type HasRoutineEmailGuidanceParams struct {
	RecipientID uuid.UUID
	WorkspaceID uuid.UUID
	DeliveryKey string
}

func (q *Queries) HasRoutineEmailGuidance(ctx context.Context, arg HasRoutineEmailGuidanceParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRoutineEmailGuidance, arg.RecipientID, arg.WorkspaceID, arg.DeliveryKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRoutineEmailRecipients = `-- name: ListRoutineEmailRecipients :many
SELECT
    account.user_id,
    workspace.workspace_id,
    account.email,
    COALESCE(NULLIF(account.full_name, ''), account.username) AS name,
    workspace.name AS workspace_name,
    workspace.slug AS workspace_slug,
    CAST(COALESCE(NULLIF(account.timezone, ''), 'UTC') AS text) AS timezone,
    CAST(COALESCE(preference.preferences -> 'weekly_digest' ->> 'email', 'true') AS boolean) AS weekly_enabled
FROM users AS account
JOIN workspace_members AS member
    ON member.user_id = account.user_id AND member.role IN ('admin', 'member', 'guest')
JOIN workspaces AS workspace
    ON workspace.workspace_id = member.workspace_id AND workspace.deleted_at IS NULL
LEFT JOIN notification_preferences AS preference
    ON preference.user_id = account.user_id AND preference.workspace_id = workspace.workspace_id
WHERE account.is_active
    AND NOT account.is_system
    AND NULLIF(TRIM(account.email), '') IS NOT NULL
    AND (
        NOT CAST($1 AS boolean)
        OR (workspace.workspace_id, account.user_id) > ($2, $3)
    )
ORDER BY workspace.workspace_id, account.user_id
LIMIT $4
`

type ListRoutineEmailRecipientsParams struct {
	HasCursor        bool
	AfterWorkspaceID uuid.UUID
	AfterUserID      uuid.UUID
	RowLimit         int32
}

type ListRoutineEmailRecipientsRow struct {
	UserID        uuid.UUID
	WorkspaceID   uuid.UUID
	Email         string
	Name          string
	WorkspaceName string
	WorkspaceSlug string
	Timezone      string
	WeeklyEnabled bool
}

func (q *Queries) ListRoutineEmailRecipients(ctx context.Context, arg ListRoutineEmailRecipientsParams) ([]ListRoutineEmailRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listRoutineEmailRecipients,
		arg.HasCursor,
		arg.AfterWorkspaceID,
		arg.AfterUserID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoutineEmailRecipientsRow{}
	for rows.Next() {
		var i ListRoutineEmailRecipientsRow
		if err := rows.Scan(
			&i.UserID,
			&i.WorkspaceID,
			&i.Email,
			&i.Name,
			&i.WorkspaceName,
			&i.WorkspaceSlug,
			&i.Timezone,
			&i.WeeklyEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoutineEmailRecipient = `-- name: LockRoutineEmailRecipient :exec
SELECT pg_advisory_xact_lock(hashtextextended(CAST($1 AS text), 184))
`

type LockRoutineEmailRecipientParams struct {
	RecipientID string
}

func (q *Queries) LockRoutineEmailRecipient(ctx context.Context, arg LockRoutineEmailRecipientParams) error {
	_, err := q.db.Exec(ctx, lockRoutineEmailRecipient, arg.RecipientID)
	return err
}

const recordRoutineEmailGuidance = `-- name: RecordRoutineEmailGuidance :exec
INSERT INTO routine_email_deliveries (
    recipient_id, workspace_id, delivery_key, kind, local_date, status, claimed_at, completed_at
) VALUES (
    $1, $2, $3,
    'briefing', $4, 'sent', $5, $5
)
ON CONFLICT (recipient_id, workspace_id, delivery_key) DO UPDATE
SET status = 'sent', completed_at = EXCLUDED.completed_at
`

type RecordRoutineEmailGuidanceParams struct {
	RecipientID uuid.UUID
	WorkspaceID uuid.UUID
	DeliveryKey string
	LocalDate   time.Time
	Now         time.Time
}

func (q *Queries) RecordRoutineEmailGuidance(ctx context.Context, arg RecordRoutineEmailGuidanceParams) error {
	_, err := q.db.Exec(ctx, recordRoutineEmailGuidance,
		arg.RecipientID,
		arg.WorkspaceID,
		arg.DeliveryKey,
		arg.LocalDate,
		arg.Now,
	)
	return err
}
